### ISSUE TITLE
Possible executemany() optimization

### ISSUE THREAD

**Issue by sekrause** [psycopg/psycopg#145]
So I was playing around with the new `psycopg` and Wireshark to learn about PostgreSQL's extended query protocol and looked at the behavior of `executemany()` at the procotol level.

Currently `executemany()` sends one Parse/Sync message at the beginning and then a Bind/Describe/Execute/Sync message for each params in the params sequence, waiting the the server response after each message. This greatly limits the performance of `executemany()` by the roundtrip time to the server (at least when the latency is not negligible).

In [this message](https://www.postgresql.org/message-id/542A3D9D.30403%402ndquadrant.com) on the PostgreSQL mailing list it was mentioned that:

> You can and should send parse/bind/describe/execute messages back-to-back without waiting for a server response. Just Sync and wait for server response at the end.
> 
> **You can even send a parse then a stream of bind/describe/execute messages for batch execution of a prepared statement against a list of params, then a single Sync at the end.**

The last sentence describes a possible optimization for `executemany()`: Don't end individual Bind/Describe/Execute message with a Sync and wait for a server-response, just send large batches of Bind/Describe/Execute messages, followed by a single Sync at the end. This should reduce the performance penalty due to server round-trip time to a minimum.

[asyncpg](https://magicstack.github.io/asyncpg/current/) does exactly that: It puts many Bind/Execute commands into a single extended query message, only the final message of the batch has a Sync at the end.

I know that you're generally supposed to use `COPY` for large batch inserts (and the new `psycopg` makes it really easy), but sometimes (e.g. for batch updates) `executemany()` is more convenient.

**Comment by dvarrazzo** [comment]
Hello @sekrause thank you for your analysis and your input.

psycopg works at libpq level, which is the C library that handles the underlying protocol. So if the functionality is not exposed we cannot reach for it.

@dlax is currently working on the pipeline/batch mode (see #116, #74) which allows psycopg to make use of certain libpq functionalities included in PostgreSQL 14.

I seem to understand that at the moment what you suggest to do is not available in libpq but it would once the batch mode is available, is that right?

Actually, thinking about it, the work in #116 is mostly an high level construct on top of the libpq 14 functionalities, but Denis has already made them available (see dc18d9452731307270aa88c060069cbe2393ff45).

So, do I understand correctly that the right way to optimise executemany is to make use of the newly available pipeline/batch libpq calls?

**Comment by dvarrazzo** [comment]
In terms of timeline, Denis work is stuck on me to review it, which can't happen right now but next week should be possible, and it should released in 3.1. This might be a feature we can develop in parallel and independent from batch mode, which we might release in 3.1 too (or maybe in a 3.0.x if we are changing no interface).

Would you like to work on this feature yourself or yours is only a suggestion (which was very welcome, don't get me wrong :slightly_smiling_face:)

**Comment by dvarrazzo** [comment]
Thank you very much anyway. We will take a look but I suspect it's a simple enough improvement to make using the newly available libpq 14 functionalities.

**Comment by dvarrazzo** [comment]
Working on it in #260. See there for details.

**Comment by dvarrazzo** [comment]
Fixed by #260
