### ISSUE TITLE
-bb flag gives error re: bytes and strings

### ISSUE THREAD

**Issue by rojalator** [psycopg/psycopg#147]
We run our code with the python -bb flag to issue errors about string / byte comparisons. Doing so with psycopg3 results in:

`python3.9/site-packages/psycopg/_encodings.py", line 64, in <module>
    py_codecs.update((k.encode(), v) for k, v in _py_codecs.items())
`
This was not the case with psycopg2 (we are in the process of moving to psycopg3 from psycopg2)
Obviously our workaround is to just use -b (or none at all) - I note though, that #122 also indicates a UNICODE error so perhaps _encodings.py requires a bit more work.

Python 3.9
psycopg 3.0.3

**Comment by dvarrazzo** [comment]
Running the test suite on `-bb` reproduces the issue, so I should be good to fix it, thank you

**Comment by dvarrazzo** [comment]
Looks like you simply can't have a dict with `Union[str, bytes]` keys under `-bb`.

I'm taking a look if it's practical to remove these occurrences.

#122 is related to the content and the use of a database which is not currently supported.

**Comment by dvarrazzo** [comment]
A fix is on the way. Do you know if there is a practical way to enable running pytest with `-bb`? `python -bb -m pytest` seems the only way.

**Comment by rojalator** [comment]
I think that is the only way, although you could add it to the #! of any script, perhaps
#!/usr/bin/env python -bb

I looked all over (including the ini files) but have never found out how!

Thanks for the rapid fix.
RJL

**Comment by rojalator** [comment]
Thanks for the fix - I confirm that it works now for us with no problem.
