### ISSUE TITLE
Have a Django driver

### ISSUE THREAD

**Issue by rngallen** [psycopg/psycopg#156]
I have installed `psycopg` as `pipenv install psycopg`

My database settings 
``` "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", cast=int),
    },
```
But I keep getting error ```raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'```

Does this mean psycopg3 is not compatible with django(3.2.9) at the moment?
How can I resolve this on psycopg3?

**Comment by dvarrazzo** [comment]
At the moment Django is only compatible with psycopg 2. Work has been done to [adapt Django to psycopg 3](https://www.psycopg.org/articles/2021/08/02/psycopg3-django-driver/) but it hasn't been merged in Django yet.

You should hear from the Django people if they are interested to finalize the interaction. I would like to but I have other priorities at the moment.

**Comment by pauloxnet** [comment]
I would be happy to help integrate Psycopg 3 with Django 4.1
In this regard, I opened an issue on Django's ticketing system, to have a unique place for discussion.
https://code.djangoproject.com/ticket/33308

**Comment by dvarrazzo** [comment]
Thank you very much @pauloxnet! Please let us know what you need. Happy to coordinate on the django ticket you linked.

**Comment by dvarrazzo** [comment]
Django has now a psycopg 3 backend. Thank you very much, @pauloxnet, and everyone else working on this massive feature!

**Comment by pauloxnet** [comment]
> Django has now a psycopg 3 backend. Thank you very much, @pauloxnet, and everyone else working on this massive feature!

Thanks Daniele, I only add the information that Django 4.2+ is compatible only with Psycopg 3.1+.

At the moment (December 2022) Django 4.2 is still in development so to install it you have to follow the instruction "[Installing the development version](https://docs.djangoproject.com/en/dev/topics/install/#installing-the-development-version)" in the Django official documentation.

Please report issue in the [Django issue tracker](https://code.djangoproject.com/) if you found some issue.
