### ISSUE TITLE
macOS: kqueue file descriptor leak

### ISSUE THREAD

**Issue by qwesda** [psycopg/psycopg#158]
I was trying to pipe data from one server to another like this:

```python
with src_cur.copy("""COPY public.src_table TO STDOUT (FORMAT BINARY);""") as copy_src:
    with dst_cur.copy("""COPY public.dst_table FROM STDIN (FORMAT BINARY);""") as copy_dst:
        while data_row := copy_src.read():
            copy_dst.write(bytes(data_row))
```

and got the following error on bigger tables:

```
sending query failed: another command is already in progress
Traceback (most recent call last):
  File ".env/lib/python3.9/site-packages/psycopg/cursor.py", line 681, in copy
    yield copy
  File "src/run_psycopg3.py", line 27, in transfer_table_data
    while data_row := copy_src.read():
  File ".env/lib/python3.9/site-packages/psycopg/copy.py", line 204, in read
    return self.connection.wait(self._read_gen())
  File ".env/lib/python3.9/site-packages/psycopg/connection.py", line 767, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File ".env/lib/python3.9/site-packages/psycopg/waiting.py", line 53, in wait_selector
    sel = DefaultSelector()
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 512, in __init__
    self._selector = select.kqueue()
OSError: [Errno 24] Too many open files
```

macOS 12.0.1 (21A559)
Python 3.9.8
psycopg-binary 3.0.4

I was adapting my code for psycopg3, previously I used the following pattern for piping data between servers. Not sure if I'm using the v3 interface wrong ...

```python
dst_fd, src_fd = os.pipe()

def copy_dst():
    with os.fdopen(dst_fd) as read_f:
        dst_cur.copy_expert(f"""COPY public.dst_table FROM STDIN;""", read_f)

dst_thread = threading.Thread(target=copy_dst)
dst_thread.start()

with os.fdopen(src_fd, 'w') as write_f:
    src_cur.copy_expert("""COPY public.src_table TO STDOUT;""", write_f)

dst_thread.join()
```

**Comment by dvarrazzo** [comment]
Are both cursors open on the same connection?

**Comment by dvarrazzo** [comment]
Is this something that happens at the first read/write or after a few loop cycles? How large is the file, or wide? Does it matter?

Would you be able add a test to reproduce the failure to the test suite?

**Comment by qwesda** [comment]
I narrowed the code down to this:

```python
def main():
    import psycopg
    import os

    with psycopg.connect(dbname=os.getenv('PGDATABASE'),
                         user=os.getenv('PGUSER'),
                         password=os.getenv('PGPASS'),
                         host=os.getenv('PGHOST'),
                         port=os.getenv('PGPORT')) as conn:
        with conn.cursor() as cur:
            cur.execute("""
CREATE TEMP TABLE dump_test_table AS
SELECT 
    md5('00' || x::text)::text AS col_00,
    md5('01' || x::text)::text AS col_01,
    md5('02' || x::text)::text AS col_02,
    md5('03' || x::text)::text AS col_03,
    md5('04' || x::text)::text AS col_04,
    md5('05' || x::text)::text AS col_05,
    md5('06' || x::text)::text AS col_06,
    md5('07' || x::text)::text AS col_07
FROM generate_series(1, 10000000) AS x;""")

            with cur.copy("""COPY pg_temp.dump_test_table TO STDOUT;""") as copy:
                while copy.read():
                    pass


if __name__ == "__main__":
    main()
```

I also created a repo [psycopg3-copy-test](https://github.com/qwesda/psycopg3-copy-test) which contains the minimal test case and one script with params for row/column count.

Key findings:
- only the reading connection is needed to reproduce the error
- it is not specific to the `BINARY` format
- the error seems to happen after ~ 1.3GB have been read, so with wider tables the error is triggered after fewer rows
- the connection is unusable after the error occurred, calling `rollback` or leaving the with scope triggers an additional error `psycopg.OperationalError: sending query failed: another command is already in progress`

**Comment by qwesda** [comment]
> Would you be able add a test to reproduce the failure to the test suite?

I'm not completely sure if this test will work for your test suite/test runner setup, so I'm just passing it here instead of creating a pull request ... 

```python
@pytest.mark.slow
def test_large_copy_to(conn):
    cur = conn.cursor()

    cur.execute("""
CREATE TEMP TABLE dump_test_table AS
SELECT 
    md5('00' || x::text)::text AS col_00,
    md5('01' || x::text)::text AS col_01,
    md5('02' || x::text)::text AS col_02,
    md5('03' || x::text)::text AS col_03,
    md5('04' || x::text)::text AS col_04,
    md5('05' || x::text)::text AS col_05,
    md5('06' || x::text)::text AS col_06,
    md5('07' || x::text)::text AS col_07,
    md5('08' || x::text)::text AS col_08,
    md5('09' || x::text)::text AS col_09,
    md5('10' || x::text)::text AS col_10,
    md5('11' || x::text)::text AS col_11,
    md5('12' || x::text)::text AS col_12,
    md5('13' || x::text)::text AS col_13,
    md5('14' || x::text)::text AS col_14,
    md5('15' || x::text)::text AS col_15
FROM generate_series(1, 10000000) AS x;""")
    
    with cur.copy("""COPY pg_temp.dump_test_table TO STDOUT;""") as copy:
        while copy.read():
            pass

    assert conn.pgconn.transaction_status == conn.TransactionStatus.INTRANS
```

**Comment by dvarrazzo** [comment]
Thank you, that's useful finding. And yes, as only one side of the copy is requested, it does seem a resource leak. However it seems that the bug is in the python selectors module.

I will check that we are not doing anything abviously stupid there, and in case not we will forward the issue to some Python tracker.

**Comment by dvarrazzo** [comment]
> If you think it should be ok, than I'll create a pull request.

Sure, so we would test other selectors too (epoll, and whatever windows uses).

Can you please:

- save your test in a separate module in one commit
- change the test run command lines so that only your test is executed

For how long does your test run before crashing? If possible don't make the data size much bigger than that.

**Comment by qwesda** [comment]
> For how long does your test run before crashing? If possible don't make the data size much bigger than that.

I added the test and reduced the generated line to the (approx.) minimum to get a reliable exception on my machine (3_000_000 with 16 column).

> * change the test run command lines so that only your test is executed

can you give me a hint where to do that?

**Comment by dvarrazzo** [comment]
> can you give me a hint where to do that?

You can run your test on the CI with something like (untested):

```diff
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
index e7f42ecc..b2154e01 100644
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -70,13 +70,13 @@ jobs:
 
       - name: Run tests (Python implementation)
         if: ${{ matrix.impl == 'python' }}
-        run: tox -c psycopg -e ${{ matrix.python }}
+        run: tox -c psycopg -e ${{ matrix.python }} -- tests/copy_to_large.py
 
       - name: Run tests (C implementation)
         if: ${{ matrix.impl == 'c' }}
         # skip tests failing on importing psycopg_c.pq on subprocess
         # they only fail on Travis, work ok locally under tox too.
-        run: tox -c psycopg_c -e ${{ matrix.python }} -- -m 'not subprocess'
+        run: tox -c psycopg_c -e ${{ matrix.python }} -- -m 'not subprocess' tests/copy_to_large.py
 
       - name: Run DNS-related tests
         if: ${{ matrix.impl == 'dns' }}
@@ -151,11 +151,11 @@ jobs:
 
       - name: Run tests (Python implementation)
         if: ${{ matrix.impl == 'python' }}
-        run: tox -c psycopg -e ${{ matrix.python }}
+        run: tox -c psycopg -e ${{ matrix.python }} -- tests/copy_to_large.py
 
       - name: Run tests (C implementation)
         if: ${{ matrix.impl == 'c' }}
-        run: tox -c psycopg_c -e ${{ matrix.python }}
+        run: tox -c psycopg_c -e ${{ matrix.python }} -- tests/copy_to_large.py
 
 
   # }}}
@@ -202,7 +202,7 @@ jobs:
 
       - name: Run tests (Python implementation)
         if: ${{ matrix.impl == 'python' }}
-        run: tox -c psycopg -e ${{ matrix.python }}
+        run: tox -c psycopg -e ${{ matrix.python }} -- tests/copy_to_large.py
 
       # Build a wheel package of the C extensions.
       # If the wheel is not delocated, import fails with some dll not found
@@ -226,7 +226,7 @@ jobs:
           &"pip" install @(Get-ChildItem wheelhouse\*.whl)
           # Fix the path for the tests using ctypes
           $env:Path = "C:\Program Files\PostgreSQL\14\bin\;$env:Path"
-          pytest
+          pytest tests/copy_to_large.py
 
 
   # }}}
```

**Comment by qwesda** [comment]
The tests seem to work fine, but they do not fail when being run by the GitHub runners.

I added a step to the macOS to show the result of `launchctl limit maxfiles` which is supposed to show the max number of file descriptors available.

On my system the command showed `maxfiles    256    unlimited` on the test runner it shows `maxfiles    65536          524288`.

If tried to change the limit with `sudo launchctl limit maxfiles 1000000 1000000`, but I still got the same error on my machine anyway:

```
generating 16 columns with 3,000,000 rows ... 0:00:30.529326
dumping table ... 0:00:08.440896
2,594,204 rows, 1,369,739,712B
```

I also tried to increase the amount of rows to 20M, but the tests still succeeded.

I'm kind of stumped ...

**Comment by dvarrazzo** [comment]
Anything relevant here? https://github.com/osquery/osquery/issues/3984

**Comment by obi1666** [comment]
I've been seeing the same problem. 
This has occurred since upgrade from Psycopg2 ->3 and Python 3.9.7 ->3.9.8

**Comment by obi1666** [comment]
> I've been seeing the same problem. This has occurred since upgrade from Psycopg2 ->3 and Python 3.9.7 ->3.9.8
> 
> MacOS 10.14.6

Increase maxfiles. seems to work so far.

**Comment by dvarrazzo** [comment]
@obi1666 how did you increase maxfiles? Can you suggest @qwesda what worked for you?

It doesn't seem that we are doing something wrong here. If any maybe we might add a note about the issue in the documentation?

**Comment by qwesda** [comment]
> Anything relevant here? [osquery/osquery#3984](https://github.com/osquery/osquery/issues/3984)

not as far as I can see.

> Increase maxfiles. seems to work so far.

It didn't work for me, I used 
```
> sudo launchctl limit maxfiles 100000 100000`
> launchctl limit maxfiles
maxfiles    100000         100000
> python run.py --column 16 --rows 3_000_000
generating 16 columns with 3,000,000 rows ...
dumping table ... 0:00:08.627152
2,594,204 rows, 1,369,739,712B
OSError: [Errno 24] Too many open files
```

**Comment by qwesda** [comment]
I have also been running a small script that monitors the kqueue count for the process (about 16 samples per second):

```
53, 23, 124, 78, 41, 85, 120, 101, 135, 107, 74, 28, 133, 86, 52, 125, 73, 54, 158, 103, 38, 91, 34, 54, 
164, 138, 86, 171, 171, 139, 116, 65, 70, 132, 94, 51, 165, 134, 77, 187, 121, 66, 129, 143, 76, 80, 149, 
109, 74, 181, 161, 95, 187, 158, 120, 84, 40, 169, 128, 75, 178, 140, 84, 197, 176, 127, 78, 187, 142, 90, 
190, 142, 126, 82, 183, 153, 117, 75, 162, 127, 107, 73, 187, 131, 96, 151, 114, 217, 185, 120, 113, 79, 194, 
163, 139, 112, 210, 181, 184, 141, 111, 211, 133, 204, 162, 111, 179, 115, 221, 174, 113, 195, 143, 86, 88, 
217, 107, 224, 211, 237, 204, 244, 93, 117, 234, 186, 86, 0, 0, 0, 0, 0, 0, 0, 0, 0
```

The code where the leak "happens" should be here, but everything looks ok to me. I did some debugging and `sel.register`/`sel.unregister` seem to be called 1 for 1. So there shouldn't be a leak here ...

Is there any documentation about `unregister` not happening instantly?

**Comment by qwesda** [comment]
I have also been running more test variants. The ~1.3GB datapoint is remarkably consistent – even with 128 columns I got.

```
generating 128 columns with 500,000 rows ... 0:08:14.675379
dumping table ... 0:02:22.545183
326,957 rows, 1,381,066,368B
[Errno 24] Too many open files
```

I thought the leak would be more closely associated with the number of row than with the total amount of bytes.
Could it be that the leak happens for every "chunk" of bytes from the connection and not for every row?

**Comment by dvarrazzo** [comment]
> I thought the leak would be more closely associated with the number of row than with the total amount of bytes.

I would have been surprised about the opposite. This seems a problem with your machine network stack, not with postgres and its client.

**Comment by obi1666** [comment]
> @obi1666 how did you increase maxfiles? Can you suggest @qwesda what worked for you?
I just just used
```sh
launchctl limit maxfiles 2048 unlimited
```
So far so good.

> 
> It doesn't seem that we are doing something wrong here. If any maybe we might add a note about the issue in the documentation?

I would have been surprised if it was a PscyoPG or Python problem. Thought it was worth noting, though.

**Comment by obi1666** [comment]
> > I thought the leak would be more closely associated with the number of row than with the total amount of bytes.
> 
> I would have been surprised about the opposite. This seems a problem with your machine network stack, not with postgres and its client.

I will try to investigate the numbers of rows being submitted in each transaction block.

**Comment by dvarrazzo** [comment]
@obi1666 

> Thought it was worth noting, though.

It is: I wouldn't mind to have the problem - and its solution - mentioned in the docs

**Comment by obi1666** [comment]
> > > I thought the leak would be more closely associated with the number of row than with the total amount of bytes.
> > 
> > 
> > I would have been surprised about the opposite. This seems a problem with your machine network stack, not with postgres and its client.
> 
> I will try to investigate the numbers of rows being submitted in each transaction block.

Firstly I am using the new connection and transactions contexts in PsycoPG 3
```python
with psycopg.connect(..., autocommit=True) as outSQL:
  dbCursor = outSQL.cursor()
  ...
  for tx in txlist:
    with outSQL.transaction():
      for subtx in tx:
        dbcursor.execute(...)
    ...

```

Previously I had said that increasing the maxfile limit to 2048 seems to have helped.
However after a restart I neglected to increase the limit again so the system default of 256 was reinstated and things were working fine even with pending commits in the order of 5000 rows.
Then, for no apparent reason, the fault reappeared.


```
error ignored rolling back transaction on <psycopg.Connection [ACTIVE] (user=[redacted] database=[redacted]) at 0x10b78a220>: sending query failed: another command is already in progress
Traceback (most recent call last):
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/connection.py", line 744, in transaction
    yield tx
  File "[redacted].py", line 113, in <module>
    dbCursor.execute(\
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/cursor.py", line 558, in execute
    self._conn.wait(
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/connection.py", line 767, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/waiting.py", line 53, in wait_selector
    sel = DefaultSelector()
  File "/[redacted]/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 512, in __init__
    self._selector = select.kqueue()
OSError: [Errno 24] Too many open files
```
line 125 mentioned below is the end of the transaction block.
The error continues
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/[redacted].py", line 125, in <module>	
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/connection.py", line 744, in transaction
    yield tx
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/transaction.py", line 205, in __exit__
    return self._conn.wait(self._exit_gen(exc_type, exc_val, exc_tb))
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/connection.py", line 767, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/waiting.py", line 52, in wait_selector
    s = next(gen)
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/transaction.py", line 125, in _exit_gen
    return (yield from self._rollback_gen(exc_val))
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/transaction.py", line 172, in _rollback_gen
    yield from self._conn._exec_command(b"; ".join(commands))
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/connection.py", line 421, in _exec_command
    self.pgconn.send_query(command)
  File "psycopg_binary/pq/pgconn.pyx", line 223, in psycopg_binary.pq.PGconn.send_query
psycopg.OperationalError: sending query failed: another command is already in progress
```

again, this is Python 3.9.8, PsycoPG 3, MacOS 10.14.6

**Comment by dvarrazzo** [comment]
Thank you @obi1666 

The second error is caused by the transaction context failing to detect that the connection is not in a state to receive a rollback: see #165. If you try your code without that block you should see only the first traceback.

Can you "clean" your example so maybe we can ask some cpython person about it?

**Comment by dvarrazzo** [comment]
(actually I'm probably wrong: the transaction block has that bug, yes, but the connection only checks for close, so it would try to run the query in transaction_state = ACTIVE, causing the same error).

**Comment by obi1666** [comment]
Reverted to old code that worked on PsycoPG2 ( ie without connection or transaction contexts.) but still importing PsycoPG3.

Line 78 is a cursor `execute` call
```
Traceback (most recent call last):
  File "/[redacted].py", line 78, in <module>
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/cursor.py", line 558, in execute
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/connection.py", line 767, in wait
  File "/[redacted]/Library/Python/3.9/lib/python/site-packages/psycopg/waiting.py", line 53, in wait_selector
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 512, in __init__
OSError: [Errno 24] Too many open files
```

This is occurring with maxfiles set at both the system default of 256 and 8192.

**Comment by obi1666** [comment]
I have completely reverted back to a reinstalled PsycoPG2. So far no problems.

**Comment by dvarrazzo** [comment]
> Reverted to old code that worked on PsycoPG2 ( ie without connection or transaction contexts.) but still importing PsycoPG3.

Thank you @obi1666, that's a clean repro.

Everything must be happening at:

https://github.com/psycopg/psycopg/blob/095ed4bec7148a92c1e0e55175fba2d91668fb76/psycopg/psycopg/waiting.py#L55-L60

Could you please add a couple of prints to take a look at whether, for some reason, we are registering but not unregistering? (The only reason I can see would be a `StopIteration` thrown in the middle but that should happen only once...)

If you verify that the calls are well paired I will ask some Python dev to take a look.

**Comment by qwesda** [comment]
> Could you please add a couple of prints to take a look at whether, for some reason, we are registering but not unregistering?

I already did this:

>  I did some debugging and `sel.register`/`sel.unregister` seem to be called 1 for 1.

In my tests they calls seemed perfectly balanced ... that's why I was asking if it is possible that `unregister` doesn't happen immediately.

I also tested replacing `DefaultSelector` with `SelectSelector` here:

https://github.com/psycopg/psycopg/blob/095ed4bec7148a92c1e0e55175fba2d91668fb76/psycopg/psycopg/waiting.py#L52-L60

The error didn't occur than – I tested it up to 200GB ...

```
./run.sh --column 64 --rows 100_000_000

generating 64 columns with 100,000,000 rows ... 2:21:35.730972
dumping table ... 1:11:01.325175
100,000,000 rows, 201,416MB
```

**Comment by dvarrazzo** [comment]
Hi @qwesda 

Uhm, maybe we are read the wrong thing all this time? Looking at your original stacktrace:
```
  File ".env/lib/python3.9/site-packages/psycopg/waiting.py", line 53, in wait_selector
    sel = DefaultSelector()
```
the error is on creation of the selector, not on register.

Looking better at these objects, they support a `close()` method to release resources, as well as a context block.

Could you please check if with the changeset 16699baf6147d702a7c32ca68aefba9557cbd821 fixes the problem?

Thank you very much

**Comment by qwesda** [comment]
> Could you please check if with the changeset [16699ba](https://github.com/psycopg/psycopg/commit/16699baf6147d702a7c32ca68aefba9557cbd821) fixes the problem?

jepp, that seems to be it! 

I tested it up to 15GB and the kqueue count oscillates between `1` and `0`.

**Comment by dvarrazzo** [comment]
Amazing! Thank you for testing! Committing this, to release soon (in 3.0.5).
