### ISSUE TITLE
cursor.description raises  "psycopg.OperationalError", other members do not.

### ISSUE THREAD

**Issue by rojalator** [psycopg/psycopg#172]
If I call rowcount, statusmessage, rownumber (and even _query) on a cursor where the cursor is "psycopg.Cursor [TUPLES_OK] [BAD]" (that is, closed) I have no problem, however, if I try to call 'description' I get an OperationalError and cannot get the value (looks like _ensure_pgconn raises the exception). 
This seems counter-intuitive: if I can get the other values and I have the results in set of tuples, why can I not get the description? Is it the use of a row factory that is the issue?

If so, or the description is not available when the other values are, could you update 'Information about the data' to indicate that?

psycopg 3.0.4, python 3.9.0, linux

Regards,
RJL

**Comment by dvarrazzo** [comment]
Thank you for the report.

It is a side effect of asking the connection for the client encoding. We can probably work around it by storing the client encoding in the cursor just before running the query.

I'm finding a few other small issues to clean up around the same issue (e.g. #173). If there aren't big reason stopping to use `cursor.description` with a closed connection I'll fix this too and release in 3.0.6.

**Comment by rojalator** [comment]
OK, thanks.

**Comment by dvarrazzo** [comment]
Released, fyi. Thank you for the report :)
