### ISSUE TITLE
cursor.rowcount with cursor.executemany() regression as of 3.0.6

### ISSUE THREAD

**Issue by zzzeek** [psycopg/psycopg#178]
heya -

this started failing as of psycopg 3.0.6.  passes with 3.0.5

```py
import psycopg

conn = psycopg.connect(user="scott", password="tiger", dbname="test", host="pg13")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE parent (
	id SERIAL NOT NULL,
	data INTEGER,
	PRIMARY KEY (id)
)
""")
cursor.executemany("""INSERT INTO parent (id, data) VALUES (%(id)s::INTEGER, %(data)s::INTEGER)""",
    ({'id': 1, 'data': 2}, {'id': 2, 'data': 3})
)
cursor.execute("""DELETE from parent""")

assert cursor.rowcount == 2

cursor.executemany("""DELETE FROM parent WHERE parent.id = %(id)s::INTEGER""", ({'id': 1}, {'id': 2}))
assert cursor.rowcount == 0, f"{cursor.rowcount}"
```

or more simply

```py
import psycopg

conn = psycopg.connect(user="scott", password="tiger", dbname="test", host="pg13")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE parent (
	id SERIAL NOT NULL,
	data INTEGER,
	PRIMARY KEY (id)
)
""")

cursor.executemany("""DELETE FROM parent WHERE parent.id = %(id)s::INTEGER""", ({'id': 1}, {'id': 2}))
assert cursor.rowcount == 0, f"{cursor.rowcount}"
```

also fails.

the cursor.rowcount is -1 when using version 3.0.6, it's 0 for previous versions.    it seems to be related executemany() not matching any rows.

**Comment by dvarrazzo** [comment]
Thank you for the report!

Yes, a botched refactoring.

There is worse: executemany with an empty sequence crashes too (#179) which means I'm going to release a 3.0.7 soon.

Could you please check if 127bf849b0ef1c4a17952d6b2e686eb9db73064d passes your tests? Or is it complicated to test it on your part?

By the way, I wouldn't mind to have SQLAlchemy tests in our regression suite. Maybe I could use your help (or some other SQLAlchemy person's) to set it up.

**Comment by zzzeek** [comment]
I think it works, though installing with pip is being weird.   whats the pip command to build a wheel without setup.py present?

**Comment by dvarrazzo** [comment]
Thank you for checking :)

`setup.py` is in the `psycopg` subdir (because there are others, to release other packages, in other dirs). It's enoughro run `pip install ./psycopg` or `python psycopg/setup.py`. Before starting to release wheels we had this suggestion in the readme:

? It is possible to install from github using `pip install git+https://github.com/psycopg/psycopg.git#subdirectory=psycopg`

**Comment by zzzeek** [comment]
yeah, something strange is happening when i do pip install from the source directory.  if i cd into any directory that has a .git checkout, the Python interpreter can't find "psycopg".  if cd to a non-git directory, then it can.  not sure if there's some magic because I installed from a .git tree.
