### ISSUE TITLE
Implement Range data types

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#19]

**Comment by dvarrazzo** [comment]
Work in progress in https://github.com/psycopg/psycopg3/tree/range-adaptation

Need to complete tests, add custom ranges catalog lookup and registration, debugging all the possible quote chars. Maybe binary?

**Comment by lelit** [comment]
Having read about [multirange](https://www.depesz.com/2020/12/21/waiting-for-postgresql-14-multirange-datatypes/), I wonder how they will be represented on the Python side.

**Comment by dvarrazzo** [comment]
I haven't looked into them yet

**Comment by dvarrazzo** [comment]
Basic objects [implemented](https://www.psycopg.org/psycopg3/docs/basic/pgtypes.html#range-adaptation). See #75 to introduce multirange support.
