### ISSUE TITLE
Add support for numpy types

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#192]
Numpy types are used by Pandas. `numpy.int32` maps well to Postgres int4, but it doesn't inherit from Python int, so dumping fails out-of-the-box (see #193).

Registering `Int4Dumper` works well for the text type, but binary support could be added.

This is a nice chunky feature I would love to see developed.

**Comment by dvarrazzo** [comment]
Added #336 for the natural prosecution

**Comment by itsankitkp** [comment]
Hey @dvarrazzo Can I take this up? Also, can you suggest some good starting pointers?

**Comment by dvarrazzo** [comment]
@itsankitkp it's in progress in #332

**Comment by itsankitkp** [comment]
> @itsankitkp it's in progress in #332

Sorry I missed that, thanks for head up
