### ISSUE TITLE
Need string quoting function for DDL commands

### ISSUE THREAD

**Issue by nagylzs** [psycopg/psycopg#199]
Example:

```
connection.execute("ALTER USER postgres WITH PASSWORD %s", [ "some_password" ])
```

The above statement produces this error **on the PostgreSQL server**:

```
2022-01-05 17:35:25.831 CET [58] ERROR:  syntax error at or near "$1" at character 35
2022-01-05 17:35:25.831 CET [58] STATEMENT:  ALTER USER postgres WITH PASSWORD $1
```

The problem is that some DDL commands don't accept parameters. The only possible solution is to quote these values on the client side, and send the command to the server as a single string, without parameters.

Since psycopg3 does not provide a function to quote strings safely, every user needs to implement his/her own version of string quoting. Some of them might contain errors and lead to program crash or even SQL injection. I think that it would be better if psycopg3 provided its own quoting function (at least for strings).

**Comment by dvarrazzo** [comment]
> The issue is know and the workarounds documented.

@nagylzs We can extend or replace this example in the documentation linked above

```python
from psycopg import sql
conn.execute(sql.SQL("CREATE TABLE foo (id int DEFAULT {})").format(42))
```

to show the ALTER USER ... PASSWORD you proposed, because it's not clear, from the example with the 42, that strings get quoted.
