### ISSUE TITLE
(question) more pythonic wrapper for libpq ?

### ISSUE THREAD

**Issue by philpep** [psycopg/psycopg#201]
Hi thanks for this new psycopg!

I'm writing some code to implement client side encryption of password using PQencryptPasswordConn, the resulting code looks like:

```python
import psycopg.pq
import psycopg.pq.abc
import psycopg.sql as sql


def encrypt_password(conn: psycopg.pq.abc.PGconn, role: str, password: str) -> str:
    return conn.encrypt_password(password.encode(), role.encode()).decode()

with psycopg.connect() as c:
    c.execute(
        sql.SQL("ALTER ROLE foo WITH PASSWORD {}").format(
            sql.Literal(encrypt_password(c.pgconn, "foo", "secret"))
        )
    )

```

I wonder If we could get rid of encode(), decode() and have an intermediate wrapper on top of libpq which could be more "pythonic".
Also it would be nice to type with `psycopg.pq.PGconn` instead of `psycopg.pq.abc.PGConn`.

What do you think?

**Comment by dvarrazzo** [comment]
Hello,

> Hi thanks for this new psycopg!

:upside_down_face: 

> I wonder If we could get rid of encode(), decode() and have an intermediate wrapper on top of libpq which could be more "pythonic".

the underlying PGconn is a thin wrapper around the libpq c calls, so it's bytes-based.  Its aim is to be complete, more than Pythonic (it is already pythonised in error management etc.)

Psycopg builds on top of it, and typically has a concept of current encoding (which is the connection client encoding) and is typically string-based. For instance:

```
In [4]: conn = psycopg.connect()

In [8]: conn.pgconn.user
Out[8]: b'piro'

In [10]: conn.info.user
Out[10]: 'piro'
```

I'm open to "pythonise more", and I think that psycopg is the right layer to do it, not psycopg.pq. However, I wouldn't like to bloat the connection interface too much. So, where could we put this helper function? on `ConnectionInfo` (i.e. `conn.info.enctypt_password()`) doesn't feel right either.

Note: your helper function assumes utf-8 encoding. A better implementation is probably:

```python
def encrypt_password(conn: psycopg.Connection, role: str, password: str) -> str:
    enc = conn.info.encoding
    return conn.pgconn.encrypt_password(password.encode(enc), role.encode(enc)).decode(enc)
```

----

> Also it would be nice to type with psycopg.pq.PGconn instead of psycopg.pq.abc.PGConn.

`psycopg.pq.PGconn` is an object re-exposed, which might be imported from `psycopg.pq.pq_ctypes.PGconn`, `psycopg_c.pq.PGconn`, `psycopg_binary.pq.PGconn`. They all share the same interface: `psycopg.abc.PGconn`. I am not sure that we can make mypy happy by having `psycopg.pq.PGconn` to be both a concrete object and an interface for the other implementation.

Also note that the `__module__` attribute for `psycopg.pq.pq_ctypes.PGconn` is customized to `psycopg.pq.PGconn`: this is probably not helpful: I think the customization should be removed.

Open to listen and to improve on both the points :)

**Comment by dvarrazzo** [comment]
> Also note that the `__module__` attribute for `psycopg.pq.pq_ctypes.PGconn` is customized to `psycopg.pq.PGconn`: this is probably not helpful: I think the customization should be removed.

Changing this. Now it should be more obvious that, when you use the interface, `psycopg.pq.abc.PGconn` you may refer to `psycopg.pq.pq_ctypes.PGconn`, `psycopg_c.pq.PGconn` or to any other object implementing the same interface.

It still needs documentation though...
