### ISSUE TITLE
Add support for anonymous records

### ISSUE THREAD

**Issue by bikeshedder** [psycopg/psycopg#207]
In the code base I'm currently working on there is often the need to perform subqueries and get the result back in a structured way. Currently the code internally uses a lot of this is mainly done using the `array` and various `jsonb_*` functions.

## Example schema + data

```sql
CREATE TABLE "food" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "name" citext UNIQUE NOT NULL,
    "calories" integer NOT NULL
);

CREATE TABLE "user" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "name" citext UNIQUE NOT NULL
);

CREATE TABLE "user_favorite_food" (
    "user_id" BIGINT REFERENCES "user" ("id") ON DELETE CASCADE,
    "food_id" BIGINT REFERENCES "food" ("id") ON DELETE CASCADE
);

WITH
    jane AS (
        INSERT INTO "user" (name) VALUES ('Jane') RETURNING id
    ),
    john AS (
        INSERT INTO "user" (name) VALUES ('John') RETURNING id
    ),
    pommes AS (
        INSERT INTO "food" (name, calories) VALUES ('Pommes', 437) RETURNING id
    ),
    pizza AS (
        INSERT INTO "food" (name, calories) VALUES ('Pizza', 637) RETURNING id
    ),
    hotdog AS (
        INSERT INTO "food" (name, calories) VALUES ('Hotdog', 426) RETURNING id
    )
INSERT INTO "user_favorite_food"
    (user_id, food_id)
VALUES
    ((SELECT id from jane), (SELECT id FROM pommes)),
    ((SELECT id from jane), (SELECT id FROM pizza)),
    ((SELECT id FROM john), (SELECT id FROM pommes)),
    ((SELECT id FROM john), (SELECT id FROM hotdog));
```

## Example queries

```sql
SELECT
   u.name,
   array((
       SELECT jsonb_build_object(
           'name', f.name,
           'calories', calories
       )
       FROM user_favorite_food AS uff, food AS f
       WHERE uff.user_id = u.id AND uff.food_id = f.id
   ))
FROM
   "user" AS u;
```

Output:

```
 name |                                           array                                           
------+-------------------------------------------------------------------------------------------
 Jane | {"{\"name\": \"Pommes\", \"calories\": 437}","{\"name\": \"Pizza\", \"calories\": 637}"}
 John | {"{\"name\": \"Pommes\", \"calories\": 437}","{\"name\": \"Hotdog\", \"calories\": 426}"}
```

(I know that this query would be faster with a normal `INNER JOIN` + `array_agg`. This code is generated as part of our query builder which also allows deeply nested queries. e.g. getting the friends of friends of friends, etc. that's why it's all done as subqueries and not `JOIN`s.)

I do despise using `JSONB` as  a transfer format between the database and the python code. I'd rather like to use anonymous records here. e.g.

```sql
SELECT
   u.name,
   array((
       SELECT (
           f.name,
           f.calories
       )
       FROM user_favorite_food AS uff, food AS f
       WHERE uff.user_id = u.id AND uff.food_id = f.id
   ))
FROM
   "user" AS u;
```

Output:

```
 name |              array              
------+---------------------------------
 Jane | {"(Pommes,437)","(Pizza,637)"}
 John | {"(Pommes,437)","(Hotdog,426)"}
```

## Parsing arrays and records

The only way to parse those results is by registering a new type in the database and then using a `RecordLoader`. Those queries however are generated dynamically and I don't think it's a good idea to flood the database with new OIDs for one-time queries. My query builder knows exactly what types to expect and the database shouldn't even bother.

Looking at the current implementation of `CompositeInfo` and `CompositeLoader` it seams that all the logic depends on actual OIDs to exist and there is no way to work around that.

## Proposed interface

I don't have a clear idea how to implement such loader so it fits the psycopg philosophy. I guess it should look somewhat similar to that:

```python
food_records = Loader(Array(AnonymousRecord(str, int)))
for row in rows:
    print(f"{row[0] favourite food:")
    for food in food_records.load(row[1]):
        print(f"- {food[0]}")
```

An even niftier interface would be to support dataclasses:

```python
@dataclass
class FavouriteFood:
    name: str
    calories: int

loader = Loader(Array(FavouriteFood))

for row in rows:
    print(f"{row[0] favourite food:")
    for food in loader.load(row[1]):
        print(f"- {food[0]}")
```

Both interface styles make sense. The former is great for dynamically generated queries (e.g. via GraphQL APIs) and the latter could provide typing information when writing code. `loader.load` could be annotated so that it knows that it returns `List[FavouriteFood]` and not just `Any`.

**Comment by dlax** [comment]
Maybe using [row factories](https://www.psycopg.org/psycopg3/docs/advanced/rows.html) could help?
```python
@dataclass
class FavouriteFood:
    name: str
    calories: int

def row_factory(cur):
    def make_row(values):
        name, ffoods = values
        return name, [FavouriteFood(*v) for v in ffoods]

    return make_row

conn = psycopg.connect()
cur = conn.cursor(row_factory=row_factory)
qs = """\
SELECT
   u.name,
   array((
       SELECT (
           f.name,
           f.calories
       )
       FROM user_favorite_food AS uff, food AS f
       WHERE uff.user_id = u.id AND uff.food_id = f.id
   ))
FROM
   "user" AS u;
"""
for row in cur.execute(qs):
    print(row)                                     
```

**Comment by bikeshedder** [comment]
That's quite nice. I didn't know psycopg 3 now supports parsing anonymous records and arrays of them...

```python
>>> list(cur.execute(qs))
[('Jane', [('Pommes', '437'), ('Pizza', '637')]), ('John', [('Pommes', '437'), ('Hotdog', '426')])]
```

I just checked and parsing top-level arrays of anonymous records works fine. It does however fail for arrays nested inside anonymous records. e.g.:

```python
>>> qs = """\
SELECT
   u.name,
   array(
       SELECT (
           f.name,
           f.calories,
           array(
               SELECT xu.name
               FROM user_favorite_food AS xuff, "user" AS xu
               WHERE xuff.user_id = xu.id AND xuff.food_id = f.id
           )
       )
       FROM user_favorite_food AS uff, food AS f
       WHERE uff.user_id = u.id AND uff.food_id = f.id
   )
FROM
   "user" AS u;
"""
>>> list(cur.execute(qs))
[('Jane', [('Pommes', '437', '{Jane,John}'), ('Pizza', '637', '{Jane}')]), ('John', [('Pommes', '437', '{Jane,John}'), ('Hotdog', '426', '{John}')])]
```

I guess psycopg has no way of autodetecting the types in this case?

**Comment by dvarrazzo** [comment]
There is a way: using binary data, Postgres will pass the client more information into the data, including the oid of the composite type's component:
```python
>>> import psycopg
>>> cnn = psycopg.connect()
>>> cur = cnn.cursor(binary=True)
>>> cur.execute(qs).fetchall()
[(b'Jane',
  [(b'Pommes',
    437,
    b'\x00\x00\x00\x01\x00\x00\x00\x00\x00>\xfd\xe9\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x04Jane\x00\x00\x00\x04John'),
   (b'Pizza',
    637,
    b'\x00\x00\x00\x01\x00\x00\x00\x00\x00>\xfd\xe9\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x04Jane')]),
 (b'John',
  [(b'Pommes',
    437,
    b'\x00\x00\x00\x01\x00\x00\x00\x00\x00>\xfd\xe9\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x04Jane\x00\x00\x00\x04John'),
   (b'Hotdog',
    426,
    b'\x00\x00\x00\x01\x00\x00\x00\x00\x00>\xfd\xe9\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x04John')])]
```

now... this doesn't look very nice, does it? The problem is that you used `citext`, which is an extension type, and as such its oid is not known (you really made a point of using _all_ the Postgres features, didn't you? :smile: ) You can see that `b'Pizza'` is returned as bytes, and the binary strings you can see are binary arrays (of citext).

We can inspect the database to get the information about citext and register the same loaders used to load text in order to load the data correctly.

The `psycopg.types.TypeInfo` object allow to fetch and manage information about Postgres types. 

```
>>> citext = psycopg.types.TypeInfo.fetch(cnn, "citext")
>>>  print(citext)
<TypeInfo: citext (oid: 4128233, array oid: 4128238)>
```

If it's registered on a connection (or a cursor), it allows to associate the oid of an array to the oid of its base type:

```python
>>> citext.register(cnn)
>>> cur = cnn.cursor(binary=True)
>>> cur.execute(qs).fetchall()
[(b'Jane', [(b'Pommes', 437, [b'Jane', b'John']), (b'Pizza', 637, [b'Jane'])]),
 (b'John',
  [(b'Pommes', 437, [b'Jane', b'John']), (b'Hotdog', 426, [b'John'])])]
```

That's better: Psycopg identified the array, but it's still returned as byte arrays because we don't have a loader associated. Because citext is pretty much text, we can use the same loaders used to load the `text` types (which will decode the binary using the connection encoding).

```python
>>> cnn.adapters.register_loader("citext", psycopg.types.string.TextBinaryLoader)
>>> cnn.adapters.register_loader("citext", psycopg.types.string.TextLoader)

>>> cur = cnn.cursor(binary=True)
>>> cur.execute(qs).fetchall()
[('Jane', [('Pommes', 437, ['Jane', 'John']), ('Pizza', 637, ['Jane'])]),
 ('John', [('Pommes', 437, ['Jane', 'John']), ('Hotdog', 426, ['John'])])]
```

So, with a bit of preparation of the connection, I think it's possible to manage the unstructured data you are requesting.

**Comment by dvarrazzo** [comment]
Note: most of the documentation about these things is in the [Data adaptation configuration](https://www.psycopg.org/psycopg3/docs/advanced/adapt.html) page. However the link to the `TypeInfo` object is weaker that what it should: most of it is in the [`psycopg.types`](https://www.psycopg.org/psycopg3/docs/api/types.html#types-information) API page, and I think some conceptual info should be in the former.

So I guess we could improve the docs a bit, but apart from that this seems working as expected. Documentation patches which you think might help an user to dive into this topic are welcome.
