### ISSUE TITLE
SyntaxError when executing \connect <db>

### ISSUE THREAD

**Issue by babaMar** [psycopg/psycopg#215]
when executing `_session.execute("\\connect %s", (_session.__my_db_name__,))` I get:
 ```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "\"
```

I know psql metacommands are not supposed to be executable, but I'm trying to switch to another database within the current session via registering an event listener, and therefore avoiding to open another connection (working with connection pooling by SQLAlchemy).

Is there a way to do this?

I tried connecting with `psql -E ...` and executing the command, though it doesn't show anything more than the usual

**Comment by dvarrazzo** [comment]
No, it is not possible. Backslash commands are psql only commands. You need to open a new connection.

**Comment by babaMar** [comment]
> No, it is not possible. Backslash commands are psql only commands. You need to open a new connection.

I understand backslash commands are psql-only ones. Does that mean there is no SQL counterpart to do that?

**Comment by dvarrazzo** [comment]
Surely not to `\c`. There is no sql counterpart of closing a connection and connecting to another database. Other commands such as `\d` result in a bunch of queries executed and the data obtained presented to the user, you know already that you can see those queries using `-E`.

`\c` in psql consist in closing the connection and creating another connection. If you want to do the same in Python you have to create a new connection object.
