### ISSUE TITLE
WHERE IN does not seem to work in psycopg3?

### ISSUE THREAD

**Issue by anaderichs** [psycopg/psycopg#216]
I tried the following. while `product_uuids` is a list of UUIDs:
`query = 'SELECT url FROM product_mapping WHERE dealer_uuid = %(dealer_uuid)s AND product_uuid IN %(product_uuids)s'`
`with self.db.cursor() as cursor:`
`    params = {`
`        'dealer_uuid': dealer_uuid,`
`        'product_uuids': product_uuids`
`    }`
`    cursor.execute(query, params)`
`    rows = cursor.fetchall()`

I get the following error:
`psycopg.errors.SyntaxError: syntax error at or near "$2"`
`LINE 1: ...roduct_mapping WHERE dealer_uuid = $1 AND product_uuid IN $2`

I am most probably doing it wrong, but I can't find the right way to do it. Thanks.

**Comment by dvarrazzo** [comment]
https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#you-cannot-use-in-s-with-a-tuple
