### ISSUE TITLE
ValueError "year -1 is out of range"

### ISSUE THREAD

**Issue by nathanstakester** [psycopg/psycopg#221]
When reading from a table with a timestamp column, I'm getting this error when selecting rows based on certain timestamp ranges, e.g.

```sql
SELECT *
  FROM table
 WHERE inserted_at BETWEEN '2021-11-01' AND '2021-12-01'
```

Whereas the following query does not throw an error:
```sql
SELECT *
  FROM table
 WHERE inserted_at BETWEEN '2021-12-01' AND '2022-01-01'
```

I have checked the `inserted_at` column of the table for negative dates/years and zero rows are returned.

```sql
SELECT *
  FROM table
 WHERE inserted_at < 0
--0 rows returned
```

```sql
SELECT *
  FROM table
 WHERE EXTRACT (YEAR FROM inserted_at) < 0
--0 rows returned
```

The error is thrown by this line in my code:

```python
pd.read_sql(query,con)
```
Where `con` is sqlalchemy.engine.connect() using a url beginning with `'postgresql+psycopg2://'`

From the first link below, I gather that the problem might be something to do with the fact that year -1 is supported by Postgres but not supported by Python.

I have tried reading in the whole table with pd.read_sql_table(table_name,con) and the same error is thrown. The other tables in the database don't cause an error for the either date range listed in the first two code snippets above. I haven't tried reading the other tables in using pd.read_sql_table().

I'm using: 
postgresql 12
psycopg2(-binary) 2.9.3 (dt dec pq3 ext lo64)
sqlalchemy 1.4.31
python 3.9.7 64 bit
pandas 1.4.0

I have tried the solutions in https://github.com/psycopg/psycopg2/issues/1161 without luck.

A search in the pandas and sqlalchemy repos don't turn up any results. Presumably there is something wrong with some of the timestamps in the `inserted_at` column in the table I'm trying to query, which postgresql seems to be ok with but causes something in my python code to trip up. It seems as though it could be something in the database connector. Could a psycopg contributor donate some of their time to looking into this?

The full traceback shows:
```python
Traceback (most recent call last):
  File "/filepath/script.py", line 208, in <module>
    main()
  File "/filepath/script.py", line 188, in main
    df = pd.read_sql(query,con)
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/pandas/io/sql.py", line 592, in read_sql
    return pandas_sql.read_query(
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/pandas/io/sql.py", line 1568, in read_query
    data = result.fetchall()
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1014, in fetchall
    return self._allrows()
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 400, in _allrows
    rows = self._fetchall_impl()
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 1803, in _fetchall_impl
    return self.cursor_strategy.fetchall(self, self.cursor)
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 981, in fetchall
    self.handle_exception(result, dbapi_cursor, e)
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 941, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2030, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/path_to_pyenv_versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 977, in fetchall
    rows = dbapi_cursor.fetchall()
ValueError: year -1 is out of range
```

**Comment by dvarrazzo** [comment]
PostgreSQL allows for years BC, python doesn't.

Probably you have a date out of range in some of the other columns, not in inserted_at.

What you can do is to identify which column has the bad data by selecting the columns you need instead of selecting *, and you can cast the value to text to find the irregular date.

Because we don't know what columna you have there, and what data you have there, we cannot help you further.

**Comment by al-cdc** [comment]
@dvarrazzo i have the same issue, have identified the column but how can I handle it? using executemany function, can I replace these dates with NULL?

**Comment by dvarrazzo** [comment]
@al-cdc hello. What do you mean with executemany? Executemany is usually to send data to the database, this problem is on reading it.

You can customise a loader: take a look at the example in the docs about [handling infinity dates](https://www.psycopg.org/psycopg3/docs/advanced/adapt.html#example-handling-infinity-date) and adapt it as you need.

**Comment by al-cdc** [comment]
@dvarrazzo , my bad i meant fetchmany(). yes, the customized loader is just what i needed, thanks.

**Comment by rcrafaeldelrey** [comment]
I m having similar errors with a date as '51218-09-20 00:00:00' in a column.  Is there a way to make pyscopg2 ignore these date format errors?

**Comment by dvarrazzo** [comment]
@rcrafaeldelrey Yes, there is. Just read what written in this ticket.

**Comment by rcrafaeldelrey** [comment]
I m using sqlalchemy, which uses psycopg2, which doesnt have the DateLoader and DateDumper mentioned above, as fair as I know.

**Comment by dvarrazzo** [comment]
@rcrafaeldelrey you can find the instructions in psycopg2 documentation

**Comment by rcrafaeldelrey** [comment]
The code bellow, executed before querying through sqlalchemy, will cast types "timestamp without time zone" into a string. I can later process the columns with regular python functions, or just change the cast_date bellow to handle date.min or date.max

`import psycopg2

def cast_date(value, cur):
    if value is None:
        return None
    return str(value)

date_oid = psycopg2.extensions.PYDATETIME.values
DATESTR = psycopg2.extensions.new_type(date_oid, "DATE", cast_date)
psycopg2.extensions.register_type(DATESTR)`
