### ISSUE TITLE
Handle Ctrl-C better

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#231]
Currently, if Ctrl-C is pressed during a long query, the connection is left in a broken state.

```python
>>> import psycopg
>>> cnn = psycopg.connect()

>>> cnn.execute("select pg_sleep(5)")
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/piro/dev/psycopg3/psycopg/psycopg/connection.py", line 808, in execute
    return cur.execute(query, params, prepare=prepare)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/cursor.py", line 557, in execute
    self._conn.wait(
  File "/home/piro/dev/psycopg3/psycopg/psycopg/connection.py", line 860, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/waiting.py", line 229, in wait_epoll
    fileevs = epoll.poll(timeout)
KeyboardInterrupt

>>> cnn.execute("select 1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/piro/dev/psycopg3/psycopg/psycopg/connection.py", line 811, in execute
    raise ex.with_traceback(None)
psycopg.OperationalError: sending query failed: another command is already in progress
```

[What pgcli does with psycopg2](https://github.com/dbcli/pgcli/blob/02134daad73b897f09454531facf8e12c1dab341/pgcli/pgexecute.py#L35-L61) makes sense: send a cancel and wait for the response. We should probably do the same by default in our wait functions, or maybe just out of them, because inside them we don't really have access to the PGconn structure.

**Comment by dvarrazzo** [comment]
Fixed for sync connections, but the same fix doesn't work for async ones. It seems that the Ctrl-C is trapped by `asyncio.run()` and never reaches the handler in `AsyncConnection.wait()`. Enabling the xfailed test `tests/test_concurrency_async.py::test_ctrl_c` there will be an output such as:

```
error ignored in rollback on <psycopg.AsyncConnection [ACTIVE] ...>: sending query failed: another command is already in progress
Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

**Comment by sekrause** [comment]
Which Python version are you using for development? I'm asking because of this bug which was fixed in Python 3.8: https://bugs.python.org/issue23057

**Comment by dvarrazzo** [comment]
I am personally developing on Python 3.8 on Linux, and the CI runs the tests on Python 3.6 to 3.10 on Linux, macOS, Windows.

At the moment, this MR has problem:

- on Windows, any version, because [I can't figure out how to send a Ctrl-C](https://github.com/psycopg/psycopg/runs/5290501819?check_suite_focus=true#step:6:180) Maybe it's a testing problem only;
- on asyncio on Linux but I assume everywhere else: [as in this xfailed test](https://github.com/psycopg/psycopg/runs/5290499793?check_suite_focus=true#step:8:90)

The BPO issue you link seems about signals+windows but also signals+linux don't seem to obey as I hope yet

**Comment by dvarrazzo** [comment]
Released in Psycopg 3.0.10. Currently [untested on Windows](https://github.com/psycopg/psycopg/blob/67f7fb2bc4fe2bc17440e6607298ca548a0e281f/tests/test_concurrency.py#L211) (the test should be fixed) and [not working in async mode](https://github.com/psycopg/psycopg/blob/67f7fb2bc4fe2bc17440e6607298ca548a0e281f/tests/test_concurrency_async.py#L160), which I don't know if it can be solved.

**Comment by dlax** [comment]
https://mail.python.org/archives/list/python-dev@python.org/message/HTWTWS3M2PKQILSKN3V7UM73ZKOOQ33K/:
> KeyboardInterrupt is generally not handled properly by asyncio, the normal
behavior here is that the code just exits with a traceback.

**Comment by dvarrazzo** [comment]
@dlax Later on I discovered [`loop.add_signal_handler()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_signal_handler) which makes the test behave well (382c67480cb2417cd6b461bbc8f9e14d123aaf8a).
