### ISSUE TITLE
Failed to install on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by KyleKotowick** [psycopg/psycopg#236]
I'm trying to install psychopg3 on a Windows Subsystem for Linux install (Linux running on a Windows OS, both of which are officially supported OS), and getting an error.

Windows OS: Windows 11
Linux OS: Ubuntu 20.04
Python version: 3.8.10
Pipenv version: 22.0.3

```
$ python3 -m venv .venv
$ source .venv/bin/activate
(.venv)$ pip install psycopg[binary]

Collecting psycopg[binary]
  Downloading psycopg-3.0.9-py3-none-any.whl (141 kB)
     |████████████████████████████████| 141 kB 9.8 MB/s
Collecting backports.zoneinfo>=0.2.0; python_version < "3.9"
  Downloading backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl (74 kB)
     |████████████████████████████████| 74 kB 14.0 MB/s
ERROR: Could not find a version that satisfies the requirement psycopg-binary==3.0.9; extra == "binary" (from psycopg[binary]) (from versions: none)
ERROR: No matching distribution found for psycopg-binary==3.0.9; extra == "binary" (from psycopg[binary])
```

**Comment by dvarrazzo** [comment]
This is probably related to #124. I don't know which manylinux tags work on WSL. None [of these](https://pypi.org/project/psycopg-binary/#files) apparently.

Can you try to install `psycopg` only and make sure a `libpq.dll` is available somewhere on your path please?

**Comment by dvarrazzo** [comment]
Any update?

**Comment by dvarrazzo** [comment]
Psycopg 3.0.15 released with manylinux2014 wheels package. Maybe it fixes this issue.
