### ISSUE TITLE
Failed to install in Docker

### ISSUE THREAD

**Issue by KyleKotowick** [psycopg/psycopg#238]
Running a Docker build for `linux/arm64`.

Dockerfile:
```
FROM public.ecr.aws/lambda/python:3.7 AS python3_7
RUN pip install --upgrade pip==22.0.3
RUN pip install psycopg[binary,pool]
```

Build command:
```
docker buildx build --platform linux/amd64 -t psychopg:latest .
```

Output:
```
#12 1.395 ERROR: Cannot install psycopg[binary,pool]==3.0, psycopg[binary,pool]==3.0.1, psycopg[binary,pool]==3.0.2, psycopg[binary,pool]==3.0.3, psycopg[binary,pool]==3.0.4, psycopg[binary,pool]==3.0.5, psycopg[binary,pool]==3.0.6, psycopg[binary,pool]==3.0.7, psycopg[binary,pool]==3.0.8 and psycopg[binary,pool]==3.0.9 because these package versions have conflicting dependencies.
#12 1.396
#12 1.396 The conflict is caused by:
#12 1.396     psycopg[binary,pool] 3.0.9 depends on psycopg-binary==3.0.9; extra == "binary"
#12 1.396     psycopg[binary,pool] 3.0.8 depends on psycopg-binary==3.0.8; extra == "binary"
#12 1.396     psycopg[binary,pool] 3.0.7 depends on psycopg-binary==3.0.7; extra == "binary"
#12 1.396     psycopg[binary,pool] 3.0.6 depends on psycopg-binary==3.0.6; extra == "binary"
#12 1.396     psycopg[binary,pool] 3.0.5 depends on psycopg-binary==3.0.5; extra == "binary"
#12 1.396     psycopg[binary,pool] 3.0.4 depends on psycopg-binary==3.0.4; extra == "binary"
#12 1.396     psycopg[binary,pool] 3.0.3 depends on psycopg-binary==3.0.3; extra == "binary"
#12 1.396     psycopg[binary,pool] 3.0.2 depends on psycopg-binary==3.0.2; extra == "binary"
#12 1.396     psycopg[binary,pool] 3.0.1 depends on psycopg-binary==3.0.1; extra == "binary"
#12 1.396     psycopg[binary,pool] 3.0 depends on psycopg-binary==3.0; extra == "binary"
#12 1.396
#12 1.396 To fix this you could try to:
#12 1.396 1. loosen the range of package versions you've specified
#12 1.396 2. remove package versions to allow pip attempt to solve the dependency conflict
#12 1.396
#12 1.396 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

It's an Amazon Linux 2 base image on an arm64 architecture, so I'd think it should be supported?

Note that if I don't include `binary` (`pip install psycopg[pool]`), it works fine.

**Comment by dvarrazzo** [comment]
The binary files we distribute [are these](https://pypi.org/project/psycopg-binary/3.0.9/#files). What manylinux tag does linux/arm64 require?

**Comment by werebear73** [comment]
I got it to build but I had to include additional libraries to my requirements.txt

psycopg
psycopg_binary
psycopg_c

**Comment by dvarrazzo** [comment]
Can you show a pip install log?

**Comment by amachanic** [comment]
I'm having this exact same issue on CentOS 7, x86.

I tried installing psycopg_binary and psycopg_c as suggested by @werebear73, but I'm unable to: The first one is not found by pip, and the second one throws an exception, "No such file or directory: 'pg_config'" (During processing of pyproject.toml.)

I was able to successfully install `psycopg==3.0.11`, but that gives me errors when I import:
"No module named psycopg_c"
"No module named psycopg_binary"

Not sure where to go from here.

**Comment by dvarrazzo** [comment]
@amachanic Please read [the install docs](https://www.psycopg.org/psycopg3/docs/basic/install.html).

- in order to install psycopg_c you need the build tools (which include pg_config).
- in order to use psycopg, unless you are using install, you need the libpq. If you install psql on the system you should have it.

CentOS 7 cannot use (yet) binary as per #124.

If you want more guidance please post your entire error message, not an abridged version, because what you pasted doesn't explain why it couldn't use the "python" implementation (likely the libpq is missing).

**Comment by dvarrazzo** [comment]
Psycopg 3.0.15 released with manylinux2014 wheels package. I believe it should fix this issue. Please let us know how it goes.
