### ISSUE TITLE
Building on FreeBSD

### ISSUE THREAD

**Issue by krowbar** [psycopg/psycopg#241]
On my version at least (13.0-RELEASE-p7) there is no need to redefine the imports from <sys/endian.h>, it matches the include of OpenBSD.  Although it compiles fine, it fails on import (betoh32 undefined).  The patch below fixes it for me.

I believe in the source this would be in psycopg_c/psycopg_c/_psycopg/endian.pxd

```
--- psycopg_c/_psycopg.c.orig   2022-03-08 16:11:25 UTC
+++ psycopg_c/_psycopg.c
@@ -1055,11 +1055,11 @@ typedef enum {
 #      define __LITTLE_ENDIAN LITTLE_ENDIAN
 #      define __PDP_ENDIAN    PDP_ENDIAN

-#elif defined(__OpenBSD__)
+#elif defined(__OpenBSD__) || defined(__FreeBSD__)

 #      include <sys/endian.h>

-#elif defined(__NetBSD__) || defined(__FreeBSD__) || defined(__DragonFly__)
+#elif defined(__NetBSD__) || defined(__DragonFly__)

 #      include <sys/endian.h>

```

**Comment by dvarrazzo** [comment]
Hello,

That code comes from [`endian.pxd`](https://github.com/psycopg/psycopg/blob/master/psycopg_c/psycopg_c/_psycopg/endian.pxd), which was copied from [this gist](https://gist.github.com/panzi/6856583). [This comment](https://gist.github.com/panzi/6856583?permalink_comment_id=1890387#gistcomment-1890387), referring to [this changeset](https://github.com/linux-sunxi/sunxi-tools/pull/59/files) confirms your finding.

**Comment by dvarrazzo** [comment]
The same issue might be present on other BSD flavours: see https://github.com/linux-sunxi/sunxi-tools/commit/384ff6473455da1a24b5037b358591f44f3bbf57

Could you please check if installing psycopg-c from the [fix-241 branch[(https://github.com/psycopg/psycopg/tree/fix-241) solves the problem?

Thank you very much
