### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by GCBallesteros** [psycopg/psycopg#243]
On attempting to connect to a postgres DB that was down I got the following error message from the raised exception:

```OperationalError: connection failed: Success```

Although it does describe the problem it did confuse me for a few seconds the fact that this was considered a success. Is it worth considering modifying the message to explain in what sense the failed connection was considered successful?

This is on version `3.0.4` and the code that was used is:

```python
with psycopg.connect(
    f"postgres://{os.environ['DB_USERNAME']}:{os.environ['DB_PASSWORD']}@{os.environ['DB_HOST']}/{os.environ['DB_NAME']}?sslmode=disable"
) as conn:
    with conn.cursor() as cur:
        query_result = cur.execute(
            "select column from table limit 1"
        )
        query_result = query_result.fetchall()
```
The complete stack trace is:

```
OperationalError                          Traceback (most recent call last)
/tmp/ipykernel_351396/3306094822.py in <module>
----> 1 with psycopg.connect(
      2     f"postgres://{os.environ['DB_USERNAME']}:{os.environ['DB_PASSWORD']}@{os.environ['DB_HOST']}/{os.environ['DB_NAME']}?sslmode=disable"
      3 ) as conn:
      4     with conn.cursor() as cur:
      5         query_result = cur.execute(

~/.pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/psycopg/connection.py in connect(cls, conninfo, autocommit, row_factory, context, **kwargs)
    567             )
    568         except e.Error as ex:
--> 569             raise ex.with_traceback(None)
    570 
    571         if row_factory:

OperationalError: connection failed: Success
```

**Comment by dvarrazzo** [comment]
Ha ha, that is confusing indeed :smile: 

However, the string `"Success"` is not generated by psycopg and I can't even find it in Postgres source, neither the libpq nor the server: `grep -r '"Success"'` doesn't find anything.

Connecting to a postgres db that is down, as in not listening to its port, generates different error messages for me, such as:

```
>>> psycopg.connect("host=localhost port=9876")
...
OperationalError: connection failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
```

Could it be some of the libraries used by the libpq (libssl is likely excluded as it's disabled in your connection string. maybe ldap?)

So, most likely there is nothing we can do here. However I would be curious to know what is exactly down in your connection attempt?

**Comment by GCBallesteros** [comment]
Thanks for the quick reply. I also found the message amusing but it looks like the problem is elsewhere. Will try to look a bit into it myself.

With regards to your last question, it is the database itself that wasn't running on the server. Once I got over my confusion the fix was as simple as turning it on.

**Comment by dvarrazzo** [comment]
If the database is not running on the server, hence the port is closed, I get a message similar to the one you receive in psql.

Closing this ticket as it is probably outside psycopg competence. However, if you have further details, please feel free to add it and we can reconsider what to do.

Cheers!
