### ISSUE TITLE
Support placeholder for IN clause

### ISSUE THREAD

**Issue by dzavodnikov** [psycopg/psycopg#249]
I gave such code (from [this answer](https://stackoverflow.com/a/28117658/1095712/)):

    with connect(db_uri) as conn:
    with conn.cursor() as cur:
        data = ("UK", "France")
        sql = "SELECT * FROM countries WHERE country IN %s"
        cur.execute(sql, (data,))
        print(cur.fetchall())

and I got following exception:

    psycopg.errors.SyntaxError: syntax error at or near "$1"
    LINE 1: SELECT * FROM countries WHERE country IN $1
                                                     ^

So, how to correctly process parameters in IN clause?

**Comment by dvarrazzo** [comment]
You can use `= any(%s)` and pass a list, instead of a tuple. 

Documentation: https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#you-cannot-use-in-s-with-a-tuple

Note that it works in psycopg2 too.
