### ISSUE TITLE
Version 3 documentación link is broken 

### ISSUE THREAD

**Issue by cr0hn** [psycopg/psycopg#252]
It’s raises 404

**Comment by dvarrazzo** [comment]
Eh? What link please?

**Comment by j-bennet** [comment]
https://www.psycopg.org/psycopg3/docs/

All your docs are 404-ing.

**Comment by dvarrazzo** [comment]
Thank you @cr0hn, @j-bennet 

[This build failed](https://github.com/psycopg/psycopg-website/runs/5612077645?check_suite_focus=true#step:6:366), investigating...

**Comment by dvarrazzo** [comment]
Fixed, thank you. A newly introduced dependency on typing_extensions was missing but, because the package is installed by pytest, it wasn't caught by the test suite.

**Comment by cr0hn** [comment]
Thanks guys
