### ISSUE TITLE
`write_row` busy loop

### ISSUE THREAD

**Issue by jerch** [psycopg/psycopg#255]
Found some weird behavior in version 3.0.10 (in both C and python variant, installed from pip).

This seems never to return, it sticks at 100% python CPU with no postgres activity:
```python
def provoke(conn):
    txt = '\\' * 536870883
    c = conn.cursor()
    c.execute('create temporary table ttt(t1 text, t2 text, t3 text, t4 text, t5 text)')
    with c.copy('COPY ttt (t1,t2) FROM STDIN') as copy:
        copy.write_row([txt] * 2)
    c.execute('select length(t1), length(t2), length(t3) from ttt')
    print(c.fetchall())
    c.execute('drop table ttt')
provoke(connection)
```
Have not yet further debugged, maybe some sort of busy loop in text escaping solely on python side. The value size was chosen for typical postgres limits, which should raise here, but it never gets to postgres side of things.

**Comment by jerch** [comment]
Some progress with the python version:

Initially it hangs on the `\\` --> `\\\\` substitution done here: https://github.com/psycopg/psycopg/blob/4d5698ff98eefa3a58500708a81916237922e195/psycopg/psycopg/copy.py#L562

After waiting for like 5min it quits there with a memory error. To get around the regexp memory error, I temporarily replaced the replacement function with this one (which no full replacement yet):
```python
cheap_repl = lambda v : v.replace(b'\\', b'\\\\')
```
which gets through the data somewhat faster without a memory error. But now things hang here: https://github.com/psycopg/psycopg/blob/4d5698ff98eefa3a58500708a81916237922e195/psycopg/psycopg/pq/pq_ctypes.py#L577

thus I aborted it manually after 10 mins. Looking at the postgres docs for that function, it states:
> The application can divide the COPY data stream into buffer loads of any convenient size.
thus I tried a quick replacement with a chunked version:
```python
    def put_copy_data(self, buffer: bytes) -> int:
        # TODO: should be done without copy
        if not isinstance(buffer, bytes):
            buffer = bytes(buffer)
        if len(buffer) > 2**20:
            pos = 0
            while pos < len(buffer):
                part = buffer[pos:pos+(2**20)]
                rv = impl.PQputCopyData(self._pgconn_ptr, part, len(part))
                if rv < 0:
                    raise e.OperationalError(f"sending copy data failed: {error_message(self)}")
                pos += 2**20
        else:
            rv = impl.PQputCopyData(self._pgconn_ptr, buffer, len(buffer))
            if rv < 0:
                raise e.OperationalError(f"sending copy data failed: {error_message(self)}")
        return rv
```
Now it gets through to the expected error from postgres:
```python
psycopg.errors.ProgramLimitExceeded: out of memory
DETAIL:  Cannot enlarge string buffer containing 1073676288 bytes by 65535 more bytes.
CONTEXT:  COPY ttt, line 1
```

Not sure yet whats the issue in C, maybe also the `PQputCopyData` call?

**Comment by dvarrazzo** [comment]
You could try and take a look via py-spy or some other tool to inspect the C stack to see where is the program stuck. See [this article](https://www.varrazzo.com/blog/2020/05/19/a-trip-into-optimisation/) for an example.

If it's stuck client-side, I'm moderately sure it is in some libpq escape function.

Is the behaviour linear or quadratic in the string size?

**Comment by jerch** [comment]
Thx for the profiling/debugging pointer, I have no experience beside the standard cProfiler and debugging packages, so might need some help to get the cython stuff into perspective.

Was able to track the issue with `PQputCopyData` further down - it is indeed an infinite loop in: https://github.com/psycopg/psycopg/blob/4d5698ff98eefa3a58500708a81916237922e195/psycopg/psycopg/generators.py#L205-L208

caused by these circumstances:
- connection is set to non blocking
- [QputCopyData](https://doxygen.postgresql.org/fe-exec_8c.html#a7fe73507f64c8ff14ab0491c571e4002) calls `pqCheckOutBufferSpace` in line 2660, if that call fails it will return 0 for nonblocking connections
- looking at [pqCheckOutBufferSpace](https://doxygen.postgresql.org/fe-misc_8c.html#a0e2b94a3b894918aba366784d2064c1b) it will only fail, if realloc does not succeed, adding an error message and returning EOF

So while the outgoing buffer has a max limit, it is not reflected directly at `QputCopyData` in non blocking mode. Maybe there should be a peek into the error messages, if `QputCopyData` returned 0? In any case I think it is needed to handle big data in chunks, this also would automatically avoid that buffer limit issue. (Have not yet checked how `copy.write` is passed down to libpq and whether big file chunks would also be affected.)
Furthermore I'd suggest to slow down the busy waiting loop in [generators.copy_to](https://github.com/psycopg/psycopg/blob/4d5698ff98eefa3a58500708a81916237922e195/psycopg/psycopg/generators.py#L207) by a tiny sleep, otherwise this may get very CPU hungry for no benefit.

**Comment by dvarrazzo** [comment]
Thank you for your analysis. It's not pretty, but maybe we can look if there's `memory` in the error message and bail out there.

> Furthermore I'd suggest to slow down the busy waiting loop in [generators.copy_to](https://github.com/psycopg/psycopg/blob/4d5698ff98eefa3a58500708a81916237922e195/psycopg/psycopg/generators.py#L207) by a tiny sleep, otherwise this may get very CPU hungry for no benefit.

Yielding a `Wait.W` should trigger scheduling. It doesn't?

> But doesnt this open the door for OOM on worker thread side (or in the queue), if tons of data arrive too fast? The queue has a limited size and blocks.

The queue has a max size of 1024 items. Every item should be about 32K items. As a result it shouldn't grow more than 32Mb of space.

**Comment by dvarrazzo** [comment]
> Have not yet checked how copy.write is passed down to libpq and whether big file chunks would also be affected

We could add a chunking mechanism downstream, in a code path common to both `write()` and `write_row()`

**Comment by jerch** [comment]
> Yielding a Wait.W should trigger scheduling. It doesn't?

The `waiting.wait` construct on the db socket does not seem to kick in for the toxic data - I guess because it is not blocking at all (as the socket has not seen any payload at this point) and returns immediately? Currently that loop runs at 100% CPU, with most time spent in `pqCheckOutBufferSpace` (prolly at the 8KB buffer expansion logic). I still wonder where that max limit comes from on libpq side, following realloc includes/defines I cannot find it being bound to postgres limits. (And I kinda dont feel yet like building the lib itself in debug mode :smile_cat:)

> We could add a chunking mechanism downstream, in a code path common to both write() and write_row().

Sounds like it would solve all the issues at once - `PQputCopyData` would play along and its invocation can be kept as it is, and also the queue can not grow overly anymore, if single chunks have an upper limit. Downside though - prechunking loses information on the source of the data bucket (no clue if the code relies on that somewhere).

**Comment by dvarrazzo** [comment]
> Downside though - prechunking loses information on the source of the data bucket (no clue if the code relies on that somewhere).

I don't think it does, no, so it's on my radar to do so. First I want to play with your example a bit: thank you for the useful repro.

> NB: That all for the python version so far, C might be a different story....

I don't think so. C is only concerned with optimising the formatting and functions, not with the IO, and implements the thin wrapper `PGconn.put_copy_data()` around the `PQputCopyData()` function.

**Comment by jerch** [comment]
Btw regarding the byte limit:
```c
PQputCopyData(PGconn *conn, const char *buffer, int nbytes)
```
Why is the byte size typed as *int*? :scream: (Hopefully this does not continue deeper into pq source, otherwise negative values might cause greater havoc here...)

**Comment by dvarrazzo** [comment]
Yes, there are some pretty old part of the libpq which use int instead of size_t...

I have created a branch with fixes for this problem. It relies on finding `memory` in the error message, so it's not pretty. Will have to test it better trying to trigger a would-block state in `put_copy_data()`.

Also fixed a bug with the working thread: the exception is now passed to the main thread and raised from there. Needs testing and to verify if similar code is necessary in the async path.

Note that the C path of the backslash escaping is much faster and only takes 3 seconds to forward the data to the now-crashing function.

```
(.venv) piro@baloo:~/dev/psycopg3$ time PSYCOPG_IMPL=c python testcopy.py 
Traceback (most recent call last):
  File "testcopy.py", line 18, in <module>
    provoke(conn)
  File "testcopy.py", line 9, in provoke
    copy.write_row([txt] * 2)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/cursor.py", line 683, in copy
    yield copy
  File "/home/piro/dev/psycopg3/psycopg/psycopg/copy.py", line 197, in __exit__
    self.finish(exc_val)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/copy.py", line 264, in finish
    self._write_end()
  File "/home/piro/dev/psycopg3/psycopg/psycopg/copy.py", line 311, in _write_end
    raise self._worker_error
  File "/home/piro/dev/psycopg3/psycopg/psycopg/copy.py", line 283, in worker
    self.connection.wait(copy_to(self._pgconn, data))
  File "/home/piro/dev/psycopg3/psycopg/psycopg/connection.py", line 861, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/waiting.py", line 222, in wait_epoll
    s = next(gen)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/generators.py", line 216, in copy_to
    raise e.OperationalError(msg)
psycopg.OperationalError: cannot allocate memory for output buffer


real	0m3.265s
user	0m2.583s
sys	0m0.672s
```

How does it look?

**Comment by jerch** [comment]
> How does it look?

Very nice :+1:.

But will the memory error message scan be reliable to distinct slow transport processing (old buckets stacking up in out buffer) vs. a single bucket overflowing the max buffer limit? From looking at `pqCheckOutBufferSpace` and  `pqPutnchar` --> `pqPutMsgBytes` it seems, new buckets simply get appended to the out buffer, so pressure from slow connection also might run into the same memory error?

**Comment by dvarrazzo** [comment]
> new buckets simply get appended to the out buffer, so pressure from slow connection also might run into the same memory error?

Do you mean the buffer to compose the error message? That would be a small realloc, not a multiMB realloc. I sincerely hope the OOM killer will come and put end to the misery of this process 💀

> Btw there is a double call perf smell there

but likely there will be only one re-allocation, the other would hit the happy path and bail out early I expect, no?

> Ah - I should stop nagging about libpq...

if you have observations about the libpq code you may get in touch with the postgres devs at pgsql-hackers mailing lists. Observations about what makes the life of a libpq client harder may be welcome. Even this conflating a memory error with what [the docs](https://www.postgresql.org/docs/14/libpq-copy.html#LIBPQ-PQPUTCOPYDATA) suggest is a would-block condition smells dodgy.

**Comment by jerch** [comment]
There might be another perf smell hidden in libpq, if used with non blocking connection - in [pqSendSome](https://doxygen.postgresql.org/fe-misc_8c.html#ac08f6d490638b656c1c5ddf9b7cb520c) at line 943 the whole buffer gets realigned for every successfully sent portion. I understand, that this might be needed for complicated SQL stuff (guess they use that for all client->server comm), but in case of big data from COPY FROM it creates alot of unnecessary memory juggling, where a small ringbuffer abstraction would be like 10 times faster -.-

> Do you mean the buffer to compose the error message? That would be a small realloc, not a multiMB realloc. I sincerely hope the OOM killer will come and put end to the misery of this process.

Ah nope, I mean the libpq out buffer, where it stores everything to be sent to the server. Currently I am not quite sure about the mechanics here for non blocking connections, will see, if I can mockup a test case to repro, what I currently think it does.

> Even this conflating a memory error with what [the docs](https://www.postgresql.org/docs/14/libpq-copy.html#LIBPQ-PQPUTCOPYDATA) suggest is a would-block condition smells dodgy.

Yes, it could at least have set errno, so a custom client binding can check for rare irregularities.

**Comment by dvarrazzo** [comment]
`pqCheckOutBufferSpace()` is an internal function so I think they can establish a return error to report an error with `palloc()`, which might be assumed not recoverable.

After securing psycopg we can drop a line to the -hackers to hear what they think and if there's space for improvement there.

**Comment by dvarrazzo** [comment]
@jerch would you be ok to take a look at https://github.com/psycopg/psycopg/pull/256 for a final review? Is there anything else that you think we should do?

**Comment by dvarrazzo** [comment]
@jerch actually, wait a moment. Looking at the libpq code, I think we should really implement sending the query in chunks, because I assume the only way to treat `PQputCopyData` kindly is to give it time to send what it has temporary in memory already.

**Comment by jerch** [comment]
> Looking at the libpq code, I think we should really implement sending the query in chunks, because I assume the only way to treat PQputCopyData kindly is to give it time to send what it has temporary in memory already.

Yes I think so too.

I currently dont quite understand their non blocking connection in conjunction with PQputCopyData, to me this looks really awkward. I see that PQputCopyData tries to flush the out buffer when called by calling pqSendSome, which may send a portion from the out buffer, the buffer gets realign with memmove, then the chunk provided to PQputCopyData will be added (if it fits within the max limit, maxbe with a realloc in between) or rejected with return value 0, because the buffer would hit the limit. So far that setup makes sense to me.

But now my confusion starts - I dont see, how that non empty buffer ever gonna be drained in future, also PQputCopyEnd calls pqSendSome only like once. What if the buffer still holds like 500MB, and pqSendSome only dealt another 64KB chunk? Does libpq have some own buffer draining exec context (at least I saw no lock/mutex stuff in pqSendSome, so it does not look like there an observer thread)? Or is the draining responsibility delegated to the lib user (psycopg here), by some other interface? I dont get it yet...

**Comment by jerch** [comment]
Your last commit looks like right fix to me. I am still puzzled about the memory error scan from above, I think this will not work correctly for fast incoming chunks and fail when it hits the max limit from those. But I was not able to provoke that yet, and there a high chance that I simply dont get it (see last comment).

**Comment by dvarrazzo** [comment]
Hi,

still playing with this matter: the behaviour of the libpq is quite complicated.

I have moved chunking the large buffers before the queue, rather than after: this, ISTM, has a better chance to apply backpressure to a client pushing too much data (in chunks too large, rather than too many records at time).

But now it comes the fun. Adding

<details>
<summary> a few prints </summary>

```diff
diff --git a/psycopg/psycopg/copy.py b/psycopg/psycopg/copy.py
index 1985de74..a17e45b5 100644
--- a/psycopg/psycopg/copy.py
+++ b/psycopg/psycopg/copy.py
@@ -275,8 +275,11 @@ class Copy(BaseCopy["Connection[Any]"]):
         using the `Copy` object outside a block.
         """
         if self._pgresult.status == ExecStatus.COPY_IN:
+            print("writing copy end")
             self._write_end()
+            print("wait for copy end")
             self.connection.wait(self._end_copy_in_gen(exc))
+            print("copy end")
         else:
             self.connection.wait(self._end_copy_out_gen(exc))

@@ -293,6 +296,7 @@ class Copy(BaseCopy["Connection[Any]"]):
         try:
             while True:
                 data = self._queue.get(block=True, timeout=24 * 60 * 60)
+                print(f"got {len(data)} bytes from queue size {self._queue.qsize()}")
                 if not data:
                     break
                 self.connection.wait(copy_to(self._pgconn, data))
@@ -317,11 +321,16 @@ class Copy(BaseCopy["Connection[Any]"]):
         if len(data) <= self.MAX_BUFFER_SIZE:
             # Most used path: we don't need to split the buffer in smaller
             # bits, so don't make a copy.
+            print(f"putting {len(data)} bytes in queue size {self._queue.qsize()}")
             self._queue.put(data)
         else:
             # Copy a buffer too large in chunks to avoid causing a memory
             # error in the libpq, which may cause an infinite loop (#255).
             for i in range(0, len(data), self.MAX_BUFFER_SIZE):
+                print(
+                    f"putting {self.MAX_BUFFER_SIZE} (or less) bytes"
+                    f" in queue size {self._queue.qsize()}"
+                )
                 self._queue.put(data[i : i + self.MAX_BUFFER_SIZE])

     def _write_end(self) -> None:
```
</details>

shows that reducing the size of the blocks sent to `PGputCopyData` from 1Mb to 128Kb changes the libpq behaviour considerably: your test passes in 9 seconds instead of 10 minutes (I had to add tests to make sure data was being written for real). There is definitely something quadratic happening there: once the producer has finished pushing data in the queue, and the queue is at its maximum length of 1024 items, the consumer visibly processes them much faster at the beginning than at the end. In the last timing taken (see [1a1395c](https://github.com/psycopg/psycopg/pull/256/commits/1a1395c448985f285ba2cf8924153df06bd23303) the timing to flush the queue is:

```
    00:00:47 putting 1048576 (or less) bytes in queue size 1023
    00:00:47 writing copy end
    00:00:47 got 1048576 bytes from queue size 1023
    ...
    00:01:25 got 1048576 bytes from queue size 640
    ...
    00:01:54 got 1048576 bytes from queue size 512
    ...
    00:03:00 got 1048576 bytes from queue size 256
    ...
    00:04:12 got 0 bytes from queue size 0
    00:04:12 wait for copy end
    00:09:59 Traceback (most recent call last):
    ...
```

so 42s for the first 128 items, 72 for the last 128.

**Comment by jerch** [comment]
The `memmove` in `pqSendSome` looks suspicious and might be quadratic - the bigger the chunk, the more often that bigger memory has to be realigned. But thats only a guess from looking at the sources, will see if I get some libpq debugging/profiling done next week (I'm currently not in town).

**Comment by dvarrazzo** [comment]
Cool, sounds great! In the meantime I have merged this branch and we can release these changes. Thank you very much for the collaboration 🙂

**Comment by jerch** [comment]
@dvarrazzo Seems setting up libpq for debugging/development is more involved, as it is part of the full postgres source. Not sure yet, if I will get this done in a timely fashion, also I have no clue yet, if and how valgrind/cachegrind will play along. Also to not mix things with python yet, it seems more straight forward to build a small test lib in C, which also means, that any results from that might have limited consequences for a python binding.
Last but not least - even if those tests reveal major perf smells within libpq, it hardly would result in code changes, that can directly be used to an advantage in psycopg yet (maybe identified anti pattern can be avoided/documented, the memove/pqSendSome chunk juggling surely looks like one of it). There is always that "eww, this is an infrastructure like API, we cannot do much about it, unless come up with a V2 API only for newer releases" thingy attached to those fundamental APIs...

**Comment by dlax** [comment]
> Seems setting up libpq for debugging/development is more involved, as it is part of the full postgres source.
You can get debug symbols from a distro package (e.g. libpq5-dbgsym on 
Debian-based systems), or is it not enough?

**Comment by jerch** [comment]
@dlax Ah thx for the pointer, will check that out.

**Comment by dvarrazzo** [comment]
Building the libpq doesn't take a lot of effort. You cat `./configure` in the postgres source dir and `make/make install` in the `src/interfaces/libpq` dir. You can throw in a few `--no-*` switches to configure to avoid installing binding to too many libraries (kerberos, etc). However, on Debian, it's just a matter of installing some `xxxlib-dev` packages which are easy to google for from the error messages on build.

Happy to hear about further improvements, as well as liasing with the postgres devs to propose patches. However it seems that the pathological behaviours are mostly triggered by pushing imprudently large buffers to the sending function, and that's something we have started guarding from :)

**Comment by jerch** [comment]
@dvarrazzo Thx for the hints, was able to get an editable debug build with these steps:
```bash
git clone git://git.postgresql.org/git/postgresql.git
cd postgresql
./configure --enable-debug --prefix=/some/target/folder --without-readline
cd src/interfaces/libpq
make && make install
```

For a quick test I added this to `pqSendSome` at line 887:
```c
printf("len: %d, remaining-pre: %d, sent: %d, remaining: %d\n", len, remaining, sent, remaining-sent);
```
to get a first idea about the out buffer fill levels. Then I ran it with psycopg-python by changing `pq = ctypes.cdll.LoadLibrary('/some/target/folder/lib/libpq.so.5.15')` in `_pq_ctypes.py` with this minimal test script:
```python
import psycopg
conn = psycopg.connect(host='localhost', dbname='postgres', user='postgres', password='mysecretpassword')
def run():
    txt = 'n' * 100000
    c = conn.cursor()
    c.execute('create temporary table ttt(t1 text, t2 text, t3 text, t4 text, t5 text)')
    with c.copy('COPY ttt (t1,t2,t3,t4,t5) FROM STDIN') as copy:
        s = time()
        print('before copydata')
        copy.write_row([txt] * 5)
        copy.write_row([txt] * 5)
    print('after copydata', time() - s)
    c.execute('select length(t1), length(t2), length(t3), length(t4), length(t5) from ttt')
    print(c.fetchall())
    c.execute('drop table ttt')
run()
```
Manually applying your buffersize fix, I get this output:
```text
before copydata
len: 131072, remaining-pre: 131077, sent: 131072, remaining: 5
len: 131072, remaining-pre: 131082, sent: 131072, remaining: 10
len: 131072, remaining-pre: 131087, sent: 131072, remaining: 15
len: 106496, remaining-pre: 106809, sent: 106496, remaining: 313
len: 131072, remaining-pre: 131390, sent: 131072, remaining: 318
len: 131072, remaining-pre: 131395, sent: 131072, remaining: 323
len: 131072, remaining-pre: 131400, sent: 131072, remaining: 328
len: 106496, remaining-pre: 107122, sent: 106496, remaining: 626
len: 631, remaining-pre: 631, sent: 631, remaining: 0
after copydata 0.036473989486694336
len: 80, remaining-pre: 80, sent: 80, remaining: 0
[(100000, 100000, 100000, 100000, 100000), (100000, 100000, 100000, 100000, 100000)]
```
Note the first remaining-pre value of 131077, which suggests, that libpq in fact creates a 5 bytes larger chunk of it. That happens in `pqPutMsgStart` - it prepends a 'd' char (prolly some sort of message type enum) and appends 4 bytes as int32 length placeholder to be filled by `pqPutMsgEnd`. Then `pqPutMsgEnd` calls `pqSendSome` with the length in terms of 8192 multiples (not sure yet why, maybe some sort of alloc optimization on server side), thus the additional 5 bytes need a second network roundtrip (and even stackup, see remaining above). Maybe max buffersize should be 5 bytes shorter here? (would safe the additional roundtrip and the memmove down below in `pqSendSome`)

Btw without applying the max buffersize fix, I get:
```
before copydata
len: 499712, remaining-pre: 500010, sent: 499712, remaining: 298
len: 499712, remaining-pre: 500308, sent: 499712, remaining: 596
len: 601, remaining-pre: 601, sent: 601, remaining: 0
after copydata 0.03318357467651367
```
thus I cannot repro yet your quadratic findings with my psycopg-python setup (maybe pythons slowiness is overly dominating, might change in pure C). More importantly here for me was to check, whether libpq would allow bigger message sizes for `send` and not hard limit it to some lowish value. This is important to not create an artificial bottleneck at the network invocation. It seems to scale message size freely up on linux, for windows there is a hard limit of 64k in `pqSendSome` (eww).

Next step is to get a small C client up and running, to profile things with valgrind.
