### ISSUE TITLE
psycopg3 not working with python3.10 (Raspberry PI Zero)

### ISSUE THREAD

**Issue by GerBreOwn** [psycopg/psycopg#257]
On my Raspi Pi Zero with the latest Raspian OS Bullseye with Python 3.10 when I try to import psycopg in my script I keep getting the error: "ImportError: no pq wrapper available. "Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: No module named '_ctypes'
- 
My code worked before I upgraded to Python3.10. I was using Python 3.9 which is the default version with Bullseye.

When I try to install libpq5 it says it is already installed and is the latest version.

Any ideas what causes this error and how it can be corrected?

Thanks

**Comment by dvarrazzo** [comment]
> No module named '_ctypes'

this is a system module. Why is ctypes not installed?

>  No module named 'psycopg_binary'

can you `pip update -U pip && pip install psycopg-binary`?

**Comment by dvarrazzo** [comment]
[This](https://www.pythonpool.com/modulenotfounderror-no-module-named-_ctypes-solved/) might explain about something missing on your system.

**Comment by j-bennet** [comment]
Hey @dvarrazzo , I'm getting the same error with 3.10.4, and I'm not on Rqsberry Pi, mine is a Macbook. I have `libpq` installed with homebrew.

```
> brew install libpq
Warning: libpq 14.5 is already installed and up-to-date.
```

Can you advise?

**Comment by dvarrazzo** [comment]
@j-bennet if you installed libpq via brew, maybe this is related to #364 ?
