### ISSUE TITLE
AsyncConnectionPool has no connection after 1 minute

### ISSUE THREAD

**Issue by MnrBnm** [psycopg/psycopg#272]
Hi,

Im using AsyncConnectionPool to create a pool of connection. The problem is after EXACTLY one minute, all the connections are being deleted without having new created one. 

I create my pool by doing so : 
```
uri = "postgresql://{username}:{pwd}@{hostname}:{port}".format(username="user", pwd="pwd",hostname="hostname", port=5432)
pool = psycopg_pool.AsyncConnectionPool(uri,min_size=20,max_size=50)
```

When i run my code, i can see the 20 connections being created in my PGADMIN. Even when i'm not doing anything, the connections are just deleted after 1 minute. 

I do this to access my pool connections : 
```
            async with pool.connection() as conn:
                async with conn.cursor(row_factory=dict_row) as cur:
                    await cur.execute(...) 
```

I saw that there is a parameter in postgresql called "idle_session_timeout"  that terminates any session that has been idle for X sec. I turned it to 0 (which basically means never deleted idle connection). 

Thank you in advance.

**Comment by dvarrazzo** [comment]
That's, like, very curious? I don't think it's caused by psycopg. What database are you connecting to? Just a normal PostgreSQL on a normal server without middleware?

When you say that you turned `idle_session_timeout` to 0: what was the default `SHOW idle_session_timeout`?

**Comment by MnrBnm** [comment]
the postgres db is in a kubernetes cluster (postgres:14-alpine3.15) in AWS. 

I've just now checked to run it on my local machine simply on a docker image (works perfectly, the 20 connections stays up) but as soon as the db is in an eks cluster, the connections don't  stays up.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/48262118/162270981-78b1872f-c085-44b2-8928-ddc317fa15ab.png">

**Comment by dvarrazzo** [comment]
Is that idle_session_timeout from your local postgres or from AWS?

**Comment by MnrBnm** [comment]
it's from AWS, by default it's at 0

**Comment by dvarrazzo** [comment]
I think you should hear from Amazon, if they allow to keep connections idle for longer. As the default is unchanged they probably have some middleware cutting inactive connections.

I'll close this ticket, but if you have further news, such as documentation where they talk about the feature and maybe a way to control it, I'm happy to hear to improve our docs.

**Comment by dvarrazzo** [comment]
You might try to play with keepalives and see if amazon respects them.

- https://www.postgresql.org/docs/current/libpq-connect.html
- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.BestPractices.html
