### ISSUE TITLE
Support for custom enums and enum arrays

### ISSUE THREAD

**Issue by ertaquo** [psycopg/psycopg#273]
Cheers!

I found that psycopg doesn't support custom enum types, so wrote [little support function](https://gist.github.com/ertaquo/91619a9c021fad7d7b0b6219ebce9f93) to generate loaders for them. Maybe it can be useful for someone?

**Comment by ertaquo** [comment]
Done, but please verify the PR - maybe i did something wrong?

**Comment by dvarrazzo** [comment]
Thank you, that's amazing! Will review soon

**Comment by dvarrazzo** [comment]
Overtaken by #274.
