### ISSUE TITLE
Query returned as bytes instead of string on some DB

### ISSUE THREAD

**Issue by Fillicia** [psycopg/psycopg#276]
Hi,

Just started to migrate from a docker/alpine Postgres database to a debian one and noticed the same query would return as bytes now versus returning as string like before. Same code, Both on Postgres 14, any idea what could cause this? 

**Alpine:**
```
psql.cur.execute("SELECT version();").fetchone()

('PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit',)
```

**Debian:**
```
psql.cur.execute("SELECT version();").fetchone()

(b'PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit',)
```

**Comment by dvarrazzo** [comment]
Hello,

Maybe the database was created with SQL_ASCII encoding. Such encoding actually means no encoding for Postgres and psycopg doesn't decode the strings received. Details [in the docs](https://www.psycopg.org/psycopg3/docs/basic/adapt.html#strings-adaptation).

You can check the database encoding with `\l` in psql and the client encoding using `cur.execute("show client_encoding")`.

You should create your database in utf8, or pass `client_encoding="utf8"` if you can't change it.

**Comment by Fillicia** [comment]
Yes that's exactly what it was! Thank you.

For reference, the template database were set to encoding SQL_ASCII from the installation. Had to change it in order to recreate my database as UTF8 using these steps https://stackoverflow.com/a/16737776

Closing this issue.
