### ISSUE TITLE
Row factories and Insert

### ISSUE THREAD

**Issue by asia653** [psycopg/psycopg#281]
It appears that row factories aren't applied to sql queries @ INSERT with RETURNING

is this expected behavior?

**Comment by dlax** [comment]
The following test case works:
```python
conn.execute("create temp table t (d text, id serial primary key)")                                                                     
                                                                                                                                        
def idf(id, *args):                                                                                                                     
    return id + 1                                                                                                                       
                                                                                                                                        
cur = conn.cursor(row_factory=rows.args_row(idf))                                                                                       
returned = cur.execute("insert into t values ('foo') returning id").fetchone()                                                          
assert returned == 2                                                                                                                    
table = conn.execute("table t").fetchall()                                                                                              
assert table == [("foo", 1)]                                                                                                            
```

**Comment by dvarrazzo** [comment]
Likely a mistake from the OP.

**Comment by asia653** [comment]
> The following test case works:
> 
> ```python
> conn.execute("create temp table t (d text, id serial primary key)")                                                                     
>                                                                                                                                         
> def idf(id, *args):                                                                                                                     
>     return id + 1                                                                                                                       
>                                                                                                                                         
> cur = conn.cursor(row_factory=rows.args_row(idf))                                                                                       
> returned = cur.execute("insert into t values ('foo') returning id").fetchone()                                                          
> assert returned == 2                                                                                                                    
> table = conn.execute("table t").fetchall()                                                                                              
> assert table == [("foo", 1)]                                                                                                            
> ```

Sorry for the delay, I was investigating this

This behavior only surfaces when using connection pools

![image](https://user-images.githubusercontent.com/2181584/168419214-53a2bfca-f8d3-40b5-9029-c1002505130c.png)

Maybe I am using this wrong or calling it wrong. I apologize if I have made a mistake

**Comment by dvarrazzo** [comment]
That's because you have `returning (id, name)`: the brackets create a tuple with a single column of result, with a field called `row`.

The syntax you want is `returning id, name`.

**Comment by asia653** [comment]
> That's because you have `returning (id, name)`: the brackets create a tuple with a single column of result, with a field called `row`.
> 
> The syntax you want is `returning id, name`.

Thanks! It was a beginner mistake after all. I did not know of this postgresql behavior
