### ISSUE TITLE
AsyncConnectionPool silent failure in nested async long running code

### ISSUE THREAD

**Issue by haf** [psycopg/psycopg#290]
When using a port-forwarding tunnel, and async connection pool and nested connections, parent connections do not report errors from writes.

### Pseudo-code

When you have code like:

```python
async def f():
    async with pool.connection() as conn:
        async with pool.connection() as conn2:
            await conn2.execute insert into
        await sleep(60 * 4.5)
        params = [ ... about 1500 dicts ]
        await conn.executemany(insert into .. values (%(..)s), params) # this write fails silently
        async with pool.connection() as conn3:
            await conn3.execute insert into
```

Then we get the middle write failing silently.

This is running in a process in uvicorn but since I'm running it locally, there's no load.

When running in k8s without SSH, everything works fine and both connections write. But when I set up a tunnel that binds localhost and forwards to the k8s svc which forwards to the db, psycopg silently fails the write.

### Versions

- OS: macOS 12.3.1 (21E258) on M1 and hence the self-compiled `psycopg[c]` bindings,
- SSH OpenSSH_8.6p1, LibreSSL 3.3.5
- Python: Python 3.9.10

psycopg = {extras = ["c"], version = "^3.0.10"}
psycopg_pool = "^3.1.1"

**Comment by dvarrazzo** [comment]
I have the same problem with k8s and psql. It doesn't seem a psycopg problem. Maybe we can try to set up tcp keepalives on the connection (we as "we users of postgresql clients").

Do you want to try [this solution](https://stackoverflow.com/a/61353359/10138) and report how it goes?

**Comment by haf** [comment]
Hi, no I don't. I want the bug fixed; I expect an exception if the connection is dead.

**Comment by dvarrazzo** [comment]
You can find in the docs a way to ]detect disconnections in the pool](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#connection-quality).

There is a plan to add built-in disconnection detection in psycopg_pool 3.2. (#247).

If you are not interested in test if that solution works, we can close this ticket here.

**Comment by haf** [comment]
Sorry, what? I think we're talking past each other here. Are you saying that silent loss of data is OK for a database driver?

**Comment by dvarrazzo** [comment]
You are the person who is managing your network. If your network drops in ways that don't warn the driver, the latter cannot do much.

I also don't have access to your network so I cannot make tests with it. As you refuse to collaborate, there is nothing I can do for you.

**Comment by haf** [comment]
I'm not refusing to collaborate 😂

**Comment by haf** [comment]
You're also wrong, I'm sorry to say. Networks are asynchronous and failure inevitable. If you've read the CAP theorem you know that you can have consistency or availability but you alway choose partition tolerance. This is a partition in the network. Since you can't detect asynchronous conditions on the TCP socket (it may be broken and there's no way for clients to know), the only time you can detect the failed connection is on write. 

What this means is that you cannot atomically and correctly infer the state of the connection with the so called solution you present. Because even if you do a `pool.check()` a nanosecond before you do the write, that nanosecond later the connection might be broken and you end up with silent data loss anyway.
