### ISSUE TITLE
Silent data loss for AsyncConnectionPool

### ISSUE THREAD

**Issue by haf** [psycopg/psycopg#291]
When using a port-forwarding tunnel, and async connection pool and nested connections, parent connections do not report errors from writes.

Networks are asynchronous and failure inevitable. If you've read the [CAP theorem](https://en.wikipedia.org/wiki/CAP_theorem) you know that you can have consistency or availability but you always choose partition tolerance. This is a partition in the network. Since you can't detect asynchronous conditions on the TCP socket (it may be broken and there's no way for clients to know), the only time you can detect the failed connection is on write.

You cannot [atomically](https://en.wikipedia.org/wiki/Atomicity_(database_systems)) and correctly infer the state of the connection with psycopg currently. Because even if you do a pool.check() a nanosecond before you do the write, that nanosecond later the connection might be broken and you end up with silent data loss anyway. Similarly, if you enable heartbeats, since they are not atomically bound to the write operation.

Thus https://github.com/psycopg/psycopg/issues/247 does not solve this issue.

The only way that you can write correct code in the light of asynchronous network failures is if the write operation itself fails. This issue is about the write operation in psycopg succeeding despite the connection being down, and therefore the application silently losing data.

### Pseudo-code

When you have code like:

```python
async def f():
    async with pool.connection() as conn:
        async with pool.connection() as conn2:
            async with conn2.cursor() as cur:
                await cur.execute insert into
        await sleep(60 * 4.5)
        params = [ ... about 1500 dicts ]
        async with conn.cursor() as cur:
            await cur.executemany(insert into .. values (%(..)s), params) # this write fails silently
        async with pool.connection() as conn3:
            async with conn3.cursor() as cur:
                await cur.execute insert into
```

Then we get the middle write failing silently.

This is running in a process in uvicorn but since I'm running it locally, there's no load.

### Workarounds

We can utilise a timer that continuously does `check` on the pool, or enable heartbeats on the connection, but it doesn't solve the underlying issue and doesn't protect (much) from silent data loss.

Besides this, the code above sleeps for four minutes, which is not "too long to be plausible" and much less than the two hour rule of thumb, so by induction, how do I know the duration between the `pool.check` and the `write` is not longer than what happened to be the timeout?

Additionally, if pool.check is done outside the scope of `async with pool.connection()`, there's no way for the calling code to unwind its unit of work to a point where it can be retried, because the write itself is not throwing an exception/error that can be used as a signal to retry; the write will just be silently ignored by the caller code (because connections need to be reestablished which creates new connection instances, != the pool.connection() instance).

It also works better if you move the connection opening to just before the write, because then the connection is fresh; this is our current workaround and it makes it all stable, but I'd very much like to work with the authors of this library to make the write error bubble all the way to the caller code.

### Versions

- OS: macOS 12.3.1 (21E258) on M1 and hence the self-compiled `psycopg[c]` bindings,
- SSH OpenSSH_8.6p1, LibreSSL 3.3.5
- Python: Python 3.9.10

psycopg = {extras = ["c"], version = "^3.0.10"}
psycopg_pool = "^3.1.1"

## References

- https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/
- https://quick-adviser.com/how-do-i-know-if-my-tcp-connection-is-broken/
- https://stackoverflow.com/questions/37917947/when-is-a-tcp-connection-considered-idle
- https://blog.stephencleary.com/2009/05/detection-of-half-open-dropped.html — however, the check logic is really good and implements exactly this; here the problem is with the unit of work (the ML models we run) and how to make retries that don't break our budget

**Comment by dvarrazzo** [comment]
@haf,

what is a nested connection?

```
        await conn.executemany(insert into .. values (%(..)s), params) # this write fails silently
```

I can't help but noticing that `AsyncConnection.executemany` doesn't even exist as a method. Are you running your code in a `try ... except: pass`?

But let's assume that you mean `Cursor.executemany()`. The operation sends the commands on the network and await for a response from the server. If the response is not OK then it throws an exception. I struggle to see how an operation can fail silently. At most I could expect a thing to hang forever.

`executemany()` discards the result (optionally, it won't, in psycopg 3.1); I would like you to take a look at those results instead. Can you replace it with a loop over params and `cursor.execute()`, and then take a look at `cursor.pgresult`? Two things can happen in `execute()`: either the operation hangs somewhere, meaning that the Python function doesn't return, or the operation terminates with a pgresult received, meaning that the server has received the message. I can't see a failure mode where the operation is terminated (`execute()` or `executemany()` return) but the message is silently lost. If you lose connection after execute and so you can't send a COMMIT to the server is a different problem, which you can solve with an autocommit connection.

Anyway, in the past I have seen reports of port-forwarding not working with async connections and certain ssh tunnels. `ssh -L` works, `sshtunnel` doesn't (https://github.com/psycopg/psycopg2/issues/801). That's not a problem we can solve. But again I expect some hanging, or some protocol failure, not to receive a COMMAND_OK message.

Also consider replacing your `executemany("insert")` with a copy operation: it will be likely faster.

**Comment by haf** [comment]
> I can't help but noticing that AsyncConnection.executemany doesn't even exist as a method.
You're right, I simplified too much: I've updated the code now to reflect the cursor we use

> The operation sends the commands on the network and await for a response from the server. If the response is not OK then it throws an exception. I struggle to see how an operation can fail silently. At most I could expect a thing to hang forever.

1000x this!

> ssh -L works

We use this.

> with a copy operation

I agree; I tried making sense of it but couldn't find docs that would tell me how to properly serialise all the types we pass in (JSONB amongst others)

> executemany() discards the result

Yes, we used to have `RETURNING id` at the end of the INSERT, but removed it for this reason, thinking it might have something to do with the reason no data was written.

>  I can't see a failure mode where the operation is terminated (execute() or executemany() return) but the message is silently lost.

Yes, that's why this bug is so mind-boggling to me too. It's hard for me to quickly / easily test this as it's affecting production data (causing our customers to see empty screens) and it only reproduces when the networking layer is tunnelled and we don't run the `check` healthcheck on the pool continuously, but we have full opentelemetry tracing set up, and I've been looking to hook into psycopg in depth to debug this. Perhaps if we could instrument the driver, we can run it again? It reproduces readily.

**Comment by haf** [comment]
Also

> what is a nested connection?

one that is opened when another is already open. This may or may not affect the outcome, and probably won't, if connections are not nested in the library around a ContextVar.

**Comment by dvarrazzo** [comment]
> [about copy] couldn't find docs that would tell me how to properly serialise all the types we pass in 

Copy.write_row() performa the same data adaptation normal querying does. https://www.psycopg.org/psycopg3/docs/basic/copy.html#writing-data-row-by-row

> Perhaps if we could instrument the driver, we can run it again? It reproduces readily.

If something resembling an error silently ignored happens, I expect it to happen [here around](https://github.com/psycopg/psycopg/blob/ebca22d15f4fdaa2f50eef6ecacc3ab697ca7904/psycopg/psycopg/cursor.py#L220).

**Comment by dvarrazzo** [comment]
Hello,

where are we with this? Was it possible for you to investigate/reproduce the issue you found?

I don't see how it is possible that psycopg reports a success in the face of a network write error. I think there is some error from the point of view of your analysis. My assumption is that the connection is interrupted before commit but your code doesn't notice it (in that case there should be entries in the server logs).

Can we close this?
