### ISSUE TITLE
Named Parameter Error

### ISSUE THREAD

**Issue by mrondin1** [psycopg/psycopg#294]
Hello - thanks for this great library. I'm getting an error while trying to used named parameters.

In the simplified example below, I am only using each parameter once and could just pass in them without names (I have this working), but in the expanded example, I used the user_id several times, thus my desire to use named parameters.

Could you please advise?

```python
cur.execute("""
		SELECT
			*
		FROM
			menu_versions mv
			JOIN menu_meal_recommendations mmr ON mmr.menu_version_id = mv.id
			JOIN permissible_meal_options pmo ON pmo.meal_id = mmr.meal_id
		WHERE
			mmr.user_id = %(user_id)s
			AND mv.id = %(menu_version_id)s
			ORDER BY
				rank ASC
			LIMIT 1;
                """, 
                {'user_id': user['user_id'], 'menu_version_id': decodedMeals[0]['menu_version_id']})
                
cur.fetchone()
```

And the error:

`
psycopg.ProgrammingError: only '%s', '%b', '%t' are allowed as placeholders, got '%''
`

**Comment by dvarrazzo** [comment]
I think you simplified your query too much. According to the error message, there is a `%'` in your query. With the sample you gave us I can't reproduce.

**Comment by mrondin1** [comment]
Thank you! I had an unescaped % elsewhere in the query when using a `y.name ilike % || z.name`.  Solved by using %%. Appreciate the help.
