### ISSUE TITLE
Commit result managed too late in pipeline mode?

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#296]
Hi @dlax,

Looking at [the example](https://www.psycopg.org/psycopg3/docs/advanced/pipeline.html#synchronization-points) added yesterday on the pipeline docs page:

```python
with psycopg.connect(autocommit=True) as conn:
    with conn.pipeline() as p, conn.cursor() as cur:
        cur.execute("INSERT INTO mytable (data) VALUES (%s)", ["one"])
        cur.execute("INSERT INTO no_such_table (data) VALUES (%s)", ["two"])
        conn.execute("INSERT INTO mytable (data) VALUES (%s)", ["three"])
        p.sync()
        cur.execute("INSERT INTO mytable (data) VALUES (%s)", ["four"])
```

there is something fishy here. I think Python shouldn't have reached `four` at all, if not with a try ... except - especially after `sync()` is called. While this might be tolerable, and the error deferred to the end of the block, although with ample disclaimers, this might be too flaky for a COMMIT.

> [from #271] there does not seem to be a need for syncing before commit(), only before rollback() is needed

I am not sure about this after all. Not so much syncing before commit, but after commit it might be useful. From the pipeline mode docs:

> The client must not assume that work is committed when it sends a COMMIT — only when the corresponding result is received to confirm the commit is complete.

Looking at our behaviour instead:

```python
# A table to cause an error on commit
# create table selfref (x serial primary key, y int references selfref (x) deferrable initially deferred);
>>> conn = psycopg.connect()
>>> pg = conn.pipeline()
>>> p = pg.__enter__()
>>> conn.execute("insert into selfref (y) values (-1)")
>>> conn.commit()  # no error here
>>> p.sync()  # no error here either!
>>> conn.execute("select 1")
Traceback (most recent call last)
ForeignKeyViolation: insert or update on table "selfref" violates foreign key constraint "selfref_y_fkey"
DETAIL:  Key (y)=(-1) is not present in table "selfref".
```

I think that it would be reasonable to expect, on `conn.commit()` (or at exit of a `transaction()` block), that, if there is an error invalidating the transaction, it is raised there.

As far as I can see, we can raise an error on commit pretty much only by doing what `Pipeline.__exit__()` does (the outermost one, not even the nested ones):

```python
# ... as above
>>> conn.commit()
>>> p.sync()
>>> conn.wait(p._fetch_gen(flush=False))
Traceback (most recent call last)
ForeignKeyViolation: insert or update on table "selfref" violates foreign key constraint "selfref_y_fkey"
DETAIL:  Key (y)=(-1) is not present in table "selfref".
```

- Maybe it would be responsible to run this operation inside `commit()`?
- Maybe it would be useful to fetch results after `sync()`, so that sync returns any possible error? This would maintain the expectation of the method to be a synchronization point.

These behaviours are higher level compared to the libpq function calls, but probably they are what the user expects. Maybe we are skipping on safety too much for the pursuit of performance here (performance can be still had if transactions or explicit syncs are not involved).

What do you think?

Thank you! :)

**Comment by dvarrazzo** [comment]
I have added two changeset to implement the above two points. I think this makes the pipeline mode more predictable to use. What do you think?

Cheers!

**Comment by dlax** [comment]
Hi @dvarrazzo,
Your analysis makes sense to me; indeed, as evidenced by this unexpected behavior on `commit()`, we probably are too "low-level" currently.
In this respect, the changes proposed in fix-296 branch look good to me; thank you.
