### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#305]
At the moment, psycopg-c build is [not compatible with Python 3.11](https://github.com/psycopg/psycopg/actions/runs/2328072296). We probably need to wait for release of Cython 3.0.0a11 because the errors during build seem already addressed and merged to master:

- https://github.com/cython/cython/issues/4500
- https://github.com/cython/cython/issues/4721

**Comment by septatrix** [comment]
It would also be nice to replace the `str` in the `Query` type alias with `LiteralString` (sadly there is no bytes equivalent)

**Comment by itsankitkp** [comment]
On related note: 
Tested on Python 3.12.0a0 (built from source)
Run
`pip install -e ./psycopg_c  `
Response:
[res.txt](https://github.com/psycopg/psycopg/files/9142462/res.txt)

**Comment by dvarrazzo** [comment]
@itsankitkp theyt seem cython-related issues. Did you build it with the master version of cython? 3.0.0a10 surely doesn't support Python 3.12.

**Comment by dvarrazzo** [comment]
> Yes, I build with master version of CPython 

And which version of Cython?

**Comment by itsankitkp** [comment]
Pip freeze result as follows:
`Cython==0.29.30`

**Comment by dvarrazzo** [comment]
Cython 0.x definitely doesn't work. As already stated, to have a chance to compile for Python 3.11 you need cython from master, for the reasons explained in this ticket. I expect Python 3.12 to need at least the same.

**Comment by itsankitkp** [comment]
I did try that but it is still failing with Cython==3.0.0a10 (Cython master)

Might need to wait for 3.0.0a11

**Comment by itsankitkp** [comment]
Error log [error.txt](https://github.com/psycopg/psycopg/files/9151486/error.txt)

**Comment by honglei** [comment]
https://pythoninsider.blogspot.com/2022/08/python-3110rc1-is-now-available.html 
Any updates for Python3.11rc1？
The https://pypi.org/project/psycopg/#files version 3.1.1 still not work under Python3.11.
```
C:\Users\Admin>c:/python311/python.exe -m pip install -U psycopy 
ERROR: Could not find a version that satisfies the requirement psycopy (from versions: none)
ERROR: No matching distribution found for psycopy
```

**Comment by dvarrazzo** [comment]
You have a typo in the package name. You can probably install `psycopg` and it should probably work already. You must have your `libpq.dll` in the system.

`psycopg[binary]` needs a specific release, which won't happen until the official Python 11 release: it is advised against loading packages on pypi for unstable releases.

I have noticed that Cython 3.0.0a11 has been released: will try if it fixes all the problems and merge this branch so that we can release packages for Py11 as soon as it's final.

**Comment by dvarrazzo** [comment]
It makes sense, @septatrix, you are right :+1: 

I've uploaded the packages just built on test pypi: instruction to install them at https://test.pypi.org/project/psycopg/3.1.2.dev0/

**Comment by dvarrazzo** [comment]
Merging to master and releasing, see #424.

**Comment by loopassembly** [comment]
> At the moment, psycopg-c build is [not compatible with Python 3.11](https://github.com/psycopg/psycopg/actions/runs/2328072296). We probably need to wait for release of Cython 3.0.0a11 because the errors during build seem already addressed and merged to master:
> 
> * [Adapt to exc_info changes in Py3.11 cython/cython#4500](https://github.com/cython/cython/issues/4500)
> * [[BUG] Use of ob_shash is deprecated on 3.11 cython/cython#4721](https://github.com/cython/cython/issues/4721)

'pg_config executable not found' is the error from python 3.11 ? if so then how much time it is going to take to be fixed?

**Comment by dvarrazzo** [comment]
@loopassembly 

> so then how much time it is going to take to be fixed?

Do I owe you anything?

Psycopg 3 for 3.11 has been released days ago. You are most likely barking at the wrong tree. But, because you are so nice, I will save you from barking more by blocking you. I have zero patience for people like you.

**Comment by septatrix** [comment]
@loopassembly I assume you are trying to build from source. If so it seems like `pg_config` is not installed though that is not the fault of this project but instead due to you missing requirements: See the [local install section](https://www.psycopg.org/psycopg3/docs/basic/install.html#local-installation)
