### ISSUE TITLE
Attempting to define the returned value of connect() as generic

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#308]
Subclassing a connection doesn't require to redefine the `connect()` method, because it is generic. However we can't explain this to mypy yet, because [the function is defined returning `Connection`](https://github.com/psycopg/psycopg/blob/79c14f47f2068cd568ee8b50df79090f16a3f9c5/psycopg/psycopg/connection.py#L673-L713).

Attempts to use [a generic self](https://mypy.readthedocs.io/en/stable/more_types.html#precise-typing-of-alternative-constructors) fail because it seems that the generic self doesn't play well with a default argument for the generic parameter.

This is a self-contained reproduction of the issue: [2023-12: edited using more modern typing techniques]

```python
from typing import Any, Callable, Generic, Self, Sequence, TypeAlias, TypeVar, overload, cast

Row = TypeVar("Row", covariant=True)
TupleRow: TypeAlias = tuple[Any, ...]
DictRow: TypeAlias = dict[str, Any]
RowFactory: TypeAlias = Callable[[Sequence[Any]], Row]

def tuple_row(values: Sequence[Any]) -> TupleRow:
    ...

def dict_row(values: Sequence[Any]) -> DictRow:
    ...

class Connection(Generic[Row]):
    @overload
    @classmethod
    def connect(cls, *, row_factory: RowFactory[Row]) -> Self:
        ...

    @overload
    @classmethod
    def connect(cls) -> Self:
        ...

    @classmethod
    def connect(cls, *, row_factory: RowFactory[Row] | None = None) -> Self:
        ...

c = Connection.connect()  # mypy reports required annotation
reveal_type(c)  # Revealed as Connection[Any], should be Connection[TupleRow]

ct = Connection.connect(row_factory=tuple_row)
reveal_type(ct)  # Revelaled as Connection[TupleRow]

cd = Connection.connect(row_factory=dict_row)
reveal_type(cd)  # Revelaled as Connection[DictRow]
```

with this definition, `connect()` without `row_factory` argument loses the info that it returns tuple rows.

It would be nice to be able to specify `Self[TupleRow]` as return values, but the typevar cannot be used with an argument.

Another attempt that I wish worked is to use a default argument instead of override: [2023-12: edited using more modern typing techniques]

```python
class ConnectionNoOverload(Generic[Row]):

    @classmethod
    def connect(cls, *, row_factory: RowFactory[Row] = tuple_row) -> Self:
        ...
```

This definitions fails with mypy errors with: _Incompatible default for argument "row_factory" (default has type "RowFactory[Tuple[Any, ...]]", argument has type "RowFactory[Row]")_. Same defining `rowFactory: RowFactory[Row] = cast(RowFactory[TupleRow], tuple_row)`. If instead we define `rowFactory: RowFactory[Row] = cast(RowFactory[Row], tuple_row)` we have the same problem of the overload example (and we are pretty much discarding the type generic parameter of the default).

Can we do something better or is this a mypy shortcoming?

Note: The examples above were edited from using a `_Self` typevar workaround to the proper PEP 673 `Self`. The example was also simplified by dropping the RowMaker/RowFactory detail.

**Comment by dlax** [comment]
There is PEP to add a `Self` type, which might help us here: https://peps.python.org/pep-0673/
It's available from python 3.11 already, https://docs.python.org/3.11/library/typing.html#typing.Self; it's in `typing_extensions` as well.

(This also reminds me about https://github.com/python/mypy/issues/11004, but does not seem obviously related.)

**Comment by dvarrazzo** [comment]
I am aware of the Self pep. They explicitly reject `Self[type]` though. I wonder if they have considered this use case in designing `Self`, so I wanted to get this problem out with eventual discussion with the mypy people.

I asked about it on the python/typing channel in Matrix, got no answer yet.

**Comment by dlax** [comment]
Maybe try https://github.com/python/typing/discussions? I think that's the "official" forum and it seems quite active.

**Comment by dvarrazzo** [comment]
Note: asked better, after moving to `typing.Self` in:

- https://github.com/python/typing/discussions/1555
- https://github.com/python/typing/discussions/1556

**Comment by dvarrazzo** [comment]
IN https://github.com/python/typing/discussions/1556 they suggested that what we are looking for here is [PEP 696](https://peps.python.org/pep-0696/) and, indeed, defining `TupleRow` the default for the `Row` TypeVar, we don't need to override `Connection.connect()` and the return value works as expected and doesn't require signature changes in subclasses.

**Comment by dlax** [comment]
That's a very good news!

**Comment by dvarrazzo** [comment]
I have verified that [MyPy 1.6 is required](https://github.com/psycopg/psycopg/actions/runs/7392679758/job/20111484045) to work correctly with TypeVar defaults, but [it's too late for Python 3.7](https://github.com/psycopg/psycopg/actions/runs/7392889523/job/20111998287). Therefore we can only make this change on the master branch.

I think it's time to wrap up 3.2.
