### ISSUE TITLE
psycopg.DataError: can't parse timestamptz 'infinity': year 0 is out of range

### ISSUE THREAD

**Issue by tfotis** [psycopg/psycopg#315]
**Summary**

I am using psycopg 2.9.3 and I am trying to migrate to psycopg 3.0.14, but I get error `psycopg.DataError: can't parse timestamptz 'infinity': year 0 is out of range`.

"infinity" datetime was handled correctly in psycopg 2.9.3 and it returned the datetime aware object.

**How to reproduce**

1. Create a table
```
CREATE TABLE "public"."psycopg3_infinity" (
    "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);
```

2. Insert a record
```
INSERT INTO "public"."psycopg3_infinity" ("created_at") VALUES ('infinity');
```

3. Fetch all rows from the table
```
import psycopg

with psycopg.connect() as conn:
    with conn.cursor() as cur:
        sql = "SELECT * FROM public.psycopg3_infinity"
        cur.execute(sql)
        rows = cur.fetchall()
```

**Traceback**

```
File "test_psycopg3.py", line 94, in test_infinity
    rows = cur.fetchall()
File "lib/python3.8/site-packages/psycopg/cursor.py", line 630, in fetchall
    records = self._tx.load_rows(self._pos, self.pgresult.ntuples, self._make_row)
File "psycopg_binary/_psycopg/transform.pyx", line 401, in psycopg_binary._psycopg.Transformer.load_rows
File "psycopg_binary/types/datetime.pyx", line 807, in psycopg_binary._psycopg.TimestamptzLoader.cload
    psycopg.DataError: can't parse timestamptz 'infinity': year 0 is out of range
```

**Comment by dvarrazzo** [comment]
I have made the messages uniforms, on the tone of "date too large (after year 10K)", which is valid for both finite and infinite out-of-range dates. Also added a doc snippet in the page about the adapters differences.

I think that's it. At the moment I'm not planning to add infinite adapters and I'd rather leave the applications roll their own, with their own rules, if they need ones. If there is a compelling design for the feature we can look into it.
