### ISSUE TITLE
use `LiteralString` in Query 

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#323]
It would also be nice to replace the `str` in the `Query` type alias with `LiteralString` (sadly there is no bytes equivalent)

_Originally posted by @septatrix in https://github.com/psycopg/psycopg/issues/305#issuecomment-1166351333_

**Comment by dvarrazzo** [comment]
@septatrix if LiteralString is available in typing_extensions we can introduce it in psycopg 3.1 no problem.

Would you like to propose a patch?

**Comment by septatrix** [comment]
> @septatrix if LiteralString is available in typing_extensions we can introduce it in psycopg 3.1 no problem.

It seems to be included [starting with 4.1.0](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#release-410-february-12-2022)

> Would you like to propose a patch?

I would first like to take a look if this would also make sense in some other places though I currently do not have much free time at hand.

**Comment by dvarrazzo** [comment]
> I would first like to take a look if this would also make sense in some other places

`sql.SQL` comes to mind...

> though I currently do not have much free time at hand.

No worry about it. If we don't hear from you we will do it in the next few days :)

**Comment by dvarrazzo** [comment]
Adding something in the branch https://github.com/psycopg/psycopg/tree/literal-string

Mostly working except this TODO which will probably require a change in typeshed to be fixed.

https://github.com/psycopg/psycopg/blob/600d6dfaf1366d2eca4486f7686c57da88f2b807/psycopg/psycopg/sql.py#L248-L251

**Comment by dvarrazzo** [comment]
> I wonder if there should be a note...

I just added an embryo of docs in https://github.com/psycopg/psycopg/commit/a39b9e75d23a30a29100e013a2d8d8233c453316 if you have suggestions please feel free to contribute :)

> I made an issue for that: https://github.com/python/typeshed/issues/8195

Oh thank you! I opened https://github.com/facebook/pyre-check/issues/635 instead. It is not a Pyre issue of course, but they might know how to liaise better and share responsibilities.

**Comment by dvarrazzo** [comment]
> please feel free to contribute :)

An example would be especially welcome, but I didn't manage to ise pyre to check a test script, in order to write something correct.

**Comment by dvarrazzo** [comment]
Branch merged. I failed to use pyre with a script using psycopg (https://github.com/facebook/pyre-check/issues/636) but as a principle things should be ok.
