### ISSUE TITLE
psycopg.errors.InternalError_: parse error - invalid geometry

### ISSUE THREAD

**Issue by 91DarioDev** [psycopg/psycopg#334]
after the migration from psycopg2 to psycopg3 i noticed there is a query is no more working and i couldn't understand why

`UPDATE utenti SET location = ST_GeographyFromText('SRID=4326;POINT(%s %s)') WHERE user_id = %s RETURNING lang, status`

what i pass on the first two placehodlers are data like `	41.885333` and `12.524688` as float numbers.

this is the traceback i get when i issue the query

```
Traceback (most recent call last):
  File "a:\myproject\asyncio\lib\site-packages\telegram\ext\_application.py", line 1473, in process_error
    await callback(update, context)
  File "a:\myproject\asyncio\lib\site-packages\telegram\ext\_application.py", line 970, in process_update
    await coroutine
  File "a:\myproject\asyncio\lib\site-packages\telegram\ext\_handler.py", line 137, in handle_update
    return await self.callback(update, context)
  File "a:\myproject\beforeprocessing.py", line 50, in beforeProcessing
    if await beforeprocessingfuncs.is_requested_location(bot, update):
  File "a:\myproject\beforeprocessingfuncs.py", line 225, in is_requested_location
    extract = await database.queryWR(query, longitude, latitude, sender_id)
  File "a:\myproject\database.py", line 29, in queryR
    res = await query(raw_query, *params, one=one, read=True)
  File "a:\myproject\database.py", line 13, in query
    await cur.execute(query, params)
  File "a:\myproject\asyncio\lib\site-packages\psycopg\cursor_async.py", line 80, in execute
    raise ex.with_traceback(None)
psycopg.errors.InternalError_: parse error - invalid geometry
HINT:  "SRID=4326;POINT($1" <-- parse error at position 18 within geometry
```

this is the location column in the db schema `public.geography(Point,4326)`

i have never seen this error before migrating from psycogp2 to psycopg3 and i changed only the library 

searching on google i can find  some results but none of them related to psycopg, but it actually worked in psycopg2 and now no more in psycopg3.

could it be something dued to the fact that now parameters are binded server side? so i tried to cast to float with `::FLOAT` but didn't help.

**Comment by dvarrazzo** [comment]
Yes, the difference is likely caused by the use of server-side parameters. The `InternalError_` is something that might be worth to communicate to postgres developers though.

The parameters in psycopg 3 must be a value in the query. In your query you have an hardcoded literal string, and your placeholders compose part of it. It was only working in psycopg2 because the resulting string happened to be valid.

I assume this would work:

```python
cur.execute(
    "UPDATE utenti SET location = ST_GeographyFromText(%s) WHERE user_id = %s RETURNING lang, status",
    ["SRID=4326;POINT(%s %s)" % (val1, val2), user_id])
```

or even

```python
cur.execute(
    "UPDATE utenti SET location = ST_GeographyFromText('SRID=4326;POINT(' || %s || ' ' || %s || ')') WHERE user_id = %s RETURNING lang, status",
    [val1, val2, user_id])
```

which seems worse.

Can you try these solutions?

**Comment by dvarrazzo** [comment]
> The InternalError_ is something that might be worth to communicate to postgres developers though.

Or probably to postgis devs? This tests (and your error message):

```python
>>> cnn.execute("select 'hello %s'", [42]).fetchone()
('hello $1',)
```

show that the placeholder is kept as literal, as part of the string, and the relative parameters discarded. So you end up calling the function `ST_GeographyFromText('SRID=4326;POINT($1 $2)')`. `InternalError_` is pretty rude; `InvalidTextRepresentation` (sqlstate `22P02`) would have been a better choice.

**Comment by 91DarioDev** [comment]
thank you very much! i tried your first snippet and it works, but since i have the db part wrapped i have to adjust it a bit

this is my wrapped query function
```
async def query(query, *params, one=False, read=False):
    async with DB_POOL_CONNECTIONS.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(query, params)
            if read:
                if not one:
                    res = await cur.fetchall()
                else:
                    res = await cur.fetchone()
                return res
 ```
 
 so i did this 
 
 ```
user_id = 1234567890
coordinates = 'SRID=4326;POINT(%s %s)' % (longitude, latitude)
query = "UPDATE utenti SET location = ST_GeographyFromText(%s) WHERE user_id = %s RETURNING lang, status"
extract = await database.query(query, coordinates, user_id)
```

if i understood well your reply it's basically the same because it was about to build the string before and then pass the string builded and it's what i am doing.

now my question is: since those values are inputed by users is it safe against sql injection? i think it should be safe because despite i build a part of the query string with users inputed data directly in python, then the string is passed the psycopg library. but i prefer to ask because i am a bit scared of manipulating query strings with users inputs. Don't I have to build that string with any helper that sanitize it? is it already fine?
i don't do any check on coordinates so they can be anything, but again, i think it should be fine because in the end the builded string is passed to the psycopg execute() in that wrapper.

thank you

**Comment by dvarrazzo** [comment]
Yes, it is safe anyway. Even if the user sneaks in a `'` to try to craft an injection string:

- in psycopg 2, that quote would be escaped into a double quote as a part of the whole `coordinates` string escaping
- in psycopg 3, whatever the content of the string, postgres will pass it as a single parameter to the `ST_GeographyFromText()` function

In both cases, `ST_GeographyFromText()` would receive an invalid parameter and will complain, but the whole query would be safe.
