### ISSUE TITLE
psycopg3 weird behaviour passing INTERVAL as parameter 

### ISSUE THREAD

**Issue by 91DarioDev** [psycopg/psycopg#335]
after migrating to psycopg3 i noticed a very strange behaviour in my old queries, after playing a bit with the code i discovered that passing seconds interval as parameter acts differently than hard coding it the query.

this query in particular shouldn't return any tuple  because of the where clause:
```
	q1 = """
			SELECT 
	   			user_id,
	   			reopen_request_time
	   		FROM
	   			utenti
			WHERE
				reopen_request_time IS NOT NULL AND 
				reopen_request_time < NOW() - INTERVAL '%s SECONDS'	
	"""

	async with database.DB_POOL_CONNECTIONS.connection() as conn:
		async with conn.cursor() as cur:
			await cur.execute(q1, [129600])
			res = await cur.fetchall()
			print(res)
```

but instead it's returning this tuple:

`[(1054685415, datetime.datetime(2022, 7, 16, 21, 42, 15, 349007))]`

the same query with the parameter hardcoded instead doesn't retun any tuple and it's right!

```
	q2 = """
			SELECT 
	   			user_id,
	   			reopen_request_time
	   		FROM
	   			utenti
			WHERE
				reopen_request_time IS NOT NULL AND 
				reopen_request_time < NOW() - INTERVAL '129600 SECONDS'	
	"""

	async with database.DB_POOL_CONNECTIONS.connection() as conn:
		async with conn.cursor() as cur:
			await cur.execute(q2)
			res = await cur.fetchall()
			print(res)
```

print: `[]`

to make things clear i print also the time now:

```
	async with database.DB_POOL_CONNECTIONS.connection() as conn:
		async with conn.cursor() as cur:
			await cur.execute('select now();')
			res = await cur.fetchall()
			print(res)
```

`[(datetime.datetime(2022, 7, 16, 22, 9, 13, 451450, tzinfo=zoneinfo.ZoneInfo(key='CET')),)]`

so since the now() time the correct query is the second one, with the paramter hardcoded. why the first one instead is retuning a tuple that it shouldn't return?
also i don't see any error in console

**Comment by 91DarioDev** [comment]
i tested that on psycopg2 it's fine so i think it's dued to the fact that paramters are binded server side, but the other times i got the error in console, this time i don't and i don't know how to fix, i tried adding ::INTEGER but it said it was invalid


i forgot to say the column type is "TIMESTAMP"

**Comment by dvarrazzo** [comment]
The problem is similar to one we saw a few days ago in #334. If you have a `%s` parameter into a literal string, psycopg will convert it into a postgres parameter (`$1`, `$2`, ...) but Postgres will not perform a parameter substitution, because the `$n` is taken as part of a literal.

There is no error because, unfortunately, the PostgreSQL interval parser is unpleasantly permissive and takes the `$` as noise, so:

```
piro=# select interval '$1 seconds';
┌──────────┐
│ interval │
├──────────┤
│ 00:00:01 │
└──────────┘
(1 row)
```

Like in #334, the solution is to keep the parameters out of the strings. Something like this (untested) should work:

```
			SELECT 
	   			user_id,
	   			reopen_request_time
	   		FROM
	   			utenti
			WHERE
				reopen_request_time IS NOT NULL AND 
				reopen_request_time < NOW() - (%s * INTERVAL '1 SECOND')	
```
