### ISSUE TITLE
AsyncConnection.notifies() gernerator blocks AsyncConnection.execute()

### ISSUE THREAD

**Issue by saschathiergart** [psycopg/psycopg#340]
I have a use case where a single `AsyncConnection` needs to listen on different channels. Which to listen on becomes known in runtime, e.g. connected clients determine what is listened and unlistened on. Unfortunately, when using the `AsynConnection.notifies()` generator, further `AsyncConnection.execute()` calls will hang. 

```
async def test_notifies():
    con = await psycopg.AsyncConnection.connect(PSYCOPG_DSN, autocommit=True)
    await con.set_autocommit(True)

    async def notifier():
        i = 0
        while True: 
            await con.execute(f'notify foo, \'{i}\'')
            print(f"notified {i}")
            await asyncio.sleep(1)
            i += 1
            if i==10:
                break
        await con.close()
        
    async def receiver():
        print("receiver: LISTENING ")
        cur = con.cursor()
        await cur.execute("listen foo")
        gen = con.notifies()
        async for n in gen:
            print("receiver: notified ")
            print(n)

    workers = [notifier(), receiver()]
    await asyncio.gather(*workers)
    
asyncio.run(test_notifies())
``` 

Output of the program:
```
receiver: LISTENING 
notified 0
```
After that the  program hangs.

**Comment by dvarrazzo** [comment]
Yes, you are not supposed to run queries while you are listening.

If you need to issue a new LISTEN on that connection, you can stop the notifies generator (using generators.close(), see [docs](https://www.psycopg.org/psycopg3/docs/advanced/async.html#asynchronous-notifications)), execute the statement, and call notifies() again. You won't lose messages doing so: they will be buffered in the libpq connection anyway.

**Comment by saschathiergart** [comment]
Thank you @dvarrazzo  for the suggestion. How do you close a running generator outside of the generator, i.e. outside of `async for n in gen:`?  

Example:
``` 

async def test_notifies():
	con = await psycopg.AsyncConnection.connect(PSYCOPG_DSN, autocommit=True)
	await con.set_autocommit(True)
	ctx = {'gen': None}

	async def notifier(ctx):
		await asyncio.sleep(1)
		i = 0
		while True: 
			gen = ctx.get("gen")
			if gen:
				await gen.aclose()
			cur = con.cursor()
			await cur.execute(f'notify foo, \'{i}\'')
			ctx['gen']=con.notifies()
			await asyncio.sleep(1)
			i += 1
			if i==10:
				break
		await con.close()
		

	async def receiver(ctx):
		print("receiver: LISTENING ")
		cur = con.cursor()
		await cur.execute("listen foo")
		gen = con.notifies()
		ctx['gen']=gen
		async for n in gen:
			print("receiver: notified ")
			print(n)

	workers = [notifier(ctx), receiver(ctx)]
	await asyncio.gather(*workers)
	
asyncio.run(test_notifies())
``` 
will result in a RunTimeError: `RuntimeError: aclose(): asynchronous generator is already running`.

I am wondering if using a generator for notifies is actually the right concept. Maybe using an event emitter like approach would make it more useful.

**Comment by dvarrazzo** [comment]
> How do you close a running generator outside of the generator, i.e. outside of async for n in gen:?

Maybe you could use a different task to call `gen.close()`.

> I am wondering if using a generator for notifies is actually the right concept. Maybe using an event emitter like approach would make it more useful.

If you wanted to do that you can use `add_notify_handler()` and then use `select()` to wait for the connection to have activity, and run a `select 1` to gather the notifies received.

**Comment by saschathiergart** [comment]
> Maybe you could use a different task to call `gen.close()`.

As far as i understand, i am doing that in my example. This makes the `AsyncConnection.notifies` only usable for special use cases. 

> If you wanted to do that you can use add_notify_handler() and then use select() to wait for the connection to have activity, and run a select 1 to gather the notifies received.

Sure, `add_notify_handler()` could be used but executing `select 1` to receive notifications is an overhead that can become big, if the application needs to get that notifications quickly. Not really an ideal solution imo.

**Comment by dvarrazzo** [comment]
> As far as i understand, i am doing that in my example. 

Ah, sorry, I missed the `aclose()`. Anyway, that's strange.

There is [a test in the test suite](https://github.com/psycopg/psycopg/blob/47019949990c5ea2007096a84d844722796212c8/tests/test_concurrency_async.py#L65) using that featue: do you want to check what it is doing?

I will try to put together a small demo program doing what you need to do (closing and reopening a notifies generator). But I don't have time right now. leaving the ticket open as a reminder.

**Comment by saschathiergart** [comment]
Yes i checked the test and my example is inspired by that. There you are closing the generator within the generator loop and im my example i am trying closing it from outside.

**Comment by saschathiergart** [comment]
Thinking about it, wouldn't it make sense to declare notifies as `asyncio.Queue` ? and put notification in the queue as they appear, thus isolating the notifications from the connection?

**Comment by dvarrazzo** [comment]
The problem you are having here is that you want to be able to send statements on the same connection you are listening from. In that moment you have to stop listening, send the statement, and start listening again. 

I suspect we can do this operation with the primitives that psycopg exposes. I can try and put together a recipe for it. If it turns out that that it can't be done, we can think about other approach. If the pattern is clean enough we might make it into ab exposed functionality. 

Being the producer a queue is just an interface, which can be created using whatever component available; I don't think it changes radically the problem of stopping and restarting the listening. If you think otherwise, I invite you to look at how generators.notifies() is implemented: you will see that it basically just two calls to libpq functions, organised in a way to be called as soon as the connection is ready for reading. You can  try to create your own notifies producer out of them, and if you come out with something that is easier to compose with other code I'm happy to consider its inclusion in thel library 🙂

**Comment by dvarrazzo** [comment]
I made some tests about this problem, some time ago, but I can't find my finding back. I seem to remember I could cancel the async version [using this pattern](https://stackoverflow.com/questions/60226557/how-to-forcefully-close-an-async-generator) and I can't remember if I could cancel successfully the sync one.

Adding a timeout parameter might be a good idea too.

**Comment by AlanCoding** [comment]
I hit a version of this issue because we had existing non-async code using [an old recipe for psycopg2](https://www.psycopg.org/docs/advanced.html#asynchronous-notifications). In that case, using `select.select` you wait until notification(s) come, and then loop over the current queue. Once you've exhausted the notifications, you can do other stuff before waiting for more messages.

The headache with this library is that I don't want that outer `while True:` here:

https://github.com/psycopg/psycopg/blob/2ca04b77dbe1ea50a422fcefeda22fa756be754c/psycopg/psycopg/connection.py#L918-L927

I have existing machinery (that still works) to wait until a notification is received. You can follow my specific problem at https://github.com/ansible/awx/pull/14222, where I duplicated the method so I could remove that outer loop. So far it works like a charm.

It's very useful to block until "notification is received _or_ 5 seconds passes". This way, the process dispatching those notifications can also be used to do periodic work. I can see how python threading `Event` objects could be used to solve the problem, as an alternative. An asyncio version could do something like `asyncio.wait_for(gen.__anext__(), 5)`, but that feels wrong, you'd probably prefer to add another task. In either case there's an added challenge of closing it out for the exit condition.

I'm agreeing with other comments that it would be nice for `.notifies()` to either take a timeout (presumably yielding a non-Notify object on timeouts), or directly expose the inner loop to only get queued notifications.

**Comment by dvarrazzo** [comment]
Hello,

Sorry for leaving this topic long unanswered. I worked on a few ways to
interrupt the generator, but the sync and asymc approaches were different
and now I can't remember what I was doing anymore...

I'm totally ok to add a timeout if this solves all the use cases we would
like to cover. The participants in this thread have concrete use cases, so
I'm happy to hear from you if this would cover your problems or if a
different interface would be preferable.

MRs are welcome too! :)

**Comment by AlanCoding** [comment]
I have not tested it (and much could be wrong), but I envision something like this https://github.com/psycopg/psycopg/compare/master...AlanCoding:yield_timeouts?expand=1, and this would be applied `AsyncConnection.notifies` method as well.

**Comment by dvarrazzo** [comment]
Please check #673 as a merge request to provide what requested in this conversation.

@jamesfmilne instead of a boolean to signify the end of a batch, the proposed interface can be used with `stop_after=1`: if more than one notification is received in the same batch they will be all yielded anyway.

**Comment by TreyBoudreau** [comment]
I have the same issue as @saschathiergart, but I can't afford to wait multiple seconds to update the (very dynamic) list of `LISTEN` changes. In my local copy I've modified the implementation of `notifies()` from:
```python
        async with self.lock:
            enc = self.pgconn._encoding
            while True:
                try:
                    ns = await self.wait(notifies(self.pgconn), interval=interval)
```
to:
```python
        while True:
            async with self.lock:
                enc = self.pgconn._encoding
                try:
                    ns = await self.wait(notifies(self.pgconn), interval=interval)
```
I think this addresses the issue described in 9c6403f while still allowing another async task to update the list of `LISTEN`s.

**Comment by dvarrazzo** [comment]
@TreyBoudreau Why to wait for multiple seconds? In psycopg 3.2 you can use `stop_after=1`. You may add a `listen_change` channel to listen on and signal there when the list of channel is updated so you can stop and re-listen again.

**Comment by dvarrazzo** [comment]
There is no 0.1 wait time if a notification is already sent. There is no polling, if not to enforce the timeout. The notifications are processed when the kernel gives the program the signal that the FD is readable. This happens immediately if a notification was already received at the time of calling `notify()`.

```python
import logging
import psycopg

logger = logging.getLogger()
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

c1 = psycopg.connect(autocommit=True)
c2 = psycopg.connect(autocommit=True)

c1.execute("listen test")

logger.info("notifying")
c2.execute("notify test")
logger.info("notified")

logger.info("listening")
for n in c1.notifies(stop_after=1, timeout=2.0):
    logger.info("received: %s", n)

logger.info("listened")
```

```
$ python test_not.py 
2024-11-22 19:44:32,225 INFO notifying
2024-11-22 19:44:32,225 INFO notified
2024-11-22 19:44:32,225 INFO listening
2024-11-22 19:44:32,225 INFO received: Notify(channel='test', payload='', pid=1036122)
2024-11-22 19:44:32,225 INFO listened
```

**Comment by TreyBoudreau** [comment]
```python
        # Allow interrupting the wait with a signal by reducing a long timeout
        # into shorter intervals.
        if timeout is not None:
            deadline = monotonic() + timeout
            interval = min(timeout, _WAIT_INTERVAL)
        else:
            deadline = None
            interval = _WAIT_INTERVAL
```

Calling `notifies(stop_after=1)` results in a loop that waits forever in `_WAIT_INTERVAL` (0.1 second) chunks. I can see the CPU usage in `top` :-)

Perhaps for my use case it would benefit me to go back to a variant of the original implementation. Something like:
```python
async def notifies(ev: asyncio.Event) -> AsyncGenerator[Notify, None]:
    """
    Yield `Notify` objects as soon as they are received from the database.
    :param ev: Continue dispatching `Notify` objects until something calls `ev.set()`.
    """
    async with self.lock:
        enc = self.pgconn._encoding
        while not ev.is_set():
            try:                                                                                                                             
                ns = await self.wait(notifies(self.pgconn))                                                                                  
            except e._NO_TRACEBACK as ex:                                                                                                    
                raise ex.with_traceback(None)                                                                                                
                                                                                                                                             
            # Emit the notifications received.                                                                                               
            for pgn in ns:                                                                                                                   
                n = Notify(                                                                                                                  
                    pgn.relname.decode(enc), pgn.extra.decode(enc), pgn.be_pid                                                               
                )                                                                                                                            
                yield n                                                                                                                      
```
Then I could `NOTIFY` in another connection and let the `listen_change` handler call `ev.set()`.

**Comment by TreyBoudreau** [comment]
For future reference, I ended up with this:
```python
async def db_listen_notify(connect: str, command_src: asyncio.Queue, notify_sink: asyncio.Queue):
    async def exec_cmd(aconn: psycopg.AsyncConnection, cmd: tuple):
        try:
            cmd_str: str = {
                'U': 'UNLISTEN {0}',
                'L': 'LISTEN {0}',
                'N': "NOTIFY {0} '{1}'"
            }[cmd[0]].format(*cmd[1:])
            async with aconn.cursor() as cur:
                await cur.execute(cmd_str)
        except KeyError:
            # unsupported command
            # print("Unsupported command:", cmd)
            pass 

    async def push_notifies(aconn: psycopg.AsyncConnection, notify_sink: asyncio.Queue):
        async with aconn.lock:
            pgconn = aconn.pgconn
            pgconn.consume_input()
            enc = pgconn._encoding
            while True:
                n = pgconn.notifies()
                if n:
                    notify_sink.put_nowait(psycopg.Notify(n.relname.decode(enc), n.extra.decode(enc), n.be_pid))
                else:
                    break

    async def queue_wait(cs: asyncio.Queue):
        result = await cs.get()
        cs.task_done()
        return result

    async def event_wait(e: asyncio.Event):
        await e.wait()
        e.clear()
        return True

    async with await psycopg.AsyncConnection.connect(connect) as aconn:
        await aconn.set_autocommit(True)
        file_handle = aconn.fileno()
        ev = asyncio.Event()
        loop = asyncio.get_running_loop()
        # set of tasks listening for commands and notifications
        pending = set()
        need_event_wait: bool = True
        need_queue_wait: bool = True
        while True:
            # (re-)create the tasks as required
            if need_event_wait:
                pending.update((loop.create_task(event_wait(ev)),))
                need_event_wait = False
            if need_queue_wait:
                pending.update((loop.create_task(queue_wait(command_src)),))
                need_queue_wait = False

            # tell asyncio to notify us on PG readability
            loop.add_reader(file_handle, ev.set)
            done, pending = await asyncio.wait(pending, return_when=asyncio.FIRST_COMPLETED)
            # remove the notification so we don't fight with psycopg over who owns connection
            loop.remove_reader(file_handle)

            for d in done:
                r = d.result()
                if type(r) is bool:
                    await push_notifies(aconn, notify_sink)
                    need_event_wait = True
                elif type(r) is tuple:
                    async with aconn.cursor() as cur:
                        await exec_cmd(aconn, r)
                    need_queue_wait = True
    return
```
This gives me 0% CPU utilization when idle.

**Comment by dvarrazzo** [comment]
@TreyBoudreau A loop waking up 10 times/sec is not a busyloop, it's pretty idle.
![image](https://github.com/user-attachments/assets/2d6fdc57-7f47-418e-a026-d23033d00b1a)

**Comment by TreyBoudreau** [comment]
@dvarrazzo I didn't describe it as a busyloop, I described it as polling. On the machine where I ran the code (an ancient Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz using CPython) the loop consumes between 0.3% and 0.7% according to `top`. For my use case I see no reason for it to use any CPU at all when idle.

If you (or anyone else) has suggestions for improving on my solution I'd really appreciate them. In particular I've basically cobbled this together out of the guts of `waiting.async_wait()` and `PGconn.notifies()`, with the `asyncio.Queue` stuff mixed in for updating the channel set. Using the `PGconn` APIs feels like using an implementation detail that might change in the future, but I didn't see any other way.

My thanks to you and the entire Psycopg team for the library!

**Comment by awoimbee** [comment]
I stumbled here because postgresql's [NOTIFY docs](https://www.postgresql.org/docs/current/sql-notify.html) state:

> If binary data or large amounts of information need to be communicated, it's best to put it in a database table and send the key of the record

*Then query the record in the LISTEN handler*

But then with psycopg:

> Yes, you are not supposed to run queries while you are listening.

As a workaround, I use:

```python
async def lockless_pgsql_notify(conn: psycopg.AsyncConnection):
    """Return NOTIFY events from the given psycopg async connection.
    Hack around <https://github.com/psycopg/psycopg/issues/340>.
    """
    while True:
        gen = conn.notifies(stop_after=1)
        notify = await anext(gen)
        await gen.aclose()
        yield notify
```
