### ISSUE TITLE
Sponsorship requested to release Apple M1 packages

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#344]
We have set up a workflow to build Apple Silicon packages for psycopg.

Building these packages comes at a cost, because of the scarcity that Apple forces on this hardware and because of Apple policies requiring to over-allocate build time for Apple Silicon workers. Further development cost was required to set up non-standard build scripts and further operational time will be required at every release because the Apple Silicon build procedure doesn't integrate easily with the existing build pipelines.

As a consequence, we ask the users of the Apple Silicon binary packages to sponsor their development and release. The cost of the packages is 2,000 USD: after this sponsorship level is cumulatively reached, Apple Silicon binary packages for the current and upcoming psycopg 2 and 3 releases will be released on PyPI. New versions of the packages will be released regularly, at least until changes in the build environment and policies stop the currently set up system from working and will require further effort to be restored.

If you are interested in the package release, you can use the project sponsorship channels to contribute. Please get in touch to make sure that your sponsorship is counted towards the release of the Apple Silicon packages. If you are already a sponsor, please get in touch if you wish to count your sponsorship towards the goal of releasing Apple Silicon packages.

Thank you very much for supporting the psycopg project.

**Comment by sckott** [comment]
just sponsored, not very much, but i'd like to put mine towards this

**Comment by hanssens** [comment]
> Please get in touch to make sure that your sponsorship is counted towards the release of the Apple Silicon packages.

Hereby, also a small contribution on my part. Thanks for the effort so far @dvarrazzo.

**Comment by meantheory** [comment]
Bumped this with my small contribution as well. Thank you @dvarrazzo.

**Comment by dvarrazzo** [comment]
Apple M1 binary packages for Psycopg 3.1.2 uploaded on PyPI. You can now `pip install psycopg[binary]` on Apple M1 too.

Thank you very much to all the contributors. Happy hacking!

**Comment by pauloxnet** [comment]
Thanks for this release, I shared about it on twitter
https://twitter.com/pauloxnet/status/1574011154686525440

**Comment by malthe** [comment]
From https://github.com/actions/runner-images/issues/9254:

> The new M1 runner is available for all plans, free in public repositories, and eligible to consume included free plan minutes in private repositories. The new runner operates exclusively on macOS 14 and to use it, simply update the runs-on key in your YAML workflow file to macos-14.

This should make it easy to build these packages are part of the pipeline.
