### ISSUE TITLE
Can't install psycopg[binary] on OS X Monterey x64

### ISSUE THREAD

**Issue by ianjevans** [psycopg/psycopg#347]
I'm working on adding a new psycopg 3 example to the CockroachDB docs, but can't install the binary package using `pip`.

```
❯ pip3 --version
pip 22.2.2 from /Users/ian/.pyenv/versions/3.10.6/envs/psycopg/lib/python3.10/site-packages/pip (python 3.10)
❯ pip install psycopg[binary]

zsh: no matches found: psycopg[binary]
```

I see that there's a `psycopg-binary` package that installs 3.0.16:
```
❯ ls ~/.pyenv/versions/psycopg/lib/python3.10/site-packages
_distutils_hack                 pip-22.2.2.dist-info            psycopg_binary-3.0.16.dist-info
distutils-precedence.pth        pkg_resources                   setuptools
pip                             psycopg_binary                  setuptools-63.2.0.dist-info
```

But that doesn't work:
```
❯ python3 example.py
Traceback (most recent call last):
  File "/Users/ian/go/src/github.com/cockroachlabs/hello-world-python-psycopg2/example.py", line 13, in <module>
    import psycopg
ModuleNotFoundError: No module named 'psycopg'
```

We have to use the binary package for the CockroachDB docs, fwiw.

**Comment by alemor10** [comment]
I use poetry but I ended up using `poetry install psycopg[c]`

**Comment by dvarrazzo** [comment]
Packages for Apple M1 are not released yet. See #344.

**Comment by ianjevans** [comment]
This isn't for an M1 Mac, this is for x64
<img width="256" alt="Screen Shot 2022-08-05 at 9 05 55 AM" src="https://user-images.githubusercontent.com/5760366/183117010-b94d0809-b699-4288-be24-bc6f079363bc.png">
.

**Comment by dvarrazzo** [comment]
The binary files are available here: https://pypi.org/project/psycopg-binary/#files

The file `psycopg_binary-3.0.16-cp310-cp310-macosx_10_9_x86_64.whl` is the one that pip should install on your machine, if I'm not mistaken.

Can you debug why it doesn't on your machine?

**Comment by ianjevans** [comment]
Ok, this looks like a problem with how zsh interprets the command. You need to escape the package name when using brackets.

```
❯ pip -v install psycopg[binary]

zsh: no matches found: psycopg[binary]
```

```
❯ pip -v install 'psycopg[binary]'

Using pip 22.2.2 from /Users/ian/.pyenv/versions/3.10.6/envs/psycopg/lib/python3.10/site-packages/pip (python 3.10)
Requirement already satisfied: psycopg[binary] in /Users/ian/.pyenv/versions/3.10.6/envs/psycopg/lib/python3.10/site-packages (3.0.16)
Collecting psycopg-binary==3.0.16
  Using cached psycopg_binary-3.0.16-cp310-cp310-macosx_10_9_x86_64.whl (2.6 MB)
Installing collected packages: psycopg-binary
Successfully installed psycopg-binary-3.0.16
```

So I think the docs should be updated to add quotes around the package name to make it usable on all platforms.

Also, if you try to install just the binary package, `pip install psycopg-binary`, the package name isn't aliased correctly in `site-packages`, so when you run an app it won't find the `psycopg` package.

**Comment by dvarrazzo** [comment]
@ianjevans I imagined something like that, because the error in your command starts with `zsh`. Does it work with double quotes too?

About installing only `psycopg-binary`: you are not supposed to do that, it was only a test to figure out why pip wasn't working. The package doesn't install the `psycopg` module, but just a speedup module `psycopg_binary`. The basic `psycopg` must still be installed, and the definition in the extra makes sure that the versions are consistent.

**Comment by ianjevans** [comment]
Yes, double quotes work as well:

```
❯ pip -v install "psycopg[binary]"

Using pip 22.2.2 from /Users/ian/.pyenv/versions/3.10.6/envs/psycopg/lib/python3.10/site-packages/pip (python 3.10)
Requirement already satisfied: psycopg[binary] in /Users/ian/.pyenv/versions/3.10.6/envs/psycopg/lib/python3.10/site-packages (3.0.16)
Requirement already satisfied: psycopg-binary==3.0.16 in /Users/ian/.pyenv/versions/3.10.6/envs/psycopg/lib/python3.10/site-packages (from psycopg[binary]) (3.0.16)
```

**Comment by dvarrazzo** [comment]
Quotes added to the `pip install` examples with extras. See https://www.psycopg.org/psycopg3/docs/basic/install.html for example.
