### ISSUE TITLE
Issue in documentation for version 3: Basic module usage

### ISSUE THREAD

**Issue by Alphorn** [psycopg/psycopg#348]
The example "Main objects in Psycopg 3" don't print the first record of the test table.

instead iterate on the pure cursor variable, the iteration should take place over "cur.fetchone():"

original version:  (no output)

        # Query the database and obtain data as Python objects.
        cur.execute("SELECT * FROM test")
        cur.fetchone()
        # will return (1, 100, "abc'def")

        # You can use `cur.fetchmany()`, `cur.fetchall()` to return a list
        # of several records, or even iterate on the cursor
        for record in cur:
            print(record)

updated version:

        # Query the database and obtain data as Python objects.
        cur.execute("SELECT * FROM test")

        # You can use `cur.fetchmany()`, `cur.fetchall()` to return a list
        # of several records
        **for record in cur.fetchone():**
            print(record)

**Comment by dvarrazzo** [comment]
No, `for record in cur.fetchone()` would iterate field by field on the first record. In that example we want to iterate record by record.
