### ISSUE TITLE
New typing error after latest minor release v3.1

### ISSUE THREAD

**Issue by haf** [psycopg/psycopg#365]
<img width="668" alt="bild" src="https://user-images.githubusercontent.com/193115/187957813-d920b9b4-5004-4964-ab84-84459b6ff681.png">

not an error with v3.0.x

**Comment by dvarrazzo** [comment]
This code doesn't have problems with mypy. Testing with the script:

```python
# test-365.py

import psycopg
from psycopg.rows import class_row

class MyObject:
    pass

async def f() -> None:
    async with await psycopg.AsyncConnection.connect() as conn:
        async with conn.cursor(row_factory=class_row(MyObject)) as cur:
            await cur.execute("")
            rec = await cur.fetchone()
            reveal_type(rec)
```

mypy reports:

```
$ mypy test-365.py 
test-365.py:14: note: Revealed type is "Union[test-365.MyObject, None]"
Success: no issues found in 1 source file
```

which is what expected.

Maybe you want to report the issue to Pylance.

**Comment by fsvenson** [comment]
@dvarrazzo I opened the issue with pyright and they claim the issue is with psycopg and that mypy has a fallback which is not in accordance with PEP, see the linked issue.

**Comment by dvarrazzo** [comment]
I am checking if `bound=Cursor[Any]` presents regressions w.r.t. `bound=Cursor[Row]`. If it doesn't I will ask you to test

**Comment by dvarrazzo** [comment]
Fixed as suggested by @erictraut, thank you very much.
