### ISSUE TITLE
psycopg.OperationalError: [Errno -8] Unrecognized service when port is omitted in connection string.

### ISSUE THREAD

**Issue by var211** [psycopg/psycopg#366]
Hello, i'm not entirely sure about this behaviour, but I was getting this error when I used connection string without `port` parameter specified with `psycopg.AsyncConnection.connect`.  I tried to investigate this error and it looks like a little bug in `resolve_hostaddr_async` function located in `conninfo.py` file.

Here, on line 305:

``` python
hosts_in = host_arg.split(",")
port_arg: str = str(params.get("port", os.environ.get("PGPORT", "")))
ports_in = port_arg.split(",")
default_port = "5432"

if len(ports_in) == 1:
    # If only one port is specified, the libpq will apply it to all
    # the hosts, so don't mangle it.
    default_port = ports_in.pop()
```

If port is ommited `ports_in` will be `['']` and `default_port` will be overwrittedn with empy string.

As a quick fix I can suggest replace
``` python
ports_in = port_arg.split(",")
```
with
``` python
ports_in = port_arg.split(",") if port_arg else []
```
But I don't spend enough time on this situation so could be wrong, and everything works fine when port is explicitly specified.

**Comment by dvarrazzo** [comment]
Hello, thank you for the report!

Your analysis seems correct. I'll check why the problem wasn't caught by the test suite and push a fix.

**Comment by dvarrazzo** [comment]
...I'm not sure I see the problem, looking at the code. Even if ports_in contains an empty string, which overrides default_port, on output the port is omitted 

https://github.com/psycopg/psycopg/blob/27340c549ae7f47af0639ea2893298ac6afa9347/psycopg/psycopg/conninfo.py#L365-L366

So, probably I'm not understanding how your DNS is mangled by this function. Can you tell me what is the value of `params` before and after its call on connection?

https://github.com/psycopg/psycopg/blob/27340c549ae7f47af0639ea2893298ac6afa9347/psycopg/psycopg/connection_async.py#L192-L193

Or is the problem that an empty string in `getaddrinfo()` makes it fail? It doesn't fail for me (on linux). What is your os?

https://github.com/psycopg/psycopg/blob/27340c549ae7f47af0639ea2893298ac6afa9347/psycopg/psycopg/conninfo.py#L345-L348

Thank you very much

**Comment by var211** [comment]
> Or is the problem that an empty string in `getaddrinfo()` makes it fail? It doesn't fail for me (on linux). What is your os?
> 
> https://github.com/psycopg/psycopg/blob/27340c549ae7f47af0639ea2893298ac6afa9347/psycopg/psycopg/conninfo.py#L345-L348
> 
Yea, this case. Empty string in  `getaddrinfo()`. I forgot to mention that it was isnside `docker` container, I have two containers on one `docker` bridge, one with `postgres:latest` and `--network-alias pg14` and `quart` app using `psycopg3` inside container created from `python:3.10.6-alpine`. So it is Alpine linux, or it may be related to `docker` DNS, and it is throwing error when no port specified in `getaddrinfo()`.

**Comment by var211** [comment]
I tried to test some more, and was able to reproduce this error only with Alpine Linux inside docker container. Under my host Arch linux os it works without errors. Not sure it will help for the test suite.

`Dockerfile`:
``` dockerfile
FROM python:3.10.6-alpine

WORKDIR /app

COPY test.py .

ENTRYPOINT [ "python" ]
CMD [ "test.py" ]
```

`test.py`:
``` python
import asyncio
import socket


async def main():
    loop = asyncio.get_running_loop()
    host = 'localhost'
    # port = '5432'
    port = ''
    result = await loop.getaddrinfo(
          host, port, proto=socket.IPPROTO_TCP, type=socket.SOCK_STREAM)
    print(result)


loop = asyncio.get_event_loop()
task = loop.create_task(main())
loop.run_until_complete(task)
pending = asyncio.all_tasks(loop=loop)

for task in pending:
    task.cancel()

group = asyncio.gather(*pending, return_exceptions=True)
loop.run_until_complete(group)

loop.close()
```

Output:
``` shell
docker build -t 'local/test' .
docker run --rm local/test:latest

/app/test.py:16: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "/app/test.py", line 18, in <module>
    loop.run_until_complete(task)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/app/test.py", line 10, in main
    result = await loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -8] Unrecognized service
```

**Comment by dvarrazzo** [comment]
Ok thank you. Does #367 fix the problem for you?

**Comment by var211** [comment]
> Ok thank you. Does #367 fix the problem for you?

Yes
