### ISSUE TITLE
Invalid access violation on Loader init exception

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#372]
An error such as the one reported in #371 fails to bubble up, causing a segfault.

See [this job](https://github.com/psycopg/psycopg/actions/runs/3052457970/jobs/4921870491), for instance.

**Comment by CaselIT** [comment]
Oh, I just remembered that windows will log in the event log this type of errors. I'll look if there are additional information in it later when I'm on the other pc

**Comment by CaselIT** [comment]
The error logged in the even logger does not really telly anything of use. In any case it's below:
```
Faulting application name: python.exe, version: 3.10.4150.1013, time stamp: 0x62445d6c
Faulting module name: _psycopg.cp310-win_amd64.pyd, version: 0.0.0.0, time stamp: 0x6315f325
Exception code: 0xc0000005
Fault offset: 0x0000000000010536
Faulting process id: 0x1f5c8
Faulting application start time: 0x01d8c7b40cf3fbdb
Faulting application path: C:\Users\me\miniconda3\envs\temp\python.exe
Faulting module path: C:\Users\me\miniconda3\envs\temp\lib\site-packages\psycopg_binary\_psycopg.cp310-win_amd64.pyd
Report Id: a65434ff-8788-4be4-b84c-7f8439111ac9
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by dvarrazzo** [comment]
The bit telling is, in the failing test:

```
OSError: [Errno 22] Invalid argument: 'C:\\Users\\me\\miniconda3\\envs\\sa\\lib\\site-packages\\tzdata\\zoneinfo\\<+00>-00'
Exception ignored in: 'psycopg_binary._psycopg.Transformer.set_pgresult'
```

`Transformer.set_pgresult` is defined `cpdef void`, so it doesn't have a chance to raise an exception.

**Comment by CaselIT** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> `Transformer.set_pgresult` is defined `cpdef void`, so it doesn't have a chance to raise an exception.

Interesting, I'm not too familiar with cython yet. Great work fixing both!
