### ISSUE TITLE
mogrify broken when named parameters are used more than once

### ISSUE THREAD

**Issue by WoLpH** [psycopg/psycopg#378]
The issue is with the `dump` function that automatically converts all parameters into tuples but doesn't take into consideration that some parameters might be used more than once.
https://github.com/psycopg/psycopg/blob/8a44473e3f75c1bfdd26052b68b1ead49b2e4ebe/psycopg/psycopg/_queries.py#L131-L144

The traceback:
```
Traceback (most recent call last):
  File "psycopg/client_cursor.py", line 40, in mogrify
    pgq = self._convert_query(query, params)
  File "psycopg/client_cursor.py", line 79, in _convert_query
    pgq.convert(query, params)
  File "psycopg/_queries.py", line 129, in convert
    self.dump(vars)
  File "psycopg/_queries.py", line 142, in dump
    self.query = self.template % self.params
TypeError: not enough arguments for format string
```

To reproduce:
```
query = '''
SELECT *
FROM some_table
WHERE some_column = %(some_value)s
AND some_other_column = %(some_value)s
'''
params = dict(some_value=1)

with psycopg.connect() as connection:
    cursor = psycopg.ClientCursor(connection)
    cursor.mogrify(query, params)
```

**Comment by WoLpH** [comment]
As a "fix" it works to replace this line:
https://github.com/psycopg/psycopg/blob/8a44473e3f75c1bfdd26052b68b1ead49b2e4ebe/psycopg/psycopg/_queries.py#L273

With this: `return [vars[item] for item in order or ()]`

However... since the `dump` method overrides `self.params`, this breaks the execution of the query

**Comment by dvarrazzo** [comment]
Querying is broken too, not only mogrify. A fix is on the way.
