### ISSUE TITLE
Transaction terminates after its connection instance is GCed

### ISSUE THREAD

**Issue by roymiloh** [psycopg/psycopg#379]
Hi, I'm just playing around, it's not a real use-case but I'd like to understand why the following behavior happens. First of all, I use a connection pool (via `psycopg_pool`) and the async flavor.

I tried to lock a row with `SELECT ... FOR UPDATE` statement with one connection from the pool, keep its transaction open, and have another transaction that updates this row and waits for the first transaction to complete before it updates.

So I did something like the following and it passed:

```py
pool = AsyncConnection("")

async def select_lock():
  conn_to_lock = pool._pool.getconn()
  cursor = await conn_to_lock.cursor().execute("SELECT ... FOR UPDATE")
  await cursor.fetchone()

async def main_run():
  await select_lock() # This should lock the row until forever

  async with pool.connection() as conn:
    await conn.execute("UPDATE same_table SET ...") # This one passes, although it shouldn't - it should wait
```

Also, when I queried `pg_stat_activity` I didn't see the transaction anymore.

However, when I do keep a reference to `conn_to_lock`, for instance something like the following:

```py
async def select_lock():
  conn_to_lock = pool._pool.getconn()
  ...
  return conn_to_lock

async def main_run():
  conn_to_lock = await select_lock() # Keeping a ref to the connection
  ...
```

**It does wait** and I see the transaction in postgres.

Any idea why? I've tried to investigate it a bit but didn't find any interesting behaviour around the connection's [`__del__`](https://github.com/psycopg/psycopg/blob/e507918489aad84df730b54b7da53b45b4550ba3/psycopg/psycopg/connection.py#L142). I also haven't observed any rollback around this transaction in general, which is odd.

**Comment by dvarrazzo** [comment]
When a psycopg connection is deleted, the server connection is terminated, yes. There is no rollback, but Postgres will behave as if there was one.

The behaviour you see is expected, as far as I can see. If you want to hold a lock you need to keep that connection alive.

**Comment by dvarrazzo** [comment]
More precisely, GC'ing the connection will GC its pgconn too, which will result in `PQfinish()` called.

https://github.com/psycopg/psycopg/blob/e507918489aad84df730b54b7da53b45b4550ba3/psycopg/psycopg/pq/pq_ctypes.py#L91-L95
