### ISSUE TITLE
Proper way to install psycopg3 binary?

### ISSUE THREAD

**Issue by pandrews-hdai** [psycopg/psycopg#384]
I'm not having much luck with google because the search results are absolutely dominated with psycopg2-specific results and manual installation steps instead of the automated process I need to use this.

I have a legacy python application that runs in an AWS Lambda packaged and deployed by Serverless, I need to install and use psycopg or some other postgres driver in this lambda but following the official documentation https://www.psycopg.org/psycopg3/docs/basic/install.html for the binary installation still leaves me unable to `import psycopg` even in my local venv to say nothing of the lambda package.

I dislike Serverless and am aware it's adding layers of complexity to the problem but since I can't use psycopg in a local venv I'm confident there's some other issue with the method of installation via pip requirements and if I can get the venv to import psycopg the lambda package will fall in line.

1. I've installed psycopg[binary] via `pip install psycopg[binary]`.
2. This was reported by `pip freeze` as `psycopg-binary==3.1.1` so I added that to my requirements.txt and requirements-serverless.txt
3. In both the package Serverless builds and my local venv I can't `import psycopg` as directed by the installation instructions because it throws a ModuleNotFoundError.
4. In a python shell in my local venv I can see there is a `psycopg_binary` module, but I also can't import that because it says: `ImportError: the psycopg package should be imported before psycopg_binary` which has 0 results on Google and the documentation gives no indication that using the binary package should be any different or require extra steps.  Does it?  What's the point of the binary installation if I also need to build the source installation?

So since the documentation is failing me, how can I actually install psycopg in a venv and import it?
Python 3.7.14
pip 22.2.2
virtualenv 20.13.2

**Comment by dvarrazzo** [comment]
Can you give a description of how you solved your problems? It would be helpful maybe, to start creating some psycopg 3 hits on google :smile: 

When you install `psycopg[binary]` you install the `psycopg` and `psycopg-binary` distribution packages (in exactly the same version, which are the only ones guaranteed to be compatible). `psycopg-binary` installs the `psycopg_binary` module and the depending libraries (libpq, libssl, kerberos, etc). This module is not supposed to be imported on its own (hence the error message), but it is detected and imported automatically by `psycopg` (by `psycopg.pq`, more precisely). You can verify that it was imported looking at `psycopg.pq.__impl__`, which should be `'binary'`. No extra step is to be taken at code level: `psycopg-binary` is just a performance speedup and distribution convenience (as it doesn't require external dependencies).

Hope this helps. If you have any pointers for other people trying to use psycopg on serverless (which I have never done) it would be great to receive. Thank you!

**Comment by pandrews-hdai** [comment]
@dvarrazzo unfortunately a lot of it was mild idiocy and a slight issue that presents if you don't follow proper order of operations.

My problem was that I didn't realize what magic pip was doing under the hood with the extra dependency [binary] and assumed psycopg-binary was self-contained.  But like you said there's extra setup information in `psycopg` so that it also installs `psycopg-binary` when you run the command that way, so in a requirements.txt file for pip a proper installation needs both packages named.

I had installed the source package first before running into some issue (I don't completely recall) building it in the custom container serverless builds its deployment packages inside.  So seeing that the instructions also include a binary distribution I "switched" to that not realizing a proper installation included both packages.

**Comment by dvarrazzo** [comment]
I can see the confusion, given the fact that psycopg2-binary is a self-contained package. That makes it difficult to pin only one of the two in a requirements file (transitive dependencies may refer to the other instead), so we moved to having a common base package to which to refer to, and speedup modules that don't change the package interface.

**Comment by ruslaniv** [comment]
Can we reopen this with proper installation instructions? 
I'm having **EXACTLY** the same problem with poetry

Here is what I have in pyproject.toml
```
[tool.poetry.dependencies]
psycopg-binary = "~3.1.9" # https://www.psycopg.org/psycopg3/
```

Running poetry install: 
<img width="283" alt="image" src="https://github.com/psycopg/psycopg/assets/7631314/ba8a6dcc-999c-43fa-a2e1-fb018f921014">

Trying to import psycopg
<img width="573" alt="image" src="https://github.com/psycopg/psycopg/assets/7631314/c0771c49-ef92-4dc5-8c80-2f3cd666e1f2">

**Comment by dvarrazzo** [comment]
>  I'm having EXACTLY the same problem with poetry

Then you have EXACTLY the same solution.

As documented *everywhere*, you need to install `psycopg[binary]` This means the `psycopg` package together with an *extra*.

In no place you have been instructed to install `psycopg-binary`, which is a package, it doesn't mean the same of  `psycopg[binary]`. More specifically, it is an internal package and an implementation detail: now it exists, tomorrow who knows.

`psycopg-binary` also doesn't pull in the `psycopg` package, no. `psycopg[binary]` installs the two of them.

> So I thought that only specifying the binary should suffice?

The documentation about installing the binary package [is here](https://www.psycopg.org/psycopg3/docs/basic/install.html#binary-installation), and this is the only supported way.

**Comment by ruslaniv** [comment]
Yeah I guess I should have been more specific - I wanted to ONLY install psycopg via requirements file and in my case using poetry and `pyproject.toml`. 
As it turned out, for whatever reason I had to specify the requirements in this weird format:
```
psycopg = {extras = ["binary"], version = "^3.1.9"}
```
while I was trying various permutations of this:
```
"psycopg[binary]" = "^3.1.9" # NB: this will NOT work in poetry
```
