### ISSUE TITLE
namedtuple_row changes non ascii column identifiers unnecessarily

### ISSUE THREAD

**Issue by Jolbas** [psycopg/psycopg#386]
I have used none ascii characters in database column identifiers and namedtuple_row did handle those perfect until a recent change. If for example a database column has the name "först", then a cursor with a namedtuple_row factory returns a namedtuple `Row(f_rst=0)` instead of `Row(först=0)` even though "först" is a valid python identifier. 
I believe this behaviour started when _re_clean changed from ```re.compile("[" + re.escape(" !\"#$%&'()*+,-./:;<=>?@[\\]^`{|}~") + "]")``` to ```re.compile(f"[^{string.ascii_lowercase}{string.ascii_uppercase}{string.digits}_]")``` in [this commit](/psycopg/psycopg/commit/d0dd0c74b6a3286594594871682614ddc0f3cbe0)

If accepted as an issue, see comment in the commit for suggestion of a possible fix

**Comment by dvarrazzo** [comment]
I see, it seems a regression. Are you saying that in psycopg 3.0.x `Row(först=0)` was accepted? Or in psycopg2?

**Comment by Jolbas** [comment]
Yes, it did work in both psycopg 3.0 and psycopg2

**Comment by dvarrazzo** [comment]
Ok, let's fix it! Can you propose a MR, with a test in the test suite?

**Comment by dvarrazzo** [comment]
I don't have the code handy, I'm not at home, but I assume the refactoring you pointed at happened because that function is used somewhere else too (composite? Enums?) It might be that non-ascii chars are accepted somewhere (such as namedtuples) and not somewhere else, and that we might need to use different functions.

**Comment by Jolbas** [comment]
I'll try to make a PR and I check if _as_python_identifier() is used elsewhere.

**Comment by Jolbas** [comment]
I did a [PR](/psycopg/psycopg/pull/388) but there were an error in the Lint check that I didn't understood. Could you please take a look.

**Comment by Jolbas** [comment]
_as_python_identifier() is also used in register_composite() in composite.py when constructing a namedtuple factory. I can't say if the change is going to have side effects but it seems to be there just for the sake of the namedtuple itself.

**Comment by dvarrazzo** [comment]
> I did a [PR](/psycopg/psycopg/pull/388) but there were an error in the Lint check that I didn't understood. Could you please take a look.

You can install black and flake8 and run them on the files before commit and push

**Comment by dvarrazzo** [comment]
> _as_python_identifier() is also used in register_composite() in composite.py when constructing a namedtuple factory. I can't say if the change is going to have side effects but it seems to be there just for the sake of the namedtuple itself.

I think that there used to be some code duplication and that function refactored common code in the same function.

Are there tests checking the behaviour of invalid or non-ascii fields names in composites?
