### ISSUE TITLE
TypeError: cannot create weak reference to 'weakref' object for pypy 3.8 and psycopg 3.1

### ISSUE THREAD

**Issue by fizyk** [psycopg/psycopg#391]
I've run on an issue on pypy I missed when it first appeared on my github actions.

I'm maintaining pytest-postgresql package for pytest, and the pypy runs begun to fail with 
`TypeError: cannot create weak reference to 'weakref' object` error:

https://github.com/ClearcodeHQ/pytest-postgresql/actions/runs/2968409786/jobs/4752401229

Truth be told, I haven't changed anything apart from the psycopg2 version being bumped by dependabot.

**Comment by dvarrazzo** [comment]
Pypy is not yet supported yet by psycopg 3 (it might work, but it's not tested, #62 sort of died there).

The error message shows that you don't have the libpq library on your system and you don't have a self-contained binary package.

I don't see the weakref error you refer to, I don't think it's related to psycopg.

Please follow the [install instructions](https://www.psycopg.org/psycopg3/docs/basic/install.html). If you have problems with Pypy, maybe we can help, but pypy is not officially supported yet.

**Comment by fizyk** [comment]
@dvarrazzo yes.... sorry, I've been running some tests to get back to 3.0.x requirements for tests, but seems that something also changed for brew I'll have to dig out somehow (or ditch macos builds on pypy for the time being). And I've polluted an actions runs before making the report.

The test url for the weakref would be here. If that's something strictly related to pypy, then I'll probably mark the test runs then.... 🤔 
https://github.com/ClearcodeHQ/pytest-postgresql/actions/runs/2968409787/jobs/4752401879#step:8:241

**Comment by om26er** [comment]
I was able to get psycopg 3.1.7 working on PyPy with a small "hack" -- it seems there is behavioral discrepancy in PyPy regarding the `ctypes` module. Here is the minimal reproducible program that causes the issue on PyPy but works fine on CPython.

```
from ctypes import py_object
from weakref import ref

class Empty():
    pass

e = Empty()
r = ref(e)
pr = py_object(r)
```

**Comment by om26er** [comment]
The hack is to comment out this line https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/lib_pypy/_ctypes/primitive.py#L54 -- of course not to be used in production. I will raise the issue with PyPy and see what response I get from them
