### ISSUE TITLE
psycopg[binary] import works on a script run but does not on jupyter although using the same python location

### ISSUE THREAD

**Issue by alfa-th** [psycopg/psycopg#394]
1. I used `pip install "psycopg[binary]"` version of psycopg
2. I installed it on a .venv
3. I run a python script using .venv where psycopg is installed where the script involves an import of psycopg and it works fine
4. I run a jupyter code block involving an import of psycopg using the same .venv as the kernel
5. What came out from the run was a `ImportError: no pq wrapper available.` error

The reason i wanted to use psycopg on jupyter was because of a data science work. Is this a jupyter issue or a psycopg issue? (Im using vscode-jupyter)

**Comment by dvarrazzo** [comment]
Probably a configuration issue from Jupiter? Can you print `sys.path` and `sys.executable` from your script in 3 and from your environment in 4?

**Comment by dvarrazzo** [comment]
I don't see `c:\\Users\\<username>\\Work\\<project_name>\\scripts` in the jupiter env. Where is psycopg installed (you can `import psycopg; print(psycopg)`

**Comment by alfa-th** [comment]
`<module 'psycopg' from 'C:\\Users\\<username>\\Work\\<project_name>\\.venv\\lib\\site-packages\\psycopg\\__init__.py'>`

**Comment by alfa-th** [comment]
Regarding 
>I don't see `c:\\Users\\<username>\\Work\\<project_name>\\scripts` in the jupiter env

For some context, the folder where i store my python scripts is `<project_name>\\scripts` while the folder where i store my jupyter files is `<project_name>\\jupyter`.

Nevertheless, i moved the corresponding jupyter file to `c:\\Users\\<username>\\Work\\<project_name>\\scripts` and it still doesnt want to import

**Comment by alfa-th** [comment]
Some new info, i tried this on a new test project with python 3.10.4 installed and it worked just fine

**Comment by dvarrazzo** [comment]
Maybe the import error message is more interesting, like what is importing `psycopg_binary` failing.

**Comment by alfa-th** [comment]
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_8392\2838210510.py in <module>
      1 import polars as pl
----> 2 from <project_name>.loader import query_as_dataframe
      3 import psycopg

c:\users\<user_name>\work\<project_name>-test\news_analyzer\loader.py in <module>
      1 from datetime import datetime
----> 2 import psycopg
      3 from loguru import logger
      4 import polars as pl
      5 

c:\Users\<user_name>\Work\<project_name>-test\.venv\lib\site-packages\psycopg\__init__.py in <module>
      7 import logging
      8 
----> 9 from . import pq  # noqa: F401 import early to stabilize side effects
     10 from . import types
     11 from . import postgres

c:\Users\<user_name>\Work\<project_name>-test\.venv\lib\site-packages\psycopg\pq\__init__.py in <module>
    112 
    113 
--> 114 import_from_libpq()
    115 
    116 __all__ = (

c:\Users\<user_name>\Work\<project_name>-test\.venv\lib\site-packages\psycopg\pq\__init__.py in import_from_libpq()
    108 no pq wrapper available.
    109 Attempts made:
--> 110 {sattempts}"""
    111         )
    112 

ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: DLL load failed: The specified module could not be found.
- couldn't import psycopg 'python' implementation: libpq library not found
```
I was able to reproduce this by just deleting my previous .venv (which is working properly and is running python 3.10) and replacing it with a new .venv that runs on python 3.7.13

**Comment by dvarrazzo** [comment]
This is the error affecting psycopg-binary:

- couldn't import psycopg 'binary' implementation: DLL load failed: The specified module could not be found.

This is probably referred to the bundled libraries, which are available in the wheel you installed:

```
 unzip -l ~/Downloads/psycopg_binary-3.1.2-cp310-cp310-win_amd64.whl 
Archive:  /home/piro/Downloads/psycopg_binary-3.1.2-cp310-cp310-win_amd64.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
   226304  2022-09-19 11:34   psycopg_binary/pq.cp310-win_amd64.pyd
        0  2022-09-19 11:34   psycopg_binary/py.typed
      257  2022-09-19 11:34   psycopg_binary/version.py
   875008  2022-09-19 11:34   psycopg_binary/_psycopg.cp310-win_amd64.pyd
     3009  2022-09-19 11:34   psycopg_binary/_psycopg.pyi
     1164  2022-09-19 11:34   psycopg_binary/__init__.py
      442  2022-09-19 11:34   psycopg_binary-3.1.2.dist-info/DELVEWHEEL
     7817  2022-09-19 11:34   psycopg_binary-3.1.2.dist-info/LICENSE.txt
     2301  2022-09-19 11:34   psycopg_binary-3.1.2.dist-info/METADATA
     1874  2022-09-19 11:34   psycopg_binary-3.1.2.dist-info/RECORD
       15  2022-09-19 11:34   psycopg_binary-3.1.2.dist-info/top_level.txt
      102  2022-09-19 11:34   psycopg_binary-3.1.2.dist-info/WHEEL
      238  2022-09-19 11:34   psycopg_binary.libs/.load-order-psycopg_binary-3.1.2
  2853376  2022-08-09 06:05   psycopg_binary.libs/libcrypto-1_1-x64-5bf5523794e95ad92aef7862fbf04c69.dll
  1850401  2022-08-09 06:05   psycopg_binary.libs/libiconv-2.dll
   475769  2022-08-09 06:05   psycopg_binary.libs/libintl-9-1125ac8dc0c4f5c3ed4712e0d8ad2947.dll
   305152  2022-09-19 11:34   psycopg_binary.libs/libpq-ab4dd38be8e2eb9dab414f8627a83a41.dll
   686592  2022-09-19 11:34   psycopg_binary.libs/libssl-1_1-x64-8788cf7684a80173c6fe38d675b7ccda.dll
    52736  2022-08-09 06:05   psycopg_binary.libs/libwinpthread-1.dll
---------                     -------
  7342557                     19 files
```

In my installation, the .libs directory is installed alongside psycopg_binary:

```
(.venv) piro@baloo:~/dev/AiFi/shared-staging$ ls -ld /home/piro/dev/AiFi/.venv/lib/python3.8/site-packages/psycopg_binary*
drwxrwxr-x 3 piro piro 4096 Jul 28 02:42 /home/piro/dev/AiFi/.venv/lib/python3.8/site-packages/psycopg_binary
drwxrwxr-x 2 piro piro 4096 Jul 28 02:42 /home/piro/dev/AiFi/.venv/lib/python3.8/site-packages/psycopg_binary-3.0.12.dist-info
drwxrwxr-x 2 piro piro 4096 Jul 28 02:42 /home/piro/dev/AiFi/.venv/lib/python3.8/site-packages/psycopg_binary.libs
```

This is what I have on my machine, which is a Linux. I don't have a windows to test. Are these paths consistent with what you have on your machine? Maybe you and jupiter run as different users and Windows has some permission rule to make this import work?

**Comment by alfa-th** [comment]
Output of `ls -ld .venv/Lib/site-packages/psycopg_binary*` on a venv that runs on python 3.7 (that has the import error on jupyter) : 
```
<user>@DESKTOP-<user> MINGW64 ~/Work/news-analyzer (main)     
$ ls -ld .venv/Lib/site-packages/psycopg_binary*
drwxr-xr-x 1 <user> 197121 0 Sep 29 18:30 .venv/Lib/site-packages/psycopg_binary/
drwxr-xr-x 1 <user> 197121 0 Sep 29 18:30 .venv/Lib/site-packages/psycopg_binary.libs/  
drwxr-xr-x 1 <user> 197121 0 Sep 29 18:30 .venv/Lib/site-packages/psycopg_binary-3.1.2.dist-info/
(.venv)
```
Output of  `ls -ld .venv/Lib/site-packages/psycopg_binary*` on a venv that runs on python 3.10 (that has no import error (working perfectly)) :
```
<user>@DESKTOP-<user> MINGW64 ~/Work/news-analyzer (main)     
$ ls -ld .venv/Lib/site-packages/psycopg_binary*
drwxr-xr-x 1 <user> 197121 0 Sep 29 17:31 .venv/Lib/site-packages/psycopg_binary/
drwxr-xr-x 1 <user> 197121 0 Sep 29 17:31 .venv/Lib/site-packages/psycopg_binary.libs/  
drwxr-xr-x 1 <user> 197121 0 Sep 29 17:31 .venv/Lib/site-packages/psycopg_binary-3.1.2.dist-info/
(.venv)
```

I also checked the psycopg's .whl files on 3.10 and 3.7 and it has the exact same file structure (there is only 1 file for windows for each python version so it was easy)

Regarding
>Maybe you and jupiter run as different users and Windows has some permission rule to make this import work?

Idk about this, there is only 1 user on my laptop, but if there is permission rule, then why did the python 3.10 version worked? and when i replaced my python 3.10 to python 3.7 (I deleted and recreated a venv) how can the error reproduced? I think this has more to do with python version

**Comment by dvarrazzo** [comment]
Closing this because I don't see any bug here

**Comment by quchunguang** [comment]
i got same issue on python 3.12, when codes works fine on 3.10.

```
(312) PS C:\> python .\test_conn.py
Traceback (most recent call last):
  File "C:\syaz.net\01_客户\000_test\testpy\test_conn.py", line 86, in <module>
    import psycopg
  File "C:\miniconda3\envs\312\Lib\site-packages\psycopg\__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
    ^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\312\Lib\site-packages\psycopg\pq\__init__.py", line 114, in <module>
    import_from_libpq()
  File "C:\miniconda3\envs\312\Lib\site-packages\psycopg\pq\__init__.py", line 106, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
```

It sseems in the latest psycopg[binary], missing libpq.dll:

```
libssl-3-x64.dll
libcrypto-3-x64.dll
libintl-9.dll
libiconv-2.dll
libwinpthread-1.dll
```

**Comment by DSLituiev** [comment]
@quchunguang  which conda channel do you use for `conda install psycopg`?

**Comment by iriswolf** [comment]
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'

Python3.12

**Comment by iriswolf** [comment]
after installing psycopg-c

couldn't import psycopg 'c' implementation: DLL load failed while importing pq: Не найден указанный модуль.

**Comment by dss010101** [comment]
> couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
> 
> Python3.12

Seeing this as well.  Still seems to run though

**Comment by gustavo-rosendo** [comment]
> > couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
> > Python3.12
> 
> Seeing this as well. Still seems to run though. What would this impact?

Any updates on this. 
I am seeing the same error, but it seems to run fine.
Is there any impact of having this error printout?

**Comment by AhlamHani** [comment]
I am seeing this error as well:

```
]2024-10-06 20:25:12,854 - psycopg.pq - DEBUG - couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
```

**Comment by liuyangc3** [comment]
same error
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'mymodule': no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
Traceback (most recent call last):
```
