### ISSUE TITLE
Typo in docs/install.rst

### ISSUE THREAD

**Issue by CHDarrenHo** [psycopg/psycopg#397]
Hi,

Just a tiny one... Under https://www.psycopg.org/psycopg3/docs/basic/install.html#handling-dependencies there's a typo: "If your project if a finished project..."

Happy to create an MR to fix...

**Comment by dvarrazzo** [comment]
Yes please, thank you :)

**Comment by CHDarrenHo** [comment]
Sorry...How do I raise an MR? I've created a branch off of master, but get a 403 when I push the branch up?

**Comment by dvarrazzo** [comment]
You need to clone psycopg in a repository of yours, by clicking "fork", top-right corner of the psycopg project github page. You can create a branch and push it in your fork, then you can create a MR from there.

If it's too much of a faff and you prefer that we fix this thing ourselves let us know, no problem. If you want to try to play with github, go ahead, we'll wait for you :)

**Comment by CHDarrenHo** [comment]
Ahhhhh okay, thank you! Sorry, I've not done this before, will get this done 😁

**Comment by dvarrazzo** [comment]
Thank you very much for your first contribution!

**Comment by CHDarrenHo** [comment]
No worries, thank you!
