### ISSUE TITLE
ClientCursor: TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by ochedru** [psycopg/psycopg#399]
I am currently in the process of converting a large code base from psycopg2 to psycopg3.
Please consider the following code snippet, tested with psycopg 3.1.2:
```python
from psycopg import connect, ClientCursor

with connect('host=locahost user=postgres password=postgres', cursor_factory=ClientCursor) as con:
    with con.cursor() as cur:
        cur.execute("SELECT format('%%s', %(param)s)", {'param': 'test'})
        print(cur.fetchone()[0])
```

With psycopg2, the result is `test` but psycopg3 raises the following error:
`TypeError: not enough arguments for format string`

Is this a bug or did I overlook a new way to escape percent signs? Thanks!

**Comment by dvarrazzo** [comment]
I think it's a bug, yes. Thank you for reporting it!

**Comment by dvarrazzo** [comment]
I should have fixed the problem, and will likely release a fix tomorrow. Would you like to check if the changeset above fixes all the problems you have found?

Thank you very much!

**Comment by ochedru** [comment]
Hi Daniele, thank you for the quick fix! I tested with the patch and I confirm this solves the problem.
