### ISSUE TITLE
Overhead in the use of epoll

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#414]
I did some profiling after the report in #411 of degraded performance in psycopg 3 vs. 2.

Some profiling shows that epoll has a non-trivial amount of overhead when used from Python.

![image](https://user-images.githubusercontent.com/199429/195410390-be2c70c0-c3b8-473e-b4b5-f65ab6d00dc1.png)

I tried a quick test implementing a wait function based on select, and the overhead is much smaller.

![image](https://user-images.githubusercontent.com/199429/195410822-75e1f0f1-0b1a-4f09-8b98-c7edc8217371.png)

To compare numbers, 10,000 simple queries in a loop are executed in 1.21 seconds with epoll, 0.96 seconds with select.

This is on a Linux platform, where `selectors.DefaultSelector` is `EpollSelector`, so, meh, disappointed.

Will try more tests and look better into the choice of the wait implementation.

<details>
<summary>Benchmark program</summary>

This version of the program (with the commented-out blocks) is what used to generate the flame graph, using:

```
py-spy record --rate 500 --native --  python ./bench.py psycopg2
py-spy record --rate 500 --native --  python ./bench.py psycopg
```

You should probably uncomment those blocks in order to create the test table in the first run. Courtesy of @zzzek and @CaselIT 

```python
import asyncio
from contextlib import contextmanager
import sys
import random
import time


table = """
CREATE TABLE customer (
        id SERIAL NOT NULL,
        name VARCHAR(255),
        description VARCHAR(255),
        q INTEGER,
        p INTEGER,
        x INTEGER,
        y INTEGER,
        z INTEGER,
        PRIMARY KEY (id)
)
"""
drop = "DROP TABLE IF EXISTS customer"

ids = list(range(10_000))
tests = 10000

data = [
    dict(
        id=i,
        name="c%d" % i,
        description="c%d" % i,
        q=i * 10,
        p=i * 20,
        x=i * 30,
        y=i * 40,
    )
    for i in ids
]

insert = """
INSERT INTO customer (id, name, description, q, p, x, y) VALUES
(%(id)s, %(name)s, %(description)s, %(q)s, %(p)s, %(x)s, %(y)s)
"""

select = """
SELECT customer.id, customer.name, customer.description, customer.q,
    customer.p, customer.x, customer.y, customer.z
FROM customer
WHERE customer.id = %(id)s
"""

# url = "host=localhost"
url = "host=/var/run/postgresql/"


@contextmanager
def time_log(message):
    start = time.monotonic()
    yield
    end = time.monotonic()
    print(f"Run {message} in {end-start} s")


def run_psycopg2(psycopg2):
    print("Running psycopg2")

    # with psycopg2.connect(url) as conn:
    #     with conn.cursor() as cursor:
    #         cursor.execute(drop)
    #         cursor.execute(table)
    #         cursor.executemany(insert, data)
    #     conn.commit()
    print(f"Insert done. Running {tests} queries")
    to_query = random.choices(ids, k=tests)
    with psycopg2.connect(url) as conn:
        with time_log("psycopg2"):
            for id_ in to_query:
                with conn.cursor() as cursor:
                    cursor.execute(select, {"id": id_})
                    cursor.fetchall()
                # conn.rollback()

    # with psycopg2.connect(url) as conn:
    #     with conn.cursor() as cursor:
    #         cursor.execute(drop)
    #     conn.commit()


def run_psycopg(psycopg):
    print("Running psycopg sync")

    # with psycopg.connect(url) as conn:
    #     with conn.cursor() as cursor:
    #         cursor.execute(drop)
    #         cursor.execute(table)
    #         cursor.executemany(insert, data)
    #     conn.commit()
    print(f"Insert done. Running {tests} queries")
    to_query = random.choices(ids, k=tests)
    with psycopg.connect(url) as conn:
        with time_log("psycopg"):
            for id_ in to_query:
                with conn.cursor() as cursor:
                    cursor.execute(select, {"id": id_})
                    cursor.fetchall()
                # conn.rollback()

    # with psycopg.connect(url) as conn:
    #     with conn.cursor() as cursor:
    #         cursor.execute(drop)
    #     conn.commit()


async def run_psycopg_async(psycopg):
    print("Running psycopg async")

    conn: psycopg.AsyncConnection
    async with await psycopg.AsyncConnection.connect(url) as conn:
        async with conn.cursor() as cursor:
            await cursor.execute(drop)
            await cursor.execute(table)
            await cursor.executemany(insert, data)
        await conn.commit()
    print(f"Insert done. Running {tests} queries")
    to_query = random.choices(ids, k=tests)
    async with await psycopg.AsyncConnection.connect(url) as conn:
        with time_log("psycopg_async"):
            for id_ in to_query:
                cursor = await conn.execute(select, {"id": id_})
                await cursor.fetchall()
                await cursor.close()
                await conn.rollback()

    async with await psycopg.AsyncConnection.connect(url) as conn:
        async with conn.cursor() as cursor:
            await cursor.execute(drop)
        await conn.commit()


async def run_asyncpg(asyncpg):
    print("Running asyncpg")

    places = dict(
        id="$1", name="$2", description="$3", q="$4", p="$5", x="$6", y="$7"
    )
    a_insert = insert % places
    a_select = select % {"id": "$1"}

    conn: asyncpg.Connection = await asyncpg.connect(url)
    async with conn.transaction():
        await conn.execute(drop)
        await conn.execute(table)
        await conn.executemany(a_insert, [tuple(d.values()) for d in data])
    await conn.close()
    print(f"Insert done. Running {tests} queries")
    to_query = random.choices(ids, k=tests)
    conn: asyncpg.Connection = await asyncpg.connect(url)
    with time_log("asyncpg"):
        for id_ in to_query:
            tr = conn.transaction()
            await tr.start()
            await conn.fetch(a_select, id_)
            await tr.rollback()
    await conn.close()

    conn: asyncpg.Connection = await asyncpg.connect(url)
    async with conn.transaction():
        await conn.execute(drop)
    await conn.close()


for name in sys.argv[1:]:
    if name == "psycopg2":
        import psycopg2
        run_psycopg2(psycopg2)
    elif name == "psycopg":
        import psycopg
        run_psycopg(psycopg)
    elif name == "psycopg_async":
        import psycopg
        if hasattr(asyncio, "WindowsSelectorEventLoopPolicy"):
            asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
        asyncio.run(run_psycopg_async(psycopg))
    elif name == "asyncpg":
        import asyncpg
        asyncio.run(run_asyncpg(asyncpg))
    else:
        print("unknown driver", sys.argv[1])
```

</details>

**Comment by dvarrazzo** [comment]
@dlax heads up - this branch is somewhat related to #415 where you were playing.

I have verified that, if we keep it to Python, select tends to be a faster choice for the case we need to handle (we wait on a single file, whereas other completion functions probably beat select in the generic case, but are optimized to listen on a large number of files). From what I measured, select on one file is faster than epoll on linux and faster than kqueue on macOS (I have only tested the latter via the `selectors.KqueueSelector` object though, which might have a bit more overhead than using `select.kqueue()`).

In the [wait-select](https://github.com/psycopg/psycopg/tree/wait-select) branch I have added [a C implementation of wait_select](https://github.com/psycopg/psycopg/blob/wait-select/psycopg_c/psycopg_c/_psycopg/waiting.pyx), which shaves a further bit of Python overhead than using the `select.select()` function, likely because it avoids to create intermediate lists (again because we need to listen on just one file per thread). The function passes all the tests (including being interruptible).

Looking at the libpq, their choice is [to use `poll()` where available, otherwise fall back on `select()`](https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/fe-misc.c#L1104). I understand that select has problem listening on FDs > 1024, so I'd like to see if we hit that limit and to try to use `poll()` as well.

Whatever the implementation, the resulting interface will leave the rest of the code unchanged and can be used to wait on the generators as they are implemented. However, the importance of having this function in C for me is that, if we reverse the flow as per #415, the functions in `generators.pyx` will be able to call this wait function without leaving the C layer and without setting/catching exceptions as the generators interface need to do.

**Comment by dlax** [comment]
Hi @dvarrazzo,

What sort of benchmark did you use to measure this?

In general, I think it would be valuable to have a shared benchmark suite so that we can agree on the measures and conclusions. That's why I started working back on the "pgbench" suite, as mentioned in #415; data shared at that time is not very usable, probably due to concurrency -- but I think that can be improved. Last time I checked, I wasn't so sure that psycopg 3 was slower that psycopg2 in fact...

For the particular case of measuring waiting overhead, I was thinking about measuring `list(cursor.stream("select generate_series(1, 10000)"))` because it calls `Connection.wait()` many times (10000 times) and does nothing more sophisticated (presumably). What do you think?

Now about changing the default wait function, I'm not sure. (But I'm not sure if you're asking for my opinion either :)) Maybe a starting point could be to expose a way for end users to select a particular implementation? (Possibly through a temporary flag we could remove afterwards, to avoid backwards compat issues.) This way, when someone comes up with a real-life performance issue, we could get insights more easily. Also, I guess I could convinced/reassured if we'd follow the move of another project; because it seems everybody uses epoll/kqueue/etc.

Finally, looking back at the implementation of various waiting functions, one thing I noticed is that we could keep a single `epoll` instance bound to the connection instead of recreating one with `select.epoll()` each time we call `wait()` (same for `Selector`). That's typically done in asyncio (and trio) as part of the event loop object. What do you think? I can work on this eventually.

I will need more time to think about other aspects you mentioned (the C - Python part; or the "reverse flow").

**Comment by dvarrazzo** [comment]
Yes, I admittedly use ad-hoc tests when tweaking for performance. I'd be happy to have something for regular use in `tests/scripts`.

I am not sure that `cursor.stream()` exercises `wait()` intensely. Actually, doing so was the cause of the slowness reported in #286: it was fixed by not yielding (hence not calling wait) unless really needed (see 7aba716e92bde573a63c2798172c4d3eed41a680), because every fetch returns more than one row. We can include it in benchmarks, but with a value of its own.

I think that, for this test, calling a simple query in a tight loop is the best we can do.

In terms of reassurance about select, the libpq uses poll internally, with select as a fallback, in PQexec, aka in the blocking version of the execution loop. We could try and measure epoll/kqueue in C too, but I understand that the improvements that these primitives bring are when listening for more than one fd at time.

Let me think about the opportunity of changing the default function...

**Comment by dlax** [comment]
> Finally, looking back at the implementation of various waiting functions, one thing I noticed is that we could keep a single epoll instance bound to the connection instead of recreating one with select.epoll() each time we call wait() (same for Selector). That's typically done in asyncio (and trio) as part of the event loop object.

For future reference, linking https://github.com/dlax/psycopg3/commit/0409601e9de80324cf528a4abe998697555e0690, which implements this idea and apparently resolves the overhead of epoll (and probably other selectors).

**Comment by dvarrazzo** [comment]
Releasing a more performing wait function with Psycopg 3.1.5.
