### ISSUE TITLE
Weird bugs when calling manually pool.connection().__aenter__() and conn.__aexit__()

### ISSUE THREAD

**Issue by pwtail** [psycopg/psycopg#432]
Hi @dvarrazzo,

I am currently in the process of implementing an async postgresql backend for django, using your driver for that. An async backend is possible because I am using greenlets.

The issue stems from the fact that django is not always using cursor as a context manager:

```python
with connection.cursor() as c:
  ...
```

Instead, it sometimes manually calls create and destroy:

```python
cursor = connection.cursor()
...
cursor.close()
```

In the async context, the explicit create-and-destroy way means that I also have to take a connection from the connection pool and return it back on cursor close. How do I do that?

```python
conn = await pool.connection().__aenter__()
await conn.__aexit__() 
```
Now, when I am trying to do that, all kinds of weird bugs can happen. I can provide you the details if you ask. For example, a thrown `GeneratorExit` starts to be handled as an error.

Is it so that this is a not intended way to use, and that explicit create-and-destroy pattern is discouraged? Or there is some other way I am not aware of?

**Comment by dvarrazzo** [comment]
Hi @pwtail,

Of course calling dunder aenter and aexit is not the intended way to use them 🙂 

If you need to get and return a connection to the pool manually you should use getconn and putconn.

**Comment by pwtail** [comment]
Thank you, it works!
