### ISSUE TITLE
Cursos.rownumber should return None if there are no tuples in the result 

### ISSUE THREAD

**Issue by pavel-tarasov** [psycopg/psycopg#437]
### Discussed in https://github.com/psycopg/psycopg/discussions/436

<div type='discussions-op-text'>

<sup>Originally posted by **pavel-tarasov** November  9, 2022</sup>
I experienced the behaviour of the attribute rownumber of Cursor class. In [doc](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.rownumber) I see that it should be `None` if there is no result to fetch. But in my example, I see 0 in this attribute after running the query, which doesn't have anything to fetch ("insert" without returning). And same behaviour when there is what to fetch from the query ("insert" with returning). So, it looks like I can't use this attribute to check if I can catch something from the query.
Question: is it correct behaviour or not? If yes, should we change the documentation?</div>

As @dvarrazzo mentioned in the discussed above, now it returns a number when there is a result, regardless of whether the result contains tuples or not. It should return None if the result doesn't contain tuples.

**Comment by dvarrazzo** [comment]
I have a fix ready in the commit above, referring to this ticket.
