### ISSUE TITLE
TupleRow can cause Pyright errors when used as a generic type argument

### ISSUE THREAD

**Issue by rpmrmartin** [psycopg/psycopg#439]
```python
from psycopg import AsyncConnection
from psycopg.rows import TupleRow

Connection = AsyncConnection[TupleRow]
```

```
Loading configuration file at /app/pyrightconfig.json
Assuming Python version 3.11
Assuming Python platform Linux
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Searching for source files
Found 1 source file
pyright 1.1.280
/app/EtlProcess/Repro.py
  /app/EtlProcess/Repro.py:4:30 - error: Expected type expression but received "TypeAlias" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations 
Completed in 0.662sec
```

The root cause seems to be that Pyright doesn't support importing `TypeAlias` from anywhere other than `typing` or `type_extensions`. I thought this was a Pyright bug, so I opened microsoft/pyright#4197, but they have closed that as as-designed, so I wonder if there's anything that you could do in psycopg.

**Comment by dvarrazzo** [comment]
Please don't paste screenshot. I appreciate the use of negative space, as a photographer, but I can't be bothered zooming in to read your traceback. Please edit the above, dropping the script and pasting the traceback in a code block.

As you nave seen, we have the `TypeAlias` in our `psycopg._compat` module. That works for mypy, and that's what we aim to, not other linters. We use `TypeAlias` in (grepgrepgrep) 13 different places: I don't want to add an if-version in all those places: `_compat` is there for that reason.

If any we can use `TypeAlias` unconditionally from `typing_extension` but we might need to change the metadata dependencies for that.

Let me add a note to the pyright ticket above.
