### ISSUE TITLE
No copy_from?

### ISSUE THREAD

**Issue by johann-petrak** [psycopg/psycopg#442]
Beginner user of psycopg3, sorry if I overlooked some documentation.

I want to import rows from a generator of chunks of rows as efficiently as possible and have seen on SO that "COPY_FROM" is probably the fastest way to do this. There is also example code around where one can use `cur.copy_from` to read from a StringIO file in Python.

However with psycopg3, all I find is `cur.copy("..... FROM STDIN")` which does not easily allow me to use anything else but STDIN for the data source. 

Is there a better alternative? Would it be useful to allow copying from/to python file objects?

**Comment by johann-petrak** [comment]
I think I misunderstood how this works. Sorry for the spam.

**Comment by dvarrazzo** [comment]
Maybe it could be useful to mention how to port the use of copy_from and copy_to to psycopg 3 here? https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#copy-is-no-longer-file-based

**Comment by johann-petrak** [comment]
I think the documentation is actually good - it was just me who was just completely misunderstanding what I read and not reading all the details properly :) 

The new API is much cleaner IMO, as it basically takes the burden from the user to handle the file objects and instead can use rows from a generator or similar directly. 

Thanks for the great library and documentation!
