### ISSUE TITLE
Copy Binary VarChar Dumper

### ISSUE THREAD

**Issue by bkief** [psycopg/psycopg#452]
I noticed there is no registered `register_dumper` for the varchar type. Was this an oversight or is there a technical reason? Any work arounds available to do a binary insert including some varchar fields?

**Comment by dvarrazzo** [comment]
...ah, maybe I understand:

```python
>>> copy.set_types(["varchar"])

ProgrammingError: cannot find a dumper for type varchar (oid 1043) format BINARY
```

if this is the problem, probably you can use "text" in `set_types()` instead of varchar, because the two types have the same binary representation.

Is the issue coming from here? Does registering text instead work?
