### ISSUE TITLE
Add a way to provide a factory for creating the connections in a pool

### ISSUE THREAD

**Issue by BinarSkugga** [psycopg/psycopg#459]
This would be useful in case all your connections need to listen to a PostgreSQL channel for example. Right now, I'm stuck doing this on a schedule because the connections expire (using `max_lifetime`) and new ones never call my `LISTEN`  command.

**Comment by dvarrazzo** [comment]
You can use the [`ConnectionPool`](https://www.psycopg.org/psycopg3/docs/api/pool.html#psycopg_pool.ConnectionPool)'s `configure` parameter for this purpose:

```python
def configure_connection(conn):
    conn.execute("LISTEN my_channel")
    conn.commit()

pool = ConnectionPool(DSN, configure=configure_connection)
```

**Comment by BinarSkugga** [comment]
Thank you !
