### ISSUE TITLE
Using a buffer to write a psycopg3 copy result through pandas

### ISSUE THREAD

**Issue by FlipperPA** [psycopg/psycopg#461]
I read up on https://github.com/psycopg/psycopg/issues/316 but have a slightly different issue.

Using `psycopg2`, I could write large results to various formats on disk using `copy_expert` and a `BytesIO` buffer like this with `pandas`:

```python
copy_sql = "COPY (SELECT * FROM big_table) TO STDOUT CSV"

buffer = BytesIO()
cursor.copy_expert(copy_sql, buffer, size=8192)
buffer.seek(0)
pd.read_csv(buffer, engine="c").to_excel(self.output_file)
```

However, I can't figure out how to replace the `buffer` in `copy_expert` with `psycopg3`'s new copy command. Is this still possible? It is quite likely I just haven't figured out the proper formula; if someone can help, I'd be happy to PR an addition to the documentation.

Another question: is the above code in psycopg2 doing what I intended, and minimizing memory usage, or does it actually copy the entire query result into `buffer` before using `pandas` to write to Excel format with `to_excel`?

Thank you for your efforts, they are very much appreciated!

**Comment by dvarrazzo** [comment]
It is explained [in the documentation](https://www.psycopg.org/psycopg3/docs/basic/copy.html#copying-block-by-block): you can use `copy()` block-by-block:

```python
copy_sql = "COPY (SELECT * FROM big_table) TO STDOUT CSV"
buffer = BytesIO()
with cursor.copy(copy_sql) as copy:
    for data in copy:
        buffer.write(data)

buffer.seek(0)
pd.read_csv(buffer, engine="c").to_excel(self.output_file)
```

This is what psycopg2 does internally; moving the iteration of the copy stream from inside a consumer function to the hands of the user (or of the file, if you copy into the database instead) allows different operation patterns, such as async copy (including mixing up an async connection with a sync file, or the other way around).

**Comment by FlipperPA** [comment]
@dvarrazzo Thanks so much for the reply and explanation. I'm guessing that in both cases (psycopg2 and psycopg3), the entire result set of the query is loaded into Python's memory footprint - or am I wrong here? What I was trying to do was stream the result from psycopg to pandas in chunks. Some of our queries get quite large - hundreds of GB large. :)

**Comment by dvarrazzo** [comment]
Yes, your pattern would load the entire dataset in memory, both with psycopg 2 and 3, because BytesIO is just a file interface over a chunk of memory.

Using a tempfile object, such as [spooled temp file](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile) would allow to start using the disk after a certain memory threshold.

**Comment by Delengowski** [comment]
@dvarrazzo 

Is there a way to cut out the intermediate bytesIO?

The buffer for read csv just requires a specific protocol 

https://github.com/pandas-dev/pandas/blob/main/pandas/_typing.py#L281

Are we not able to just add these methods to return of `cursor.copy()`? Or maybe an object in-between (which matches the protocol) that just yields directly from `copy` ?

**Comment by dvarrazzo** [comment]
@Delengowski 

It seems simple enough to write an adapter object implementing the `ReadBuffer` protocol, to consume the data read from copy in a queue and to expose it to Pandas.

I have an excess of work in other projects right now and I don't have the resources to study the details of the problem. Are you considering to provide a sponsorship to the project in order to provide this feature?

**Comment by Delengowski** [comment]
Yes I am.

I am digging further into the pandas code, but my investigations are supporting my hypothesis of the passed object only requiring a `.read()` method.


edit:

My largest concern is that the object will require a `.seek()`, unsure what kind of `csv.CSVSniffer` use by pandas.

**Comment by dvarrazzo** [comment]
Can it be made to return `seekable` -> `False`?

**Comment by Delengowski** [comment]
So good news, I was able to make a solution without making an intermediate buffer, using only a wrapper object. Its very naive, and does nothing to account for number of rows to read, but it works as a starting point.

```python
import pandas as pd

class MockFile:

    def __init__(self, cursor):
        self.cursor = iter(cursor)

    def read(self, size=-1):
        try:
            res = next(self.cursor)
            return res.tobytes()
        except StopIteration:
            return b""

with cur.copy("COPY (SELECT * FROM studentss) TO STDOUT CSV") as copy:
    print(pd.read_csv(MockFile(copy), engine="c"))
```

**Comment by Delengowski** [comment]
Doesn't seem to be faster

```python
In [4]: %%timeit
   ...: with cur.copy(sql) as copy:
   ...:     pd.read_csv(MockFile(copy), engine="c")
   ...:
   ...:
1.68 s ± 16.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: %%timeit
   ...: buffer = BytesIO()
   ...: with cur.copy(sql) as copy:
   ...:     for data in copy:
   ...:         buffer.write(data)
   ...: buffer.seek(0)
   ...: pd.read_csv(buffer, engine="c")
   ...:
   ...:
1.21 s ± 31.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by Delengowski** [comment]
```python
In [7]: %%pyinstrument
   ...: with cur.copy(sql) as copy:
   ...:     pd.read_csv(MockFile(copy), engine="c")
   ...:
   ...:

  _     ._   __/__   _ _  _  _ _/_   Recorded: 22:53:14  Samples:  4625
 /_//_/// /_\ / //_// / //_'/ //     Duration: 4.805     CPU time: 4.805
/   _/                      v5.0.2

Cell [7]

4.804 <module>  <ipython-input-7-49024d316d74>:1
`- 4.803 read_csv  pandas/io/parsers/readers.py:868
      [3 frames hidden]  pandas
         4.782 CParserWrapper.read  pandas/io/parsers/c_parser_wrapper.py:222
         `- 3.911 MockFile.read  populate_postgres.py:58
            |- 3.041 Copy.__iter__  psycopg/_copy.py:81
            |     [7 frames hidden]  psycopg, <built-in>
            |        2.158 Connection.wait  psycopg/connection.py:406
            |        `- 1.055 [self]  psycopg/connection.py
            |- 0.538 [self]  populate_postgres.py
            |- 0.175 next  <built-in>
            `- 0.157 memoryview.tobytes  <built-in>



In [8]: %%pyinstrument
   ...: buffer = BytesIO()
   ...: with cur.copy(sql) as copy:
   ...:     for data in copy:
   ...:         buffer.write(data)
   ...: buffer.seek(0)
   ...: pd.read_csv(buffer, engine="c")
   ...:
   ...:
Out[8]:
        434577  3.14  foo
0       434578  3.14  foo
1       434579  3.14  foo
2       434580  3.14  foo
3       434581  3.14  foo
4       434582  3.14  foo
...        ...   ...  ...
999994  434572  3.14  foo
999995  434573  3.14  foo
999996  434574  3.14  foo
999997  434575  3.14  foo
999998  434576  3.14  foo

[999999 rows x 3 columns]

  _     ._   __/__   _ _  _  _ _/_   Recorded: 22:53:32  Samples:  3107
 /_//_/// /_\ / //_// / //_'/ //     Duration: 3.230     CPU time: 3.230
/   _/                      v5.0.2

Cell [8]

3.230 <module>  <ipython-input-8-e2a2f635d1ef>:1
|- 2.505 Copy.__iter__  psycopg/_copy.py:81
|     [7 frames hidden]  psycopg, <built-in>
|        1.778 Connection.wait  psycopg/connection.py:406
|        `- 0.817 [self]  psycopg/connection.py
|- 0.367 [self]  <ipython-input-8-e2a2f635d1ef>
|- 0.189 read_csv  pandas/io/parsers/readers.py:868
|     [3 frames hidden]  pandas
`- 0.168 BytesIO.write  <built-in>

**Comment by Delengowski** [comment]
Unsurprisingly,

The no buffer method uses less memory.

There's no way to do this without converting the memory view to bytes, maybe something that goes straight to numpy, for pandas to consume.

![no_buffer](https://github.com/user-attachments/assets/b3cb40d3-1c26-402c-a099-8180b2504298)

![buffer](https://github.com/user-attachments/assets/99fb4329-7432-4253-91dd-1ee862e523d0)

**Comment by Delengowski** [comment]
Here's an implementation that can actually support chunked reading. It performs similar writing to a buffer, but still slower. While keep a memory footprint closer to what my attempt had.


```python
In [4]: %%timeit
   ...: with cur.copy(sql) as copy:
   ...:     pd.read_csv(MockFile(copy), engine="c")
   ...:
   ...:

1.3 s ± 20.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]:

In [5]: %psource MockFile
class MockFile:

    def __init__(self, cursor):
        self.cursor = cursor

    def read(self, size=-1):
        if size == -1:
            chunk = bytearray()
            for row in self.cursor:
                chunk.extend(row)
            return bytes(chunk)
        else:
            chunk = bytearray()
            counter = 0
            for row in self.cursor:
                chunk.extend(row.tobytes())
                counter += row.nbytes
                if counter >= size:
                    break
        return bytes(chunk)

In [11]: %%pyinstrument
    ...: with cur.copy(sql) as copy:
    ...:     pd.read_csv(MockFile(copy), engine="c")
    ...:
    ...:

  _     ._   __/__   _ _  _  _ _/_   Recorded: 12:15:40  Samples:  3417
 /_//_/// /_\ / //_// / //_'/ //     Duration: 3.508     CPU time: 3.509
/   _/                      v5.0.2

Cell [11]

3.508 <module>  <ipython-input-11-49024d316d74>:1
`- 3.507 read_csv  pandas/io/parsers/readers.py:868
      [5 frames hidden]  pandas
         3.417 CParserWrapper.read  pandas/io/parsers/c_parser_wrapper.py:222
         `- 3.282 MockFile.read  populate_postgres.py:60
            |- 2.414 Copy.__iter__  psycopg/_copy.py:81
            |     [7 frames hidden]  psycopg, <built-in>
            |        1.725 Connection.wait  psycopg/connection.py:406
            |        `- 0.753 [self]  psycopg/connection.py
            |- 0.536 [self]  populate_postgres.py
            |- 0.166 bytearray.extend  <built-in>
            `- 0.166 memoryview.tobytes  <built-in>
         0.079 CParserWrapper.__init__  pandas/io/parsers/c_parser_wrapper.py:60
         `- 0.079 MockFile.read  populate_postgres.py:60
            `- 0.062 Copy.__iter__  psycopg/_copy.py:81
                  [2 frames hidden]  psycopg
```

![Image](https://github.com/user-attachments/assets/f114f911-098b-4e55-854a-734b5e0b681b)

**Comment by Delengowski** [comment]
@dvarrazzo  Let me know what you think of this. I found this issue from looking for ways to get my data into pandas faster. I am admittedly a bit out of my depth with psycopg. I'd be happy to try to formalize this if it seems worthwhile. I would just request some guidance how to best integrate this. I imagine my experimentation will not suffice as a PR submittal.

**Comment by FlipperPA** [comment]
@Delengowski I'm including where we landed, just in case it helps, since we were looking to keep a low memory footprint as well.

We used to write files through `psycopg` for CSV, Excel, and Parquet formats, but switched to DuckDB for Excel and Parquet. For CSV, we stayed basic with `psycopg`, which doesn't seem to balloon memory at all, even on multi-terabyte queries:

```python
with open(csv_file, "wb") as output_file_handle:
    with cursor.copy(copy_sql, query_runner.params) as copy:
        for stream_data in copy:
            output_file_handle.write(stream_data)
```

For XLSX and Parquet, we've started using DuckDB like this:

```python
    import duckdb
    from duckdb_extensions import extension_importer

    duckdb.sql(f"SET extension_directory = '{output_path}';")
    duckdb.sql(f"SET temp_directory = '{output_path}';")
    extension_importer.import_extension("postgres_scanner")

    duckdb.sql(f"""
        ATTACH 'host=your-pg-server.com user={username} password={password} dbname=your-db' AS pg_connection (TYPE POSTGRES);
    """)

    ddb_query = "SELECT * FROM your_table".replace("'", "''")

    extension_importer.import_extension("excel")
    duckdb.sql(f"""
        LOAD excel;
        COPY (SELECT * FROM postgres_query('pg_connection','{ddb_query}'))
        TO '/tmp/duckdb-test.xlsx'
        WITH (FORMAT xlsx, HEADER true, SHEET 'Results');
    """)
```

**Comment by dvarrazzo** [comment]
What I would try to do, to parallelize the operation between Postgres and Pandas, is to run the copy in a thread and push CSV data page as fast as it can into a Queue, managed by MockFile. In the main thread you can read `pd.read_csv`.

If you give the queue a max size you can control how much memory you use. Copy would block if the queue is too full, read would block if the queue is empty.
