### ISSUE TITLE
Refactor: get version from metadata

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#465]
At the moment, packages versions is established in the version.py module and parsed from setup.py. This makes setup.py somewhat brittle.

The system was meant to keep a 1-1 lock between psycopg and psycopg-c packages, but we might have a bit more flexibility there. For instance, in release 3.1.7 we only released psycopg and psycopg-c packages, but not psycopg-binary, because we didn't have Scaleway runners available but the code was compatible with 3.1.6. So [we hacked setup.py](https://github.com/psycopg/psycopg/commit/cefcafff6e29e534f7a6ce5ba9a7e97f1bd193c2) for this specific release.

Consider using setup.cfg as the authoritative place where to set the version, use `importlib.metadata` to import in `version.py` or in `__init__.py`.

**Comment by deepsghimire** [comment]
I would like to contribute on this issue. Is there anything else I need to know or consider before starting?

**Comment by dvarrazzo** [comment]
Thank you, @deepsghimire. I would empty the `psycopg/setup.py`, moving all the dependencies and extras to `psycopg/setup.cfg`. Versions should be authoritatively written there, and exposed to Python using [`importlib.metadata.version()`](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions) (for Python 3.7 we need to add the dependency on the `importlib_metadata` backport module; the `_compat.py` module is the right place to import and expose the if-versioned objects).

The project contains three packages (`psycopg`, `psycopg_c`, `psycopg_pool`) which should have the same structure w.r.t. versions.

There's a cute little script, `tools/bump_version.py`, which I started using to automate release chores: if you want to upgrade it too you are welcome, but it's not necessary.

Thank you very much!

**Comment by dvarrazzo** [comment]
Fixed, and first change to get in 3.2!

Thank you very much, @deepsghimire!
