### ISSUE TITLE
Short-lived connections with max_idle

### ISSUE THREAD

**Issue by khoben** [psycopg/psycopg#472]
- PostgreSQL server with short-lived connections
(about 60 seconds) which will be closed by server side timeout;
- Sample AsyncConnectionPool:

```python
pool = AsyncConnectionPool(
            connectinfo=self.__conn_info,
            min_size=2,
            max_size=10,
            max_idle=60,
            **self.__kwargs
)
```
With this configuration the pool will be reduced after ~60 seconds to `min_size`, but the remaining `min_size` connections are no longer valid and will still be in the pool. And `max_idle` has absolutely no effect on some connections.

What if close the connection anyway and then add a new one?:

```python
import logging
from typing import Any, Optional

from psycopg import AsyncConnection
from psycopg_pool import AsyncConnectionPool
from psycopg_pool.pool_async import AddConnection

logger = logging.getLogger("psycopg.pool")


class PatchedAsyncPool(AsyncConnectionPool):

    async def _shrink_pool(self) -> None:
        to_close: Optional[AsyncConnection[Any]] = None
        add_connection_after_close = False

        async with self._lock:
            # Reset the min number of connections used
            nconns_min = self._nconns_min
            self._nconns_min = len(self._pool)

            # If the pool can shrink and connections were unused, drop one
            if nconns_min > 0:
                # CHANGED
                to_close = self._pool.popleft()
                self._nconns -= 1
                self._nconns_min -= 1
                if self._nconns <= self._min_size:
                    add_connection_after_close = True

        if to_close:
            logger.info(
                "shrinking pool %r to %s because %s unused connections"
                " in the last %s sec",
                self.name,
                self._nconns,
                nconns_min,
                self.max_idle,
            )
            await to_close.close()
            # CHANGED
            if add_connection_after_close:
                logger.info(
                    "establishing new connection after shrink to"
                    " keep up `min_size` connections"
                )
                self.run_task(AddConnection(self))
```

**Comment by dvarrazzo** [comment]
I don't understand the problem, as well as the solution. What do you mean "results in the use of a timeout-closed connection"? Can you show a stand-alone script or add a failing test to the test suite to show the problem?

**Comment by khoben** [comment]
I'll add some clarification:

Setup:
PostgreSQL 14 with [idle_session_timeout](https://www.postgresql.org/docs/14/runtime-config-client.html#GUC-IDLE-SESSION-TIMEOUT)  equal to 60 seconds;
Any client code using a connection pool with `min_size` > 1:

```python
pool = AsyncConnectionPool(
            conninfo=self.__conn_info,
            min_size=2,
            max_size=10,
            max_idle=60,
            **self.__kwargs
)
```

The problem is that if the number of pending connections in the pool is less than or equal to `min_size`, they will not be updated based on `max_idle` time. And then there will be an error repeating `min_size` times (the server has closed the connection) when accessing the connection pool.

**Comment by khoben** [comment]
If `max_idle` behaves like `shrinking rate`, then everything works as it should. Probably the case of time-out refreshing connections should be handled by the client code.

**Comment by dvarrazzo** [comment]
The pool isn't designed to handle `idle_session_timeout`: as far as the pool is concerned, it will be just a broken connection, and, as documented, the pool doesn't check for broken connection on `getconn()`.

As per postgres documentation:

> Be wary of enforcing this timeout on connections made through connection-pooling software or other middleware, as such a layer may not react well to unexpected connection closure. It may be helpful to enable this timeout only for interactive sessions, perhaps by applying it only to particular users.

AFAICS, setting `idle_session_timeout` for a connection pool doesn't make any sense at all.
You can disable that setting for the connection pool only by passing it the parameter `kwargs={"options": "-c idle_session_timeout=30"}` (the single `kwargs` pool parameter is expanded into connection kwargs arguments).

This problem isn't limited to shrinking down from a max_conn > min_conn, it will happen whenever one connection in the pool is unused for the timeout duration, so what proposed here is not a solution.
