### ISSUE TITLE
Enforce for `max_lifetime` in `pool.check()`

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#482]
I'm also thinking that `check()` might be a good moment to check if `max_lifetime` is expired, because it's already in the business of taking out all the connections from the pool and exercise them. This is much simpler and can be done in a bugfix for psycopg_pool 3.1. It would be up to the user to call `pool.check()` periodically.

_Originally posted by @dvarrazzo in https://github.com/psycopg/psycopg/issues/247#issuecomment-1378712987_

**Comment by dvarrazzo** [comment]
It should be as easy as (untested):

```diff
diff --git a/psycopg_pool/psycopg_pool/pool.py b/psycopg_pool/psycopg_pool/pool.py
index 609d95df..47c9561b 100644
--- a/psycopg_pool/psycopg_pool/pool.py
+++ b/psycopg_pool/psycopg_pool/pool.py
@@ -409,6 +409,13 @@ class ConnectionPool(BasePool[Connection[Any]]):
 
         while conns:
             conn = conns.pop()
+
+            if conn._expire_at <= monotonic():
+                logger.info("discarding expired connection %s", conn)
+                conn.close()
+                self.run_task(AddConnection(self))
+                continue
+
             try:
                 conn.execute("SELECT 1")
                 if conn.pgconn.transaction_status == TransactionStatus.INTRANS:
```

It needs the equivalent async, tests in the test suite, an entry in the changelog.

It seems simple enough if someone would like to try it.

**Comment by A-Posthuman** [comment]
If max_lifetime doesn't actually enforce (on its own) the lifetime, please update your docs because they are currently misleading and mention nothing about that the user is responsible for enforcing this via calling pool.check() periodically. The docs currently say:

"The maximum lifetime of a connection in the pool, in seconds. Connections used for longer get closed and replaced by a new one."

**Comment by dvarrazzo** [comment]
No, you are wrong, the connection lifetime is not only enforced by
`check()`. It is regularly verified at `putconn()`.

This ticket is about it not being verified at check *too*, and now it is.
