### ISSUE TITLE
v3.1.3 of the binary was deleted

### ISSUE THREAD

**Issue by justinTM** [psycopg/psycopg#483]
so, basically, the newest version of psycopg (3.1.6 the last time i checked) does not work -- and has some cryptic errors i've already spent a few hours trying to solve -- and the most recent error is this:

3.1.3 for the binary distro via pypi does not exist anymore

--

setting aside my strong opinions on leaving permanent URLs to relied-upon resources, does anyone know of a workaround for the latest version? otherwise, i'll just find a hard copy of the 3.1.3 version and use it directly in our private file-share.

thank you!

Justin

**Comment by justinTM** [comment]
sorry, this is a poetry error. i checked via cli but should have just checked the actual pypi website

**Comment by dvarrazzo** [comment]
You haven't given a great show of yourself, man.

**Comment by justinTM** [comment]
psycopg has been an enormous PITA over the past few months, i apologize.
