### ISSUE TITLE
Add integration tests with SQLAlchemy

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#488]
See #487 

We all love (but hate (but love)) semver, but it would be nice to check for accidental breakages.

Testing would slow down. Maybe we should add an "integration tests" workflow to run before release and daily on cron?

@zzzeek, @CaselIT would you like to help me with this? Either providing a MR or suggesting a "script" procedure to run a SQLAlchemy+psycopg test, and which versions to test?

Thank you very much!

**Comment by CaselIT** [comment]
Hi Daniele,

I can look at creating an integration pypeline test for sqlalchemy, that maybe could be extended also to other 3rd party dialects.

How about making it run on commits on the master branch and optionally manually? That would not impact normal PRs but it would catch issues fairly quickly once a new feature is in marter

**Comment by dvarrazzo** [comment]
@CaselIT can you explain better: do you see this pipeline running in the SA repo or in the PG repo?

**Comment by CaselIT** [comment]
I meant in PG repo

There are already tox test in the pipeline that runs using psycopg master in sqlalchemy

**Comment by zzzeek** [comment]
right but I hardly ever look at our "master" runner because it breaks so often for things that aren't our issue.  Though in this case, it did pick up this problem; it runs nightly.    but if psycopg had this in CI in response to new changes then it would be more of an alert that  a particular change is breaking.

**Comment by CaselIT** [comment]
I'm creating something

**Comment by dvarrazzo** [comment]
> I meant in PG repo

That's ok, we are talking about the same idea then :D I was a bit confused.

> right but I hardly ever look at our "master" runner because it breaks so often for things that aren't our issue.

On our side, I would run integration tests on branches master and maint-3.1 of psycopg 3 (and analogous for psycopg2 if easy - it should).

Considering that the goal of this test is to avoid that changes in PG accidentally break SA (and similarly other 3rd party integrations), I think it would be appropriate to run SA tests using the psycopg dialect on the currently supported versions of SA. Maybe 1.4.x and 2.0.x? Looking at your timeline on pypi it seems 1.3.x is not maintained anymore.

Is it worth to test Alembic too or you don't think that a breakage in Alembic would be missed by a test in SA? Should we test it, which versions?

I think that it would be already valuable to test the packages released on PyPI rather than the development branches, the reason being that, if a breakage happens in psycopg maint branch vs. a SA released version, is our fault; if it happens on an SA maint branch against psycopg it's yous :yum: 

Happy to hear your input. Thank you very much!

**Comment by CaselIT** [comment]
> Maybe 1.4.x and 2.0.x

only v2 for psycopg. 1.4 could be added if we want to extend this to psycopg2

> Is it worth to test Alembic too or you don't think that a breakage in Alembic would be missed by a test in SA? Should we test it, which versions?

I don't think alembic would add anything valuable here, since it uses sqlalchemy for all sql execution

**Comment by CaselIT** [comment]
> I'm creating something

fighting the ci at the moment. Trying to use services, and of course they don't work :(
> psql: error: could not translate host name "pg" to address: Temporary failure in name resolution

I'm gonna copy your docker run

**Comment by dvarrazzo** [comment]
I stopped using services for tests in GitHub Actions: not a chance to configure the `postgresql.conf`.

**Comment by CaselIT** [comment]
I don't really need to. Managed to make the service work, but need to use localhost instead of the name of the service...
