### ISSUE TITLE
Move macOS arm64 builds to AWS

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#491]
At the moment we use Scaleway to source runners to build macOS arm64 builds. Unfortunately the provider is unreliable: none was available to build 3.1.7 and some availability appeared after 3.1.8 packages were already released.

We also requested access on MacStadium but we had no answer. Their initiative to support free software is now closed.

AWS seems to provide [Mac M1 workloads](https://aws.amazon.com/ec2/faqs/#macos_workloads) so we might start using it instead.

**Comment by malthe** [comment]
See https://github.com/psycopg/psycopg/issues/344#issuecomment-1987291400 – M1 runner now available to all GitHub plans, including open source 🚀

**Comment by dvarrazzo** [comment]
I looked into AWS in the past and it was too cumbersome and expensive.

Tried to use Github runner in the last release, and it seems ok.
