### ISSUE TITLE
`ConnectionPool`'s kwargs parameter is not ideal for typing and auto-completion

### ISSUE THREAD

**Issue by bluetech** [psycopg/psycopg#493]
The forwarding kwargs in `ConnectionPool`'s constructor means that all of the forwarded arguments are not type checked and can't be auto-completed/discovered in code editors.

This is the kwargs:

https://github.com/psycopg/psycopg/blob/f058590f2d2ffa122cff2aa81c2646dcfba4b4ff/psycopg_pool/psycopg_pool/pool.py#L30-L40

and these are the "missing" parameters:

https://github.com/psycopg/psycopg/blob/f058590f2d2ffa122cff2aa81c2646dcfba4b4ff/psycopg_pool/psycopg_pool/base.py#L40-L56

This also holds for the other pool types.

Possible solutions I can think of are:

- Eliminate the kwargs; duplicate all of the parameters.
- Wait for [PEP-692](https://peps.python.org/pep-0692/). This will fix the type safety, but probably not the code editor part.
- Replace the params with a configuration type. This is a breaking change, unless moved to a factory method.

**Comment by dvarrazzo** [comment]
Would you like to provide a MR?

**Comment by dvarrazzo** [comment]
Yes, the first solution is a chore and a pita, but it's the only viable one.

Default values should be dropped from the base classes, so they will be duplicated between sync/async but not between base/subclass.

**Comment by dvarrazzo** [comment]
psycopg-pool 3.1.6 released with this fix. Thank you for your contribution, @bluetech :slightly_smiling_face:
