### ISSUE TITLE
Execution of arbitrary user-supplied SQL is not supported

### ISSUE THREAD

**Issue by kpinc** [psycopg/psycopg#497]
Hello,

My users input and execute arbitrary sql to validate, update, explore, and analyze complex data.  Although not presently enforced, psycopg3 does not allow execution of sql supplied as a (non-literal) string.   This means that I cannot write psycopg2 applications that get sql from a user to execute.

PEP675 is motivated by the desire to prevent application developers from writing insecure code.  That is not a reason to block functionality that supports a legitimate use-case.  Some kind of escape mechanism should exist so that arbitrary sql can be executed.

All access to our databases is controlled through the Postgres permission system, with each person having their own Postgres login which grants them only the permissions they need.  There is no reason to restrict what can be done with SQL.

Basically, our users have an application that mimics `psql`, but is web-based and supports various options for downloading results.    The core of the code accepts a string from the user, containing however many SQL statements the user supplies, and then executes them.  Something like:

    def runsql(user, sql):
        '''Show SQL output'''
        with psycopg.connect(f"user={user}") as conn:
            with conn.cursor() as cur:
                cur.execute(sql)
                more = True
                while more:
                    for record in cur:
                        print(record)
                    print(f'Rows affected: {cur.rowcount}')
                    more = cur.nextset()

Our databases contain complex data validation triggers.  Users rely on these to ensure data integrity and so often use transactions to make 'blocks" of their changes.  A trivial, entirely made up, example of a block of SQL that our users might execute would:

- begin a transaction
- run a SELECT producing the average age of  first-time mothers
- insert a row for "joe" into biography, which indicates "mary" is joe's mother
- again SELECT the average age of first-time mothers
- update the birthdate of all females in Thailand born before 2010 by 12 hours to correct a timezone problem
- again select the average age of first-time mothers
- rollback the transaction

Behind the scenes, database  validation is ensuring that mary is not giving birth to joe after she's dead, that no female is having offspring before first menses, etc.  If there's a problem -- no worries, the transaction rolls back.  If the user likes what they see, they re-run the sql and change the final rollback to a commit.  They may download all output produced as a spreadsheet and keep it for future reference.

One way to resolve this problem would be to have a separate distribution "extra" (psycopg3[unsafe]) that does not have the "literal" restriction on sql.  Alternately, there could be a way to flag exceptions.  Like #noqa in flake8 or #pylint for pylint, etc.  I'm unclear on how to implement any of this but would be willing to help.  Tell me what direction you'd like to go. Maybe, per PEP675, there's a #type hack that would get around the limitation.  But I imagine that this would vary based on the type-checker and it seems to be best to have something "built-in".  At the very least, have something documented.

If, indeed, you already have a solution I'd be happy to submit a documentation patch which describes it.  (I have strong suspicions that once you actually enforce the literal string requirement for sql there will be much wailing and gnashing of teeth because there will be lots of existing code utilizing bad-practice.  It would be nice to have an upgrade path that gives people a way to transition to safety.)

Of course, I could always grab the source, run it through sed, and make my own version of psycopg3.  But that's just a horrible kludge.

PEP675 says that "too many people are doing it wrong, here's a good tool to fix that".  It does not say that "some programs, like psql, are just too dangerous and should not be implementable in python."

P.S.  It is awesome that psycopg3 supports using Postgres's server-side sql parser, and is able to work with multiple result sets.  (And can asynchronously retrieve results too!) The server-side sql parsing and multi-resultset handling eliminates a whole lot of annoyance.  Thank you!  These two features go hand-in-hand with being able to supply non-literal sql strings, because the only use cases I can see for all of these is when arbitrary sql is received from a known-trusted external source.  I'd be happy to work on the documentation with you to make this relationship clear.

**Comment by dvarrazzo** [comment]
> Although not presently enforced, psycopg3 does not allow execution of sql supplied as a (non-literal) string. This means that I cannot write psycopg2 applications that get sql from a user to execute.

That will never be enforced: it is only a type hint. You will have linters complaining, and you will be able to work around with a `cast(LiteralString, sql)`.

**Comment by kpinc** [comment]
On Thu, 26 Jan 2023 17:41:21 -0800
Daniele Varrazzo ***@***.***> wrote:

> > Although not presently enforced, psycopg3 does not allow execution
> > of sql supplied as a (non-literal) string. This means that I cannot
> > write psycopg2 applications that get sql from a user to execute.  
> 
> That will never be enforced: it is only a type hint. You will have
> linters complaining, and you will be able to work around with a
> `cast(LiteralString, sql)`.

Thank you very much for your reply.

If you are interested in a patch to the docs which make
this clear please reply and I'll try to contribute.

Regards,

Karl ***@***.***>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by dvarrazzo** [comment]
Hello Karl

> If you are interested in a patch to the docs which make
> this clear please reply and I'll try to contribute.

Sure! If you opened this ticket, probably the intentions are not clear. Feel free to propose a wording that you think would have worked better for you.

Thank you very much!
