### ISSUE TITLE
Is Psycopg3 module thread safe?

### ISSUE THREAD

**Issue by Scolymus** [psycopg/psycopg#518]
I have read that psycpog2 is _multithreading safe_, but not _multiprocess safe_ (e.g., https://access.crunchydata.com/documentation/psycopg2/2.7.4/usage.html#thread-safety). 

I'm working with Celery and I use a self construct class for SQL managing based on _psycopg2 ThreadedConnectionPool_. Right now I create the object for this class in each process to avoid an error (`psycopg2.OperationalError: SSL error: decryption failed or bad record mac`) but I was wondering if psycopg3 is thread safe or is just like psycopg2 on this behaviour, since I cannot find this in the documentation.

**Comment by dvarrazzo** [comment]
No, the behaviour is the same. You cannot share connections across processes. Linux is not happy.
