### ISSUE TITLE
Connection failed, port 5432 failed

### ISSUE THREAD

**Issue by vkocubinsky** [psycopg/psycopg#519]
After upgrade python from 3.10 to 3.11 I catch  issue with connection. I can't connect to postgresql with psycopg. But everything is good with postgresql and I can connect to postgresql with psql or with psycopg2.  I use postgresql from docker image "image: bitnami/postgresql:14". Client computer is Mac M1. 

```
In [1]: import psycopg2

In [2]: psycopg2.connect("postgresql://dev:1234@myhost:5432/mydb")
Out[2]: <connection object at 0x102467760; dsn: 'user=dev password=xxx dbname=mydb host=myhost port=5432', closed: 0>

In [3]: import psycopg

In [4]: psycopg.connect("postgresql://dev:1234@myhost:5432/mydb")
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
Cell In[4], line 1
----> 1 psycopg.connect("postgresql://dev:1234@myhost:5432/mydb")

File ~/Library/Python/3.11/lib/python/site-packages/psycopg/connection.py:728, in Connection.connect(cls, conninfo, autocommit, prepare_threshold, row_factory, cursor_factory, context, **kwargs)
    723     rv = cls._wait_conn(
    724         cls._connect_gen(conninfo, autocommit=autocommit),
    725         timeout=params["connect_timeout"],
    726     )
    727 except e.Error as ex:
--> 728     raise ex.with_traceback(None)
    730 if row_factory:
    731     rv.row_factory = row_factory

OperationalError: connection failed: :18a0:6af2:b15d:b7c8), port 5432 failed: could not receive data from server: Connection refused
```

Left the same comment in discussion https://github.com/psycopg/psycopg/discussions/270.

**Comment by JelteF** [comment]
Adding my comment from the discussion here too: https://github.com/psycopg/psycopg/discussions/270:

> I can reproduce this issue consistently enough that the SSL tests for pgbouncer never pass on Cirrus CI, which is using an ARM based MacOS runner. An example of a failed run can be found here: [cirrus-ci.com/task/5261931737513984](https://cirrus-ci.com/task/5261931737513984)
>
> It's failing with psycopg, psycopg-c and psycopg-binary in the same way

Mainly because for whoever wants to reproduce and debug this further, it might be easier to do so in Cirrus CI if you don't own a physical Mac M1 machine.

**Comment by dvarrazzo** [comment]
`OperationalError: connection failed: :18a0:6af2:b15d:b7c8), port 5432 failed`

Is your server listening in ipv6?

**Comment by JelteF** [comment]
Hmm my error also seems ipv6 related:
```
psycopg.OperationalError: connection failed: :1), port 10213 failed: could not receive data from server: Connection refused
```

localhost is probably mapped to ipv6 loopack (`:1`) on M1 for some reason.

**Comment by dvarrazzo** [comment]
I've seen it happening other time because of the way it is defined in `/etc/hosts`.

**Comment by vkocubinsky** [comment]
That is interesting. I can't connect to PostgreSQL with `psycopg3`. But I am able to connect to PostgreSQL with `psycopg2` and with `psql`(it is a client for PostgreSQL). So it is hard to say is it a problem of `psycopg3` or is it network configuration problem. From my point of view if I just select `psycopg2` or `psql` my configuration is good. 

My network configuration is computer A which is Mac, with docker(colima) and postgresql in docker with image  "bitnami/postgresql:14" with default network configuration. Docker expose port 5432. I can reproduce issue only from other computer, let say B, which is either Intel Mac or M1 mac. So need to more than 1 computer to reproduce.

**Comment by dvarrazzo** [comment]
> PostgreSQL with psycopg3. But I am able to connect to PostgreSQL with psycopg2 and with psql(it is a client for PostgreSQL).

With *exactly* the same connection string? Or referring to the host in different ways (e.g. localhost vs. ip)?

**Comment by JelteF** [comment]
For my reproducing case it's using the exact same connection string: localhost for both `psycopg3` and `psql`. But with `psql` connection succeeds. 

How's psycopg3 doing the hostname resolution. Does it do it itself, or pass it off to libpq? Because libpq has logic to try the next IP address that a hostname resolves to if the first one failed (see `try_next_addr = true` cases in libpq, e.g. https://github.com/postgres/postgres/blob/b6a0d469cae4410a05b5e109748278065a931b68/src/interfaces/libpq/fe-connect.c#L2502-L2513)

**Comment by vkocubinsky** [comment]
Connection string is exactly the same for psycopg2 and psycopg3 here is success `psycopg2` connection
 
```
In [1]: import psycopg2

In [2]: psycopg2.connect("postgresql://dev_ps:1234@valery2017.local:5432/cmpdb")
Out[2]: <connection object at 0x1025f3610; dsn: 'user=dev_ps password=xxx dbname=cmpdb host=valery2017.local port=5432', closed: 0>
```

and here is `psycopg3` failed connection 
```
In [1]: import psycopg

In [2]: psycopg.connect("postgresql://dev_ps:1234@valery2017.local:5432/cmpdb")
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
Cell In[2], line 1
----> 1 psycopg.connect("postgresql://dev_ps:1234@valery2017.local:5432/cmpdb")

File ~/Library/Python/3.11/lib/python/site-packages/psycopg/connection.py:728, in Connection.connect(cls, conninfo, autocommit, prepare_threshold, row_factory, cursor_factory, context, **kwargs)
    723     rv = cls._wait_conn(
    724         cls._connect_gen(conninfo, autocommit=autocommit),
    725         timeout=params["connect_timeout"],
    726     )
    727 except e.Error as ex:
--> 728     raise ex.with_traceback(None)
    730 if row_factory:
    731     rv.row_factory = row_factory

OperationalError: connection failed: :18a0:6af2:b15d:b7c8), port 5432 failed: could not receive data from server: Connection refused
```

it is latest 3.1.8 Psycopg

**Comment by vkocubinsky** [comment]
I guess @JelteF is right, I tried to use ip addressed instead of name and now I am able to connect with psycopg3

```
psycopg.connect("postgresql://dev_ps:1234@192.168.1.73:5432/cmpdb")
<psycopg.Connection [IDLE] (host=192.168.1.73 user=dev_ps database=cmpdb) at 0x105ec9a10>
```
```

**Comment by dvarrazzo** [comment]
Do you connect from the same hosts? What does `ping valery2017.local` say?

Which packages did you install: the binary version or from source (would be good to get the name of the packages that pip installed). Is it an entry in `/etc/hosts`?

**Comment by dvarrazzo** [comment]
The remote computer you use resolves the name on ipv6. I've had hours of fun with a public-facing website not being reachable on https by macOS's because of a missing ipv6 listen in nginx configuration.
