### ISSUE TITLE
no version goit tags

### ISSUE THREAD

**Issue by kloczek** [psycopg/psycopg#52]
According to https://pypi.org/project/psycopg2-binary/ latest version is 2.8.6 however there is no here any verion tags.
Is it possible to add at least last version tag and keep adding those tags on each new release?

**Comment by dlax** [comment]
psycopg2 code lives at https://github.com/psycopg/psycopg2; there is a [2_8_6](https://github.com/psycopg/psycopg2/releases/tag/2_8_6) tag over there.
This repo, here, is about psycopg*3*.
