### ISSUE TITLE
Incomplete error-message in traceback

### ISSUE THREAD

**Issue by exhuma** [psycopg/psycopg#521]
I am in the process of migrating from psycopg2 to psycopg3 and ran into this error-message in my unit-tests:

```
E   sqlalchemy.exc.DataError: (psycopg.DataError) timestamp too small (before year 1): {s!r}
E   (Background on this error at: https://sqlalche.me/e/20/9h9h)
```

Somewhere in my test-seeds I seem to have an incorrect timestamp that passed in psycopg2. Unfortunately, the error message  is not detailed enough as it only shows `{s!r}` as offending value. My guess is that there is a leading `f` missing somewhere when the error-message is generated.

I was unable to run a debugger as the culprit is in `transform.pyx` which is not working well in the debugger.

Manually digging through the seeded data is cumbersome and error-prone. It would be good to have a more detailed error-message here. At least with a working display of the offending value.

**Comment by exhuma** [comment]
nb: according to my traceback, the error-message originates [here](https://github.com/psycopg/psycopg/blob/8ca1d4ef95264b32c069eb81ee5f68f1d0c16587/psycopg_c/psycopg_c/_psycopg/transform.pyx#L464)

**Comment by dvarrazzo** [comment]
You are right: the problem is here:

https://github.com/psycopg/psycopg/blob/8ca1d4ef95264b32c069eb81ee5f68f1d0c16587/psycopg_c/psycopg_c/types/datetime.pyx#L1076

Thank you for the report :)

**Comment by exhuma** [comment]
Found the culprit. Some entries have infinity dates which led me to this: https://www.psycopg.org/psycopg3/docs/advanced/adapt.html#example-handling-infinity-date

Unfortunately this customisation happens on the cursor level and I'm using SQLAlchemy so I generally don't see the cursor. I did not find how to configure dumpers/loaders for SQLAlchemy on either the SA docs, nor the psycopg docs. Any idea how that can be done?

**Comment by dvarrazzo** [comment]
I'm sorry, no. You will have to hear from SA people.

**Comment by dvarrazzo** [comment]
If you can change the query, you could use `max(my_date, '0001-01-01'::date)` to return that value in a range accepted by Python.

**Comment by exhuma** [comment]
Thank you for taking the time to reply even if it was off-topic. I will see what I can do.
