### ISSUE TITLE
Connection params inconsistent with pool params

### ISSUE THREAD

**Issue by comodore31** [psycopg/psycopg#542]
```
# This ok
from psycopg import connect
with connect(conninfo='<url>', user='postgres', password='postgres', connect_timeout=7200, autocommit=True) as con:
    print(con.execute('select 1 a').fetchall())

# This is not ok
from psycopg_pool import ConnectionPool
pool = ConnectionPool(conninfo='<url>', user='postgres', password='postgres', connect_timeout=7200, autocommit=True)
with pool.connection(connect_timeout=7200, autocommit=True) as con:
    con.autocommit=False
    print(con.execute('select 1 a').fetchall())
```

For the ConnectionPool we get error:
TypeError: ConnectionPool.__init__() got an unexpected keyword argument 'user'

Could it be possible to have a consistent way to connect?

**Comment by dlax** [comment]
```python
pool = ConnectionPool(conninfo='<url>', kwargs=dict(user='postgres', password='postgres', connect_timeout=7200, autocommit=True))
```
is the way to pass keyword arguments to the connect operation from a connection pool, see https://www.psycopg.org/psycopg3/docs/api/pool.html.

**Comment by comodore31** [comment]
Ok but why this way to pass keyword is not the same than psycopg.connect ?

**Comment by dlax** [comment]
See this discussion https://github.com/psycopg/psycopg/discussions/237 and maybe others.

**Comment by dvarrazzo** [comment]
The reason why that doesn't work is that the connection keywords is an open set and collisions with the pool keywords are possible, see discussions.

You can:

```python
conninfo = "url"
kwargs = {"user": "foo"}

psycopgg.connect(conninfo, **kwargs)
PsycopgPool(conninfo, kwargs=kwargs)
```

but this still leaves out the initialization that can happen in the pool configure callback.

In order to write code that works in a similar way with or without pool you can use [the `NullConnectionPool`](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#null-connection-pools). It exists exactly for this reason.

**Comment by Mr-Pekka** [comment]
Would it be possible to add autocomit and row_factory argument to the pool.connection() method? when we want to overwrite the pool configuration?
this to avoid:
with pool.connection() as conn:
  conn.autocimut = False  # avoid this line
  conn.row_factory = class.... # avoid this line
  con.execute(...)
new code:
with pool.connection(autocimit=False, row_factory=...) as conn:
   conn.execute(..)


Thanks

**Comment by dlax** [comment]
`row_factory` is being added in #540

**Comment by dvarrazzo** [comment]
> Would it be possible to add autocomit and row_factory argument to the pool.connection() method?

This is a different issue. We can discuss about that, but not in a closed ticket regarding the pool constructor vs. the connection constructor.

Note that I'm not 100% sure that if you change connection configuration such as autocommit or row_factory, if the connection is correctly reset on putconn.
