### ISSUE TITLE
AsyncConnection leaves queries running on PG server when interrupted with Ctrl+C, or when an async task is canceled & leaves connection unusable

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [psycopg/psycopg#543]
AsyncConnection doesn't seem to work very well if it gets interrupted during a query:

- If the user presses Ctrl+C, the query is not canceled and the _server continues to run it_ after the program exits.
- If the user cancels a coroutine, again the query is not canceled.  One possibility is that the program might be exiting anyway, in which case again the server will continue to run the query after exit.  Alternatively, the program might want to then reuse the connection for something else, at which point it will fail since the connection is still in use.

The following test case demonstrates the problems.  First, create two files.  Adjust the connection information for a PG cluster as appropriate.  The test cases demonstrate the case of running a query `SELECT pg_sleep(15);` to sleep 15 seconds, in four scenarios:

- Normal/traditional synchronous method, and interrupt with SIGINT.
- Same as above but trivially adapted for asyncio. Again interrupt with SIGINT.
- Cancel the query after 3 seconds using asyncio.Task.cancel and then exit the program.
- Cancel the query after 3 seconds using asyncio.Task.cancel, and then try to run another query on the connection.

I am new to asyncio, but I feel like these look like fairly idiomatic / best practice examples of using asyncio.

I am aware of the workaround at https://www.psycopg.org/psycopg3/docs/advanced/async.html#interrupting-async-operations-using-ctrl-c to call `loop.add_signal_handler(signal.SIGINT, conn.cancel)`, however I feel that has a couple of problems:

- I can't figure out how to chain signal handles with `loop.add_signal_handler`.  Any new signal handler stomps on the old one.  And unlike `signal.signal`, it doesn't return the old one for me to chain it myself.  This is a problem since I create multiple connections in my program as it runs that are fairly removed from my `main` function.
- It doesn't say or do anything to help me with proper task cancellation semantics, like in my test cases.  As best I can tell, instead of just calling `Task.cancel`, I have to get my hands on the underlying connection of the task itself, call `AsyncConnection.cancel()` on that, manually suppress the resulting `QueryCanceled` error myself, and then wait for all this before I can try to reuse the connection.

**`cancel_demo.py`**
```python
import sys
import asyncio

import psycopg

# Edit connection information as needed
con_args = {
    "autocommit": True,
    "application_name": "canceldemo",
    "host": "localhost",
    "port": "5432",
    "user": "postgres",
    "dbname": "postgres",
}


def syncmain() -> None:
    with psycopg.Connection.connect(**con_args) as con:
        with con.cursor() as cur:
            print("run query")
            cur.execute("SELECT pg_sleep(15);")
            print("query done")


async def asyncmain() -> None:
    async with await psycopg.AsyncConnection.connect(**con_args) as con:
        async with con.cursor() as cur:
            print("run query")
            await cur.execute("SELECT pg_sleep(15);")
            print("query done")


async def task_cancel() -> None:
    async with asyncio.TaskGroup() as tg:
        main_task = tg.create_task(asyncmain())
        await asyncio.sleep(3)
        main_task.cancel()


async def reuse_con() -> None:
    async with await psycopg.AsyncConnection.connect(**con_args) as con:

        async def some_task() -> None:
            async with con.cursor() as cur:
                print("run query")
                await cur.execute("SELECT pg_sleep(15);")
                print("query done")

        async with asyncio.TaskGroup() as tg:
            main_task = tg.create_task(some_task())
            await asyncio.sleep(3)
            main_task.cancel()
        # try to use the connection again
        await some_task()


print()
print(f"test mode {sys.argv[1]}")
print()
match sys.argv[1]:
    case "sync":
        syncmain()
    case "async":
        asyncio.run(asyncmain())
    case "task_cancel":
        asyncio.run(task_cancel())
    case "reuse_con":
        asyncio.run(reuse_con())
```

**`canceldemo.sh`**

```
#!/bin/bash

set -m

python canceldemo.py sync &
sleep 5
kill -INT %%
wait
sleep 5
psql -U postgres -h localhost -p 5432 postgres -c \
    "SELECT clock_timestamp() - xact_start AS age, query FROM pg_catalog.pg_stat_activity WHERE application_name = 'canceldemo';" | cat

python canceldemo.py async &
sleep 5
kill -INT %%
wait
sleep 5
psql -U postgres -h localhost -p 5432 postgres -c \
    "SELECT clock_timestamp() - xact_start AS age, query FROM pg_catalog.pg_stat_activity WHERE application_name = 'canceldemo';" | cat
sleep 10 # wait for last query to exit before next test

python canceldemo.py task_cancel
sleep 5
psql -U postgres -h localhost -p 5432 postgres -c \
    "SELECT clock_timestamp() - xact_start AS age, query FROM pg_catalog.pg_stat_activity WHERE application_name = 'canceldemo';" | cat

python canceldemo.py reuse_con
sleep 5
psql -U postgres -h localhost -p 5432 postgres -c \
    "SELECT clock_timestamp() - xact_start AS age, query FROM pg_catalog.pg_stat_activity WHERE application_name = 'canceldemo';" | cat
```

And here is the output when I run it:

```
% ./canceldemo.sh

test mode sync

run query
Traceback (most recent call last):
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/canceldemo.py", line 62, in <module>
    syncmain()
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/canceldemo.py", line 21, in syncmain
    cur.execute("SELECT pg_sleep(15);")
  File "/Users/james.johnston/Library/Caches/pypoetry/virtualenvs/ttmigrate-E386TQsv-py3.11/lib/python3.11/site-packages/psycopg/cursor.py", line 719, in execute
    self._conn.wait(
  File "/Users/james.johnston/Library/Caches/pypoetry/virtualenvs/ttmigrate-E386TQsv-py3.11/lib/python3.11/site-packages/psycopg/connection.py", line 957, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "psycopg_binary/_psycopg/waiting.pyx", line 175, in psycopg_binary._psycopg.wait_c
KeyboardInterrupt
[1]+  Interrupt: 2            python canceldemo.py sync
 age | query
-----+-------
(0 rows)
```
As expected, the normal synchronous implementation cancels the statement on Ctrl+C.

But when run with asyncio:

```
test mode async

run query
error ignored in rollback on <psycopg.AsyncConnection [ACTIVE] (host=localhost database=postgres) at 0x1053d0150>: sending query and params failed: another command is already in progress
Traceback (most recent call last):
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/canceldemo.py", line 29, in asyncmain
    await cur.execute("SELECT pg_sleep(15);")
  File "/Users/james.johnston/Library/Caches/pypoetry/virtualenvs/ttmigrate-E386TQsv-py3.11/lib/python3.11/site-packages/psycopg/cursor_async.py", line 90, in execute
    await self._conn.wait(
  File "/Users/james.johnston/Library/Caches/pypoetry/virtualenvs/ttmigrate-E386TQsv-py3.11/lib/python3.11/site-packages/psycopg/connection_async.py", line 349, in wait
    return await waiting.wait_async(gen, self.pgconn.socket)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james.johnston/Library/Caches/pypoetry/virtualenvs/ttmigrate-E386TQsv-py3.11/lib/python3.11/site-packages/psycopg/waiting.py", line 136, in wait_async
    await ev.wait()
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/canceldemo.py", line 64, in <module>
    asyncio.run(asyncmain())
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
[1]+  Interrupt: 2            python canceldemo.py async
       age       |        query
-----------------+----------------------
 00:00:09.971746 | SELECT pg_sleep(15);
(1 row)
```

Notice that the query is still running on the server, even after the Python process exited!

However, also note _**there is a clue in the stack trace**_ - the `CancelledError` error type actually thrown which is in the stack trace of `wait_async`, which hints at a possible solution?

Now it continues to cancel a task:

```
test mode task_cancel

run query
error ignored in rollback on <psycopg.AsyncConnection [ACTIVE] (host=localhost database=postgres) at 0x10764df50>: sending query and params failed: another command is already in progress
       age       |        query
-----------------+----------------------
 00:00:08.183682 | SELECT pg_sleep(15);
(1 row)
```

Here, the connection wasn't able to be exited properly when leaving the "async with" block: see the "another command is already in progress" error.  And again, the process has abandoned a query to continue running.

Next, we try to reuse the connection after it was canceled.

```

test mode reuse_con

run query
run query
error ignored in rollback on <psycopg.AsyncConnection [ACTIVE] (host=localhost database=postgres) at 0x106695e90>: sending query and params failed: another command is already in progress
another command is already in progress
Traceback (most recent call last):
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/canceldemo.py", line 68, in <module>
    asyncio.run(reuse_con())
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/canceldemo.py", line 54, in reuse_con
    await some_task()
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/canceldemo.py", line 46, in some_task
    await cur.execute("SELECT pg_sleep(15);")
  File "/Users/james.johnston/Library/Caches/pypoetry/virtualenvs/ttmigrate-E386TQsv-py3.11/lib/python3.11/site-packages/psycopg/cursor_async.py", line 94, in execute
    raise ex.with_traceback(None)
psycopg.OperationalError: sending query failed: another command is already in progress
       age       |        query
-----------------+----------------------
 00:00:08.211381 | SELECT pg_sleep(15);
(1 row)
```

Unsurprisingly, it fails since we didn't cancel the query, and then we turn right around and try to run another one while the first one hasn't finished.

In this case, there really ought to be no error at all, because I chose to cancel it: "Once all tasks have finished, if any tasks have failed with an exception other than [asyncio.CancelledError](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError), those exceptions are combined in an [ExceptionGroup](https://docs.python.org/3/library/exceptions.html#ExceptionGroup) or [BaseExceptionGroup](https://docs.python.org/3/library/exceptions.html#BaseExceptionGroup) (as appropriate; see their documentation) which is then raised." -----from https://docs.python.org/3/library/asyncio-task.html#asyncio.TaskGroup

Interestingly enough, if I make a one line change to https://github.com/psycopg/psycopg/blob/090ee7ec81cbf7eab9ab8d982e623d9c468c7b6f/psycopg/psycopg/connection_async.py#L346-L362 and change `KeyboardInterrupt` to `asyncio.CancelledError`, then the program runs more as expected.  All 3 async test cases change their outputs as follows:

- The `async` test mode shows `asyncio.CancelledError` and `KeyboardInterrupt` chained together in the stack trace, and no query is left behind to run on PG.  The former error has a stack trace similar to the normal synchronous stack trace, which seems reasonable enough.
- The `task_cancel` test mode shows the expected result:
```
test mode task_cancel

run query
 age | query
-----+-------
(0 rows)
```
- It's a similar thing with `reuse_con` test mode:
```
test mode reuse_con

run query
run query
query done
 age | query
-----+-------
(0 rows)
```

Is this the right solution, or is there more to it?  Could it be as simple as changing the caught exception to `CancelledError` (maybe leave KeyboardError as well just to catch both just in case)?  I am new to both psycopg3, asyncio, and libpq / PG protocol, as well as not super experienced on the intricacies of signal handling in Python in general, so I'm not sure if there are other edge cases to consider, or if this breaks something else in subtle ways.

**Comment by dvarrazzo** [comment]
Hello! Thank you very much for your in-depth analysis of the problem!

I think that simply adding the CancelError to the exception handler, without removing the KeyboardInterrupt, is a good solution.

I will convert your demo scripts to tests in the unit test. I think that there is already some test already in place, marked as known failure, because I remember that we were able to handle query interruption more easily in the sync path than in the async path.
