### ISSUE TITLE
pypi source tarball does not include tests

### ISSUE THREAD

**Issue by FelixSchwarz** [psycopg/psycopg#546]
It would be nice if the source tarball on pypi would contain everything required to run the test suite. Currently the "tests" folder is missing.

Benefit: The pypi releases are gpg signed (thank you for that!). For Linux distributions having a gpg signature ensures we only use trustworthy sources but of course we also want to run the test suite to ensure the code works on the target platform.

**Comment by dvarrazzo** [comment]
Hello,

it is not customary to include tests in the tarball, and with the current project structure it is not practical (tests are common to both the `psycopg` and `psycopg-c` distribution packages).

It is not expected to distribute tests to the end users. Packaging distributions can obtain the tests from the git repository without exposing the user to any unsigned content.
