### ISSUE TITLE
When to commit transaction: before closing cursor vs before closing connection

### ISSUE THREAD

**Issue by danielkauffman** [psycopg/psycopg#548]
At https://www.psycopg.org/psycopg3/docs/basic/transactions.html the documentation states:

> If the **cursor** is closed with a transaction open, no COMMIT command is sent to the server, which will then discard the connection.

However, my understanding is that transactions are managed at the connection level, and I'm able to create a cursor, execute SQL, close the cursor, and then commit on the connection. Should the documentation here state:

> If the **connection** is closed...

**Comment by dvarrazzo** [comment]
You are right. Fixing it.
