### ISSUE TITLE
Filedescriptor out of range in select() in v3.1.8

### ISSUE THREAD

**Issue by bharadwajyarlagadda** [psycopg/psycopg#552]
This is a duplicate of the issue [532](https://github.com/psycopg/psycopg/issues/532). I already have commented the same under the closed issue. But, I am creating this issue for better visibility/reach as we are facing this issue on critical production systems.

We are facing the issue where it says `filedescriptor out of range in select()`:
```
2023-04-20T13:28:04.417291Z |     1 | 139809410157368 | 1160808107 |    MainProcess-Thread-7729 (job) |                    base:36   | ERROR   | Unable to connect to the database <table_name> due to an unexpected error: filedescriptor out of range in select()
Traceback (most recent call last):
  File "/app/app/database/base.py", line 34, in connect
    yield conn
  File "/app/app/database/orion_job.py", line 24, in _table_exists
    cursor.execute(
  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 719, in execute
    self._conn.wait(
  File "/usr/lib/python3.10/site-packages/psycopg/connection.py", line 957, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/psycopg/waiting.py", line 219, in wait_select
    rl, wl, xl = select.select(
ValueError: filedescriptor out of range in select()
```

Python version being used: 3.10
`psycopg` version: 3.1.8
Here are the dependencies that were installed as part of our docker container:
```
/app # pip freeze
Babel==2.11.0
certifi==2022.12.7
decorator==5.1.1
elasticsearch==7.14.1
elasticsearch-dsl==7.4.1
iso8601==1.1.0
kazoo==2.5.0
marshmallow==3.19.0
numpy==1.23.5
packaging==23.0
pandas==1.1.5
psycopg==3.1.8
py==1.11.0
pykafka==2.8.0
python-dateutil==2.8.2
pytimeparse==1.1.8
pytz==2022.6
retry==0.9.2
schedule==1.1.0
six==1.16.0
tabulate==0.9.0
typing_extensions==4.5.0
urllib3==1.26.13
zulu==2.0.0
```

The operating system for the docker container is:
```
/app # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.2
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

I see that there is a mention of a fix to be released in 3.1.9. Can we know when this version will be released? Currently we are facing this issue on critical production systems.

It would be great if the version 3.1.9 gets released today (or) is there any other way to bypass this?

**Comment by dvarrazzo** [comment]
> This is a duplicate of the issue https://github.com/psycopg/psycopg/issues/532. I already have commented the same under the closed issue. But, I am creating this issue for better visibility/reach as we are facing this issue on critical production systems.

This is not welcome behaviour.
