### ISSUE TITLE
Is it possible to use executemany update by list dictionary with column name ,value, id?

### ISSUE THREAD

**Issue by namaandrupa** [psycopg/psycopg#557]
cur.execute("""
            CREATE TABLE test(
                id serial PRIMARY KEY,
                num integer,
                data text,
                update_time timestamp DEFAULT NOW());
        """)

For example , i have list of dictionany:
list_dict_update = [{id:56,'column':'num','value':222},{id:58,'column':'num','value':1111},{id:58,'column':'data','value':1111}]

how to update like this with the same insert, i don't know how to do.
         cur.executemany(
             SQL("UPDATE {} SET **{%(column)s}**=%(value)s, id=%(data)s where id=%(id)s;").format(Identifier(table)),list_dict_update)

Do you have any ideas to solve this .

**Comment by dvarrazzo** [comment]
Untested:

```python
cur.executemany(
    """
    UPDATE test
    SET num = %(num)s, data = %(data)s
    WHERE id = %(id)s
    """,
    list_dict_update)
```

or, if you have the table name in a variable:

```python
cur.executemany(
    SQL("""
        UPDATE {}
        SET num = %(num)s, data = %(data)s
        WHERE id = %(id)s
        """).format(Identifier(table)),
    list_dict_update)
```

**Comment by namaandrupa** [comment]
sorry , I mean that: 
update test set num='abc' where id=56; 
update test set data='bdc' where id=58;

i mean that update different column ;

how to use executemany UPDATE in this case:
cur.executemany(SQL("""UPDATE test SET {}=%s where id=%s""").format (....what continue write here  with dict ex [{id:56,num:'abc'},{id:58,data:'bdc'}]

**Comment by namaandrupa** [comment]
thank you so much,

**Comment by namaandrupa** [comment]
it works when i add Identifier(colum):

query = SQL("UPDATE test SET {}=%s where id=%s")
with conn.pipeline():
   for id, column, value in [(56, 'num', 222), (58, 'data', 1111)]:
     conn.execute(query.format(Identifier(column), (value, id))

**Comment by namaandrupa** [comment]
I have one mor question:
value_update2 = [
  {"id": 12,"menu_position": "0","fid": 0,"menu1": "sdfasdf","link": "#", "update_time": ""},
  {"id": 13,"menu_position": "tdh","fid": 0,"menu1": "zxcddfd","link": "#","update_time":""},
]
types = {  "id": "bigint",  "menu_position": "text",  "fid": "integer",  "menu1": "text",  "link": "text",
  "update_time": "timestamp without time zone"
}
cast_fields = [SQL(f"""{k}=NULLIF(%({k})s::text,'')::{v.split(' ')[0]}""") for k,v in types.items()]

with psycopg.connect(DNS, row_factory=dict_row) as conn:
    query = Composed([SQL("UPDATE ttvx_schema.admin_first_menu SET "), SQL(", ").join(cast_fields), SQL(" where id=%(id)s")])
    with conn.cursor() as cur:
        cur.executemany(query, value_update2)
    conn.commit()
    
If safety to use code above ?
