### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#562]
For some times, documentation links have been broken. At the time of writing, [this](https://www.psycopg.org/psycopg3/docs/api/objects.html#psycopg.ConnectionInfo.encoding) reads like:

> The value returned is always normalized to the Python _codec ~codecs.CodecInfo.name_:

instead of being `name` with a link to the object in the python docs.

What's going on there?

**Comment by dlax** [comment]
Isn't this supposed to work with a `py:attr:` prefix in the reference for intersphinx? Or is there some magic options resolving this under the hood?

**Comment by dvarrazzo** [comment]
The default interpreted text role is set to object, which should dispatch to the most reasonable target.

https://github.com/psycopg/psycopg/blob/4d0337afd5b9992ed3d5caa3f33f7ec1a6d1670d/docs/conf.py#L96C16-L97

**Comment by dlax** [comment]
sphinx-autodoc-typehints may be posing problem; when I remove it from the `extensions` list in `conf.py`; the link gets back as expected.

**Comment by dvarrazzo** [comment]
I have disabled the extension and now links look better. I haven't checked the quality of the docs, but now at least the basics are working again.
