### ISSUE TITLE
InvalidSqlStatementName: prepared statement "_pg3_xxx" does not exist

### ISSUE THREAD

**Issue by rokclimb15** [psycopg/psycopg#563]
I'm using the following code with `3.1.9` with Aurora Postgres 14 and no proxy. It works for 10-15 iterations, then emits the error continuously. Is it possible that `executemany` doesn't track and close prepared statements correctly?

```
import psycopg

db = psycopg.connect(host=self.host, user=self.user, password=self.password, dbname=self.database,
                                     connect_timeout=5, autocommit=True, prepare_threshold=0)
                                     
with db.cursor() as cursor:
    cursor.executemany("INSERT INTO table VALUES (...) ON CONFLICT DO UPDATE SET ...", big_list_of_rows)
```

**Comment by dvarrazzo** [comment]
I don't know about Aurora. Does it work with `prepare_threshold=None`?

**Comment by rokclimb15** [comment]
It does work with that setting, but performance isn't what I need since it doesn't prepare statements. Glad to help set up any tests to determine the problem and contribute a fix if possible.

**Comment by dvarrazzo** [comment]
> It does work with that setting, but performance isn't what I need since it doesn't prepare statements

Did you compare the performances? Can you give a measure of the speedup of using vs. not using prepared statements in executemany (which should be running in pipeline mode)? Did you compare it with a solution based on COPY+UPSERT?

> Glad to help set up any tests to determine the problem and contribute a fix if possible.

I'm not so glad to work for free to support Amazon, so, Aurora will not receive specific support, unless there is sponsorship for the work.
