### ISSUE TITLE
libpq.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Lifr0m** [psycopg/psycopg#573]
\- couldn't import psycopg 'c' implementation: libpq.so.5: cannot open shared object file: No such file or directory
I encountered this while importing psycopg. Before that psycopg-c has been built with custom pg_config in PATH (I built postgresql from source). Without pg_config in path it doesn't work. I tried to use LD_LIBRARY_PATH added to PATH, but this didn't help.
Debian 11, Ubuntu 22.04. Python 3.10.11. Postgresql 15.3. Latest psycopg version. I installed psycopg-c like psycopg[c] with pip.

**Comment by dlax** [comment]
`export LD_LIBRARY_PATH=$(pg_config --libdir)`

**Comment by Lifr0m** [comment]
I tried in normal ssh connection and all works with only pg_config. The problem was that I was executing pip commands through remote ssh commands.
