### ISSUE TITLE
psycopg[binary] windows kerberos gssapi doesn't work

### ISSUE THREAD

**Issue by kslader8** [psycopg/psycopg#579]
I can't seem to get gssapi to work for connecting like I could in psycopg2. Can you provide some guidance on what I'm doing wrong?

mit kerberos 5

pyproject.toml
```
**[tool.poetry.dependencies]**
gssapi = "^1.8.2"
psycopg = {extras = ["binary"], version = "^3.1.9"}
```

debugging, I can see the option is set correctly:
ConninfoOption(keyword=b'gsslib', envvar=b'PGGSSLIB', compiled=None, val=b'gssapi', label=b'GSS-library', dispchar=b'', dispsize=7)

---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
Cell In[7], line 1
----> 1 psycopg.connect("host=hostname user=username password=ignore port=26100 krbsrvname=posgres gsslib=gssapi dbname=ear")

File [...\.venv\lib\site-packages\psycopg\connection.py:728](file:///...venv/lib/site-packages/psycopg/connection.py:728), in Connection.connect(cls, conninfo, autocommit, prepare_threshold, row_factory, cursor_factory, context, **kwargs)
    723     rv = cls._wait_conn(
    724         cls._connect_gen(conninfo, autocommit=autocommit),
    725         timeout=params["connect_timeout"],
    726     )
    727 except e._NO_TRACEBACK as ex:
--> 728     raise ex.with_traceback(None)
    730 if row_factory:
    731     rv.row_factory = row_factory

OperationalError: connection failed: SSPI continuation error: The specified target is unknown or unreachable
 (80090303)

**Comment by dvarrazzo** [comment]
On which platform?

**Comment by kslader8** [comment]
Windows 10 x64

**Comment by dvarrazzo** [comment]
Are you able to check the difference between the kerberos lib bundled with psycopg 2 and the one bundled with psycopg 3?

**Comment by kslader8** [comment]
this is an issue with the underlying library bundle not working as smoothly in windows. I'm closing this issue
