### ISSUE TITLE
Error message when combining query values and named parameters with Jsonb containing %

### ISSUE THREAD

**Issue by madsruben** [psycopg/psycopg#581]
Hi. I seem to be having an issue executing a query containing both named parameters and query values (%s), where one of the named query parametes is a Jsonb value containing a percentage sign in the json data.
Based on the examples on https://www.psycopg.org/psycopg3/docs/basic/params.html#execute-arguments , I believe this combination is supposed to be supported:
```
cur.execute(    # correct
    SQL("INSERT INTO {} VALUES (%s)").format(Identifier('numbers')),
    (10,))
```
My apologies if I have not understood correctly.

python: 3.9.2
psycopg[binary]: 3.1.9
postgres: 13.9

**table schema:**
```
=> \d static.nodes_hist
                         Table "static.nodes_hist"
     Column     |           Type           | Collation | Nullable | Default
----------------+--------------------------+-----------+----------+---------
 sid            | integer                  |           |          |
 content        | jsonb                    |           |          |
 node_sid       | integer                  |           |          |
Indexes:
    "sid_idx" btree (sid)
```

**preliminary setup:**
```
import psycopg
from psycopg import sql
from psycopg import ClientCursor
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb

conn = psycopg.connect('dbname=db user=usr password=pwd host=localhost', cursor_factory=ClientCursor, row_factory=dict_row)
updateId = 999
```

**failing query:**
```
query = sql.SQL('insert into static.nodes_hist (node_sid, {col}) values (%s, {val})').format(
    col=sql.Identifier('content'),
    val=sql.Literal(Jsonb({'x': 'percentage%'}))
)
conn.cursor().execute(query, (updateId, ))
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrr/mnx/mnx/venv/lib/python3.9/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.ProgrammingError: only '%s', '%b', '%t' are allowed as placeholders, got '%"'
```

**succeeding query, no issues when % is not part of the json:**
```
query = sql.SQL('insert into static.nodes_hist (node_sid, {col}) values (%s, {val})').format(
    col=sql.Identifier('content'),
    val=sql.Literal(Jsonb({'x': 'nopercentage'}))
)
conn.cursor().execute(query, (updateId, ))
```

**also succeeding query, where all the parameters are named parameters and no query values are passed:**
```
query = sql.SQL('insert into static.nodes_hist (node_sid, {col}) values ({updateid}, {val})').format(
    col=sql.Identifier('content'),
    val=sql.Literal(Jsonb({'x': 'percentage%'})),
    updateid=sql.Literal(updateId)
)
conn.cursor().execute(query)
```

I can modify the query to only use named parameters, but I'm wondering if this is a generic bug.

Thank you.

**Comment by dvarrazzo** [comment]
Please read the docs about percentage signs in the query.

**Comment by madsruben** [comment]
> 

Thank you for the quick reply.

I did read about percentage signs in the query, but the value here is from user input, ie. a json object from an API that is being POSTed and contains a regular string. It would then be written to the database. But if the json contains text such as "the annual interest rate is 5%", the query fails.. I'm not sure why we would try to look for identifiers in that part of an sql.Literal. 

Do you maybe have a pointer as to which part of the documentation you're referring to?

**Comment by dlax** [comment]
For user input, you should use query parameters not client-side composition:
~~~python
>>> from psycopg.types.json import Jsonb
>>> conn.execute("select %s", [Jsonb({"msg": "the annual interest rate is 5%"})]).fetchone()
({'msg': 'the annual interest rate is 5%'},)
~~~

**Comment by dvarrazzo** [comment]
You will have to double % signs yourself. I couldn't find a way to do it
without breaking every query for the people who fixed the problem
themselves.

Why are not adding a placeholder to the query dynamically and pass the jsob
as value?

**Comment by madsruben** [comment]
Just to be clear; I can fix it for my query. It's just that with a certain combination of options, you end up in a state where the code is looking for placeholders inside a Jsonb() or an sql.Literal(), which in my opinion should never happen.

```python
conn.execute(sql.SQL("select %s, {somevalue}").format(
    somevalue=Jsonb({"msg": "the annual interest rate is 5%"})
), [Jsonb({"msg": "the annual interest rate is 5%"})]).fetchone()
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrr/mnx/mnx/venv/lib/python3.9/site-packages/psycopg/connection.py", line 879, in execute
    raise ex.with_traceback(None)
psycopg.ProgrammingError: only '%s', '%b', '%t' are allowed as placeholders, got '%"'
```

with %b inside the user provided text string:
```python
conn.execute(sql.SQL("select %s, {somevalue}").format(
    somevalue=Jsonb({"msg": "the annual interest rate is 5%b"})
), [Jsonb({"msg": "the annual interest rate is 5%"})]).fetchone()
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrr/mnx/mnx/venv/lib/python3.9/site-packages/psycopg/connection.py", line 879, in execute
    raise ex.with_traceback(None)
psycopg.ProgrammingError: the query has 2 placeholders but 1 parameters were passed
```
inside an sql.Literal():
```python
conn.execute(sql.SQL("select %s, {somevalue}").format(
    somevalue=Jsonb({"msg": "the annual interest rate is 5%b"})
), [sql.Literal(Jsonb({"msg": "the annual interest rate is 5%"}))]).fetchone()
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrr/mnx/mnx/venv/lib/python3.9/site-packages/psycopg/connection.py", line 879, in execute
    raise ex.with_traceback(None)
psycopg.ProgrammingError: the query has 2 placeholders but 1 parameters were passed
```

**Comment by dvarrazzo** [comment]
The psycopg.sql module functionalities are "client-side composition": the
query you compose behaves like normal queries, and in psycopg % signifies
placeholder, and the original components lose their semantics. There is no
promise that they maintain it.

**Comment by madsruben** [comment]
Thank you for the explanation. A large reason for using psycopg is to be able to safely handle variables from the outside, without having to worry about them being parsed/interpreted as SQL. The way I've understood to escape them safely, is to either pass them as the second argument to .execute(), or to provide them as an sql.Literal() inside the format string.

When such a syntax errors occurs, solely based on a certain piece of text being provided from a user, I have to ask if my assumptions for safe handling are wrong, and whether I have to test all code for any such edge cases to make sure that somehow a percentage, quote, or similar isn't accidentally parsed by sql.SQL. I really don't want to have to worry about that.

Mentally having to always make sure to never combine Jsonb in named parameters at the same time as you have parameters in the second argument to .execute(), does not seem like the appropriate solution.

**Comment by madsruben** [comment]
By the way, please don't get me wrong, I absolutely love psycopg and I think it's an awesome mix of reliability, flexibility and ease-of-use. Please keep up the very good work :-)

I boiled the issue I'm having down to this, and I realize it has nothing to do with Json.
- If you have a query with no parameters passed as the second argument to .execute(), using sql.Literal() works fine:
```python
user_text = 'bobby table%s'

sql.SQL("select {text_obj}").format(text_obj=sql.Literal(user_text))
>>> Composed([SQL('select '), Literal('bobby table%s')])

conn.execute(sql.SQL("select {text_obj}").format(text_obj=sql.Literal(user_text)))
conn.cursor().mogrify(sql.SQL("select {text_obj}").format(text_obj=sql.Literal(user_text)))
"select 'bobby table%s'"
```
- If, for some reason, you run exactly the same query, but you pass a second argument to .execute(), it will not only parse the %s for the second argument you passed, but also try to look for an argument for the %s in the user_text. 
```python
sql.SQL("select {text_obj}, %s").format(text_obj=sql.Literal(user_text))
>>> Composed([SQL('select '), Literal('bobby table%s'), SQL(', %s')])

conn.execute(sql.SQL("select {text_obj}, %s").format(text_obj=sql.Literal(user_text)), ('someval', ))
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrr/mnx/mnx/venv/lib/python3.9/site-packages/psycopg/connection.py", line 879, in execute
    raise ex.with_traceback(None)
psycopg.ProgrammingError: the query has 2 placeholders but 1 parameters were passed
```

My only point is that I think the two cases should be consistent in the handling of the user_text variable, and I think that for anyone combining named parameters and second-argument parameters, this behaviour might not be obvious, and it doesn't show up until someone tries to input a percentage sign in the user_text. 

Thank you again for the attention and understanding.

**Comment by dvarrazzo** [comment]
The problem here is that you are layering two levels of parameters expansion. At the time of the first expansion, we don't know whether there will be the need of a second expansion. If there isn't such need (e.g. you call `cur.execute(composible)`) then a `%` is worth a `%`. If there are parameters (as in `cur.execute(composible, params)`) then the `%` should be escaped as `%%`. Maybe we could add a param to `Composible.as_string()` to tell if expansion needs percent escaping or not, but I am not sure that it would solve the problem or if someone may come with another layer of parameter expansion and make the care useless.

There is correct code that can be written: you have to pass the parameters to execute. You can build a query dynamically, by adding the placeholders you need as you go, and accumulate the parameters in a map to pass, at the end, to `execute()`.
