### ISSUE TITLE
`cursor` as iterable has unexpected behavior ?

### ISSUE THREAD

**Issue by BielStela** [psycopg/psycopg#583]
the problem is 95% my fault that I did:
```python
cursor.execute('SELECT id FROM "material"')  # has some records
for material_id in cursor:
    cursor.execute(insert_query, (material_id))
```
And as you (I bet) already noticed, the `insert_query` will **only** run for the **first** result of  `SELECT id FROM "material"` since the cursor is reused and, I guess, the results set wiped, changing the contents of cursor in the middle of the iteration. 

On the other hand, if I use `cursor.fetchall()` the results are "cristalized" into a list that stays intact during the whole iteration. 

I realize that this this maybe lands more in the realm of python iterator vs list behavior but maybe pointing that `fetchall()` and plain `cursor` have different behaviors in the documentation could save some headaches?

pd: Thank you all for the amazing work here!

**Comment by dvarrazzo** [comment]
`fetchall()` is declared returning a list. Iterating an object and changing it inplace has unexpected behaviour with builtin objects too. I don't really think that we should add anything that is psycopg specific: it's just Python common sense.
