### ISSUE TITLE
psycopg_pool does not check connection lifetime before giving a connection to a calling code

### ISSUE THREAD

**Issue by Tiendil** [psycopg/psycopg#584]
How to reproduce:

- Configure `idle_session_timeout` in PostgreSQL, `max_lifetime` & `min_size` in psycopg_pool, `max_lifetime < idle_session_timeout`, `min_size=2`.
- Wait for an `idle_session_timeout` seconds doing nothing.
- Try to get a connection from the pool and execute an SQL query.

Result:

- `psycopg.OperationalError: consuming input failed: server closed the connection unexpectedly`

Expected result:

- Pool detects that existing connections lifetime is expired and requests a new connection(s) from the DB.
- => SQL query executed succesfully.

Temporary solution:

- Periodically execute the `check` method.

Potential cause of the problem:

- Database closes a connection, but psycopg_pool does not close it => next SQL query fails because the connection is closed by the DB.
- psycopg_pool checks connection `_expire_at` attribute only [when connection is returned to pool](https://github.com/psycopg/psycopg/blob/f09eb30f6f7bcf702fb4e42a1a9349f9a9d34b01/psycopg_pool/psycopg_pool/pool_async.py#L533), but not before give it to a code.
- No queries —> no connections returned to a pool —> no connections checked for a lifetime.

Such behaviour complicates the development and life of not-so-popular projects in production. Also, it is not obvious for new developers.

Is it by design, or is it a bug?

**Comment by Tiendil** [comment]
Thanks for the fast answer!

And sorry for the wrong bug report.

**Comment by dvarrazzo** [comment]
No worreis, it's not the first time someone expects that `idle_session_timeout` is kept in consideration by the pool. I think it does need a suggestion in the docs about how to disable it.

**Comment by dvarrazzo** [comment]
Added docs here: https://www.psycopg.org/psycopg3/docs/advanced/pool.html#pool-and-idle-session-timeout-setting
