### ISSUE TITLE
Behavior of connection pool connections vs regular connections with context managers

### ISSUE THREAD

**Issue by Styrke** [psycopg/psycopg#592]
According to the documentation about [Using connections from the pool](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#using-connections-from-the-pool):

> The `connection()` context behaves like the [`Connection`](https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection) object context

and then continues
> At the end of the block the connection is returned to the pool [...]

but the documentation for the referenced Connection class states that
> Connections behave as context managers: on block exit, the current transaction will be committed (or rolled back, in case of exception) and the connection will be closed.

So will the connection be closed or not when the context block ends?

I assume that this confusion is caused by a change in behavior from psycopg2, but it would be nice to have confirmation.

This is also an opportunity to improve the already excellent documentation.

**Comment by dvarrazzo** [comment]
On Wed, 5 Jul 2023, 19:10 Jonas Meinertz Hansen, ***@***.***>
wrote:

> I assume that this confusion is caused by a change in behavior from
> psycopg2, but it would be nice to have confirmation.
>
Yes, that's correct. The difference in the behaviour of the connection
compared to psycopg2 is documented [here](
https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#with-connection).

>
