### ISSUE TITLE
Incorrect Year Calculation in psycopg

### ISSUE THREAD

**Issue by david-shiko** [psycopg/psycopg#594]
Summary:
When using psycopg to execute SQL queries, the calculation of the birthdate year seems to be incorrect. The year is always calculated as the current year minus the fifth argument provided, instead of calculating it based on the actual value of the 'YEAR' argument.

Steps to Reproduce:

Execute an INSERT statement to the users table with the birthdate field calculated as CURRENT_DATE - INTERVAL '%s YEAR'.
Select the inserted data and compare the birthdate year with the expected year.
Expected Behavior:
The birthdate field should reflect a date 20 years prior to the current date.

Actual Behavior:
The birthdate field reflects a date 5 years prior to the current date.

Possible Cause:
It appears psycopg is considering the position of the argument ($5) rather than the actual value (current year - value). Changing the order of birthdate supplying alters the result.

Relevant Code:
```
create_user = (
    'INSERT INTO users (tg_user_id, fullname, goal, gender, birthdate, country, city, comment) '
    "VALUES (%s, %s, %s, %s, CURRENT_DATE - INTERVAL '%s YEAR', %s, %s, %s)"
)
params = (1, 'Test User', 1, 1, 20, 'USA', 'San Francisco', 'Hello, world!',)
cursor.execute(create_user, params)
cursor.execute('SELECT fullname, goal, gender, birthdate, country, city, comment FROM users')
result = cursor.fetchall()
expected_result  = [{'fullname': 'Test User', 'goal': 1, 'gender': 1, 'birthdate': datetime.date(2003, 7, 6), 'country': 'USA', 'city': 'San Francisco', 'comment': 'Hello, world!'}]
actual_result = [{'fullname': 'Test User', 'goal': 1, 'gender': 1, 'birthdate': datetime.date(2018, 7, 6), 'country': 'USA', 'city': 'San Francisco', 'comment': 'Hello, world!'}]
```
Environment:
```
PostgreSQL version: 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
psycopg version: 3.1.9
psycopg-binary version: 3.1.9
psycopg2-binary version: 2.9.6
Python version: [Your Python version]
```
This issue is occurring [during testing/in production/etc]. In pure psql and with the use of psycopg2, the behavior is as expected.

**Comment by dlax** [comment]
That's probably due to [server-side binding](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#server-side-binding), which is different from psycopg2. If you execute the query doing the interpolation client-side, it should work as "expected":
```python
from psycopg import sql
conn.execute(sql.SQL("INSERT INTO d VALUES (CURRENT_DATE - INTERVAL '{} YEAR')").format(12))
```
```
$ psql -c 'table d;'
        date         
---------------------
 2011-07-07 00:00:00
(1 row)
```

**Comment by david-shiko** [comment]
>
So, do you mean that this is normal behavior? And are you suggesting the use of `from psycopg import sql` and string formatting for such queries, rather than using parameterized parameters (`%s`)?

**Comment by dlax** [comment]
> So, do you mean that this is normal behavior?

No, that's not what I mean. I was just pointing to a difference with 
psycopg2 which might explain this.

**Comment by dlax** [comment]
On the other hand, the date operation in the query can be written as:
```python
>>> from datetime import timedelta
>>> import psycopg
>>> conn = psycopg.connect()
>>> conn.execute("SELECT CURRENT_DATE - %s", (timedelta(days=5 * 365),)).fetchone()
(datetime.datetime(2018, 7, 8, 0, 0),)
```

**Comment by dvarrazzo** [comment]
On Thu, 6 Jul 2023, 22:02 David, ***@***.***> wrote:

> Steps to Reproduce:
>
> Execute an INSERT statement to the users table with the birthdate field
> calculated as CURRENT_DATE - INTERVAL '%s YEAR'.
>

You are sticking a placeholder into quotes. Of course, as a result, the
placholder will be interpreted as a literal. $5 should arguably raise a
parsing error; if it doesn't it's up to the database, which decided to
ignore unexpected chars.

You can use `current_date - %s * '1 year'::interval` as something that
works more along the grain of the type system.

**Comment by dvarrazzo** [comment]
Closing as working as expected.
