### ISSUE TITLE
Can we use `:variable` placeholder notation instead of `%(variable)s`?

### ISSUE THREAD

**Issue by rnarkk** [psycopg/psycopg#595]
We use `:variable` notation to develop APIs and wish to use that notation when pass parameters to `execute` method, instead of replacing them with `%(variable)s`.

**Comment by dvarrazzo** [comment]
On Sat, 8 Jul 2023, 15:34 Rin Arakaki, ***@***.***> wrote:

> We use :variable notation to develop APIs and wish to use that notation
> when pass parameters to execute method, instead of replacing them with
> %(variable)s.
>
We don't support the `:` style placeholders and we are not planning to do
so.

My suggestion is that you look at the implementation of the Cursor class
and that you create your own subclass parsing the query with the rules you
set up.

See the work that is being prepared in
https://github.com/psycopg/psycopg/pull/560 (soon to be merged) to provide
a different query transformation (in that case no-op, but the principle
discussed there would be similar).

>
