### ISSUE TITLE
connection string for psycopg-pool 

### ISSUE THREAD

**Issue by weidezhang** [psycopg/psycopg#597]
hi,

i'm using psycopg[pool] package. I'm wondering what connection string i should provide. I am using a db vendor which provided pool connection string using pgbouncer vs non-pooled connection string.  And they have the flexbility to choose the amount of connections between pooled and non-pooled connection. 

So I'm wonder for psycopg-pool to be usable, shall I disable pgbouncer pooled connection from db vendor side ? Or I can use both altogether ? 

Thanks for the clarification.

**Comment by dvarrazzo** [comment]
On Mon, 10 Jul 2023, 12:14 Weide Zhang, ***@***.***> wrote:

> So I'm wonder for psycopg-pool to be usable, shall I disable pgbouncer
> pooled connection from db vendor side ? Or I can use both altogether ?
>

Probably it's better not using pgbouncer together with the pool, and using
the direct connection.

>
