### ISSUE TITLE
best way to use data in where in clause

### ISSUE THREAD

**Issue by YuriFontella** [psycopg/psycopg#598]
if someone can help me with something that i believe is not a serious problem

I have the code:

```
ids = [10,100,1000]
ids_in = tuple(ids)
query = 'select * from table where id in (%(ids_in)s)'
db.execute(query, { 'ids_in': ids_in })
```

but the query is being executed like this:
`select * from table where id in ('10,100,1000')`
the values are going as a single string with quotes

I'm using the row_factory dict_row in the connection and I need to use a dict as a parameter in the execute

thanks

**Comment by dvarrazzo** [comment]
See docs at
https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#you-cannot-use-in-s-with-a-tuple

**Comment by YuriFontella** [comment]
thanks for your help @dvarrazzo
