### ISSUE TITLE
do multiple executemany use pipeline mode together?

### ISSUE THREAD

**Issue by crashbandicode** [psycopg/psycopg#605]
The documentation states:
> Starting from Psycopg 3.1, [executemany()](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.executemany) makes use internally of the pipeline mode; as a consequence there is no need to handle a pipeline block just to call executemany() once.

If I have a call like 

```
with self.pool.connection() as conn:
            with conn.cursor() as cursor:
                cursor.executemany(query=insert_query1,
                                   params_seq=iter_rows,
                                   returning=False)
                 cursor.executemany(query=insert_query2,
                                   params_seq=iter_rows,
                                   returning=False)
                                   ...
```
Are all of the executemany's being pipelined or would this be a situation where I want to explicitly do a ` with conn.pipeline() as p, conn.cursor() as cur:...`

**Comment by dvarrazzo** [comment]
In your example there will be two pipelines executed, and if you use
conn.pipeline() there will be only one. However, iirc, at the end of
executemant there will be a sync point, so the difference might be
irrelevant.

You can run a little experiment yourself using the trace mode (see #314 for
an example) and verify the difference between the two ways to call
executemany.

**Comment by crashbandicode** [comment]
Ah I see. Okay. Thank you. We can close.
