### ISSUE TITLE
Embedded libz.so.1 missing

### ISSUE THREAD

**Issue by bkabrda** [psycopg/psycopg#615]
Hi :wave: I noticed that that [psycopg-binary 3.1.9](https://files.pythonhosted.org/packages/41/41/b7882d63442adadd832000d53b715d01c25c752d5b4bfbe795f374db519f/psycopg_binary-3.1.9-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) contains file `psycopg_binary.libs/libcrypto-e8aec44f.so.1.1` which depends on `libz.so.1`. AIUI the [manylinux2014 format](https://peps.python.org/pep-0599/#the-manylinux2014-policy) doesn't allow depending on system libz. This seems to have been removed sometime in between now and the 2.8.6 release which correctly included embedded libz (but this was also releasing under `manylinux1`, not `manylinux2014`).

Could you please re-add the embedded `libz` to fix compliance with the `manylinux2014` format? Thanks!

**Comment by henryiii** [comment]
Those PEPs are not updated, they are historical documents. See PEP 600.

For this issue, see https://github.com/pypa/auditwheel/pull/334#issuecomment-1065861650 :

> > According to the manylinux policies, libz.so.1 should not be whitelisted.
> 
> You're probably talking about the previous [PEP 513](https://peps.python.org/pep-0513), [PEP 571](https://peps.python.org/pep-0571) & [PEP 599](https://peps.python.org/pep-0599). Those 3 PEP have been superseded by the much more generic [PEP 600](https://peps.python.org/pep-0600) which does not list allowed / disallowed libraries & which states:
> 
> > `manylinux_${GLIBCMAJOR}_${GLIBCMINOR}_${ARCH}`
> > This tag is a promise: the wheel’s creator promises that the wheel will work on any mainstream Linux distro that uses glibc version `${GLIBCMAJOR}.${GLIBCMINOR}` or later, and where the `${ARCH}` matches the return value from distutils.util.get_platform(). (For more detail about architecture tags, see [PEP 425](https://peps.python.org/pep-0425).)
> 
> `libz.so.1` is available on all mainstream Linux distros & not whitelisting it caused some issues (ranging from "not working" to "security issue" on unmaintained grafted library). `libz.so.1` is also part of the [LSB Core specification](https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/libz.html) which more or less means it should also be available on all Linux distros (i.e. not just the mainstream ones).
> 
> CPython itself relies on zlib for multiple modules (although, if you're using CPython and linking zlib statically, it does not depend on `libz.so.1`).
> 
> Your company should probably update its minimal runtime package with `libz.so.1`.

**Comment by dvarrazzo** [comment]
Thank you for the insider details, @henryiii 

@bkabrda we are just manylinux users. All we can do is to keep the build system up to date and use the latest available versions of manylinux/cibuildwheel on release. If there is an issue that can be fixed by upgrading the build chain components, that's something we can fix. The choice of packages to include is up to the PyPA, who has the most up-to-date knowledge and is probably who you should refer to about the reported issue.
