### ISSUE TITLE
sending query and params failed: number of parameters must be between 0 and 65535

### ISSUE THREAD

**Issue by eliadl** [psycopg/psycopg#620]
Hi, I have a working app using sqlalchemy 2.0 + psycopg2.
When I upgrade psycopg2 to **psycopg 3.1**, something breaks.

When I insert "too many values" (rows/columns) at once, I now get this error.
```
sqlalchemy.exc.OperationalError: (psycopg.OperationalError) sending query and params failed: number of parameters must be between 0 and 65535
```

I'm aware the fault isn't necessarily with psycopg, since sqlalchemy is also mentioned.
But since psycopg is what's been updated, I ask here in case it is.

I encounter this in two instances when using "too many parameters" (many rows and/or columns):
1. with [`DataFrame.to_sql`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html) (pandas 2.x). 
 (can be worked around by setting `chunksize=500` in my case)
2. with [`Insert.on_conflict_do_update`](on_conflict_do_update).
 Here I tried [controlling the batch size](https://docs.sqlalchemy.org/en/20/core/connections.html#insert-many-values-behavior-for-insert-statements) with `insertmanyvalues_page_size=100` but it doesn't seem to have any effect.

Please advise.

**Comment by dvarrazzo** [comment]
You have to send less parameters per query, or you can use a [client-binding cursor](https://www.psycopg.org/psycopg3/docs/advanced/cursors.html#client-side-binding-cursors) (which I don't know to use from sqlalchemy) or you can stick to psycopg2, if you don't have control.

You should get in touch with sqlalchemy regards how to control it to send less parameters or to use different cursor.

**Comment by eliadl** [comment]
Thank you.

If it helps future travelers, I think I've found the issue (or at least part of it).

I was [specifying a fixed VALUES clause for an INSERT statement](https://docs.sqlalchemy.org/en/20/core/dml.html#sqlalchemy.sql.expression.Insert.values), 
while I should have passed these values using the ["normal method"](https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html#orm-bulk-insert-statements).

In other words, I was doing this:

```python
statement = Insert(SomeTable).values(params)
session.execute(statement)
```

instead of this:

```python
statement = Insert(SomeTable)
session.execute(statement, params)
```

---

The [**`Insert.values()`**](https://docs.sqlalchemy.org/en/20/core/dml.html#sqlalchemy.sql.expression.Insert.values) documentation kind of explains it too:

> It is essential to note that **passing multiple values is NOT the same as using traditional executemany() form**. The above syntax is a **special** syntax not typically used. To emit an INSERT statement against multiple rows, the normal method is to pass a multiple values list to the [Connection.execute()](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Connection.execute) method, which is supported by all database backends and is generally more efficient for a very large number of parameters.
