### ISSUE TITLE
How to insert multiple rows with Psycopg?

### ISSUE THREAD

**Issue by gamaleonardo** [psycopg/psycopg#621]
Hello,

In PostgreSQL documentation, we can see that it's possible to insert multiple rows within an INSERT query:

https://www.postgresql.org/docs/current/dml-insert.html#:~:text=You%20can%20insert%20multiple%20rows,%2C%20'Milk'%2C%202.99)%3B

But reading psycopg3 documentation, I couldn't find anything talking about it. Is that possible to do dynamically?
Something like:

```python
values = [(tuple1), (tuple2), (tuple3)]
query = "INSERT INTO table VALUES %s" # I know that it won't work, just to give an example of my thought
cur.execute(query, values)
```

Would you have an idea?
Thank you

**Comment by dvarrazzo** [comment]
Just use [`executemany()`](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.executemany)

```python
values = [(tuple1...), (tuple2...), ...]
query = "INSERT INTO table (field1, field2, ...) VALUES (%s, %s, ...)"  # as many %s as the values in each tuple
cur.executemany(query, values)
```

or use [`copy()`](https://www.psycopg.org/psycopg3/docs/basic/copy.html#writing-data-row-by-row)

```python
with cur.copy("COPY table (field1, field2, ...) FROM STDIN") as copy:
    for record in values:
        copy.write_row(record)
```

**Comment by gamaleonardo** [comment]
Thanks @dvarrazzo!
