### ISSUE TITLE
Is "psycopg[binary]" compatible with Ubuntu-20.04?

### ISSUE THREAD

**Issue by goffioul** [psycopg/psycopg#622]
I'm using django/psycopg on a Ubuntu-20.04 system, with postgresql-12 and libpq5. After upgrading to django-4.2.4, I wanted to try psycopg3 (I've been using psycopg2 so for years, without any problem). I installed the binary package with `pip install "psycopg[binary]"`, which installed version 3.1.10. But I then started to get exceptions thrown in various views, in the middle of the view rendering process, particularly while rendering a related field in form views:
```
NotSupportedError at [snip]/units/new/

server-side cursors not supported in pipeline mode
```
What further caught my attention is the invalid/unexpected PipelineStatus reported in the last entry of the django backtrace (with debug mode enabled):
![Screenshot from 2023-08-11 08-15-10](https://github.com/psycopg/psycopg/assets/1114187/655b83ea-5ada-4c91-97d6-84e2b9b01033)

So I figured there might be some ABI incompatibility between the precompiled binary package and my Ubuntu install. I tried then both pure-python (`psycopg`) and local-install (`psycopg[c]`), and they both work fine.

The question is then really: is there a known incompatibility between the binary package and Ubuntu-20.04?

**Comment by dvarrazzo** [comment]
> The question is then really: is there a known incompatibility between the binary package and Ubuntu-20.04?

Considering that the entire psycopg 3 project has been created on Ubuntu 20.04 and 22.04, I'd say no, it's actually the most tested platform.

> server-side cursors not supported in pipeline mode

I think you have to discuss this with the django project. I believe I saw in the past this error but I'm not sure.

**Comment by dvarrazzo** [comment]
I have no idea what line causes that error. Can you reproduce it (with a Python script, not a django project).

**Comment by goffioul** [comment]
FYI, I found the culprit. The psycopg-binary package is indeed binary-incompatible with Ubuntu-20.04.

**Comment by dvarrazzo** [comment]
Probably with some library you added manually?

If you have found some incompatibility, please provide a Dockerfile based on Ubuntu 20.04 reproducing it and we will look into it. Thank you.

**Comment by goffioul** [comment]
It's really nothing fancy: simply use the django app with apache, using a virtualenv (in my case in daemon mode), and enable phppgadmin on the same apache server. You end up with 2 incompatible versions of libpq within the same process.

**Comment by dvarrazzo** [comment]
That "nohing fancy" seems looking for troubles to me. You are using separate virtualenvs into the same process, so you are obtaining separate python and shared C, into which you are running both psycopg 2 and 3.

psycopg-binary is not incompatible with ubuntu: the same setup is a Russian roulette on any supported platform.

**Comment by goffioul** [comment]
I think you misunderstood, there aren't multiple virtualenvs, nor multiple psycopg versions. But you're right that using psycopg-binary is a Russian roulette, the install docs of psycopg2 is more forthcoming in that regard.

**Comment by dvarrazzo** [comment]
Ah, the other libpq comes from php. Which runs in the same process of python. No two virtualenvs, but that doesn't make it more straightforward.

You could have found the same problem on psycopg2-binary: this is not a psycopg-specific problem, but of whatever two systems not designed to run together crammed into the same process by apache+mod_kitchensink instead of kept in separate processes.

Feel free to ignore your own responsibilities and blame others: we are out of the blast radius. :+1:
