### ISSUE TITLE
When calling a postgresql function that returns `setof text`, psycopg return list of tuples

### ISSUE THREAD

**Issue by EdmundsEcho** [psycopg/psycopg#623]
I'm using `psycopg[binary, pool]` v3.1.10 and python 3.11.4.

The postgresql (version 13) function is as follows

```sql
...
returns setof text as $$
    select core.shared_types();
$$ language sql;
```

The underlying source is a `setof text` generated from `pg_type.typname` with a data type described as follows:
```
                       List of data types
   Schema   | Name |                 Description
------------+------+---------------------------------------------
 pg_catalog | name | 63-byte type for storing system identifiers
```

### The type returned by way of psycopg

The cursor `<class 'psycopg.Cursor'>` with records `<class 'tuple'>`.

### Expected

The cursor `<class 'psycopg.Cursor'>` with records `<class 'str'>`.

I'm new to this module so could be wrong in what to expect.  But given the newness of v3, and the unusual (perhaps) type of the source, I thought it might be something worth reviewing.

## Update

This returning of a tuple with `setof` return types is not limited to this underlying type.  I have an `setof My_Composite_Type`; to access the value I need to unwrap it from within a tuple.

**Comment by dvarrazzo** [comment]
What query are you running?

**Comment by EdmundsEcho** [comment]
@dvarrazzo Thank you for the follow-up.  The query is

```py
conn.execute("select shared_types()")
```
...when I iterate through the cursor I get tuples.

Similarly,
```py
def get_levels(cursor, *args) -> psycopg.Cursor:
    """ returns cursor setof Level ... (value, count)"""
    sql = f"select get_levels({_mk_stubs(args)})"
    return cursor.execute(sql, args)

def _mk_stubs(args):
    return ','.join(['%s'] * len(args))
```

Finally, perhaps related to my misunderstanding (?), I had the registered composite types working before adding a registered enum to one of the composite types.  Then I started getting "str" errors when referencing `field.field_idx` and other attributes to the composite type.

**Comment by dvarrazzo** [comment]
Look, I have really no idea about what you are asking. You should put together a self-contained example.

I have created a set returning function as you describe:

```
piro=# create function setoftext() returns setof text as $$
    values ('foo'::text), ('bar'), ('baz');
$$ language sql;
```

amd I can call it from psycopg:

```python
import psycopg
conn = psycopg.connect("")
cur = conn.execute("select setoftext()")
cur.fetchone()
('foo',)
```

this is the expected behaviour: the type is always a tuple, because it's a record with a single field.

If you have a more complex case that you think doesn't work, involving with composite types, enum registration, row factories... please put together a self-contained example.

**Comment by EdmundsEcho** [comment]
Will do.

**Comment by EdmundsEcho** [comment]
Just to close out on the stream (i.e., my "catching-up" and consolidating what I've gathered), once I understood that a record is encoded using a tuple (of the vanilla variety), it all fell into place.  

I use nested composite types as inputs and return values to some of my postgresql functions.  They include a field that is an array of a composite type, and an enum.

### Using composite attributes when loading requires registration
Loading (postgresql -> python): In order to use the named attributes of the composite types requires registering them as outlined in the docs.  Perhaps *surprisingly*, I was not able to "assert" a successful registration of the type without also calling `info.register()` (i.e., not just calling `register_composite(info)`).  Having to register what seemed like twice, was counter-intuitive.

### Dumping nested composite types was straightforward
Dumping (python -> postgresql), was relatively simple.  My ability to "get data into the db" worked as expected instantiating each composite using a tuple (which can be composed/nested accordingly).  This included creating a list of the tuples for my array of composite values. 

### I was unable to use the auto-generated class for registered types to instantiate my input types
I could not find a way to use the `<class 'psycopg.types.composite.my_entry_for_each_composite'>` to instantiate the data needed as input to the postgresql functions.  I could get the job done with my own namedtuples but saw no use given the extra overhead (both performance, and maintenance).

Finally, the only reason to register the `enum` boiled down to:
1. the inference would fail if I forced a binary return format (`binary=true` in the exec call)
2. augment the integrity of the python code base... that said, it might be considered redundant: I'll learn soon enough if the `str` value is wrong when the call to the db fails.  Managing two sources of truth is always a bit of a pain vs benefit of extra typing in a non-static typed python paradigm.

Thank you for v3 of this driver.  Being new to package in general, I'm glad I did not have to concern myself with the wrinkles that come with older versions of python.  The docs were also solid given the relative newness of the major upgrade.

**Comment by dvarrazzo** [comment]
On Sun, 20 Aug 2023, 04:26 Edmund Cape, ***@***.***> wrote:

>  Perhaps *surprisingly*, I was not able to "assert" a successful
> registration of the type without also calling info.register() (i.e., not
> just calling register_composite(info)). Having to register what seemed
> like twice, was counter-intuitive.
>
This is unlikely, as `register_composite()` calls `info.register()`
internally.

https://github.com/psycopg/psycopg/blob/49de89d710cad985ec7b13abc39a160a86cb91a6/psycopg/psycopg/types/composite.py#L297

For other things you found issue with, again, if you present us some code
that seems not working correctly for you, we can look into it.

**Comment by EdmundsEcho** [comment]
> This is unlikely, as `register_composite()` calls `info.register()`
internally.

Given the detailed and spot-on documentation for how to register the composite, And what you have said here, something has to be "off" at my end.  

I tested it again ensuring that I was registering the types with `context=None` to trigger a global scope... and it works as you said it should.  I'll update the earlier post where I must have been using `context=conn`.

This has me recall something in the docs talking about a template connection, or how there is a way to "inherit" properties from one connection to the next.  I'm using the pool api, so may well find something there.  The idea of global scope works, but is less "deliberate".

Thank you again for your help.
