### ISSUE TITLE
Migrating from psycopg2: What to do with NamedTupleCursor?

### ISSUE THREAD

**Issue by seperman** [psycopg/psycopg#625]
Hello,

I'm migrating to psycopg2. The `extras` module does not exist in psycopg3 and I don't see it mentioned in https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html

I don't see `NamedTupleCursor` in the source code either. Please advise on how to move forward. This breaking change should not have been covered in the migration docs?

**Comment by dvarrazzo** [comment]
Hello,

you can use [`namedtuple_row`](https://www.psycopg.org/psycopg3/docs/api/rows.html#psycopg.rows.namedtuple_row) See [Row Factories](https://www.psycopg.org/psycopg3/docs/advanced/rows.html#row-factories) for details.

```python
import psycopg
import psycopg.rows

conn = psycopg.connect("", row_factory=psycopg.rows.namedtuple_row)

conn.execute("select 10 as foo, 20 as bar").fetchone()
Row(foo=10, bar=20)
```

You are right, we should mention it in the migration docs.
