### ISSUE TITLE
Unable to correctly select vector datatype

### ISSUE THREAD

**Issue by frankiedrake** [psycopg/psycopg#629]
I have a table with a column type `vector` which is available in `pgvector` extension. Actually it is an array of floats.
The problem is that when I select this column I get a string type in Python that looks like this:
```
[-0.057490326,0.025269473,-0.015406527,0.044699334,0.21428017,-0.008904852,0.09528428,-0.015780648,0.09894659,0.044970367,0.047535848,-0.05172373...]
```
Is that possible to add some automatic numeric mapping of this type, to avoid pre/post data modification?

**Comment by dvarrazzo** [comment]
Yes, you can write a loader to convert the pgvector format into a list of python floats or anything else is suitable for you application (a numpy array, for instance).

The procedure is roughly:

```python
import psycopg
conn = psycopg.connect("")

class VectorLoader(psycopg.adapt.Loader):
    """Loader to load vector format to Python list of float"""
    def load(self, data):
        return [float(x) for x in data[1:-1].decode().split(",")]

# Query the catalog
vector_info = psycopg.types.TypeInfo.fetch(conn, "vector")
# <TypeInfo: vector (oid: 510468, array oid: 510474)>

# Add the vector type information to the connection
vector_info.register(conn)

# Register the loader on the vector class
conn.adapters.register_loader("vector", VectorLoader)

# Now you can query the vector type
cur = conn.execute("select '[1.1,2.2,3.3]'::vector")
cur.fetchone()[0]
# [1.1, 2.2, 3.3]
```

In a similar way you can write a `VectorDumper` class to convert a Python list to a vector.

Documentation is available in [Data Adaptation Configuration](https://www.psycopg.org/psycopg3/docs/advanced/adapt.html) in the docs and in the [`TypeInfo` class](https://www.psycopg.org/psycopg3/docs/api/types.html#types-information).

**Comment by bjornmp** [comment]
If anyone came here using Python3 and is getting `AttributeError: 'memoryview' object has no attribute 'split'`, just add `.tobytes()` as follows:

Python 2
`return [float(x) for x in data[1:-1].split(b",")]`

Python 3
`return [float(x) for x in data.tobytes()[1:-1].split(b",")]`
