### ISSUE TITLE
IndeterminateDatatype error for None parameter in prepared query

### ISSUE THREAD

**Issue by akrherz** [psycopg/psycopg#640]
This code works in psycopg2
```python
conn = psycopg2.connect("dbname=mydb")
cursor = conn.cursor()

cursor.execute("prepare myplan as insert into test(tt) values ($1)")

cursor.execute("execute myplan(%s)", [None,])
```
but fails with psycopg
```
Traceback (most recent call last):
  File "/tmp/t.py", line 8, in <module>
    cursor.execute("execute myplan(%s)", [None,])
  File "/opt/miniconda3/envs/prod/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.IndeterminateDatatype: could not determine data type of parameter $1
```

what makes me wonder if this is unexpected is that this works
```python
conn = psycopg.connect("dbname=akrherz")
cursor = conn.cursor()

cursor.execute("insert into test(tt) values (%s)", [None,])
```
thanks

**Comment by dvarrazzo** [comment]
This is one of those cases where the types should be specified, as documented in [different cast rules](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#different-cast-rules).

In the case of the [PREPARE statement](https://www.postgresql.org/docs/current/sql-prepare.html) this can be done with a syntax such as `prepare myplan (text) as insert into test(tt) values ($1)`.

However, psycopg 3 provides [prepared statements](https://www.psycopg.org/psycopg3/docs/advanced/prepare.html) at protocol level, which are more efficient than prepared statement at SQL level, so you don't actually need prepare/execute at all.
