### ISSUE TITLE
Age function record data type misinterpreted

### ISSUE THREAD

**Issue by alexhenman** [psycopg/psycopg#643]
There seems to be some peculiarity with the way the result from calling the `age` function is being interpreted. The [postgres documentation](https://www.postgresql.org/docs/current/functions-datetime.html#id-1.5.8.15.6.2.2.1.1.1.1) suggests that an `interval` is returned but it seems something unusual is happening in how this is getting parsed by psycopg.

Minimal steps for replicating are this:

```python
connection = psycopg.connect(...)
cursor = connection.cursor()

# This returns datetime.timedelta(days=6) when it should be 6 months and 6 days
cursor.execute("SELECT age('2020-07-07 00:00:00'::timestamp, '2020-01-01 00:00:00'::timestamp);").fetchone()[0]

# Whereas just subtracting the timestamps results in the right output: datetime.timedelta(days=188)
cursor.execute("SELECT '2020-07-07 00:00:00'::timestamp - '2020-01-01 00:00:00'::timestamp;").fetchone()[0]
```

**Comment by dvarrazzo** [comment]
There seems to be a problem, yes, thank you for the report:

```
>>> conn.execute("select '6 months 6 days'::interval").fetchone()[0]
datetime.timedelta(days=6)
```

**Comment by alexhenman** [comment]
@dvarrazzo thanks for the very speedy fix!

**Comment by dvarrazzo** [comment]
No worries. Will release the fix in a couple of days: waiting to know if
the workaround in #645 works to release it too.
