### ISSUE TITLE
Psycopg3 Async Connection pool leakage/timeout problem

### ISSUE THREAD

**Issue by ucals** [psycopg/psycopg#646]
I have a leakage problem in my Psycopg3 Async Connection pool and I cannot find the source of the problem.

I extended my Flask app such that once the server starts up it creates an Async Connection pool. 

Then, whenever a request is made, the app gets the connections needed to retrieve the data from the database, execute the queries, process the results and return the results for the user.

My implementation works for a while, but after few usages, it stops working. The exception thrown is `psycopg_pool.PoolTimeout`.

When I get the pool stats, I see that `pool_available = 0`, while `requests_queued` and `requests_errors` keep increasing at each new try, indicating that the available connections have exhausted.

Can anyone help me find the source of the problem?

Here's the implementation:

1. The reusable connection pool:
```python
# db.py
import os
from psycopg_pool import AsyncConnectionPool

class DB:
    def __init__(self):
        self.async_pool = None

    def connect_async(self):
        conninfo = (f"dbname={os.environ['DBNAME']} "
                    f"user={os.environ['POSTGRES_USER']} "
                    f"password={os.environ['POSTGRES_PASSWORD']} "
                    f"host={os.environ['POSTGRES_HOST']} "
                    f"port={os.environ['POSTGRES_PORT']}")
        self.async_pool = AsyncConnectionPool(
            conninfo, min_size=4, max_size=10, timeout=15)

    def get_async_pool(self):
        if self.async_pool is None:
            self.connect_async()
        return self.async_pool

# extensions.py
from db import DB

my_db = DB()
```

2. The query execution:
```python
# search.py
from extensions import my_db

async def keyword_search(query):
    async with my_db.get_async_pool().connection() as aconn:
        async with aconn.cursor() as cur:
            # query = ...  keyword search logic
            await cur.execute(query)
            documents = await cur.fetchall()
            column_names = [desc[0] for desc in cur.description]
    return [dict(zip(column_names, doc)) for doc in documents]

async def semantic_search(query):
    async with my_db.get_async_pool().connection() as aconn:
        async with aconn.cursor() as cur:
            # query = ...  semantic search logic
            await cur.execute(query)
            documents = await cur.fetchall()
            column_names = [desc[0] for desc in cur.description]
    return [dict(zip(column_names, doc)) for doc in documents]

async def full_search(query):
    ks, ss = await asyncio.gather(keyword_search(query), semantic_search(query))
    return ks + ss
```

3. The Flask app:
```python
from extensions import my_db
from search import full_search

@bp.route('/search', methods=['GET'])
async def search_fn():
    query = request.args.get('query')
    for _ in range(2):
        try:
            results = await full_search(query)
            return jsonify(results)
        except psycopg_pool.PoolTimeout as e:
            stats = my_db.get_async_pool().get_stats()
            app.logger.error({'error': str(e), 'pool_stats': stats})
            
    return jsonify({'error': 'Database connection timeout'}), 500
```

Other info that might be relevant:
- The only async route in the application is the `search_fn` above; all others are sync.

Thanks in advance!

**Comment by dvarrazzo** [comment]
Do you successfully exit the `connection()` block?

**Comment by ucals** [comment]
I just went through all logs. The blocks:

```python
async with my_db.get_async_pool().connection() as aconn:
        async with aconn.cursor() as cur:
            # query = ...  keyword search logic
            await cur.execute(query)
            documents = await cur.fetchall()
            column_names = [desc[0] for desc in cur.description]
```

never raise any exceptions. So, I assume they are working as intended.

However, I'm logging the result of get_stats() at every API call, and I'm observing the number "pool_available" decreasing every once in a while, until it reaches 0 (and then the system stops working).

**Comment by ucals** [comment]
Just to confirm, the syntax is this, right?

```Python
# With connection pool
async with my_pool.connection() as aconn:
    async with aconn.cursor() as cur:
        await cur.execute(...)
        
# Without connection pool
async with await psycopg.AsyncConnection.connect(conninfo) as aconn:
    async with aconn.cursor() as cur:
        await cur.execute(...)
```
With the connection pool, there's no `await` in the first line, while without the connection pool, there is an `await` keyword.. right?

**Comment by ucals** [comment]
Well, I think I found a solution:
- Downgraded to psycopg2
- Changed the connection pool implementation to ThreadedConnectionPool
- Completely removed the asyncio implementation
- Re-implemented using low-level ThreadPoolExecutor

Something like this:

```python
@contextmanager
def get_cursor():
    con = pool.getconn()
    try:
        yield con.cursor()
        con.commit()
    finally:
        pool.putconn(con)

def keyword_search(query):
    with get_cursor() as cur:
        # query = ...  keyword search logic
        cur.execute(query)
        documents = await cur.fetchall()
        column_names = [desc[0] for desc in cur.description]
    return [dict(zip(column_names, doc)) for doc in documents]

def semantic_search(query):
    with get_cursor() as cur:
        # query = ...  semantic search logic
        cur.execute(query)
        documents = await cur.fetchall()
        column_names = [desc[0] for desc in cur.description]
    return [dict(zip(column_names, doc)) for doc in documents]

def full_search(query):
    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
        ks_future = executor.submit(keyword_search, ...)
        ss_future = executor.submit(semantic_search, ...)
        ks = ks_future.result()
        ss = ss_future.result()
    return ks + ss
```

So far, so good... no more leakages...

**Comment by dvarrazzo** [comment]
This is a bug tracker, not a scrapbook. If you are not interested in solving the original problem we can close it here.

As far as I can see, your query doesn't terminate in time and other requests pile up.

**Comment by dvarrazzo** [comment]
Added docs section about [logging pool operations](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#debugging-pool-usage).  It is useful to figure out what the pool is doing.

**Comment by ucals** [comment]
Hey @dvarrazzo ,
First of all, congrats for the library! Psycopg is great!

I was interested in any solution... and I just posted one here to help anyone who might have the same problems that I had.

Anyway, thanks for the help!
