### ISSUE TITLE
Issue with sslcert with 3.1.11

### ISSUE THREAD

**Issue by ollz272** [psycopg/psycopg#650]
Hi,

We recently upgraded to 3.1.11 (and tried 3.1.12) and we're getting errors with our integration with ddtrace (i will raise an issue there as well)

We have ssl as require, and this is the error we get:
psycopg2.ProgrammingError: invalid dsn: invalid connection option "sslcertmode"

This only happens with the upgrade to 3.1.11 (or 12), so i believe this may be a psycopg issue, but im not sure.

**Comment by dvarrazzo** [comment]
Hello,

As far as I can see, the `sslcertmode` parameter was introduced in [libpq 16](https://www.postgresql.org/docs/16/libpq-connect.html) and is not available in [libpq 15](https://www.postgresql.org/docs/15/libpq-connect.html) or older.

The Psycopg 3.1.11 and 3.1.12 binary packages ship with libpq 16, at least on Linux, so, if you install `psycopg[binary]>=3.1.11` you should have support for the option:

```
(.venv) piro@sherekhan:~/dev/psycopg3/tmp$ pip install "psycopg[binary]>=3.1.11"
Collecting psycopg[binary]>=3.1.11
  Using cached psycopg-3.1.12-py3-none-any.whl (171 kB)
Collecting typing-extensions>=4.1
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting psycopg-binary==3.1.12
  Using cached psycopg_binary-3.1.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Installing collected packages: typing-extensions, psycopg-binary, psycopg
Successfully installed psycopg-3.1.12 psycopg-binary-3.1.12 typing-extensions-4.8.0

(.venv) piro@sherekhan:~/dev/psycopg3/tmp$ python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg
>>> psycopg.pq.__impl__
'binary'
>>> psycopg.pq.__build_version__
160000
>>> psycopg.pq.version()
160000
>>> psycopg.connect("", sslcertmode="disable")
<psycopg.Connection [IDLE] (database=piro) at 0x7f4c43f5f940>
>>> 
```

Conversely, if libpq version is < 16, the option won't be available.

```
>>> import psycopg
>>> psycopg.pq.version()
150003
>>> psycopg.connect("", sslcertmode="disable")
Traceback (most recent call last):
    ...
psycopg.OperationalError: invalid connection option "sslcertmode"
```

On other platforms (macos, windows), Postgres might have not been available at build time, so the binary package should have been bundled with libpq 15.

If you don't use the `[binary]` extra, but use `psycopg[c]` or just the basic `psycopg`, it will use the system libpq, so it's up to you to install at least v16 on your client. You can still check the version used by calling `psycopg.pq.version()`.

What output do you get from the following? What platform are you using?

- `psycopg.pq.__impl__`
- `psycopg.pq.__build_version__`
- `psycopg.pq.version()`

**Comment by ollz272** [comment]
Hi!

Ok, this makes sense, thanks for updating on where the issue originates! I suppose then its not an issue with psycopg, but with ddtrace not supporting libpq16. 

I'm using macos, and it seems to be using v16:
```python
>>> import psycopg
>>> psycopg.pq.__impl__
'binary'
>>> psycopg.pq.__build_version__
160000
>>> psycopg.pq.version()
160000
```
I will raise the issue further with ddtrace.

**Comment by dvarrazzo** [comment]
Looking better at your error report:

> We have ssl as require, and this is the error we get:
> psycopg2.ProgrammingError: invalid dsn: invalid connection option "sslcertmode"

The error is raised by psycopg2 not 3.

Current psycopg2-binary version is bundling libpq 15.3. We are upgrading the packages to bundle libpq 16.0. Note that, if you use psycopg2 non-binary, and your system has libpq 16 installed, `sslmodecert` would work too.

Closing, this side.

**Comment by mark-a-dev** [comment]
I am experiencing this issue trying to run a server with `uvicorn` and we have psycopg 3 installed:
- psycopg = 3.1.12
- psycopg-binary = 3.1.12
- psycopg-pool = 3.1.8
