### ISSUE TITLE
Please document a common Azure PostgreSQL Szenario

### ISSUE THREAD

**Issue by ToTru** [psycopg/psycopg#654]
Asuming I create a connection pool with 5 connections

pool = ConnectionPool(conninfo=pg.get_db_conn('DTCONFIG'), min_size=5, max_size=5, open=True)

And later the Azure PostgreSQL database switches, what will happen if a connection from the pool is requested.

try:
        with pool.connection(timeout=5) as conn:

Will the pool try to re-connect to the database, which is now the standby database, or will it come back with a timeout exception?

**Comment by dvarrazzo** [comment]
Azure databases are not tested: tests are performed with vanilla Postgres. If other database vendors exhibit a different behaviour compatibility is not guaranteed.

Azure is a commercial product: if there is a sponsorship to improve their support we can consider a collaboration.
