### ISSUE TITLE
Psycopg doesn't support multiple hosts in the connection string

### ISSUE THREAD

**Issue by yancyxu** [psycopg/psycopg#674]
I have a PostgreSQL server setup with one primary and two secondary servers. The primary server is responsible for read-write operations, while the secondary servers are read-only. If the primary server goes down, one of the secondary servers will be promoted to primary to continue operations. Currently, I am using psycopg_pool to connect to this PostgreSQL cluster for read-write operations, so it can only connect to the primary database.

The issue I am encountering is as follows:
When connecting to the PostgreSQL cluster using psycopg, if my primary node (192.168.1.11) goes down and one of the remaining secondary nodes (192.168.1.3) is promoted to primary, my program throws an error: psycopg_pool.PoolTimeout: couldn't get a connection after 30.0 sec. The configuration target_session_attrs=read-write doesn’t seem to perform automatic failover by connecting to the next available primary node. Even restarting the program doesn’t help. The issue is resolved only when I change the connection string in my program to:
`pool=psycopg_pool.ConnectionPool(postgresql://postgres:postgres@192.168.1.3:5431,192.168.1.2:5431,192.168.1.1:5431/postgres?target_session_attrs=read-write),`
placing the new primary node at the beginning of the DSN, allowing a successful connection.

My questions are:

1. Does psycopg provide functionality for simple automatic failover?
2. By default, does psycopg only connect to the first IP address in the DSN, disregarding the target_session_attrs=read-write setting?

**Comment by dvarrazzo** [comment]
Hello,

there is nothing that shouldn't work.. except #602 where a similar issue has been reported.

Yesterday I noticed an issue that might be related, so I will investigate further into why `target_session_attrs` seem to cause problems.

**Comment by dvarrazzo** [comment]
Work to solve the problem started in #675

**Comment by dvarrazzo** [comment]
Fixed by #675

**Comment by dvarrazzo** [comment]
Psycopg 3.1.13 released with this bug fixed. Testing is welcome. Cheers!
