### ISSUE TITLE
Test issues with 3.1.13

### ISSUE THREAD

**Issue by mweinelt** [psycopg/psycopg#681]
Hi!

After updating from 3.1.12 to 3.1.13 I see a few tests failing for our package in nixpkgs, and I think they're related to #675.

```
psycopg> ============================= test session starts ==============================
psycopg> platform linux -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0 -- /nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/bin/python3.11
psycopg> cachedir: /build
psycopg> Using --randomly-seed=1210518465
psycopg> default selector: EpollSelector
psycopg> Server version: PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 12.3.0, 64-bit
psycopg> libpq wrapper implementation: c
psycopg> libpq used: 150005
psycopg> libpq compiled: 150005
psycopg> rootdir: /build/source
psycopg> configfile: pyproject.toml
psycopg> testpaths: tests
psycopg> plugins: anyio-4.0.0, randomly-3.13.0
psycopg> collected 4724 items / 78 deselected / 4646 selected       

[...]

psycopg> =========================== short test summary info ============================
psycopg> FAILED tests/test_module.py::test_connect[args3-kwargs3-user=foo] - AssertionError: assert {'user': 'foo', 'host': '/build/run/postgresql'} == ...
psycopg> FAILED tests/test_module.py::test_connect[args0-kwargs0-] - AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> FAILED tests/test_module.py::test_connect[args1-kwargs1-dbname=foo user=bar] - AssertionError: assert {'user': 'bar', 'dbname': 'foo', 'host': '/build/run...
psycopg> FAILED tests/test_module.py::test_connect[args2-kwargs2-port=15432] - AssertionError: assert {'host': '/build/run/postgresql', 'port': '15432'} =...
psycopg> FAILED tests/test_connection.py::test_connect_args[args4-kwargs4-dbname=qux user=joe port=5433] - AssertionError: assert {'user': 'joe', 'dbname': 'qux', 'host': '/build/run...
psycopg> FAILED tests/test_connection.py::test_connect_args[args1-kwargs1-] - AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> FAILED tests/test_connection.py::test_connect_args[args0-kwargs0-] - AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> FAILED tests/test_psycopg_dbapi20.py::test_connect_args[args0-kwargs0-] - AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> FAILED tests/test_psycopg_dbapi20.py::test_connect_args[args1-kwargs1-] - AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> ERROR tests/pq/test_pgresult.py::test_ntuples[3] - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function Ba...
```

<details><summary>Full test log</summary>
<pre>
psycopg> ______________________ ERROR at setup of test_ntuples[3] _______________________
psycopg> 
psycopg> cls = <class '_pytest.runner.CallInfo'>
psycopg> func = <function call_runtest_hook.<locals>.<lambda> at 0x7fff8a543d80>
psycopg> when = 'setup'
psycopg> reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)
psycopg> 
psycopg>     @classmethod
psycopg>     def from_call(
psycopg>         cls,
psycopg>         func: "Callable[[], TResult]",
psycopg>         when: "Literal['collect', 'setup', 'call', 'teardown']",
psycopg>         reraise: Optional[
psycopg>             Union[Type[BaseException], Tuple[Type[BaseException], ...]]
psycopg>         ] = None,
psycopg>     ) -> "CallInfo[TResult]":
psycopg>         """Call func, wrapping the result in a CallInfo.
psycopg>     
psycopg>         :param func:
psycopg>             The function to call. Called without arguments.
psycopg>         :param when:
psycopg>             The phase in which the function is called.
psycopg>         :param reraise:
psycopg>             Exception or exceptions that shall propagate if raised by the
psycopg>             function, instead of being wrapped in the CallInfo.
psycopg>         """
psycopg>         excinfo = None
psycopg>         start = timing.time()
psycopg>         precise_start = timing.perf_counter()
psycopg>         try:
psycopg> >           result: Optional[TResult] = func()
psycopg> 
psycopg> /nix/store/ghh2dgix6cfhwglxab5aar02y4qa73xb-python3.11-pytest-7.4.3/lib/python3.11/site-packages/_pytest/runner.py:341: 
psycopg> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
psycopg> /nix/store/ghh2dgix6cfhwglxab5aar02y4qa73xb-python3.11-pytest-7.4.3/lib/python3.11/site-packages/_pytest/runner.py:262: in <lambda>
psycopg>     lambda: ihook(item=item, **kwds), when=when, reraise=reraise
psycopg> /nix/store/c2ix0mkb3jlb1gpbc96x5q5sczr9cpxg-python3.11-pluggy-1.3.0/lib/python3.11/site-packages/pluggy/_hooks.py:493: in __call__
psycopg>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
psycopg> /nix/store/c2ix0mkb3jlb1gpbc96x5q5sczr9cpxg-python3.11-pluggy-1.3.0/lib/python3.11/site-packages/pluggy/_manager.py:115: in _hookexec
psycopg>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
psycopg> /nix/store/ghh2dgix6cfhwglxab5aar02y4qa73xb-python3.11-pytest-7.4.3/lib/python3.11/site-packages/_pytest/unraisableexception.py:83: in pytest_runtest_setup
psycopg>     yield from unraisable_exception_runtest_hook()
psycopg> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
psycopg> 
psycopg>     def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
psycopg>         with catch_unraisable_exception() as cm:
psycopg>             yield
psycopg>             if cm.unraisable:
psycopg>                 if cm.unraisable.err_msg is not None:
psycopg>                     err_msg = cm.unraisable.err_msg
psycopg>                 else:
psycopg>                     err_msg = "Exception ignored in"
psycopg>                 msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
psycopg>                 msg += "".join(
psycopg>                     traceback.format_exception(
psycopg>                         cm.unraisable.exc_type,
psycopg>                         cm.unraisable.exc_value,
psycopg>                         cm.unraisable.exc_traceback,
psycopg>                     )
psycopg>                 )
psycopg> >               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
psycopg> E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function BaseConnection.__del__ at 0x7fff92cf8220>
psycopg> E               
psycopg> E               Traceback (most recent call last):
psycopg> E                 File "/nix/store/8g2ls46nckapfkljvwg9q2h8zn048b1k-python3.11-psycopg-3.1.13/lib/python3.11/site-packages/psycopg/connection.py", line 163, in __del__
psycopg> E                   warn(
psycopg> E               ResourceWarning: connection <psycopg.Connection [IDLE] (user=psycopg database=test_db) at 0x7fff8a556c90> was deleted while still open. Please use 'with' or '.close()' to close the connection
psycopg> 
psycopg> /nix/store/ghh2dgix6cfhwglxab5aar02y4qa73xb-python3.11-pytest-7.4.3/lib/python3.11/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
psycopg> =================================== FAILURES ===================================
psycopg> _____________________ test_connect[args3-kwargs3-user=foo] _____________________
psycopg> 
psycopg> monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fff8a5566d0>
psycopg> dsn = 'host=/build/run/postgresql user=psycopg', args = ()
psycopg> kwargs = {'dbname': None, 'user': 'foo'}, want = 'user=foo'
psycopg> 
psycopg>     @pytest.mark.parametrize(
psycopg>         "args, kwargs, want",
psycopg>         [
psycopg>             ((), {}, ""),
psycopg>             (("dbname=foo",), {"user": "bar"}, "dbname=foo user=bar"),
psycopg>             ((), {"port": 15432}, "port=15432"),
psycopg>             ((), {"user": "foo", "dbname": None}, "user=foo"),
psycopg>         ],
psycopg>     )
psycopg>     def test_connect(monkeypatch, dsn, args, kwargs, want):
psycopg>         # Check the main args passing from psycopg.connect to the conn generator
psycopg>         # Details of the params manipulation are in test_conninfo.
psycopg>         import psycopg.connection
psycopg>     
psycopg>         orig_connect = psycopg.connection.connect  # type: ignore
psycopg>     
psycopg>         got_conninfo = None
psycopg>     
psycopg>         def mock_connect(conninfo):
psycopg>             nonlocal got_conninfo
psycopg>             got_conninfo = conninfo
psycopg>             return orig_connect(dsn)
psycopg>     
psycopg>         monkeypatch.setattr(psycopg.connection, "connect", mock_connect)
psycopg>     
psycopg>         conn = psycopg.connect(*args, **kwargs)
psycopg> >       assert drop_default_args_from_conninfo(got_conninfo) == conninfo_to_dict(want)
psycopg> E       AssertionError: assert {'user': 'foo', 'host': '/build/run/postgresql'} == {'user': 'foo'}
psycopg> E         Common items:
psycopg> E         {'user': 'foo'}
psycopg> E         Left contains 1 more item:
psycopg> E         {'host': '/build/run/postgresql'}
psycopg> E         Full diff:
psycopg> E         - {'user': 'foo'}
psycopg> E         + {'host': '/build/run/postgresql', 'user': 'foo'}
psycopg> 
psycopg> tests/test_module.py:35: AssertionError
psycopg> _________________________ test_connect[args0-kwargs0-] _________________________
psycopg> 
psycopg> monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fff8a6f7d90>
psycopg> dsn = 'host=/build/run/postgresql user=psycopg', args = (), kwargs = {}
psycopg> want = ''
psycopg> 
psycopg>     @pytest.mark.parametrize(
psycopg>         "args, kwargs, want",
psycopg>         [
psycopg>             ((), {}, ""),
psycopg>             (("dbname=foo",), {"user": "bar"}, "dbname=foo user=bar"),
psycopg>             ((), {"port": 15432}, "port=15432"),
psycopg>             ((), {"user": "foo", "dbname": None}, "user=foo"),
psycopg>         ],
psycopg>     )
psycopg>     def test_connect(monkeypatch, dsn, args, kwargs, want):
psycopg>         # Check the main args passing from psycopg.connect to the conn generator
psycopg>         # Details of the params manipulation are in test_conninfo.
psycopg>         import psycopg.connection
psycopg>     
psycopg>         orig_connect = psycopg.connection.connect  # type: ignore
psycopg>     
psycopg>         got_conninfo = None
psycopg>     
psycopg>         def mock_connect(conninfo):
psycopg>             nonlocal got_conninfo
psycopg>             got_conninfo = conninfo
psycopg>             return orig_connect(dsn)
psycopg>     
psycopg>         monkeypatch.setattr(psycopg.connection, "connect", mock_connect)
psycopg>     
psycopg>         conn = psycopg.connect(*args, **kwargs)
psycopg> >       assert drop_default_args_from_conninfo(got_conninfo) == conninfo_to_dict(want)
psycopg> E       AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> E         Left contains 1 more item:
psycopg> E         {'host': '/build/run/postgresql'}
psycopg> E         Full diff:
psycopg> E         - {}
psycopg> E         + {'host': '/build/run/postgresql'}
psycopg> 
psycopg> tests/test_module.py:35: AssertionError
psycopg> _______________ test_connect[args1-kwargs1-dbname=foo user=bar] ________________
psycopg> 
psycopg> monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fff8a6ad090>
psycopg> dsn = 'host=/build/run/postgresql user=psycopg', args = ('dbname=foo',)
psycopg> kwargs = {'user': 'bar'}, want = 'dbname=foo user=bar'
psycopg> 
psycopg>     @pytest.mark.parametrize(
psycopg>         "args, kwargs, want",
psycopg>         [
psycopg>             ((), {}, ""),
psycopg>             (("dbname=foo",), {"user": "bar"}, "dbname=foo user=bar"),
psycopg>             ((), {"port": 15432}, "port=15432"),
psycopg>             ((), {"user": "foo", "dbname": None}, "user=foo"),
psycopg>         ],
psycopg>     )
psycopg>     def test_connect(monkeypatch, dsn, args, kwargs, want):
psycopg>         # Check the main args passing from psycopg.connect to the conn generator
psycopg>         # Details of the params manipulation are in test_conninfo.
psycopg>         import psycopg.connection
psycopg>     
psycopg>         orig_connect = psycopg.connection.connect  # type: ignore
psycopg>     
psycopg>         got_conninfo = None
psycopg>     
psycopg>         def mock_connect(conninfo):
psycopg>             nonlocal got_conninfo
psycopg>             got_conninfo = conninfo
psycopg>             return orig_connect(dsn)
psycopg>     
psycopg>         monkeypatch.setattr(psycopg.connection, "connect", mock_connect)
psycopg>     
psycopg>         conn = psycopg.connect(*args, **kwargs)
psycopg> >       assert drop_default_args_from_conninfo(got_conninfo) == conninfo_to_dict(want)
psycopg> E       AssertionError: assert {'user': 'bar', 'dbname': 'foo', 'host': '/build/run/postgresql'} == {'user': 'bar', 'dbname': 'foo'}
psycopg> E         Common items:
psycopg> E         {'dbname': 'foo', 'user': 'bar'}
psycopg> E         Left contains 1 more item:
psycopg> E         {'host': '/build/run/postgresql'}
psycopg> E         Full diff:
psycopg> E         - {'dbname': 'foo', 'user': 'bar'}
psycopg> E         + {'dbname': 'foo', 'host': '/build/run/postgresql', 'user': 'bar'}
psycopg> 
psycopg> tests/test_module.py:35: AssertionError
psycopg> ____________________ test_connect[args2-kwargs2-port=15432] ____________________
psycopg> 
psycopg> monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fff8a5577d0>
psycopg> dsn = 'host=/build/run/postgresql user=psycopg', args = ()
psycopg> kwargs = {'port': 15432}, want = 'port=15432'
psycopg> 
psycopg>     @pytest.mark.parametrize(
psycopg>         "args, kwargs, want",
psycopg>         [
psycopg>             ((), {}, ""),
psycopg>             (("dbname=foo",), {"user": "bar"}, "dbname=foo user=bar"),
psycopg>             ((), {"port": 15432}, "port=15432"),
psycopg>             ((), {"user": "foo", "dbname": None}, "user=foo"),
psycopg>         ],
psycopg>     )
psycopg>     def test_connect(monkeypatch, dsn, args, kwargs, want):
psycopg>         # Check the main args passing from psycopg.connect to the conn generator
psycopg>         # Details of the params manipulation are in test_conninfo.
psycopg>         import psycopg.connection
psycopg>     
psycopg>         orig_connect = psycopg.connection.connect  # type: ignore
psycopg>     
psycopg>         got_conninfo = None
psycopg>     
psycopg>         def mock_connect(conninfo):
psycopg>             nonlocal got_conninfo
psycopg>             got_conninfo = conninfo
psycopg>             return orig_connect(dsn)
psycopg>     
psycopg>         monkeypatch.setattr(psycopg.connection, "connect", mock_connect)
psycopg>     
psycopg>         conn = psycopg.connect(*args, **kwargs)
psycopg> >       assert drop_default_args_from_conninfo(got_conninfo) == conninfo_to_dict(want)
psycopg> E       AssertionError: assert {'host': '/build/run/postgresql', 'port': '15432'} == {'port': '15432'}
psycopg> E         Common items:
psycopg> E         {'port': '15432'}
psycopg> E         Left contains 1 more item:
psycopg> E         {'host': '/build/run/postgresql'}
psycopg> E         Full diff:
psycopg> E         - {'port': '15432'}
psycopg> E         + {'host': '/build/run/postgresql', 'port': '15432'}
psycopg> 
psycopg> tests/test_module.py:35: AssertionError
psycopg> ________ test_connect_args[args4-kwargs4-dbname=qux user=joe port=5433] ________
psycopg> 
psycopg> conn_cls = <class 'psycopg.Connection'>
psycopg> monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fff896fd3d0>
psycopg> setpgenv = <function setpgenv.<locals>.setpgenv_ at 0x7fff8b0cf100>
psycopg> pgconn = <psycopg_c.pq.PGconn [IDLE] (user=psycopg database=test_db) at 0x7fff8b0f5b70>
psycopg> args = ('dbname=foo port=5433',), kwargs = {'dbname': 'qux', 'user': 'joe'}
psycopg> want = 'dbname=qux user=joe port=5433'
psycopg> 
psycopg>     @pytest.mark.parametrize(
psycopg>         "args, kwargs, want",
psycopg>         [
psycopg>             ((), {}, ""),
psycopg>             (("",), {}, ""),
psycopg>             (("host=foo user=bar",), {}, "host=foo user=bar"),
psycopg>             (("host=foo",), {"user": "baz"}, "host=foo user=baz"),
psycopg>             (
psycopg>                 ("dbname=foo port=5433",),
psycopg>                 {"dbname": "qux", "user": "joe"},
psycopg>                 "dbname=qux user=joe port=5433",
psycopg>             ),
psycopg>             (("host=foo",), {"user": None}, "host=foo"),
psycopg>         ],
psycopg>     )
psycopg>     def test_connect_args(conn_cls, monkeypatch, setpgenv, pgconn, args, kwargs, want):
psycopg>         got_conninfo: str
psycopg>     
psycopg>         def fake_connect(conninfo):
psycopg>             nonlocal got_conninfo
psycopg>             got_conninfo = conninfo
psycopg>             return pgconn
psycopg>             yield
psycopg>     
psycopg>         monkeypatch.setattr(psycopg.connection, "connect", fake_connect)
psycopg>         conn = conn_cls.connect(*args, **kwargs)
psycopg>         got_params = drop_default_args_from_conninfo(got_conninfo)
psycopg> >       assert got_params == conninfo_to_dict(want)
psycopg> E       AssertionError: assert {'user': 'joe', 'dbname': 'qux', 'host': '/build/run/postgresql', 'port': '5433'} == {'user': 'joe', 'dbname': 'qux', 'port': '5433'}
psycopg> E         Common items:
psycopg> E         {'dbname': 'qux', 'port': '5433', 'user': 'joe'}
psycopg> E         Left contains 1 more item:
psycopg> E         {'host': '/build/run/postgresql'}
psycopg> E         Full diff:
psycopg> E           {
psycopg> E            'dbname': 'qux',
psycopg> E         +  'host': '/build/run/postgresql',
psycopg> E            'port': '5433',
psycopg> E            'user': 'joe',
psycopg> E           }
psycopg> 
psycopg> tests/test_connection.py:415: AssertionError
psycopg> ______________________ test_connect_args[args1-kwargs1-] _______________________
psycopg> 
psycopg> conn_cls = <class 'psycopg.Connection'>
psycopg> monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fff90b92810>
psycopg> setpgenv = <function setpgenv.<locals>.setpgenv_ at 0x7fff897847c0>
psycopg> pgconn = <psycopg_c.pq.PGconn [IDLE] (user=psycopg database=test_db) at 0x7fff8b0f6ca0>
psycopg> args = ('',), kwargs = {}, want = ''
psycopg> 
psycopg>     @pytest.mark.parametrize(
psycopg>         "args, kwargs, want",
psycopg>         [
psycopg>             ((), {}, ""),
psycopg>             (("",), {}, ""),
psycopg>             (("host=foo user=bar",), {}, "host=foo user=bar"),
psycopg>             (("host=foo",), {"user": "baz"}, "host=foo user=baz"),
psycopg>             (
psycopg>                 ("dbname=foo port=5433",),
psycopg>                 {"dbname": "qux", "user": "joe"},
psycopg>                 "dbname=qux user=joe port=5433",
psycopg>             ),
psycopg>             (("host=foo",), {"user": None}, "host=foo"),
psycopg>         ],
psycopg>     )
psycopg>     def test_connect_args(conn_cls, monkeypatch, setpgenv, pgconn, args, kwargs, want):
psycopg>         got_conninfo: str
psycopg>     
psycopg>         def fake_connect(conninfo):
psycopg>             nonlocal got_conninfo
psycopg>             got_conninfo = conninfo
psycopg>             return pgconn
psycopg>             yield
psycopg>     
psycopg>         monkeypatch.setattr(psycopg.connection, "connect", fake_connect)
psycopg>         conn = conn_cls.connect(*args, **kwargs)
psycopg>         got_params = drop_default_args_from_conninfo(got_conninfo)
psycopg> >       assert got_params == conninfo_to_dict(want)
psycopg> E       AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> E         Left contains 1 more item:
psycopg> E         {'host': '/build/run/postgresql'}
psycopg> E         Full diff:
psycopg> E         - {}
psycopg> E         + {'host': '/build/run/postgresql'}
psycopg> 
psycopg> tests/test_connection.py:415: AssertionError
psycopg> ______________________ test_connect_args[args0-kwargs0-] _______________________
psycopg> 
psycopg> conn_cls = <class 'psycopg.Connection'>
psycopg> monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fff89733550>
psycopg> setpgenv = <function setpgenv.<locals>.setpgenv_ at 0x7fff90bc2980>
psycopg> pgconn = <psycopg_c.pq.PGconn [IDLE] (user=psycopg database=test_db) at 0x7fff90b1ede0>
psycopg> args = (), kwargs = {}, want = ''
psycopg> 
psycopg>     @pytest.mark.parametrize(
psycopg>         "args, kwargs, want",
psycopg>         [
psycopg>             ((), {}, ""),
psycopg>             (("",), {}, ""),
psycopg>             (("host=foo user=bar",), {}, "host=foo user=bar"),
psycopg>             (("host=foo",), {"user": "baz"}, "host=foo user=baz"),
psycopg>             (
psycopg>                 ("dbname=foo port=5433",),
psycopg>                 {"dbname": "qux", "user": "joe"},
psycopg>                 "dbname=qux user=joe port=5433",
psycopg>             ),
psycopg>             (("host=foo",), {"user": None}, "host=foo"),
psycopg>         ],
psycopg>     )
psycopg>     def test_connect_args(conn_cls, monkeypatch, setpgenv, pgconn, args, kwargs, want):
psycopg>         got_conninfo: str
psycopg>     
psycopg>         def fake_connect(conninfo):
psycopg>             nonlocal got_conninfo
psycopg>             got_conninfo = conninfo
psycopg>             return pgconn
psycopg>             yield
psycopg>     
psycopg>         monkeypatch.setattr(psycopg.connection, "connect", fake_connect)
psycopg>         conn = conn_cls.connect(*args, **kwargs)
psycopg>         got_params = drop_default_args_from_conninfo(got_conninfo)
psycopg> >       assert got_params == conninfo_to_dict(want)
psycopg> E       AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> E         Left contains 1 more item:
psycopg> E         {'host': '/build/run/postgresql'}
psycopg> E         Full diff:
psycopg> E         - {}
psycopg> E         + {'host': '/build/run/postgresql'}
psycopg> 
psycopg> tests/test_connection.py:415: AssertionError
psycopg> ______________________ test_connect_args[args0-kwargs0-] _______________________
psycopg> 
psycopg> monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fff896f1650>
psycopg> pgconn = <psycopg_c.pq.PGconn [IDLE] (user=psycopg database=test_db) at 0x7fff895fd170>
psycopg> args = (), kwargs = {}, want = ''
psycopg> 
psycopg>     @pytest.mark.parametrize(
psycopg>         "args, kwargs, want",
psycopg>         [
psycopg>             ((), {}, ""),
psycopg>             (("",), {}, ""),
psycopg>             (("host=foo user=bar",), {}, "host=foo user=bar"),
psycopg>             (("host=foo",), {"user": "baz"}, "host=foo user=baz"),
psycopg>             (
psycopg>                 ("host=foo port=5433",),
psycopg>                 {"host": "qux", "user": "joe"},
psycopg>                 "host=qux user=joe port=5433",
psycopg>             ),
psycopg>             (("host=foo",), {"user": None}, "host=foo"),
psycopg>         ],
psycopg>     )
psycopg>     def test_connect_args(monkeypatch, pgconn, args, kwargs, want):
psycopg>         got_conninfo: str
psycopg>     
psycopg>         def fake_connect(conninfo):
psycopg>             nonlocal got_conninfo
psycopg>             got_conninfo = conninfo
psycopg>             return pgconn
psycopg>             yield
psycopg>     
psycopg>         monkeypatch.setattr(psycopg.connection, "connect", fake_connect)
psycopg>         conn = psycopg.connect(*args, **kwargs)
psycopg> >       assert drop_default_args_from_conninfo(got_conninfo) == conninfo_to_dict(want)
psycopg> E       AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> E         Left contains 1 more item:
psycopg> E         {'host': '/build/run/postgresql'}
psycopg> E         Full diff:
psycopg> E         - {}
psycopg> E         + {'host': '/build/run/postgresql'}
psycopg> 
psycopg> tests/test_psycopg_dbapi20.py:147: AssertionError
psycopg> ______________________ test_connect_args[args1-kwargs1-] _______________________
psycopg> 
psycopg> monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fff896f2590>
psycopg> pgconn = <psycopg_c.pq.PGconn [IDLE] (user=psycopg database=test_db) at 0x7fff895ff380>
psycopg> args = ('',), kwargs = {}, want = ''
psycopg> 
psycopg>     @pytest.mark.parametrize(
psycopg>         "args, kwargs, want",
psycopg>         [
psycopg>             ((), {}, ""),
psycopg>             (("",), {}, ""),
psycopg>             (("host=foo user=bar",), {}, "host=foo user=bar"),
psycopg>             (("host=foo",), {"user": "baz"}, "host=foo user=baz"),
psycopg>             (
psycopg>                 ("host=foo port=5433",),
psycopg>                 {"host": "qux", "user": "joe"},
psycopg>                 "host=qux user=joe port=5433",
psycopg>             ),
psycopg>             (("host=foo",), {"user": None}, "host=foo"),
psycopg>         ],
psycopg>     )
psycopg>     def test_connect_args(monkeypatch, pgconn, args, kwargs, want):
psycopg>         got_conninfo: str
psycopg>     
psycopg>         def fake_connect(conninfo):
psycopg>             nonlocal got_conninfo
psycopg>             got_conninfo = conninfo
psycopg>             return pgconn
psycopg>             yield
psycopg>     
psycopg>         monkeypatch.setattr(psycopg.connection, "connect", fake_connect)
psycopg>         conn = psycopg.connect(*args, **kwargs)
psycopg> >       assert drop_default_args_from_conninfo(got_conninfo) == conninfo_to_dict(want)
psycopg> E       AssertionError: assert {'host': '/build/run/postgresql'} == {}
psycopg> E         Left contains 1 more item:
psycopg> E         {'host': '/build/run/postgresql'}
psycopg> E         Full diff:
psycopg> E         - {}
psycopg> E         + {'host': '/build/run/postgresql'}
psycopg> 
psycopg> tests/test_psycopg_dbapi20.py:147: AssertionError
</pre>
</details>

For the tests I currently provide a Postgres 15 instance through

```
export PSYCOPG_TEST_DSN="host=/build/run/postgresql user=psycopg"
```

I would appreciate help to understand how to get them to work.

**Comment by dvarrazzo** [comment]
Hello,

yes, the failure seems related to the changes made for #675, and it seems an error with the tests, not with the adapter.

I have tried to reproduce, but couldn't so far. I tried using `PSYCOPG_TEST_DSN=host=/var/run/psycopg/ user=psycopg3_test` (where `var/run/psycopg/` is a symlink to the default location `var/run/postgresql/`), which seems to reproduce what you tried.

The problem seems related to the function `tests._test_connection.drop_default_args_from_conninfo` which is a helper to verify that two connection infos are equivalent. Could you please inspect what happens in that function (what it receives as input, what it returns for output) and what value it is compared against?

If you run only:

```
pytest "tests/test_connection.py::test_connect_args[args4-kwargs4-dbname=qux user=joe port=5433]"
```

how does the value `host=/build/run/postgresql` manage to get into `got_conninfo`?

https://github.com/psycopg/psycopg/blob/b68e36426f2f6e061292eec8df6201e8a550e194/tests/test_connection.py#L441-L455

**Comment by mweinelt** [comment]
Looks like it is leaking in from the environment I use to set up our postgresql instance.

```
PGUSER
PGDATABASE
PGHOST
PGDATA
```

Works after calling `setpgenv({})` as done on `master`.

```patch
diff --git a/tests/test_connection.py b/tests/test_connection.py
index 52808af0..10f0a6ca 100644
--- a/tests/test_connection.py
+++ b/tests/test_connection.py
@@ -409,6 +409,7 @@ def test_connect_args(conn_cls, monkeypatch, setpgenv, pgconn, args, kwargs, wan
         return pgconn
         yield
 
+    setpgenv({})
     monkeypatch.setattr(psycopg.connection, "connect", fake_connect)
     conn = conn_cls.connect(*args, **kwargs)
     got_params = drop_default_args_from_conninfo(got_conninfo)
diff --git a/tests/test_module.py b/tests/test_module.py
index 030b7580..948c00b9 100644
--- a/tests/test_module.py
+++ b/tests/test_module.py
@@ -15,7 +15,7 @@ from .test_connection import drop_default_args_from_conninfo
         ((), {"user": "foo", "dbname": None}, "user=foo"),
     ],
 )
-def test_connect(monkeypatch, dsn, args, kwargs, want):
+def test_connect(monkeypatch, dsn, args, kwargs, want, setpgenv):
     # Check the main args passing from psycopg.connect to the conn generator
     # Details of the params manipulation are in test_conninfo.
     import psycopg.connection
@@ -29,6 +29,7 @@ def test_connect(monkeypatch, dsn, args, kwargs, want):
         got_conninfo = conninfo
         return orig_connect(dsn)
 
+    setpgenv({})
     monkeypatch.setattr(psycopg.connection, "connect", mock_connect)
 
     conn = psycopg.connect(*args, **kwargs)
diff --git a/tests/test_psycopg_dbapi20.py b/tests/test_psycopg_dbapi20.py
index bc8b1cc9..69c2fa75 100644
--- a/tests/test_psycopg_dbapi20.py
+++ b/tests/test_psycopg_dbapi20.py
@@ -133,7 +133,7 @@ def test_time_from_ticks(ticks, want):
         (("host=foo",), {"user": None}, "host=foo"),
     ],
 )
-def test_connect_args(monkeypatch, pgconn, args, kwargs, want):
+def test_connect_args(monkeypatch, pgconn, args, kwargs, want, setpgenv):
     got_conninfo: str
 
     def fake_connect(conninfo):
@@ -142,6 +142,7 @@ def test_connect_args(monkeypatch, pgconn, args, kwargs, want):
         return pgconn
         yield
 
+    setpgenv({})
     monkeypatch.setattr(psycopg.connection, "connect", fake_connect)
     conn = psycopg.connect(*args, **kwargs)
     assert drop_default_args_from_conninfo(got_conninfo) == conninfo_to_dict(want)
```
