### ISSUE TITLE
query remains in *idle in transaction*

### ISSUE THREAD

**Issue by arjunChouksey** [psycopg/psycopg#684]
I've been using psycopg and initially i was create connection for each query to execute them like this

```
from psycopg import connect

with connect(**config) as connection:
      with connection.cursor() as _cursor:
             _cursor.execute(query="HERE GOES SELECT QUERY")
             records = _cursor.fetchall() 
```

but above piece of code was causing creation of connection on every single query, so i changed it to

```
from psycopg import connect

connection = connect(**config) 

with connection.cursor() as _cursor:
       _cursor.execute(query="HERE GOES SELECT QUERY")
       records = _cursor.fetchall() 

```

but now my queries are in **idle in transaction**  when i run following query in db 

`SELECT  *  FROM pg_stat_activity where wait_event ='ClientRead' `

can somebody tell what i'm a doing wrong and what is correct way to run select query for psycopg ?

**Comment by dvarrazzo** [comment]
This is documented in [Transaction management](https://www.psycopg.org/psycopg3/docs/basic/transactions.html).

You can use an autocommit connection or use a `transaction()` block.
