### ISSUE TITLE
Deadlock when using pipeline mode

### ISSUE THREAD

**Issue by wemoloh** [psycopg/psycopg#685]
When inserting a large amount of data, psycopg hangs when using pipeline mode.  It does not hang if pipeline mode is not used (but it is much slower when the amount of inserted data is small).

Platform: Windows Server 2019
psycopg version: 3.1.13
PostgreSQL version: 15.2
Python version: 3.11.5

For example, given the following definitions:

```sql
create table test (bigdata text[]);
```

```python
from psycopg import connect

def insert_a_lot(cur, nrows, nchars, nvals):
    for _ in range(nrows):
        data = ['a' * nchars] * nvals
        cur.execute('insert into test (bigdata) values (%s)', (data,))
```

...the following code executes as expected:

```python
with connect(TESTDB) as conn, conn.cursor() as cur:
    insert_a_lot(cur, 10, 1000, 1000)
```

...but the following code just hangs forever.  The database reports the connection is left in 'ClientRead' state:

```python
with connect(TESTDB) as conn, conn.cursor() as cur:
    with conn.pipeline():
        insert_a_lot(cur, 10, 1000, 1000)
```

**Comment by dvarrazzo** [comment]
Hello,

I have played with the issue. On Linux, with psycopg 3.1.17, using the C extension the script never blocks, using the Python implementation, the script blocks about the 50% of the times.

When it blocks, a ctrl-c reveals:

```
Traceback (most recent call last):
  File "/home/piro/dev/psycopg3/test-685.py", line 12, in <module>
    with conn.pipeline():
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/connection.py", line 958, in pipeline
    with pipeline:
  File "/home/piro/dev/psycopg3/psycopg/psycopg/_pipeline.py", line 248, in __exit__
    self._conn.wait(self._exit_gen())
  File "/home/piro/dev/psycopg3/psycopg/psycopg/connection.py", line 974, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/waiting.py", line 342, in wait_poll
    fileevs = poll.poll(timeout)
KeyboardInterrupt
```

In these days I'm making some changes to the generators/wait functions in #673 (needed to implement interruptibe notification listenres): I identified some shortcomings that I thought related to this report, but I don't think it's the case and the test fails in that branch too.

Taking a look at `Pipeline._exit_gen()`...

**Comment by dvarrazzo** [comment]
Using the `PSYCOPG_WAIT_FUNC` to choose a wait function, and `PSYCOPG_IMPL` to choose python/c implementation, it seems that all the python wait function (`wait_poll`, `wait_selector`, `wait_select`) block, `wait_c` doesn't. The Python wait functions block both with Python and C generators.

**Comment by dvarrazzo** [comment]
A few prints showed that the hang happened in `generators.fetch`, with `yield WAIT_R` not returning. This seems to suggest that we read too soon from the pipeline, before the data is totally flushed. And, effectively, this change fixes the problem in 3.1.17:

```diff
diff --git a/psycopg/psycopg/_pipeline.py b/psycopg/psycopg/_pipeline.py
index 7064f603..6b09c69f 100644
--- a/psycopg/psycopg/_pipeline.py
+++ b/psycopg/psycopg/_pipeline.py
@@ -132,8 +132,7 @@ class BasePipeline:
             self._enqueue_sync()
             yield from self._communicate_gen()
         finally:
-            # No need to force flush since we emitted a sync just before.
-            yield from self._fetch_gen(flush=False)
+            yield from self._fetch_gen(flush=True)
 
     def _communicate_gen(self) -> PQGen[None]:
         """Communicate with pipeline to send commands and possibly fetch
```

@dlax what do you think? Maybe we used to send a sync and it got lost in a refactoring?

**Comment by dlax** [comment]
I cannot reproduce the issue on my side.

> Maybe we used to send a sync and it got lost in a refactoring?

Could be https://github.com/psycopg/psycopg/commit/773944be133e0269b60031f3645664c1f2f1cf0b#diff-b72fee89b5b546cb07a77fa3825789c8ad6f3623dca6e3d30a3f376ab60c5f3e, but not sure. The sync is enqueued in the `try:` block, but maybe it cannot be sent because the output buffer is full on server-side?

**Comment by dvarrazzo** [comment]
Oh, it has been there for a long time, May 2022. Thank you for taking a look, @dlax.

It's curious that the issue doesn't manifest using the C wait function. However that reduces the number of users affected.

@wemoloh are you using only `psycopg` and not the `[binary]` or `[c]` extension?

**Comment by wemoloh** [comment]
Hi @dvarrazzo, thank you for investigating this.  I am using the `[binary]` extension.  I am on Windows, so #645 makes `wait_select` the default, but the block still happens even if I set `PSYCOPG_WAIT_FUNC=wait_c`.  I've upgraded to version 3.1.17 but it makes no difference.  The only thing that does seem to work is your `_exit_gen` patch at 3d230d4000940f98c0faf73978d17f9f2862cc95.

**Comment by dvarrazzo** [comment]
Thank you for confirming that #685 fixes the issue for you too, @wemoloh (and sorry for getting back on this ticket so late). I will try to release a 3.1.18 including this change in the next few days.
