### ISSUE TITLE
Problem resolving localhost in async mode

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#695]
Locally I spin up a Postgres container on port 5433 for executing my tests and  everything is working.
On gitlab I  have a pipeline using the [gitlab Postgres service](https://docs.gitlab.com/ee/ci/services/postgres.html), everything worked prior to *3.1.13* but since then my app is unabled to reach the Postgres db.

 I do not use **psypcopg** directly, only via **sqlalchemy** so I do not know if this would be useful but here is a gist containing the logs extracted from the gitlab job:

https://gist.github.com/vacarme/90311ce419ea4f99a8b91b1136656a10

_Originally posted by @vacarme in https://github.com/psycopg/psycopg/issues/694#issuecomment-1845205702_

**Comment by dvarrazzo** [comment]
@vacarme from your log it seems that we resolve `localhost` to `::1` instead of `127.0.0.1` and most likely postgres is not listening on IPV6.

I don't know why this should be a problem with psycopg 3.1.13 but not 3.1.12: I didn't expect the async name resolution to change. I am probably wrong in some way.

Are you able to provide the content of `/etc/hosts`?

**Comment by dminhhoang26** [comment]
I think Async mode is having problem (psycopg==3.1.13), every of my sync connect work, but async is not (sometime it work, but rarely), i'm not a good developer so i cannot figure out the issue.
```
psycopg.OperationalError: connection is bad: 9000:5302:1a00::1", port 5432 failed: Network is unreachable
        Is the server running on that host and accepting TCP/IP connections?
```

**Comment by dvarrazzo** [comment]
@dminhhoang26 what is the content of your `/etc/hosts` file?

**Comment by dvarrazzo** [comment]
Aww... I think I found the problem:

https://github.com/psycopg/psycopg/blob/70ef364324ba3448ef9ac0e29329c9d802380e4b/psycopg/psycopg/conninfo.py#L451-L454

The `yield attempt` is outside the loop. So if the hosts file is configured to resolve first ipv4, then ipv6, will try only ipv6 resolution.

Adding a test to verify it. Can you test if with this change:

```diff
--- a/psycopg/psycopg/conninfo.py
+++ b/psycopg/psycopg/conninfo.py
@@ -451,7 +451,7 @@ async def _split_attempts_and_resolve(params: ConnDict) -> AsyncIterator[ConnDic
     attempt = params.copy()
     for item in ans:
         attempt["hostaddr"] = item[4][0]
-    yield attempt
+        yield attempt
 
 
 @cache
```

the problem is solved?

**Comment by dminhhoang26** [comment]
> @dminhhoang26 what is the content of your `/etc/hosts` file?

I'm running my FastAPI app in wsl Ubuntu and using psycopg3 directly, my `/etc/hosts` file:
```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateHosts = false
127.0.0.1       localhost
127.0.1.1       DESKTOP-HIDEN.        DESKTOP-HIDEN

192.168.1.14    host.docker.internal
192.168.1.14    gateway.docker.internal
127.0.0.1       kubernetes.docker.internal

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by dminhhoang26** [comment]
@dvarrazzo thank you very much! I think i will try to use the async connection again in the future.

> @dminhhoang26 I don't see from this hosts file how localhost may be resolved to `9000:5302:1a00::1`. What was your connection string?
> 
> Because that's WSL, I'm unable to test it directly. Did you try if making the change above fix the problem?

My postgres is a live server (not localhost) from (Neon tech)[https://neon.tech/] and `sync and async` connection parameters are the same, i'm trying refactor my sync connect to async one but facing the issue. this is my code snippet:
```python
# my connection function
    PG_CONNECTIONSTRING = f"""postgres://{PyEnv.POSTGRES_USER}:{PyEnv.POSTGRES_PW}@{PyEnv.PG_HOST}:{PyEnv.PG_PORT}/{PyEnv.POSTGRES_DB}{"?sslmode=require" if PyEnv.PG_SSLMODE else ""}"""

    def get_conn(self) -> psycopg.Connection:
        conn = psycopg.connect(conninfo=self.PG_CONNECTIONSTRING)
        print(f"Successfully connected to the database {PyEnv.POSTGRES_DB}")
        return conn

    async def get_conn_async(self):
        return await psycopg.AsyncConnection.connect(conninfo=self.PG_CONNECTIONSTRING)

# this is how i use it:
        querySql = sql.SQL(
            """
            SELECT *
            FROM {tbl}
            WHERE code = %s
            ;"""
        ).format(tbl=sql.Identifier(PROVINCES_TABLE))

        async with await self.dbHelper.get_conn_async() as con:
            async with con.cursor(row_factory=rows.dict_row) as cur:
                await cur.execute(querySql, [code])
                rec = await cur.fetchone()
```

**Comment by dvarrazzo** [comment]
@dminhhoang26 Thank you, a fix should be on the way.

Are you able to run:

```python
import socket
socket.getaddrinfo(PyEnv.PG_HOST, PyEnv.PG_PORT, type=socket.SOCK_STREAM, family=socket.AF_UNSPEC)
```

with your environment values?

**Comment by dminhhoang26** [comment]
Hi @dvarrazzo , here is the result with my environment values:
```
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('52.220.170.93', 5432)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('13.228.46.236', 5432)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('13.228.184.177', 5432))]
```

**Comment by dvarrazzo** [comment]
Psycopg 3.1.15 being released, which should fix this issue. Please try it out and let us know how it goes, thank you!

**Comment by vacarme** [comment]
Successfully tested in a gitlab pipeline, the previously broken *Postgres* service now works like a charm.

Thanks you for your really quick reaction.

**Comment by dacevedo12** [comment]
Hi, sorry for reviving this old thread, but I'm experiencing what looks like a regression of this issue.

For some reason it attempts to connect to ipv6 on a machine that does not support it. 
Perhaps this can help? https://github.com/aio-libs/aiohappyeyeballs

**Comment by dvarrazzo** [comment]
@dacevedo12 No regression. Your network is not configured correctly.
