### ISSUE TITLE
Fips support in psycopg / C / pools?

### ISSUE THREAD

**Issue by bschollnick** [psycopg/psycopg#697]
Sorry to ask...

- I assume psycopg v3 is supporting FIPS, since v2 did as well...  But if so, shouldn't it be documented somewhere? (Documentation enhancement suggestion)
- Is it safe to assume that psycopg v3 binary also **does not** support FIPS, due to the libssl, etc, being included in the binary?
- Does the psycopg[c] extension/package also support FIPS?
- Does the psycopg[pools] extension/package also support FIPS?

I'm asking since I can't find any documentation that confirms or denies this....  I see documentation that the base psycopg v2 package (**non-binary**) supports it...

**Comment by dvarrazzo** [comment]
I have no idea what FIPS is. Can you explain?

**Comment by bschollnick** [comment]
Sorry, FIPS was new to me when I heard about it.  FIPS stands for Federal Information Processing Standards, and it is a program overseen by NIST and the Department of Commerce that requires specific security standards for data and encryption.

The major difference, is that OpenSSL is switched to FIPS mode, and only certified encryption/hashing methods are allowed.  For example, AES (128, 192, 256), SHA are allowed.  MD5 is not for **secure/encryption purposes**, but for basic hashing it may be allowed depending on the hash implementation.

hashlib, specifically mentions this in the introduction, see https://docs.python.org/3/library/hashlib.html.  (Be aware, the doc at first glance is contradictory, seemingly stating that MD5 is FIPS compliant, but down a bit, it clarifies "[md5()](https://docs.python.org/3/library/hashlib.html#hashlib.md5) is normally available as well, though it may be missing or blocked if you are using a rare “FIPS compliant” build of Python.".

So is openSSL included in C/Pools/Binary for v3?  is MD5 being used, assuming it's available?

**Comment by dvarrazzo** [comment]
So, the answer is similar to the one given in psycopg2 (of which I had forgotten):

- OpenSSL is a transitive dependency, used by the libpq.
- `psycopg[c]` (both Python and C code) use the system libpq, which uses the system OpenSSL. Whether it supports FIPS or not depends on the system and is outside psycopg domain.
- `psycopg[binary]` uses an OpenSSL built in the CI using [this script](https://github.com/psycopg/psycopg/blob/master/tools/build/build_libpq.sh). No guarantee is made about whether FIPS is supported or not.
- `psycopg[pool]` is independent from OpenSSL.

The [install page](https://www.psycopg.org/psycopg3/docs/basic/install.html) documents clearly that the Python and the C version of psycopg bind with the system library, therefore FIPS support is dictated by what else is installed on the system, and I don't think there is the need to document it further.
