### ISSUE TITLE
SSL connection unexpectedly closed when rebooting AWS Postgres server

### ISSUE THREAD

**Issue by davidmnovak** [psycopg/psycopg#701]
I am connecting to an AWS RDS Postgres instance from a python api using an asynchronous connection pool. This works perfectly.

However, when the database server is restarted, i.e. in a managed update, the connection fails with:

`'psycopg.OperationalError: consuming input failed: terminating connection due to administrator command', 
'SSL connection has been closed unexpectedly'`

Is there a better solutoin than to close the pool, and open a new one, or restarting the api server?

**Comment by dvarrazzo** [comment]
You can call [`check()`](https://www.psycopg.org/psycopg3/docs/api/pool.html#psycopg_pool.ConnectionPool.check) on the pool if you know when the event happens.

If you don't, you can use the `check` pool parameter, available from pool 3.2. See [docs here](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#connection-quality) for details.

**Comment by davidmnovak** [comment]
Thanks for the hint on version 3.2. I've resolved it by using check() on the operational error exception and it seems to resolve it nicely.
