### ISSUE TITLE
LoggingCursor equivalent in psycopg

### ISSUE THREAD

**Issue by george-6th** [psycopg/psycopg#702]
I am trying to log every query made using psycopg. In psycopg2, this was possible with the `cursor_factory=LoggingCursor` on the connection or the cursor (https://www.psycopg.org/docs/advanced.html#connection-and-cursor-factories).
```py
import psycopg2
import psycopg2.extensions
import logging

class LoggingCursor(psycopg2.extensions.cursor):
    def execute(self, sql, args=None):
        logger = logging.getLogger('sql_debug')
        logger.info(self.mogrify(sql, args))

        try:
            psycopg2.extensions.cursor.execute(self, sql, args)
        except Exception, exc:
            logger.error("%s: %s" % (exc.__class__.__name__, exc))
            raise

connection = psycopg2.connect(dsn, cursor_factory=LoggingCursor)
```

Is there a similar `cursor_factory` equivalent that can be used on the connection in psycopg (version 3)?

**Comment by dvarrazzo** [comment]
You can subclass [`psycopg.ClientCursor`](https://www.psycopg.org/psycopg3/docs/advanced/cursors.html#client-side-binding-cursors) to do the same. Then yes, there is `cursor_factory` or you can just instantiate a cursor as shown in the `ClientCursor` docs.
