### ISSUE TITLE
Consider to add parsing/type conversion of connection arguments

### ISSUE THREAD

**Issue by mbergen** [psycopg/psycopg#707]
I'm currently exploring the usage of psycopg as driver when using SQLAlchemy, and would like to set connection arguments, namely `prepare_threshold`.
SQLAlchemy has two ways to pass these:
Either via appending them as query parameters to the connection URL, or by passing a dictionary.
When using the former, the arguments are being passed and set as type `str`, which then fails when they are being evaluated (cause `prepare_threshold` is expected as `Optional[int]`.

It could be argued that this is something for SQLAlchemy to implement, but that would mean every new argument or changed type from psycopg would need to be changed there as well.

This is only a suggestion, as the the working alternative (passing the dictionary) works flawlessly, so feel free to close this issue if it is out of scope.

**Comment by dvarrazzo** [comment]
We might accept prepare_threshold as string too, if it makes sense, but first let's try and figure out well.

Looking at the arguments we support in connection:

```python
    def connect(
        cls,
        conninfo: str = "",
        *,
        autocommit: bool = False,
        prepare_threshold: Optional[int] = 5,
        row_factory: Optional[RowFactory[Row]] = None,
        cursor_factory: Optional[Type[Cursor[Row]]] = None,
        context: Optional[AdaptContext] = None,
        **kwargs: Any,
    ) -> "Connection[Any]":
        """
```

what about the others? How does SA pass `autocommit`? `row_factory` and `cursor_factory` are callables/objects: would there be a need to have them as strings too (for instance deep-importing them)?

What do you mean with:

> It could be argued that this is something for SQLAlchemy to implement, but that would mean every new argument or changed type from psycopg would need to be changed there as well.

I think, if you have a workaround, I would avoid to treat prepare_threshold differently from other psycopg parameters (meaning as opposite as libpq parameters, which are in the `kwargs` here and are all basically strings, including the port).

**Comment by mbergen** [comment]
> what about the others? How does SA pass `autocommit`? `row_factory` and `cursor_factory` are callables/objects: would there be a need to have them as strings too (for instance deep-importing them)?

When passing options via URL query params (`postgresql+psycopg://user:password@host:port/dbname[?key=value&key=value...]`), they are all pased as strings, but it is possible to pass them in python as well:
```python
engine = create_engine(
    "postgresql+psycopg://user:pass@hostname/dbname?prepare_threshold=10",
    connect_args={"connection_factory": MyConnectionFactory},
)
```
This example would actually pass 
`connect_args={"prepare_threshold": "10", "connection_factory": MyConnectionFactory}`,
where `prepare_threshold` will then have the type not usable in psycopg.

> What do you mean with:
> 
> > It could be argued that this is something for SQLAlchemy to implement, but that would mean every new argument or changed type from psycopg would need to be changed there as well.

Essentially if parsing of these string query arguments into appropriate types (e.g. `prepare_threshold: Optional[int]`) would be done on the SA side, this would need to happen for all arguments that might be added in the future for them to be usable, which might be delayed compared to when they are introduced in psycopg. When parsing happens in psycopg, it would be working without changes to SA.

> I think, if you have a workaround, I would avoid to treat prepare_threshold differently from other psycopg parameters (meaning as opposite as libpq parameters, which are in the `kwargs` here and are all basically strings, including the port).

My workaround right now is to implement the parsing in my application, catching URLs with prepare_threshold set, parsing the string and removing the option from the URL before passing it to SA.
Essentially this is only needed cause i have to disable statement preparation in some tests, since types are dropped/recreated from the database while the application is still running.

**Comment by dvarrazzo** [comment]
I've thought about it a bit but I don't think that guaranteeing for every argument to possibly be a string is a good idea.

The connection string in psycopg contains only the arguments to be passed to the libpq. This makes sure that the same connection string can be used by every libpq program, such as psql or psycopg2. I would prefer not to muddle this separation. It is not guaranteed that SA will do what I believe it does from the description of its behaviour that you gave me: to unpack the string arguments and pass them as keyword arguments. It might sometimes move to pass the arguments as url or as connection string, and in that case it won't be enough to treat the argument as string, we should also start to parse it out from the url and separate what we pass or not pass to the libpq.

Other constructor arguments are more difficult to be represented as strings: classes (`cursor_factory`), functions (`row_factory`) or instances (`context`). I don't know if SA has any special provision to set `autocommit` from the url.

In the example you have above there is clearly the possibility to put `prepare_threshold`: 10 in the `connect_args`. I don't see a reason for having it to specify it in a string and there are easy workaround, such as to parse the url on your side or to organise your tests to not use the url for these arguments.

**Comment by mbergen** [comment]
Thank you for taking the time for this!
