### ISSUE TITLE
problem with operator "is"

### ISSUE THREAD

**Issue by hian18** [psycopg/psycopg#714]
i my code
with psycopg.connect(conninfo=conninfo) as conn:
    print(conn.execute('select (True = %s)x', (True,)).fetchone())
the result is
(True,)

but if I use is it results in an error
with psycopg.connect(conninfo=conninfo) as conn:
    print(conn.execute('select (True is %s)x', (True,)).fetchone())
this error
psycopg.errors.SyntaxError: syntax error at or near "$1"
LINE 1: select (True is $1)x

**Comment by dvarrazzo** [comment]
It's a documented issue: `IS` doesn't seem parametrizable in postgres. Probably it's implemented as unary operator. I thought it only supported `IS NULL` but it seems it supports booleans too. It doesn't support much else anyway: `SELECT 10 is 10` raises a syntax error in psql, for instance.

https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#you-cannot-use-is-s

You can use `IS NOT DISTINCT FROM %s` to get the same effect of `IS`.
