### ISSUE TITLE
Running multiple queries in a non transaction block

### ISSUE THREAD

**Issue by uyha** [psycopg/psycopg#715]
I have an SQL file that contains queries for setting up my database, naturally this file has many SQL commands. However, commands such as `CREATE MATERIALIZED VIEW` will error out with the message
```
psycopg.errors.ActiveSqlTransaction: CREATE MATERIALIZED VIEW ... WITH DATA cannot run inside a transaction block
```

The snippet I use to run the SQL file is as follows
```python
import psycopg

conn_string = ...
sql_file = ...
with psycopg.connect(conn_string) as conn,
        open(sql_file) as f:
    conn.execute(f.read())
```

If I have only 1 SQL command in the SQL file, then the snippet runs without problem, but if I have more `CREATE MATERIALIZED VIEW` commands, it will error as above. Setting `autocommit` to `True` also doesn't help.

**Comment by uyha** [comment]
My solution currently is using [sqlparse](https://github.com/andialbrecht/sqlparse) to split the statements and execute them individually. So I guess my question now is, will `psycopg` plan to support this feature? or users should use `sqlparse` for situations like this.

Solution:
```python
import psycopg
import sqlparse

conn_string = ...
sql_file = ...
with psycopg.connect(conn_string) as conn,
        open(sql_file) as f:
    for statement in sqlparse.split(f.read()):
        conn.execute(statement)  # type: ignore
```

**Comment by dvarrazzo** [comment]
[As documented](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#multiple-statements-in-the-same-query), postgres wraps more than one statement in an implicit transaction and therefore statements that cannot run in transactions (such as CREATE DATABASE) cannot be executed in multiple statements.

We are not planning to add a workaround which would force us to parse the SQL statement. psycopg is agnostic and doesn't put semantic in the statements passed to the database; the responsibility is the user's.
