### ISSUE TITLE
cursor.executemany  statusmessage shows None

### ISSUE THREAD

**Issue by XtopherM** [psycopg/psycopg#717]
Hi! 
I'm currently using psycopg 3.1.17 and I noticed that when using the `cursor.executemany` function, this one shows `cursor.statusmessage` as `None`. This is not a HUGE issue, might be a bug, maybe a new feature even, however it took me a couple of minutes to figure out that the INSERTS and UPDATES were actually happening even tho I was getting a None as response.  
Thank you to everyone involved! 

Here a sample code to reproduce the issue:
```python
import psycopg
import pandas as pd 

df = pd.DataFrame({'idx':[1,2,3], 'namex':['Jon', 'Juan', 'Jhon']})
print(df)
connection = psycopg.connect(
                host="localhost",
                port='5498',
                dbname="testing",
                user="test_user",
                password='pass',
            )
connection.autocommit=True
with connection as conn:
    with conn.cursor() as cur:
        cur.execute('DROP TABLE IF EXISTS test_insert_table')
        print(cur.statusmessage)
        cur.execute('CREATE TABLE test_insert_table (idx int, namex text)')
        print(cur.statusmessage)
        cur.execute("""
                    INSERT INTO test_insert_table (idx, namex) 
                    VALUES (%(idx)s, %(namex)s)
                """, df.to_dict('records')[0])
        print(cur.statusmessage)
        cur.executemany("""
                    INSERT INTO test_insert_table (idx, namex) 
                    VALUES (%(idx)s, %(namex)s)
                """, df.to_dict('records'))
        print(cur.statusmessage)
        response = cur.execute('SELECT * FROM test_insert_table').fetchall()
        print(cur.statusmessage)
        print(response)
```
Output:
```
   idx namex
0    1   Jon
1    2  Juan
2    3  Jhon
DROP TABLE
CREATE TABLE
INSERT 0 1
None
SELECT 4
[(1, 'Jon'), (1, 'Jon'), (2, 'Juan'), (3, 'Jhon')]
```

**Comment by dvarrazzo** [comment]
Yes, I see. This comes from the fact that executemany doesn't store the results returned, unless you use `returning=True`.

I don't think it's worth changing the implementation to return a result, which would be arbitrary anyway (the first? the last?). Using `returning=True`, otoh, it is well defined what result is currently handled by the cursor.

If you want a feedback on the action of the last query you can use `rowcount`, which will return the sum of all the records affected.

I don't think there is any reasonable improvement we can make here.
