### ISSUE TITLE
Move some pool messages to DEBUG

### ISSUE THREAD

**Issue by corby** [psycopg/psycopg#729]
When requesting or returning a connection from/to the pool, the system dumps an INFO message that should be DEBUG level so we don't load up our logs with uninformative log lines (and blow out our DataDog bill)

```
2024-01-31 11:31:40,771 - INFO - [psycopg.pool:_getconn_with_check_loop:218] connection given by 'pool-1'
2024-01-31 11:31:40,923 - INFO - [psycopg.pool:putconn:314] returning connection to 'pool-1'
```

**Comment by dvarrazzo** [comment]
I believe that the logging at info level is correct. For a reference, [sqlalchemy logs at info level every query](https://docs.sqlalchemy.org/en/20/core/engines.html#configuring-logging). Looking at other messages we send, DEBUG is mostly used for internal use, INFO carries information that can be useful to users; moving getconn/putconn at DEBUG level would drown those information.

If you want to log only the warnings or nothing at all you can configure the logger's level, for instance:

```python
logging.getLogger("psycopg.pool").setLevel(logging.WARNING)
```
