### ISSUE TITLE
Docs: The psycopg2->psycopg3 differences page does not mention that psycopg2.errorcodes has gone away

### ISSUE THREAD

**Issue by kpinc** [psycopg/psycopg#730]
Hi,

The psycopg2->psycopg3 differences page does not mention that psycopg2.errorcodes has gone away.

Likewise (poor example):
```
try:
  something()
except psycopg2.Error as err:
  if err.pgcode == psycopg2.errorcodes.INSUFFICIENT_PRIVILEGE:
    pass
```

Changes to:

```
try:
  something()
except psycopg3.Error as err:
  if err == psycopg2.errors.INSUFFICIENT_PRIVILEGE:
    pass
```

**Comment by dvarrazzo** [comment]
Mah... `errorcodes` was a silly module. [`psycopg2.errors`](https://www.psycopg.org/docs/errors.html) is a much better way to deal with exception:

```python
try:
    something()
except psycopg2.errors.InsufficientPrivilege:
    pass
```

and this patter is available in psycopg 3 too. Your code is an error, that's not the way you use exception classes.
