### ISSUE TITLE
Question: how is the `check` method being used?

### ISSUE THREAD

**Issue by rodolfolottin** [psycopg/psycopg#736]
Hey! Thank you for all your hard work in maintaining this library. Huge fan!

I've been going through the codebase, but I couldn't find how the `check` method is used. The docstrings mention that `check_connection` is used internally by `check`, but even after adding some debug breakpoints, I couldn't figure out how this happens. Could you quickly explain how it's used?

I wanted to confirm if adding `check=AsyncConnectionPool.check_connection` is sufficient for the connection pool to handle failed connections and create new ones automatically, or if I should handle that manually.

**Comment by dvarrazzo** [comment]
Documentation [is here](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#connection-quality). Yes, `check=AsyncConnectionPool.check_connection` should be all you need.
