### ISSUE TITLE
AsyncConnectionPool connection deadlock/hang (between event loops?)

### ISSUE THREAD

**Issue by dabdine** [psycopg/psycopg#737]
Versions:
- python: 3.12
- psycopg: 3.1.16
- psycopg_pool: 3.2.1

Given this example:
```python
import asyncio
import os

from psycopg import AsyncConnection
from psycopg.rows import TupleRow
from psycopg_pool import AsyncConnectionPool


def get_pool() -> AsyncConnectionPool[AsyncConnection[TupleRow]]:
    return AsyncConnectionPool(conninfo=os.environ["CONNECTION_INFO"], min_size=1, max_size=10)


class Foo:
    def __init__(self) -> None:
        self.pool = get_pool()

    async def some_func(self) -> None:
        async with self.pool.connection() as conn:
            cursor = await conn.execute("SELECT 1;")
            rows = await cursor.fetchall()
            print(rows)


async def create_foo() -> Foo:
    return Foo()


foo = asyncio.run(create_foo())
asyncio.run(foo.some_func())
```

Will produce this:
```bash
...
    raise PoolTimeout(
psycopg_pool.PoolTimeout: couldn't get a connection after 30.00 sec
```

As it appears that the pool is opened in the first event loop (`asyncio.run(create_foo())` -> implicitly opens the pool as `open` defaults to `True`), it blocks the line `async with self.pool.connection()`, which gets stuck on `await self.getconn(...)` in line 190 of pool_async.py.

Changing the `open` parameter to `False` and then opening the pool prior to using it does work, presumably because the pool was opened in the same event loop:

```python
import asyncio
import os

from psycopg import AsyncConnection
from psycopg.rows import TupleRow
from psycopg_pool import AsyncConnectionPool


def get_pool() -> AsyncConnectionPool[AsyncConnection[TupleRow]]:
    return AsyncConnectionPool(conninfo=os.environ["CONNECTION_INFO"], min_size=1, max_size=10, open=False)


class Foo:
    def __init__(self) -> None:
        self.pool = get_pool()

    async def some_func(self) -> None:
        await self.pool.open()  # or `async with self.pool as pool:` and `async with pool.connection() as conn:
        async with self.pool.connection() as conn:
            cursor = await conn.execute("SELECT 1;")
            rows = await cursor.fetchall()
            print(rows)


async def create_foo() -> Foo:
    return Foo()


foo = asyncio.run(create_foo())
asyncio.run(foo.some_func())
```

The use case for this is running a server in FastAPI, where I want to initialize the connection pool in some service object utilized by the API (represented by Foo in the example). The (startup) initialization is happening in a different event loop than the event loop used by fastapi to handle the request(s).

**Comment by dabdine** [comment]
May be related to: https://github.com/psycopg/psycopg/issues/646

**Comment by dabdine** [comment]
This seems to be understood to a degree based on this comment in `AsyncConnectionPool#__init__`:
```python
        # If these are asyncio objects, make sure to create them on open
        # to attach them to the right loop.
        self._lock: ALock
        self._sched: AsyncScheduler
        self._tasks: AQueue[MaintenanceTask]
```

and the docs do allude to deprecating the use of `open` as a constructor argument at some point in the future https://www.psycopg.org/psycopg3/docs/api/pool.html

Perhaps the bare minimum here would be to error or log when the pool is opened in a loop that is separate from the loop used to interact with the pool?

**Comment by dvarrazzo** [comment]
Is there a way to detect the condition?

**Comment by dabdine** [comment]
> Is there a way to detect the condition?

possibly tracking the id/hash of the event loop when the locks and such are created, then checking those when calls that utilize them (like `pool.connection()`) are called, but would need to play with it a bit when I get more time. That would only be useful to raise/log to warn the caller(s) about this issue though (which I mentioned earlier can be fine for now).

**Comment by dabdine** [comment]
We may want to consider using a threading Lock instead to lock across event loops (and threads). May also need to look at the use of `asyncio.Queue` since that's loop-bound.

**Comment by dvarrazzo** [comment]
All this is temporary: you are using a deprecated way of doing things (it was a poor design choice at a time I knew less about asyncio life cycle).

We raise warnings for the issue. The problem I see here is that the warnings are `DeprecationWarning`, which are disabled by default. Just changing the warning to be a `RuntimeWarning`, which is not ignored, should have pointed at the issue more quickly and allowed you to fix it.

**Comment by dlax** [comment]
> The problem I see here is that the warnings are DeprecationWarning, which are disabled by default. Just changing the warning to be a RuntimeWarning, which is not ignored, should have pointed at the issue more quickly and allowed you to fix it.

Indeed. But `FutureWarning` would be more appropriate, I think, and this is not ignored by default.

**Comment by dvarrazzo** [comment]
> Indeed. But FutureWarning would be more appropriate, I think, and this is not ignored by default.

I think that a runtime warning is appropriate if we are tying to create asyncio objects without a loop. It's not a problem about something to happen in the future.

The change of the default for open might be. However I don't quite get the distinction that the docs make:

> Changed in version 3.7: Previously [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) and [FutureWarning](https://docs.python.org/3/library/exceptions.html#FutureWarning) were distinguished based on whether a feature was being removed entirely or changing its behaviour. They are now distinguished based on their intended audience and the way they’re handled by the default warnings filters.

I've open #738: happy to get a review from the two of you :slightly_smiling_face:

**Comment by dlax** [comment]
On second thought and re-reading the docs, the `DeprecationWarning` seems appropriate to me: the intended audience is Python developers. The warning shows up when using the development mode `python -X dev` (which is [recommended](https://docs.python.org/3/library/asyncio-dev.html) when developing with asyncio), or when running tests with pytest.

**Comment by dabdine** [comment]
> All this is temporary: you are using a deprecated way of doing things (it was a poor design choice at a time I knew less about asyncio life cycle).
> 
> We raise warnings for the issue. The problem I see here is that the warnings are `DeprecationWarning`, which are disabled by default. Just changing the warning to be a `RuntimeWarning`, which is not ignored, should have pointed at the issue more quickly and allowed you to fix it.

Even if the `open` parameter were to be removed from `AsyncConnectionPool` today, this issue would still be present, though. Here's a version that explicitly sets `open` to `False` and causes the hang:


```python
import asyncio
import os

from psycopg import AsyncConnection
from psycopg.rows import TupleRow
from psycopg_pool import AsyncConnectionPool


def get_pool() -> AsyncConnectionPool[AsyncConnection[TupleRow]]:
    return AsyncConnectionPool(conninfo=os.environ["CONNECTION_INFO"], min_size=1, max_size=10, open=False)


class Foo:
    def __init__(self) -> None:
        self.pool = get_pool()

    async def init(self) -> None:
        await self.pool.open()

    async def some_func(self) -> None:
        async with self.pool.connection() as conn:
            cursor = await conn.execute("SELECT 1;")
            rows = await cursor.fetchall()
            print(rows)


async def create_foo() -> Foo:
    foo = Foo()
    await foo.init()
    return foo

foo = asyncio.run(create_foo())
asyncio.run(foo.some_func())
```


In this case, `open` is still called in the first event loop, just later in the program lifecycle. I tried doing exactly this initially to resolve the problem.

**Comment by dvarrazzo** [comment]
>
> foo = asyncio.run(create_foo())asyncio.run(foo.some_func())
>
> I think that this pattern is problematic whatever asyncio object involves.

`asyncio.run()` docs <
https://docs.python.org/3/library/asyncio-runner.html#asyncio.run> say:

> This function should be used as a main entry point for asyncio programs,
and should ideally only be called once.

Googling for "multiple asyncio run calls" is instructive too.

I think that it is reasonable to ask that the pool warns that it will not
work correctly when an arguably correct usage pattern is used. But, if
something is wrong at a different and lower level, it's not its
responsibility to tell the user that they are doing something wrong.

I don't think that a code warning "you can use the pool only in the loop
where it was created" is necessary, because this is likely the case with
every asyncio object. If you think that the documentation can be improved,
you are welcome to propose to add a warning box where you think it would
have been useful to read it.

**Comment by dabdine** [comment]
> foo = asyncio.run(create_foo())asyncio.run(foo.some_func()) I think that this pattern is problematic whatever asyncio object involves.
> `asyncio.run()` docs < https://docs.python.org/3/library/asyncio-runner.html#asyncio.run> say:
> This function should be used as a main entry point for asyncio programs,
> and should ideally only be called once. Googling for "multiple asyncio run calls" is instructive too. I think that it is reasonable to ask that the pool warns that it will not work correctly when an arguably correct usage pattern is used. But, if something is wrong at a different and lower level, it's not its responsibility to tell the user that they are doing something wrong. I don't think that a code warning "you can use the pool only in the loop where it was created" is necessary, because this is likely the case with every asyncio object. If you think that the documentation can be improved, you are welcome to propose to add a warning box where you think it would have been useful to read it.

The use of `asyncio.run` was only for convenience of demonstrating the issue. I created a gist with four different test cases: The first test case creates two event loops without calling `asyncio.run`. The last three utilize FastAPI and the (starlette) TestClient. Two of the FastAPI test cases demonstrate workarounds (for others that may see this issue). While I agree asyncio.run should only be called once in practice, should the same be said for the use of multiple event loops? Even if so, it would be nice to make it more clear to folks when it is hanging. A doc update to add a warning near the constructor `open` and the `open` call would be good enough for now I suppose.

https://gist.github.com/dabdine/684614c72df3ac1bdf2dc84bf063fd55

**Comment by dvarrazzo** [comment]
Look, if you create a task in a loop, then start a second loop, does it sound a reasonable assumption, for you, that the task will work across loops? Where is, in asyncio, this guarantee? In asyncio I see big red flags saying "if you don't use `asyncio.run()`, [you must know what you are doing](https://docs.python.org/3/library/asyncio-eventloop.html)":

> Application developers should typically use the high-level asyncio functions, such as `asyncio.run()`, and should rarely need to reference the loop object or call its methods. This section is intended mostly for authors of lower-level code, libraries, and frameworks, who need finer control over the event loop behavior.

For me, it is obvious that something, in this scenario, will break. And for me it's not our responsibility to teach this obvious fact about asyncio. So, as already asked, if you want, you can propose a documentation patch, but to me "the pool must be used in the loop it is created" seems obvious enough to not deserve any docs.

Using lifespan in FastAPI is not "a workaround", as you put it: it's the documented way to manage the lifespan of app resources, both in FastAPI and in the pool docs (we mention the older style `app.on_event`, but the use case is the same).

This ticket can be closed here, because, as you mentioned, the change in the warning doesn't affect the fact that the pool will not work across loops, and it's not supposed to.

**Comment by dabdine** [comment]
First, let me state that I'm very thankful for your continued support and maintenance of this library.

I have not been advocating to teach people about how asyncio works. I'm only advocating for documenting the behavior of this library if it is used in an unsupported asyncio configuration (multiple loops).

If I get a chance I will update the docs, and perhaps look at locking a bit more in a separate PR.
