### ISSUE TITLE
Support Pipeline/Batch mode

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#74]
In this mode, several cursor may send commands to the same connection and then sit in a queue to receive the result.

https://www.postgresql.org/docs/14/libpq-pipeline-mode.html

**Comment by dlax** [comment]
@dvarrazzo, as I'm progressing on this, I'm wondering where we should put tests for this feature. Would they live alongside other tests in `test_connection.py`, `test_cursor.py`, `test_transaction.py`, `test_server_cursor.py` (and async siblings)? Or should we just add a `test_pipeline.py` file?

**Comment by dvarrazzo** [comment]
Certain major features have their own test file, because it made more sense working focused on that (e.g. `test_prepared.py`). If you find more convenient to have `test_pipeline.py` and `test_pipeline_async.py`. I think it makes sense so.

**Comment by dvarrazzo** [comment]
Finally closed in #175.

Thank you very much, @dlax. This was an epic work!
