### ISSUE TITLE
Explicit commit() forbidden within a Transaction context and force_rollback=True

### ISSUE THREAD

**Issue by bezborodow** [psycopg/psycopg#741]
I prefer to explicitly commit a transaction at the end of each block. For this, I specify the `force_rollback` option as true as per the documentation for [`Connection.transaction()`](https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection.transaction).

There seems to be a problems with this however. When calling `commit()` the following error is raised:

> `ProgrammingError: Explicit commit() forbidden within a Transaction context. (Transaction will be automatically committed on successful exit from context.)`

Steps to reproduce:

```
    with pool.connection() as conn:
        with conn.transaction(force_rollback=True):
            conn.execute('update _______ ...')
            conn.commit() # <--- Raises ProgrammingError!
```

Actual behaviour: The `ProgrammingError` above is raised.

The expected behaviour is that the transaction should commit.

Interestingly, calling execute with 'commit' as a string however does work, which is somewhat of a workaround:

```
    with pool.connection() as conn:
        with conn.transaction(force_rollback=True):
            conn.execute('update _______ ...')
            conn.execute('commit')
```

**Comment by bezborodow** [comment]
```
[dbezborodov@bms-test psycopg]$ git grep  "forbidden within"
psycopg/psycopg/_connection_base.py:                "Explicit commit() forbidden within a Transaction "
psycopg/psycopg/_connection_base.py:                "Explicit rollback() forbidden within a Transaction "
```

**Comment by dvarrazzo** [comment]
> I prefer to explicitly commit a transaction at the end of each block. For this, I specify the force_rollback option as true as per the documentation for [Connection.transaction()](https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection.transaction).

I don't see the relations between the two statements and it doesn't seem that what `force_rollback` is there for.

I don't know what you mean for "you prefer to explicitly commit". Then don't use a transaction block?

**Comment by dvarrazzo** [comment]
The reason why we don't want to accept a `commit()` in a transaction block is that these blocks can be nested, and in a level deeper than the first the right thing to run would be a SAVEPOINT operation.

So we will not accept a MR to accept `commit()` if a transaction block is open. The right way to use the feature is to just let the block exit.

You are free to force the system by running your own `execute("COMMIT")` in conjunction with `force_rollback`, the responsibility is yours. However, in terms of interface, the error stopping you from running `commit()` in the block is the right thing to do.

**Comment by bezborodow** [comment]
Thank you Daniele for your quick reply. I use Psycopg 3 heavily in my projects.

> I don't see the relations between the two statements and it doesn't seem that what `force_rollback` is there for.
> 
> I don't know what you mean for "you prefer to explicitly commit". Then don't use a transaction block?

In the `psql` interface it is possible to do something like this:

1. Start a transaction.

```
bms=> start transaction;
START TRANSACTION
```

2. Check the data that I am about to operate on.

bms=*> select project_id, project_code, due from projects;
 project_id | project_code |    due     
------------+--------------+------------
          2 | TAA1002      | 
          3 | TAA1003      | 
          1 | TAA1001      | 2024-03-02
(3 rows)
```

3. Manipulate that data.

```
bms=*> update projects set due = null;
UPDATE 3
```

4. Verify my changes.

```
bms=*> select project_id, project_code, due from projects;
 project_id | project_code | due 
------------+--------------+-----
          2 | TAA1002      | 
          3 | TAA1003      | 
          1 | TAA1001      | 
(3 rows)
```

5. Rollback my changes if I am not happy with them.

```
bms=*> rollback;
ROLLBACK
bms=> select project_id, project_code, due from projects;
 project_id | project_code |    due     
------------+--------------+------------
          2 | TAA1002      | 
          3 | TAA1003      | 
          1 | TAA1001      | 2024-03-02
(3 rows)
```

At no point was an actual error raised. It was a user decision to roll back the changes.
If I _was_ happy with the changes, I would have _explicitly_ sent a `commit` command. That is what I meant by "explicitly": I am purposefully and deliberately telling the server that I am happy with my changes and that I want to commit them (or roll them back.)

Because I am paranoid I like to follow this process in my coding also. :)

That is, I prefer to see a "commit" line at the end of every transaction block, not have it implicitly occur once having left the transaction block.

I suppose it is okay to "force the system." I don't mind this. I just wanted to explain my reasoning better.

Thanks again.

**Comment by bezborodow** [comment]
And yes, I agree that I might be abusing the intention of `force_rollback` to achieve this coding style...

**Comment by bezborodow** [comment]
I am looking at the documentation for [`SAVEPOINT`](https://www.postgresql.org/docs/current/sql-savepoint.html), and at the end of each block, there is a `COMMIT` command:

```
BEGIN;
    INSERT INTO table1 VALUES (1);
    SAVEPOINT my_savepoint;
    INSERT INTO table1 VALUES (2);
    ROLLBACK TO SAVEPOINT my_savepoint;
    INSERT INTO table1 VALUES (3);
COMMIT;
```

**Comment by dvarrazzo** [comment]
> I suppose it is okay to "force the system." I don't mind this. I just wanted to explain my reasoning better.

You are welcome to do it. You know what you are doing, so that's ok. Psycopg won't get in the way of it.

To explain better the design of the transaction blocks behaviour, if you were allowed to do this:

```python
with conn.transaction() as t1
    conn.execute("OP1")
    with conn.transaction() as t2:
       conn commit()
    raise Rollback()
```

In t1, we assume that we can run OP1 and then roll back the change. If t2 was allowed to commit, then OP1 will be committed even if t2 is a nested transaction and t1 tried to roll back. Therefore we deny the possibility to use the `commit()` method.

If you don't like this, you should avoid to use transaction the blocks because they have this specific semantics and committing halfway doesn't make sense (even if "halfway" is the last statement of the block - we cannot know that).

You can work around the limitation by issuing a COMMIT in an execute, we won't police that, and you are responsible of the state of your application. I just think that, if you want that level of control, the `transaction()` method might not have the semantic you want.

**Comment by dvarrazzo** [comment]
> committing halfway doesn't make sense (even if "halfway" is the last statement of the block - we cannot know that).

With this I meant:

```python
with conn.transaction():
    conn.execute("OP1")
    conn.commit()
    conn.execute("OP2")
    conn.execute("OP3")
```

in which state does OP2 happen? Inside the a new transaction or outside any transaction? For sure it wouldn't happen in the transaction of OP1, unless we lied. It would happen outside for postgres but it seems inside, looking at the python code. And where does OP3 happen? In the same transaction of OP2 or not?
