### ISSUE TITLE
Binary copy performance on Mac

### ISSUE THREAD

**Issue by ankane** [psycopg/psycopg#745]
Hi, big thanks for this library!

I wanted to report a large difference in binary copy performance between Mac and Linux (as well as between psycopg and Ruby's [pg gem](https://github.com/ged/ruby-pg) on Mac).

Project | Platform | Time
--- | --- | ---
psycopg 3 | Linux | 10 sec
psycopg 3 | Mac | 321 sec
pg gem | Mac | 4 sec

Here's [a repo](https://github.com/ankane/psycopg-repro) to reproduce ([CI results](https://github.com/ankane/psycopg-repro/actions/runs/8133986713)), but also sharing the scripts below.

Python script

```python
import psycopg

conn = psycopg.connect(dbname='repro', autocommit=True)
conn.execute('DROP TABLE IF EXISTS items')
conn.execute('CREATE TABLE items (id bigserial, description text)')

description = 'test' * 100

cur = conn.cursor()
with cur.copy('COPY items (description) FROM STDIN WITH (FORMAT BINARY)') as copy:
    copy.set_types(['text'])

    for i in range(1000000):
        # show progress
        if i % 10000 == 0:
            print('.', end='', flush=True)

        copy.write_row([description])

print()
```

Ruby script

```ruby
require "pg"

conn = PG.connect(dbname: "repro")
conn.exec("DROP TABLE IF EXISTS items")
conn.exec("CREATE TABLE items (id bigserial, description text)")

description = "test" * 100

coder = PG::BinaryEncoder::CopyRow.new
conn.copy_data("COPY items (description) FROM STDIN WITH (FORMAT BINARY)", coder) do
  1000000.times do |i|
    # show progress
    putc "." if i % 10000 == 0

    conn.put_copy_data([description])
  end
end

puts
```

This happens with `psycopg`, `psycopg[binary]`, and `psycopg[c]` (version 3.1.18).

**Comment by dvarrazzo** [comment]
I don't have a mac immediately handy to test.

Can you compare with strace (or the mac equivalent) the different syscalls pattern between psycopg and ruby?

**Comment by ankane** [comment]
I'm not aware of a way to get strace-like output without disabling System Integrity Protection, but looking at samples of the processes, psycopg is spending ~99% of time on `_platform_memmove`, which hardly shows up at all with Ruby.

```text
+ !       2213 __pyx_pw_14psycopg_binary_2pq_6PGconn_63put_copy_data  (in pq.cpython-311-darwin.so)
+ !       : 2211 PQputCopyData  (in libpq.5.dylib)
+ !       : | 2211 pqPutMsgEnd  (in libpq.5.dylib)
+ !       : |   2205 pqSendSome  (in libpq.5.dylib)
+ !       : |   + 2205 _platform_memmove  (in libsystem_platform.dylib)
```

(count is out of 2230 samples)

**Comment by ankane** [comment]
It looks like there's some mention of `memmove` / `PQputCopyData` in #255 and of similar behavior in the code:

https://github.com/psycopg/psycopg/blob/558cbe7ef7ef6a6d1f6c65e368aaaf9f9a10108e/psycopg/psycopg/_copy_base.py#L49-L52

**Comment by ankane** [comment]
It looks like the issue is the connection is in nonblocking mode but never flushed. From the [Postgres docs](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQSETNONBLOCKING):

> In the nonblocking state, successful calls to PQsendQuery, PQputline, PQputnbytes, PQputCopyData, and PQendcopy will not block; their changes are stored in the local output buffer until they are flushed.

Adding the flush logic from `copy_end` to `copy_to` seems to fix it.

**Comment by dvarrazzo** [comment]
Can you provide a MR so we can make other tests? Thank you very much :slightly_smiling_face:
