### ISSUE TITLE
Releases on GitHub

### ISSUE THREAD

**Issue by malthe** [psycopg/psycopg#747]
GitHub releases are a convenient way for people to keep up to date and provide a complementary source for the official distribution.

Some links with more information:
- https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
- https://github.com/marketplace/actions/github-release
- https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by dvarrazzo** [comment]
Github releases will not be used. We deal with enough bureaucracy as is it and this would be a duplication.

You can use PyPI RSS feed to get information about releases.
