### ISSUE TITLE
Syntax error when creating an interval with a placeholder

### ISSUE THREAD

**Issue by elpres** [psycopg/psycopg#749]
Trying to execute this statement fails with a SyntaxError pointing at the placeholder, even though the syntax IMO seems to be correct:
```python
cur.execute("SELECT interval %(duration)s", {'duration': '1 hour'})
```
The same statement with the interval duration filled in works fine:
```python
cur.execute("SELECT interval '1 hour'")
```
Or is it me who is making some mistake here?

Also, thank you for your work!

Psycopg version used: 3.1.18

**Comment by dlax** [comment]
You can use a `datetime.timedelta` value and let Psycopg adapt the type as an interval, e.g.:
```python
>>> from datetime import timedelta
>>> conn.execute("select %(interval)s", {'interval': timedelta(hours=1)}).fetchone()
(datetime.timedelta(seconds=3600),)
```

**Comment by elpres** [comment]
Yes, I know, and there is another workaround that I found:
```python
cur.execute("SELECT make_interval(hours => %(duration)s)", {'duration': 1})
```
But the original version looks like valid syntax that should not throw an error. Also, it worked with Psycopg2. I only stumbled upon it because a statement that used to work just fine before moving to Psycopg3 started throwing an error all of a sudden.

**Comment by dlax** [comment]
No, it's not a valid syntax it seems. See what psql says:
```
# select interval $1 \bind "'1 hour'"\g
ERROR:  syntax error at or near "$1"
LINE 1: select interval $1
                        ^
# select $1 \bind "interval '1 hour'"\g
      ?column?
---------------------
 "interval '1 hour'"
(1 row)
```

**Comment by elpres** [comment]
Ah, so it's Postgres who is rejecting this kind of usage. And I guess that it worked before because Psycopg2 would fill in the placeholders on the client side, right?

Anyway, thanks for looking into this. Let's close the issue then.
