### ISSUE TITLE
Parameter doesn't get resolved

### ISSUE THREAD

**Issue by novotl** [psycopg/psycopg#750]
I'm having issues with running this simple parametric query `SELECT INTERVAL {} DAY` which works perfectly fine with `psycopg2`. I didn't find anything in the documentation that would suggest a different API.

## Psycopg (V3)
```
>>> import psycopg
>>> con = psycopg.connect('postgresql://postgres:pass@localhost:5432/postgres')
>>> con.execute("SELECT INTERVAL '%s' DAY", [42]).fetchall()
[(datetime.timedelta(days=1),)]
```

Looking into `pg_stat_activity` explains the wrong result
```
SELECT pid, query, backend_start FROM pg_stat_activity;
-- SELECT INTERVAL '$1' DAY
```

## Psycopg2
```
>>> import psycopg2
>>> con = psycopg2.connect('postgresql://postgres:pass@localhost:5432/postgres')
>>> cur = con.cursor()
>>> cur.execute("SELECT INTERVAL '%s' DAY", [42])
>>> cur.fetchall()
[(datetime.timedelta(days=42),)]
```

## Versions summary:
```
╰─ pip freeze | grep psycopg
psycopg==3.1.18
psycopg2-binary==2.9.9

postgres=# SELECT version();
                                                     version
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 15.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
```

**Comment by dlax** [comment]
Using `INTERVAL %s` does not work with Psycopg 3 because of server-side binding; see https://github.com/psycopg/psycopg/issues/749 for a similar (recent) question.

And about:
~~~python
>>> con.execute("SELECT INTERVAL '%s' DAY", [42]).fetchall()
[(datetime.timedelta(days=1),)]
~~~
this is because of a complex story:
- psycopg parsing the query as `"select interval '$1' day"`
- executing it with parameters [b'42']
- but the postgres ignoring the parameters because the query  `"select interval '$1' day"`  has *in fact* no placeholder

See in psql:
~~~
# select interval '$1' day;
 interval
----------
 1 day
(1 row)
~~~

**Comment by novotl** [comment]
Right! So the correct way would be 

```python
>>> conn.execute('SELECT %s', [timedelta(days=5)]).fetchall()
[(datetime.timedelta(days=5),)]

>>> conn.execute('SELECT NOW() + %s', [timedelta(days=5)]).fetchall()
[(datetime.datetime(2024, 3, 19, 15, 12, 41, 387776, tzinfo=datetime.timezone.utc),)]
```

To be fair, the documentation has all the bits that lead to this issue

https://www.psycopg.org/psycopg3/docs/basic/params.html
> The placeholder must not be quoted:
> cur.execute("INSERT INTO numbers VALUES ('%s')", ("Hello",)) # WRONG
> cur.execute("INSERT INTO numbers VALUES (%s)", ("Hello",))   # correct

https://www.psycopg.org/psycopg3/docs/basic/adapt.html#date-time-types-adaptation
> Python timedelta objects are converted to PostgreSQL interval.

But it's difficult to piece them together. It's unfortunate that `INTERVAL '$1' day` is legit query that doesn't result in syntax error.

I was searching for `interval` keyword in documentation and only found that one mention ☝️. Personally I would appreciate one example how it should be used.

**Comment by dvarrazzo** [comment]
In psycopg 3 you cannot put together a literal from two halves, one of which is in the query and one of which is in the parameter. So things like this don't work:

```python
cursor.execute("select '%s days'::interval", [ndays])
```

I have never seen the `INTERVAL 1 day` syntax, but, if it's legit, it is some horrible syntactic sugar, which notoriously causes cancer to the semicolon (cit. Alan Perlis). So, not only I prefer not to document it, but I also suggest you to not use it,m and use a standard syntax instead.

There are two obvious solutions that I see:

```python
cursor.execute("select %s * '1 day'::interval", [ndays])  # my preferred one: Euclid rocks
cursor.execute("select %s::interval", [f"{ndays} days"])  # you can do this too
```

apart the one already suggested of using a timedelta object:

```python
cursor.execute("select %s", [timedelta(days=ndays)])
```
