### ISSUE TITLE
Question:  is it need to flush after copy.write_row

### ISSUE THREAD

**Issue by my-vegetable-has-exploded** [psycopg/psycopg#751]
When I read pyvector-python's codes, I found them flush the conn after calling copy.write_row.
https://github.com/pgvector/pgvector-python/blob/1b81759673df531879b5d9081025c0b356acff50/examples/bulk_loading.py#L35-L36
is it  necessary？

Thank you for your time.

**Comment by dvarrazzo** [comment]
It shouldn't be, but it's probably related to #745, that should be fixed in a few days. The author is the same that reported the bug.

You can try to add it to see if there is a performance improvement. When we will fix the bug it shouldn't cause you problem.

**Comment by my-vegetable-has-exploded** [comment]
Thanks ！
