### ISSUE TITLE
Psycopg cuts away part of IPv6 address

### ISSUE THREAD

**Issue by stinovlas** [psycopg/psycopg#752]
## Problem
MWE:
```python
from psycopg import Connection
Connection.connect("postgresql://user:password@[2001:1488:fffe:20::229]:5432/dbname")
```

Output:
```
Traceback (most recent call last):
  File "/home/jmusilek/git/others/auctions/psycopg_mwe.py", line 3, in <module>
    Connection.connect("postgresql://user:password@[2001:1488:fffe:20::229]:5432/dbname")
  File "/home/jmusilek/.virtualenvs/auctions/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect
    raise last_ex.with_traceback(None)
psycopg.OperationalError: connection failed: 1488:fffe:20::229", port 5432 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

As you can see from the traceback, `psycopg` tries to connect to `1488:fffe:20::229`, not `2001:1488:fffe:20::229`. The first part is cut off. This happens with all IPv6 addresses and also when I specify a hostname in conninfo, which is then resolved to an IPv6 address. This does not happen with IPv4 addresses.

Unfortunatelly, I wasn't able to track down where this happens.

**Comment by dlax** [comment]
It seems to me that it's the error message that is wrong (includes truncated address), because of https://github.com/psycopg/psycopg/blob/558cbe7ef7ef6a6d1f6c65e368aaaf9f9a10108e/psycopg/psycopg/pq/misc.py#L105

If you put a `print(f"{obj.error_message=}")` above this line, you should see that the full address is actually used to connect.

**Comment by dvarrazzo** [comment]
Uh, right. Maybe we should have the stripping stricter. There are a few words that are used, such as `ERROR`, `WARNING`... but they also undergo l10n. Maybe there is some pattern we can use though (such as stripping a single uppercase word).
