### ISSUE TITLE
Connection is not closed when process exit

### ISSUE THREAD

**Issue by tungwaiyip** [psycopg/psycopg#753]
I have a gunicorn application. The request is set to timeout in 60s. In one case, I have a slow query that ran a lot longer than 60s. gunicorn kill the worker. 

```
[2024-03-28 04:34:56 +0000] [572] [CRITICAL] WORKER TIMEOUT (pid:593)
2024-03-28 04:34:56,134 [593] [WARNING] psycopg        : error ignored in rollback on <conn>: sending query and params failed: another command is already in progress
[2024-03-28 04:34:56 +0000] [593] [INFO] Worker exiting (pid: 593)
worker_exit(<Worker 593>)
```

However, the connection is not closed on the server side. Once gunicorn restarted the worker, another slow request comes in. The slow queries snowballed on the server side. It seems `Connection.__exit__` tried to clean up with `self.rollback()`. But the second log line showed that it is failed.

I tried to reproduce this using a script. It did not replicate the gunicorn worker error. But I have experimented with various strategies.

```
import signal
import psycopg

def signal_handler(*args):
    print("signal_handler")
    # Three ways to clean up. The goal is to close the connection before exit.
    #conn.close()
    #conn.rollback()
    #conn.cancel()

#signal.signal(signal.SIGTERM, signal_handler)

with psycopg.connect("postgres://username:password@host.docker.internal:5432/dbname") as conn:
    with conn.cursor() as cur:
        cur.execute("select pg_sleep(60)")
        print(cur.fetchall())
```

I tried five ways to handle it

1. Kill process using Ctrl-C

```
^CTraceback (most recent call last):
  File "/app/q.py", line 22, in <module>
    cur.execute("select pg_sleep(61)")
  File "/usr/local/lib/python3.10/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
KeyboardInterrupt
```

Connection is closed. This is the desirable outcome.

2. Kill using SIGTERM

In another terminal, run

```
pkill -SIGTERM python
```

The python processed is terminated. However the query is still running on the server.

3. Handle with conn.close()

Add a signal handler. Cleanup with `conn.close()`

Kill using SIGTERM

```
signal_handler
Traceback (most recent call last):
  File "/app/q.py", line 22, in <module>
    cur.execute("select pg_sleep(61)")
  File "/usr/local/lib/python3.10/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.OperationalError: consuming input failed: connection pointer is NULL
```

The query is still running.

4. Handle with conn.rollback()

Add a signal handler. Cleanup with `conn.rollback()`

The process seems to hang. The query is still running.

5. Handle with conn.cancel()

Add a signal handler. Cleanup with `conn.cancel()`

```
signal_handler
Traceback (most recent call last):
  File "/app/q.py", line 22, in <module>
    cur.execute("select pg_sleep(62)")
  File "/usr/local/lib/python3.10/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.QueryCanceled: canceling statement due to user request
```

The connection is closed.

What is the proper way to ensure the connections are closed before exit?

**Comment by dvarrazzo** [comment]
Hello,

among the things you have tried to do, the right one is to send a cancel, like in strategy 5. You cannot send a rollback because the connection is still running.

This test program shows the operations.

```python
import os
import time
import signal
import psycopg
import logging
import threading

logger = logging.getLogger()
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

conn = psycopg.connect("")

def sleeper():
    logger.info("starting query")
    try:
        conn.execute("select pg_sleep(10)")
    except psycopg.errors.QueryCanceled as e:
        logger.warning("query got canceled: %s", str(e))
    logger.info("query finished")


def cancel_query(signum, frame):
    logger.warning(f"got signal {signum}, cancelling quuery")
    conn.cancel()


signal.signal(signal.SIGTERM, cancel_query)

t = threading.Thread(target=sleeper)
t.start()
time.sleep(2)

logger.info("killing myself")
os.kill(os.getpid(), signal.SIGTERM)
logger.info("I am dead")
```

Reading both the postgres and program output together:

```
$ sudo tail -f /var/log/postgresql/postgresql-15-main.log &
$ python test-753.py 
2024-03-29 09:33:18,830 INFO starting query
2024-03-29 09:33:20,831 INFO killing myself
2024-03-29 09:33:20,832 WARNING got signal 15, cancelling quuery
2024-03-29 09:33:20.835 GMT [1717909] piro@piro ERROR:  canceling statement due to user request
2024-03-29 09:33:20.835 GMT [1717909] piro@piro STATEMENT:  select pg_sleep(10)
2024-03-29 09:33:20,839 INFO I am dead
2024-03-29 09:33:20,840 WARNING query got canceled: canceling statement due to user request
2024-03-29 09:33:20,840 INFO query finished
```

So, 5 works. However, on top of that, you probably want to set a [`statement_timeout`](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-STATEMENT-TIMEOUT) of 60 seconds, or just a couple of seconds longer. This way, even if the python handler will not work as expected, the server will terminate the query anyway.

The way it should go is that the server should terminate the query when requested, try to send the cancellation error back to the client, find the client connection closed because the Python process died, and close the connection on its side.

Modifying the program this way to remove the handler but introducing a query timeout:

```diff
--- test-753.py	2024-03-29 09:33:16.460078685 +0000
+++ test-753-nohandler.py	2024-03-29 09:37:30.534200138 +0000
@@ -9,6 +9,8 @@
 logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
 
 conn = psycopg.connect("")
+with conn.transaction():
+    conn.execute("set statement_timeout to '3s'")
 
 def sleeper():
     logger.info("starting query")
@@ -24,7 +26,7 @@
     conn.cancel()
 
 
-signal.signal(signal.SIGTERM, cancel_query)
+# signal.signal(signal.SIGTERM, cancel_query)
 
 t = threading.Thread(target=sleeper)
 t.start()
```

The output looks like:

```
$ python test-753-nohandler.py 
2024-03-29 09:39:00,466 INFO starting query
2024-03-29 09:39:02,468 INFO killing myself
Terminated
$
2024-03-29 09:39:03.467 GMT [1720223] piro@piro ERROR:  canceling statement due to statement timeout
2024-03-29 09:39:03.467 GMT [1720223] piro@piro STATEMENT:  select pg_sleep(10)
2024-03-29 09:39:03.478 GMT [1720223] piro@piro LOG:  could not send data to client: Broken pipe
2024-03-29 09:39:03.478 GMT [1720223] piro@piro STATEMENT:  select pg_sleep(10)
2024-03-29 09:39:03.479 GMT [1720223] piro@piro FATAL:  connection to client lost
```

So I suggest you to use the handler in the kill signal, but also introduce a statement timeout as a safety net.

**Comment by tungwaiyip** [comment]
This sounds good. I could not reproduce my production error with this simple script. But it seems the error come from this line

https://github.com/psycopg/psycopg/blob/558cbe7ef7ef6a6d1f6c65e368aaaf9f9a10108e/psycopg/psycopg/connection.py#L148

`.rollback()` is called in `__exit__` as some sort of error handling.

**Comment by dvarrazzo** [comment]
That's not an error, it is a warning, probably caused by trying to call `rollback()` in a handler when another query is already running.

As suggested, the only safe thing you can do in a handler is `cancel()`.
