### ISSUE TITLE
Notifies not generated if consumed in other thread

### ISSUE THREAD

**Issue by malthe** [psycopg/psycopg#756]
The same connection `conn` is used in two threads:

1. The first thread waits for `conn.notifies()`.
2. The second thread runs a statement that triggers a notification.

You would expect that the first thread would receive the notification, but that's not the case – the notifies are consumed and distributed only to handlers registered using `conn.add_notify_handler`.

When notifies are consumed, the select/polling happening as part of `conn.notifies()` will cause a loop-around, but we won't see any notifications and will just resume waiting. What should happen is that any notification received on the connection must be distributed to open `notifies` generators.

A `notifies` generator should be considered open when `conn.notifies()` returns (iterating should not be required). When iteration completes (due to a `timeout` or `stop_after` setting), the generator can be considered closed.

**Comment by dvarrazzo** [comment]
> You would expect that the first thread would receive the notification, but that's not the case – the notifies are consumed and distributed only to handlers registered using conn.add_notify_handler.

I don't think that yours is the right expectation. Most likely the notifications are returned together with the return message to the second thread, therefore the first one doesn't get to see them. I would call it a race condition, except that the first thread is likely bound to predictably lose the race.

I would say don't do that.

**Comment by malthe** [comment]
@dvarrazzo since I had a draft changeset ready to make this change, I decided to push it for review – that said, obviously feel free to close this pull request given that you've already stated your view on the current behavior.

I think the proposed behavior is better (more correct, less surprising), but it can be seen in different ways. I'm incorporating your library into https://github.com/malthe/pq and was hoping that I could test things using just a single connection.

**Comment by dvarrazzo** [comment]
Thank you for the MR! Happy to review It and open to change my mind if it
makes sense 🙂
