### ISSUE TITLE
ImportError undefined symbol after installing psycopg2-binary on pypy

### ISSUE THREAD

**Issue by jaraco** [psycopg/psycopg#759]
In [this build](https://github.com/jaraco/jaraco.postgres/actions/runs/8513408499/job/23317010295) of [jaraco.postgres](/jaraco/postgres), the CI is failing early in discovery when `import psycopg2` fails with the following error:

```
___________________ ERROR collecting tests/test_postgres.py ____________________
ImportError while importing test module '/home/runner/work/jaraco.postgres/jaraco.postgres/tests/test_postgres.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_postgres.py:14: in <module>
    import psycopg2
.tox/py/lib/pypy3.10/site-packages/psycopg2/__init__.py:51: in <module>
    from psycopg2._psycopg import (                     # noqa
E   ImportError: /home/runner/work/jaraco.postgres/jaraco.postgres/.tox/py/lib/pypy3.10/site-packages/psycopg2/_psycopg.pypy310-pp73-x86_64-linux-gnu.so: undefined symbol: PyInterpreterState_Main
```

I see that psycopg2-binary doesn't in fact have any binaries for pypy, so it must have been built from source (however pip does that on ubuntu 22.04). Perhaps PyPy is unsupported, but since my search for issues on PyPy didn't turn up anything relevant, so I'm reporting it here.

**Comment by dvarrazzo** [comment]
Pypy is not supported on psycopg 2. It is supported in psycopg 3.
