### ISSUE TITLE
error with numpy types (psycopg v3)

### ISSUE THREAD

**Issue by EdmundsEcho** [psycopg/psycopg#761]

**Comment by EdmundsEcho** [comment]
I had everything up and running until I refactored some code to use numpy dataframes.  I was surprised when I got a 
```
psycopg.ProgrammingError: cannot adapt type 'int64' using placeholder '%t' (format: TEXT)
```

... given the builtin support for numpy types.  Is there something I'm missing in how to avoid this error?

I've played around using different python types, including casting to int to no avail.

Thank you in advance for any pointers on how to troubleshoot.

**Comment by dvarrazzo** [comment]
The numpy scalar adapters have been merged to master but haven't been released yet. They will be released in psycopg 3.2.

**Comment by EdmundsEcho** [comment]
Thank you for your quick reply. And all round for the postgres adapter :)

**Comment by CarMoreno** [comment]
Is there a tentative release date for this feature?

**Comment by dvarrazzo** [comment]
We have pretty much finished all the features we wanted to add for 3.2. There are only [a handful of small pending items](https://github.com/psycopg/psycopg/milestones/3.2).

I am currently very busy with other jobs and have very limited time, but I would like to release 3.2 within this month.
