### ISSUE TITLE
Single parameter in tuple does not work for DROP TABLE

### ISSUE THREAD

**Issue by lk-1984** [psycopg/psycopg#769]
Here is the example function:

```
def drop_table(name):
    try:
        with psycopg.connect(
            conninfo=CONNECTION_INFO
        ) as connection:
            with connection.cursor() as cursor:
                result = cursor.execute("DROP TABLE %s;", (name,))
                connection.commit()
    except Exception as e:
        log.error(e)
```

Note: if I replace parameter "name" with a string of the actual table, it will still fail with same error.

Here is the error log:

```
2024-04-05 07:36:36,864 drop_table.py ERROR syntax error at or near "$1"
LINE 1: DROP TABLE $1;
                   ^
```

With psql:

```
DROP TABLE;
```

Error log:

```
ERROR:  syntax error at or near ";"
LINE 1: DROP TABLE;
                  ^
```

So it looks like that by some odd reason it cannot parse the single string in a tuple with length of 1 as a parameter for the DROP TABLE.

**Comment by dvarrazzo** [comment]
You cannot parametrize table names. Use [`psycopg.sql`](https://www.psycopg.org/psycopg3/docs/api/sql.html) instead. Something like (untested):

```python
cursor.execute(sql.SQL("DROP TABLE {}").format(sql.Identifier(name)))
```

**Comment by lk-1984** [comment]
Thank you. Not pretty, but works.
