### ISSUE TITLE
Initial Connect SSL negotiation packet Error

### ISSUE THREAD

**Issue by vitruvvius** [psycopg/psycopg#77]
When using the binary version, ie psycopg[binary] calls into libpq, 
the following initial setup (with *** being user / password )
```
await AsyncConnectionPool("postgresql://*****:******@localhost:26257/passport", max_size=50).wait()
```

causes a
```
WARNING:psycopg.pool:error connecting in 'pool-1': connection failed: Connection refused
could not send SSL negotiation packet: Connection refused
```

I use this url in other libs (java / rust sqlx). Is there a different url it's expecting? Typically, SSL takes care of itself.

**Comment by dvarrazzo** [comment]
Does the same happen with the system libpq? I.e. if you install `psycopg[c]`? (Hint: look at [`pq.__impl__`](https://www.psycopg.org/psycopg3/docs/api/pq.html#psycopg.pq.__impl__) to know what implementation you are using)

Do you get the same error with a normal `psycopg.connect()`?

However, connection refused seems to suggest that the connection wasn't established and that SSL is just the first to notice.

**Comment by vitruvvius** [comment]
Potentially the latter,

I switched localhost to 127.0.0.1 w/ other people receive similar errors. It is now connected

**Comment by vitruvvius** [comment]
Out of curiosity, which of the three is the fastest to use?

**Comment by vitruvvius** [comment]
When using 127.0.0.1 instead of localhost, it defers the error down the road to

ask: <Task pending name='pool-1-worker-0' coro=<AsyncConnectionPool.worker() done, defined at /Users/tsalemy/passport/florence/skin/passport/lib/python3.9/site-packages/psycopg_pool/pool_async.py:321> wait_for=<Future cancelled>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='pool-1-worker-1' coro=<AsyncConnectionPool.worker() done, defined at /Users/tsalemy/passport/florence/skin/passport/lib/python3.9/site-packages/psycopg_pool/pool_async.py:321> wait_for=<Future cancelled>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='pool-1-worker-2' coro=<AsyncConnectionPool.worker() done, defined at /Users/tsalemy/passport/florence/skin/passport/lib/python3.9/site-packages/psycopg_pool/pool_async.py:321> wait_for=<Future cancelled>>
ERROR:grpc._cython.cygrpc:Unexpected [AttributeError] raised by servicer method [/account.AccountApi/Upsert]

**Comment by vitruvvius** [comment]
The url works for other libs, mainly:

pgsql
cockroach sql
rust sqlx
among others

So I'm not sure why connection refused would fail for this in particular

**Comment by vitruvvius** [comment]
Same Url Works for psycopg.connect() / psycopg.AsynConnection.connect

**Comment by dvarrazzo** [comment]
If 127.0.0.1 behaves differently from localhost, it's usually caused by what's in /etc/hosts, and IPv6 getting in the way. However it should work like psql at least.

C and binary have the same performance: binary is a precompiled version of c and bundled with the libraries it uses. Looks like the bundled version doesn't behave like your system one

**Comment by dvarrazzo** [comment]
The warnings you see at the end seem caused by AsyncPool.close() not being called at the end at program exit: https://www.psycopg.org/psycopg3/docs/advanced/pool.html#pool-life-cycle

**Comment by vitruvvius** [comment]
the 127.0.0.1 errors comes when one attempts to acquire a connection. interesting - so the AsyncConnectionPool, even though it's still active as a global when using 127.0.0.0.1, does not properly close the connections if it fails to connect....

nonetheless, the url still seems to be not working across all paths

does it work on your end?

**Comment by vitruvvius** [comment]
One possibility is that I have to manually add the certificates since database is running in secure mode (ssl required on server)..... although other libraries have never required this for me

**Comment by dvarrazzo** [comment]
The warnings from the pool seem to come from worker tasks, not from broken connections. The last error (ERROR:grpc._cython.cygrpc:Unexpected [AttributeError] raised by servicer method [/account.AccountApi/Upsert]) is not our code :)

**Comment by vitruvvius** [comment]
yes - the last line denotes where in the codebase this happens

**Comment by vitruvvius** [comment]
I tried w/ the c module (both binary and c)

**Comment by vitruvvius** [comment]
running psql {url} dictates for me typically whether a url will work

when running psql "postgres://****:*****@localhost:26257/vive?sslmode=require" it works

but again, not in this lib. i can try adding ssl root

**Comment by vitruvvius** [comment]
same error attempting above

**Comment by dvarrazzo** [comment]
> running psql {url} dictates for me typically whether a url will work

I agree with your test: if it works with psql it should work with psycopg. The problem is that, usually, it does :D

**Comment by vitruvvius** [comment]
I’m running on macosx too

**Comment by vitruvvius** [comment]
For clarity, running in a virtualenv shouldn’t affect host name lookup right?

I can run in docker container under Debian and see whether host.internal.docker works

**Comment by dvarrazzo** [comment]
No, virtualenv is a Python-only matter, it doesn't affect host resolution.

**Comment by vitruvvius** [comment]
Anything else i can do to provide more logs as to the underlying error?

**Comment by dvarrazzo** [comment]
You could use ldd to verify what libpq your psql is binding to, and what libpq is psycopg binding to. Or use strace to sniff the communication...

**Comment by vitruvvius** [comment]
Changing url to bind to

0.0.0.0 or 127.0.0.1

on the synchronous, non-pool API works (normal psycopg.connect)

 - this worries me broadly about sql hostname lookup for remote environments in GCP/AWS. kick the can down the road.

**Comment by dvarrazzo** [comment]
Does it mean that sync and async behave differently?

Another option is that you let me SSH in the machine you are testing and we share a tmux shell

**Comment by vitruvvius** [comment]
No - I double checked all options now working. It has to do with underlying libpq hostname lookup on MacOSX. I will close - but have another question on COPY error
