### ISSUE TITLE
Add timeout (with a sensible default) to cancel_safe

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#779]
As suggested in https://github.com/psycopg/psycopg/issues/534#issuecomment-2037987893 I think that we should have a timeout on cancelling, because with all async methods the libpq expects the client to to that.

@dlax suggested to leave it to our client (https://github.com/psycopg/psycopg/issues/534#issuecomment-2042757578) but I think it's our responsibility to do so, because most time people won't even know that they need a timeout until when they will misconfigure their firewall and their program will get stuck (hence the default) and because the asyncio facilities are not available in sync code.

Opening this ticket to allow #763 to proceed and add the timeout after merging.

**Comment by dlax** [comment]
> @dlax suggested to leave it to our client ([#534 (comment)](https://github.com/psycopg/psycopg/issues/534#issuecomment-2042757578)) but I think it's our responsibility to do so, because most time people won't even know that they need a timeout until when they will misconfigure their firewall and their program will get stuck (hence the default) and because the asyncio facilities are not available in sync code.

On second thought, I don't disagree.

So I can work on that issue next, it that's okay by you.

**Comment by dvarrazzo** [comment]
> So I can work on that issue next, it that's okay by you.

Ok for me, thank you very much!

I think the pattern should be the same as in the `connect()` generator (so much that some refactoring may be introduced, or maybe we could decide that the timeout is useful on `wait_conn()` after all...
