### ISSUE TITLE
Allow sending updated timeout to notifies generator

### ISSUE THREAD

**Issue by malthe** [psycopg/psycopg#788]
Sometimes, when iterating through `notifies(...)`, as a result of processing the notification, perhaps we want to update the `timeout` value.

A use-case is that we're scanning through notifications that a new item has been pushed onto some queue, with a scheduling time set in the future. If the date is within the time window of our original timeout, we want to update it (decrease it) – to match the scheduling time.

While we could of course just call `notifies(...)` again – with a new `timeout` value – it would be more efficient to be able to feed in an updated timeout using [`generator.send`](https://docs.python.org/3/reference/expressions.html#generator.send), e.g.
```python
for notify in (gen := conn.notifies(timeout=60)):
    ...
    gen.send(updated_timeout)
```
This proposal feeds somewhat into https://github.com/psycopg/psycopg/pull/757 where there's a minor cost in establishing the `notifies(...)` generator (chiefly having to add a notify handler, but in the async case also having to `socket.dup` the file descriptor, closing it again on exit).

**Comment by dvarrazzo** [comment]
I don't see any problem in calling notifies again, and this seems an excessive complication of something simple and working.

I believe that if you want such refined policies you should add them yourself in your application. If any we can make sure that the building blocks are complete and well composible together. Psycopg is largely a mechanism and you should be the one building your policies.

**Comment by malthe** [comment]
For what it's worth, the suggested change will amount to just:
```python
-                        yield ns.popleft()
+                        updated_timeout = yield ns.popleft()
+                        if updated_timeout is not None:
+                            deadline = monotonic() + updated_timeout
```
I agree that it's a balance and psycopg should be a simple mechanism, but this is hardly an excessive complication; actually, it enables the user to exactly do that – build the policy – because you're able to feed back the value from your own code.

But as I mentioned in the description, some of the motivation for this is that I'm suggesting some changes to `notifies(..)` that involve:
```python
ns: deque[Notify] = deque()
self.add_notify_handler(ns.append)
try:
    # generate notifies
    ...
finally:
    self.remove_notify_handler(ns.append)
```
Which is nothing major, but somehow being able to stay inside the notifier longer, if it means making it possible to adjust the timeout, seems to me a reasonable change to the building block, enabling better composition actually.
