### ISSUE TITLE
Suggestion: Replace SELECT 1 with an empty query

### ISSUE THREAD

**Issue by Eyal-Shalev** [psycopg/psycopg#790]
The current implementation of `psycopg_pool.pool.ConnectionPool.check_connection` uses the `SELECT 1` statement to check if a connection is valid.

However this goes through the PostgreSQL query planner which means we can make this process a little bit faster by sending an empty query instead.

This can be done by replacing `conn.execute("SELECT 1")` with `conn.execute("--ping")`

References:
- https://github.com/rails/rails/pull/42368
- [jackc/pgx ping implementation (Go)](https://github.com/jackc/pgx/blob/a3d9120636fc263debce595f3ba05bcd9f4ee809/pgconn/pgconn.go#L1815-L1817)
- https://github.com/sqlalchemy/sqlalchemy/issues/8491

**Comment by dvarrazzo** [comment]
Thank you very much, I will look into this idea and your implementation :slightly_smiling_face:

**Comment by dvarrazzo** [comment]
Implemented in #791.
