### ISSUE TITLE
excecute with str argument?

### ISSUE THREAD

**Issue by eykamp** [psycopg/psycopg#801]
The docs say that execute can take a string, but ruff objects.  Looking at the code, I can see why.

From docs:
query (str, bytes, [sql.SQL](https://www.psycopg.org/psycopg3/docs/api/sql.html#psycopg.sql.SQL), or [sql.Composed](https://www.psycopg.org/psycopg3/docs/api/sql.html#psycopg.sql.Composed)) – The query to execute.

From cursor.py:
`    def execute(
        self,
        query: Query,
`
From abc.py: 
`   Query: TypeAlias = Union[LiteralString, bytes, "sql.SQL", "sql.Composed"]`

Why does this union not include str?

**Comment by dvarrazzo** [comment]
Because a LiteralString is a string. LiteralString is not managed yet by Mypy. If someone uses a linter that can manage it, then they will get a warning that only literal strings are accepted.

**Comment by eykamp** [comment]
Are you sure?  From https://docs.python.org/3/library/typing.html:

typing.*LiteralString*
Special type that includes only literal strings.

Any string literal is compatible with `LiteralString`, as is another `LiteralString`. However, an object typed as just `str` is not. A string created by composing `LiteralString`-typed objects is also acceptable as a `LiteralString`.

**Comment by dvarrazzo** [comment]
Yes, I am pretty sure. Testament is the fact that psycopg works with Python 3.7, LiteralString only exists from Python 3.11. Python doesn't treat LiteralString in any special way, but type checkers can use it to spot unsafe usage, which is the goal of using `LiteralString`.

Maybe we could document that the type accepted is `LiteralString`, but at the moment it makes no runtime difference.

**Comment by eykamp** [comment]
> Maybe we could document that the type accepted is `LiteralString`.

This would resolve the issue if the intent was to not accept a regular str.  If the intent is to accept strs (including LiteralString), you should probably put str in the Union, instead of LiteralString.

Conceptually, LiteralString is a subclass of str (though I'm sure it's not implemented this way).

What I don't know is if your intent is to accept a str argument (I know that none of this impacts things at runtime).

Personally, I want things to work the way the Psycopg docs are written (i.e. I want to pass a str), and I want the code updated to reflect that, which it currently does not.
