### ISSUE TITLE
Suggestion: scalar_row to type check at runtime

### ISSUE THREAD

**Issue by tommyhe6** [psycopg/psycopg#805]
Similar to `class_row` having strict runtime checks with Pydantic, it would be nice for the new `scalar_row` to accept a primitive type with type checking at runtime. Right now, I mainly do something similar to
```
    async with conn.cursor(row_factory=args_row(lambda x: x)) as cur:
        await cur.execute(
            """
                 select exists(
                     select
                         1 
                     from A
                     where a = %s;
                 );
             """,
             (1,),
        )
        allowed = await cur.fetchone()
        assert isinstance(allowed, bool), "allowed is not bool"
```
with a final assertion. It would be nicer with 3.2.0 and above to be able to have `allowed` typed as a `bool` and checked without the manual assert afterwards.
As a side note, when do you expected 3.2.0 to be released?

**Comment by dvarrazzo** [comment]
No, this is not going to happen, psycopg is not Pydantic.
