### ISSUE TITLE
 RuntimeWarning: coroutine 'AsyncCursor.execute' was never awaited

### ISSUE THREAD

**Issue by dss010101** [psycopg/psycopg#806]
I have the code below.  read_sql is method on my DBReader class and it's using pd.read_sql.
```
import pandas as pd

async def read_sql_async(self, sql, params = None):
  t1 = timeit.default_timer()
  async with await psycopg.AsyncConnection.connect(self.connect_str) as conn:
     #await asyncio.to_thread(pd.read_sql, query, con)
     res = await asyncio.get_event_loop().run_in_executor(None, pd.read_sql, sql, conn, params)
  print(f'perf: {timeit.default_timer() - t1}')
  return res
```

the asyncio code is below
```
async def test_thread_asyncio():
   db_reader = DataReader()
   sql = "select id, name from factor f where f.id = ANY(%s)"
   threads = 20
   id_partitions = np.array_split(list(range(1, 10000)), threads)
   id_partitions = [[p.tolist()] for p in id_partitions]
   tasks = {db_reader.read_sql_async(sql, params=p) for p in id_partitions}

   for task in asyncio.as_completed(tasks):
      try:
         df = await asyncio.shield(task)
      except Exception as exc:
         log.exception(f'error retrieving data')
      else:
         if df is not None:
            print(f'shape: {df.shape}')   
```

When i run this, im getting the following error:
```
/usr/local/lib/python3.12/site-packages/pandas/io/sql.py:2674: RuntimeWarning: coroutine 'AsyncCursor.execute' was never awaited
...
...
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 631, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/workspaces/v8_pi_lab/src/v8_pi_lab/data/providers/db_provider.py", line 116, in read_sql_async
    res = await asyncio.get_event_loop().run_in_executor(None, pd.read_sql, sql, conn, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/io/sql.py", line 706, in read_sql
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/io/sql.py", line 2739, in read_query
    columns = [col_desc[0] for col_desc in cursor.description]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by dss010101** [comment]
Earlier i was trying to use concurrent.futures.ThreadPool, but noticed what may be blocking, either from the connection or from pd.read_sql, hence why i opted to write a test using asyncio.  Below is the earlier version of the code which runs, but for the blocking...

```
def read_sql(self, sql, params = None):
  t1 = timeit.default_timer()
  with warnings.catch_warnings():
	 warnings.simplefilter("ignore", UserWarning)
	 with psycopg.connect(self.connect_str, autocommit=True) as conn:
		df = pd.read_sql(sql, con = conn, params = params)
	 
	 self.log.debug(f'perf: {timeit.default_timer() - t1}')
	 return df
```
the concurrent futures code is this:
```
import concurrent.futures as cf

def test_thread_pool():
   db_reader = DataReader()
   sql = "select id, name from factor f where f.id = ANY(%s)"
   threads = 20
   id_partitions = np.array_split(list(range(1, 10000)), threads)
   id_partitions = [[p.tolist()] for p in id_partitions]
   with cf.ThreadPoolExecutor(max_workers=threads) as exec:
      futures = {
         exec.submit(db_reader.read_sql, sql, params=p):
           p for p in id_partitions
      }
      
      for future in cf.as_completed(futures):
         ids = futures[future]
         try:
            df = future.result()
         except Exception as exc:
            log.exception(f'error retrieving data for: {ids}')
         else:
            if df is not None:
               print(f'shape: {df.shape}')   

```
The output of the debug line from read_sql looks like this:
```
perf: 0.7313497869981802
perf: 0.8116309550023288
perf: 3.401154975006648
perf: 5.22201336100261
perf: 6.325166654998611
perf: 6.338692951001576
perf: 6.573095380997984
perf: 6.5976604809984565
perf: 6.8282670119951945
perf: 7.291718505999597
perf: 7.4276196580030955
perf: 7.407097272000101
perf: 8.38801568299823
perf: 9.119963648998237
```

You'll notice that it is incrementing - id have expected it to be all roughly around the same time - so it seems there is some sql blocking.   Also, the time gap between the first two threads and 3rd is always about 2-3 seconds - why is that? 
I've also tried creating a new DbReader instance for each thread..but same effect.

anyone know if the connection or pandas read_sql blocks? or how to solve?

**Comment by dvarrazzo** [comment]
I don't see an execute in this example. It must be buried in some of your helper functions. You might need to add an `await` there.

**Comment by dss010101** [comment]
> I don't see an execute in this example. It must be buried in some of your helper functions. You might need to add an `await` there.

the execute is likely in pandas read_sql.  so im doing this as shown above:

```
res = await asyncio.get_event_loop().run_in_executor(None, pd.read_sql, sql, conn, params)
```

But using the psycopg.AsyncConnection seems to be causing an error as shown above...
What is the right way to do this if it isnt a bug?

**Comment by dvarrazzo** [comment]
Ask pandas. It's not a psycopg bug. Most likely they expect a sync connection, not an async one.

**Comment by dvarrazzo** [comment]
run_in_executor is exacly used to run sync code in async framework, so I expect it would use a sync connection.

**Comment by dss010101** [comment]
> run_in_executor is exacly used to run sync code in async framework, so I expect it would use a sync connection.

yes but with the await, it should not block other coroutine. do you have better soultion/implementation?

**Comment by dvarrazzo** [comment]
This error is clearly reporting you that sync code is calling an async function like it was sync. The error happens in pandas, but it is caused by the fact that you have passed the pandas method an async object where they expect a sync one. There is nothing else to discuss here.

async/await is not magic: it is _cooperative_ concurrency. You cannot pass an async object to a sync framework and it would become magically concurrent. I invite you to read more documentation about the topic, which is outside the scope of what we can provide.
