### ISSUE TITLE
v = connection.exec_driver_sql("select pg_catalog.version()").scalar() returning bytestring instead of str on Azure Postgres with psycopg>3 and sqlalchemy2

### ISSUE THREAD

**Issue by ddimmich** [psycopg/psycopg#813]
Linking to initial discussion on SQLAlchemy's page: https://github.com/sqlalchemy/sqlalchemy/discussions/11373
Hi,

We're facing an odd issue on our machines connecting to Azure Postgres - when getting the version string in
dialects/postgresql/base.py

    def _get_server_version_info(self, connection):
        v = connection.exec_driver_sql("select pg_catalog.version()").scalar()
        print(v) # added by me for debugging

The machine connecting to the postgres server in azure prints a bytestring:

b'PostgreSQL 15.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit'

Whereas with the same setup on AWS's postgres (debian, same python 3.11, same installed requirement.txt) we get:

PostgreSQL 13.13 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit

Obviously the postgres versions are different, but even before upgrading to postgres 15 on Azure we still got the bytestring with Postgres 13.12 there. The bytes type fails to be parsed by the regex, and throws the exception below.

  File "/data/www/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3198, in _get_server_version_info
    m = re.match(
        ^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 166, in match
    return _compile(pattern, flags).match(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object

Psql otherwise works fine, and django's orm, which uses the same credentials and same postgres driver runs without issue.

When I 'hack' this line  v = connection.exec_driver_sql("select pg_catalog.version()").scalar() to have a .decode() at the end, sqlalchemy happily gets the version, and continues.

I've also checked if collation/encoding/ctype are any different but cannot figure out what might be causing it. I've also tried upgrading to the latest sqlalchemy & psycopg's to no avail. The debian machines are both running the same version and are controlled by ansible - they have the same libpq/postgres client libraries.

Not sure what else I can check.

Has anyone else experienced this behaviour?

Thank you in advance for your attention,
Damian

**Comment by ddimmich** [comment]
This happens with both psycopg 3.1.9 and 3.1.18

**Comment by ddimmich** [comment]
For reference, I was able to reproduce this using psycopg directly:

In [13]: with connection.cursor() as cur:
    ...:     print(cur.execute("select pg_catalog.version()").fetchone())
    ...: 
(b'PostgreSQL 15.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit',)

Thank you.

**Comment by ddimmich** [comment]
Figured it out - on Azure the client encoding defaulted to SQL_ASCII which psycopg takes as 'no encoding' - and ends up returning byte strings.

Adding an explicit encoding to the end of the string fixes it:

`f"db+postgresql+psycopg://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{CELERY_RESULTS_DB}?client_encoding=utf8"
`

**Comment by dvarrazzo** [comment]
That's correct: the only way that psycopg returns bytes from text fields is that the client encoding is set to SQL_ASCII. For PostgreSQL, SQL_ASCII doesn't mean ASCII, [it means no encoding](https://www.postgresql.org/docs/current/multibyte.html#MULTIBYTE-CHARSET-SUPPORTED). Therefore psycopg will not decode the data returned. Documentation is [here](https://www.psycopg.org/psycopg3/docs/basic/adapt.html#strings-adaptation).

psycopg2 is wrong from this PoV, but changing it would break too much code.
