### ISSUE TITLE
enhancement: Support for pgbouncer SHOW STATS (disabling Extended Query Protocol)

### ISSUE THREAD

**Issue by ecerulm** [psycopg/psycopg#817]
I'm connecting to pgbouncer and trying to perform a `SHOW STATS` (which will be answered by pgbouncer itself, not forwarded to Postgresql). 

It's erroring out with `ProtocolViolation: extended query protocol not supported by admin console`, which is an error generated by pgbouncer. 

As the pgbouncer documentation explains in the [Admin console section]: 

> The admin console currently only supports the simple query protocol. Some drivers use the extended query protocol for all commands; these drivers will not work for this.

I haven't seen any way to "force" simple query protocol in psycopg 3.x. See [my stackoverflow question]

 so I guess here I'm requesting two things

* Update documentation to write somewhere about Extended Query Protocol / Simple Query Protocol , since I don't think it's mentioned , at least googling `site:https://www.psycopg.org/psycopg3 "extended query protocol"` gives no results. Maybe at least mention that psycopg3 is only "Extended Query Protocol" (if that is indeed the case)  
* Add support for simple query protocol for specific commands maybe `cur.execute("", force_simple_query_protocol=True)`, 

[my stackoverflow question]: https://stackoverflow.com/questions/78472610/in-psycopg-3-x-is-it-possible-to-disable-the-extended-query-protocol?noredirect=1#comment138345595_78472610
[Admin console section]: https://www.pgbouncer.org/usage.html#admin-console

**Comment by dvarrazzo** [comment]
The question cropped up recently, see #808. Therefore I think we need to add some notes in the documentation.

You can use the [`ClientCursor`](https://www.psycopg.org/psycopg3/docs/advanced/cursors.html#client-side-binding-cursors) and keep the connection in autocommit mode.

**Comment by dvarrazzo** [comment]
Checking if the need to use autocommit can be relaxed: see #820.
