### ISSUE TITLE
Add instructions to build documentation from source 

### ISSUE THREAD

**Issue by ecerulm** [psycopg/psycopg#821]
I was trying to create a PR for https://github.com/psycopg/psycopg/issues/819

But I ran into problems trying to build the documentation from the sources

So far I tried 

```
# from a virtualenv with 3.12
cd docs 
pip install -U pip
pip install sphinx
pip install psycopg
make html
```

This fails with 

```
make html          
Running Sphinx v7.3.7
making output directory... done

Theme error:
no theme named 'furo' found (missing theme.toml?)
make: *** [html] Error 2

```

I think writing a docs/README.md with the minimal instructions on how to generate the html docs is needed.

**Comment by ecerulm** [comment]
So far the instructions as far I know should be 


```
python -m venv venv
source venv/bin/activate
pip install -U pip
pip install sphinx furo
pip install -e . 
cd docs
make html
cd _build/html
python3 -m http.server 8000
```

And then open http://localhost:8000

**Comment by dvarrazzo** [comment]
You are right, we should add it.

Quick instructions:

```
make env
source .venv/bin/activate
make serve
```

and connect to http://localhost:8000.

The proper requirement are installed by `pip install psycopg[docs]`, see the `Makefile` body.
