### ISSUE TITLE
Is possible to stdout the command run by `copy.write_row`?

### ISSUE THREAD

**Issue by Urahara** [psycopg/psycopg#828]
I'm writting a logging cursor I was able to override `execute` method to print the sql commands, but I did not found what method should I override in order to have the raw query of `copy.write_row` from copy context manager, is this possible?

**Comment by dvarrazzo** [comment]
No, `Copy.write_row()` doesn't execute a statement, only `cursor.copy()`
does. After this statement has been executed, paycopg uses the protocol
described in https://www.postgresql.org/docs/current/libpq-copy.html

**Comment by Urahara** [comment]
Thanks @dvarrazzo
