### ISSUE TITLE
Add context that can be used to register adapters

### ISSUE THREAD

**Issue by CaselIT** [psycopg/psycopg#83]
From https://github.com/sqlalchemy/sqlalchemy/issues/6842#issuecomment-925770384

I've a question, more like an use case, maybe it's better as an issue in psycopg tracker.

In the dialect I wanted to register hstore and user provided json dumps/loads globally when requiresed provided, but I think it's not advisable, since it causes issues both in the tests suite that necessarily try different combinations, and because doing so would mean that an user cannot have two engines with different configurations. So I think I'll move the registration per-connection, like in the other dialects.

Looking at how the registration happens in psycopg, my question/use case was: would it be possible for psycopg to have a "Context" class concept that could be used to register these adapters. Then in the connect call I could pass the context and the connection inherits from it? The idea being that each dialect (so basically each engine) would have its own context, I would do the registration only once, not on each connection. Something like this:

```py
ctx = psycopg.context()
psycopg.types.json.set_json_loads(my_loads, ctx)
psycopg.types.hstore.register_hstore(hstore_info, ctx)
# other register stuff with ctx
conn = psycopg.connect(..., context=ctx)
```

Note that none of this is blocking or even required, just an use case that I though of while working on the dialect, and maybe also useful for direct users of psycopg, like a library that uses it could have its own customization in a context, avoiding polluting the global state.

@dvarrazzo has already provided an implementation at https://github.com/psycopg/psycopg/compare/connection-custom-context

**Comment by dvarrazzo** [comment]
As @CaselIT mentioned, this seems an useful feature and is being added.

I will test the feature in the django backend, where it would have been useful, and let Federico to test it in SQLAlchemy, after which it can be merged to master.
