### ISSUE TITLE
Can't query bytea field with decode() within the query

### ISSUE THREAD

**Issue by DerBunteBall** [psycopg/psycopg#837]
Why e.g. this leads to the error below:

```python
conn.execute("SELECT * FROM table WHERE x = decode(%s, 'hex');", (my_var_of_type_string, ))
```

This leads to this error:

```
psycopg.errors.InvalidParameterValue: invalid hexadecimal data: odd number of digits
```

Query in PostgreSQL and DB Tools work and lead to wanted result. x is a bytea type.

I guess I'm just to silly to do it right but also can't find something on the web.

**Comment by dvarrazzo** [comment]
Hello! Could you please give us a more contained example? With a concrete
value and the example in psql.that instead works?

Thank you very much!

**Comment by DerBunteBall** [comment]
x is in PostgreSQL a bytea field storing a byte string representation of a "text hex string".

If you have this ```2c5961b15f100d4b2a6c``` as a "text hex string" to find it in the DB the SQL is this:

```sql
SELECT y, z FROM table WHERE x = decode('2c5961b15f100d4b2a6c', 'hex');
```

decode should convert the incoming "text hex string" to a bytea type.

In Python it's simply a string variable.

For PostgreSQL this should be a TEXT to BYTEA conversion I guess.

The above SQL works for me in DBeaver. So I get y, z of the wanted row.

**Comment by DerBunteBall** [comment]
Found issue.

I'm just an idiot. Copying issue. It's a bad idea to copy a hex string and don't count it.
