### ISSUE TITLE
Release libpq 17 binary packages

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#852]
As mentioned in #838. we have released 3.2 binary packages wrapping libpq 16. Therefore the features based on libpq v17 are not available yet.

This task is a reminder to make new release as soon as PostgreSQL v17 is available.

**Comment by sekrause** [comment]
> This task is a reminder to make new release as soon as PostgreSQL v17 is available.

https://www.postgresql.org/about/news/postgresql-17-released-2936/

**Comment by dvarrazzo** [comment]
Thank you for the heads up! I will try and put together binary packages across the weekend.
