### ISSUE TITLE
Unpublished dev version specified for extras

### ISSUE THREAD

**Issue by KOliver94** [psycopg/psycopg#853]
The newly released version `3.2.0` introduced an issue for people using extras such as `[c]` or `[binary]` because the specified versions for these extra requirements are `3.2.0.dev1` which cannot be resolved as these are not published on pypi.

https://github.com/psycopg/psycopg/blob/06a6e5e213577fca0fa1c6ca62def8fa5803663a/psycopg/setup.cfg#L62-L65

**Comment by dvarrazzo** [comment]
Oh no :\ fixing immediately.

**Comment by dvarrazzo** [comment]
New 3.2.1 packages will be released as soon as the CI bakes them.
