### ISSUE TITLE
How to use copy batch update data?

### ISSUE THREAD

**Issue by TinJieWang** [psycopg/psycopg#856]

**Comment by dvarrazzo** [comment]
https://www.psycopg.org/psycopg3/docs/basic/copy.html

**Comment by TinJieWang** [comment]
Referencing the official documentation's `This is more efficient than performing separate queries, but in case of several INSERT (and with some SQL creativity for massive UPDATE too) you may consider using` [copy()](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.copy)., it suggests utilizing `COPY` over `execute_many` for efficiency. However, the specific [COPY documentation page](https://www.psycopg.org/psycopg3/docs/basic/copy.html#copy) does not provide an example demonstrating the use of `COPY` for updating data. Hence, could you share any established best practices for conducting batch updates?
