### ISSUE TITLE
Batch update data user copy

### ISSUE THREAD

**Issue by TinJieWang** [psycopg/psycopg#857]
Referencing the official documentation's [section](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.copy:~:text=This%20is%20more%20efficient%20than%20performing%20separate%20queries%2C%20but%20in%20cases%20of%20multiple%20INSERTS%20%28and%20with%20ingenious%20SQL%20for%20extensive%20UPDATES%29%2C%20using%20COPY%20is%20advised.), it suggests utilizing `COPY` over `execute_many` for efficiency. However, the specific [COPY documentation page](https://www.psycopg.org/psycopg3/docs/basic/copy.html#copy) does not provide an example demonstrating the use of `COPY` for updating data. Hence, could you share any established best practices for conducting batch updates?

**Comment by dvarrazzo** [comment]
First, this is not a bug. At most you should o[pen a discussion.

Second, every single example in the COPY page is about uploading data.

The COPY docs page is adequate to people who have understanding of the COPY system and it is not a tutorial about COPY.

If you need personal tutoring, please reach out personally so we can discuss about my hourly fee for personal tuition.
