### ISSUE TITLE
psycopg-binary can't be installed with M1 CPU starting from 3.1.20

### ISSUE THREAD

**Issue by maybephilipp** [psycopg/psycopg#858]
Hello everyone!

I have issues installing psycopg-binary on macOS with M1 Pro CPU. 3.1.18 and 3.1.19 versions work, but all later ones are broken - pip says "No matching distribution found".

```
ERROR: Could not find a version that satisfies the requirement psycopg-binary==3.1.20 (from versions: 3.1.4, 3.1.5, 3.1.6, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19)
ERROR: No matching distribution found for psycopg-binary==3.1.20
```

Was m1 deprecated in your build system?

Thanks

**Comment by AshwinSundar** [comment]
I think the next version should be `3.2.1`, not `3.20`

https://www.psycopg.org/psycopg3/docs/

**Comment by maybephilipp** [comment]
> I think the next version is called `3.2.1`, not `3.1.20`

https://www.psycopg.org/psycopg3/docs/news.html#psycopg-3-1-20

**Comment by dvarrazzo** [comment]
Which version of Python are you using?

MacOS M1 packages for Psycopg 3.1.20 on are available for Python 3.10, 3.11, 3.12.

If you are you using Python 3.9, unfortunately support was dropped from some of the build infrastructure and we can't release that package anymore.

**Comment by maybephilipp** [comment]
@dvarrazzo Nah, I tried 3.11 and 3.12 - both complaining. Poetry reports:

*I tried without Poetry too, just plain `python3.11 -m venv venv && ./venv/bin/pip install psycopg-binary==3.1.20` doesn't work either*

```
Poetry
Version: 1.8.3
Python:  3.11.7

Virtualenv
Python:         3.11.7
Implementation: CPython
Path:           /Users/ileep/Library/Caches/pypoetry/virtualenvs/fin-snake-pits-nUqOSej8-py3.11
Executable:     /Users/ileep/Library/Caches/pypoetry/virtualenvs/fin-snake-pits-nUqOSej8-py3.11/bin/python
Valid:          True

Base
Platform:   darwin
OS:         posix
Python:     3.11.7
Path:       /opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11
Executable: /opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/bin/python3.11
```

**Comment by dvarrazzo** [comment]
As you can see, the `psycopg_binary-3.1.20-cp312-cp312-macosx_14_0_arm64.whl` is available in the [3.1.20 binary packages](https://pypi.org/project/psycopg-binary/3.1.20/#files). That's the package that you should receive.

If you are able to debug why you don't receive it, it would be helpful. I don't own an Apple M1 for testing.

**Comment by guychris** [comment]
Hi, I just ran into perhaps a related issue, using Python 3.8, looking at the binary release pages, there are no ARM64 MacOS packages for python 3.8 or 3.9 for psycopg-binary versions 3.1.20 or 3.2.1. https://pypi.org/project/psycopg-binary/3.2.1/#files

**Comment by dvarrazzo** [comment]
@guychris as reported above, Python 3.8 ARM for macOS are not generated because the build infrastructure doesn't support it anymore.

**Comment by guychris** [comment]
> @guychris as reported above, Python 3.8 ARM for macOS packages are not generated because the build infrastructure doesn't support it anymore.

Sorry I missed that when reading through. Thank you for confirming.

**Comment by stevejalim** [comment]
I'm also seeing this with python 3.11.3 on and ARM M1:

```
Python version: 3.11.3 (main, May 31 2023, 16:09:47) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Version info: sys.version_info(major=3, minor=11, micro=3, releaselevel='final', serial=0)
```

```
$ pip install -v psycopg-binary==3.2.1                                                                                                                                       [2024-07-08-dependency-bumps]
Using pip 24.1.2 from /Users/steve/.pyenv/versions/3.11.3/envs/REDACTED/lib/python3.11/site-packages/pip (python 3.11)
ERROR: Could not find a version that satisfies the requirement psycopg-binary==3.2.1 (from versions: 3.1.4, 3.1.5, 3.1.6, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19)
ERROR: No matching distribution found for psycopg-binary==3.2.1
```

```
$ pip install -v "psycopg[binary]==3.2.1" --no-cache-dir                                                                                                                     [2024-07-08-dependency-bumps]
Using pip 24.1.2 from /Users/steve/.pyenv/versions/3.11.3/envs/REDACTED/lib/python3.11/site-packages/pip (python 3.11)
Collecting psycopg==3.2.1 (from psycopg[binary]==3.2.1)
  Obtaining dependency information for psycopg==3.2.1 from https://files.pythonhosted.org/packages/8a/0e/0f755db36f47f96464463385552f8f132a981731356837c9a30a11ab2d35/psycopg-3.2.1-py3-none-any.whl.metadata
  Downloading psycopg-3.2.1-py3-none-any.whl.metadata (4.2 kB)
Collecting typing-extensions>=4.4 (from psycopg==3.2.1->psycopg[binary]==3.2.1)
  Obtaining dependency information for typing-extensions>=4.4 from https://files.pythonhosted.org/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl.metadata
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
INFO: pip is looking at multiple versions of psycopg[binary] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement psycopg-binary==3.2.1; implementation_name != "pypy" and extra == "binary" (from psycopg[binary]) (from versions: 3.1.4, 3.1.5, 3.1.6, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19)
ERROR: No matching distribution found for psycopg-binary==3.2.1; implementation_name != "pypy" and extra == "binary"
```

**Comment by dvarrazzo** [comment]
I have asked for some help at https://github.com/pypa/cibuildwheel/discussions/1926 because I have no direct experience about macOS build target or whatever else might make the newer wheel not compatible.

**Comment by dvarrazzo** [comment]
It seems that it now impossible to build binary packages targeting macOS 11, 12, 13:

- Scaleway, from which we were previously using runners, now only makes macOS 14 runners available.
- Githob Actions runners macos-14 can only build wheels for macOS 14.
- Github Actions runers macos-13-arm64 are not available: [a test build](https://github.com/psycopg/psycopg/actions/runs/9846850845) started yesterday hasn't been picked up by a runner in 12 hours.

So, I see three solutions:

1. Don't do anything. ARM64 binary packages will be made available only for macOS 14. M1 users can upgrade their system, or using python or c implementation.
2. Build the binary packages on an Intel macos-12 runner and test the artifact on ARM macos-14 runner. This would only work until the macos-12 runners are available, which might not be for long.
3. Build every dependency from source. This is beyond the amount of work I am willing to do for free and my macOS knowledge.

Most likely, 1 will happen. I don't think 2. is worth. If someone is willing to pay for a few days of work to put together 3 please let me know.

**Comment by dvarrazzo** [comment]
For extra info, the schedule [macOS EOL](https://endoflife.date/macos) is

- macOS 11 EOL since September 2023
- macOS 12 will be EOL in 4 months (Oct 2024)
- macOS 13 will be EOL in 1 year 4 months (Cot 2025)

**Comment by maybephilipp** [comment]
Wow, haha, I didn't want to upgrade cus of the exact opposite reason that something will be broken since 14 is still pretty fresh :D

OK, I will upgrade the system then, for me it's not a problem (idk how it is for others). Thank you for this information!

btw I have macOS Ventura 13.5.2. So this actually means that builds will not works for M2 and M3 either.. This makes me less sad.

_Kinda miss time now when I was running archlinux on a normal pc back in time 😅_

**Comment by dvarrazzo** [comment]
I have added some [documentation](https://www.psycopg.org/psycopg3/docs/basic/install.html#binary-installation) and [release notes](https://www.psycopg.org/psycopg3/docs/news.html#psycopg-3-1-20) specifying that macOS binary packages are now only supported for macOS 14 and newer.

Please update your OS or use a [pure Python installation](https://www.psycopg.org/psycopg3/docs/basic/install.html#pure-python-installation) or a [local C build](https://www.psycopg.org/psycopg3/docs/basic/install.html#local-installation).

**Comment by stevejalim** [comment]
Thanks @dvarrazzo for the clear summary - I apprecaite it. I'll get my colleagues to upgrade their development machines from 13 to 14 as well.

Thank you, too, for all your work on psycopg. 🙇 👍 👍 👍 👍 👍

**Comment by thierryba** [comment]
you can always set MAC_OSX_DEPLOYMENT_TARGET=11.0 in your env to build for any previous version of macOS.

**Comment by dvarrazzo** [comment]
@thierryba 

> you can always set MAC_OSX_DEPLOYMENT_TARGET=11.0 in your env to build for any previous version of macOS.

Not in my experience. If you are able to build binary for macOS 11 on the Github Action runners a MR is welcome.

**Comment by thierryba** [comment]
I am not too familiar with gihub action but if I find a way to try it out, I will make a PR.

**Comment by thierryba** [comment]
BTW I did it here https://github.com/psycopg/psycopg/pull/925

Any suggestion on how to move this forward?

**Comment by dvarrazzo** [comment]
With the extremely kind help of @bwoodsend, psycopg-binary 3.2.4 will ship libraries built from source, therefore unaffected by `MACOSX_DEPLOYMENT_TARGET` inflation.
