### ISSUE TITLE
String type annotations break backwards compatibility

### ISSUE THREAD

**Issue by adebrecht661** [psycopg/psycopg#860]
3.2 changed some type annotations to use string annotations instead of types, e.g.

3.1: `DictRow: TypeAlias = Dict[str, Any]`
3.2: `DictRow: TypeAlias = "dict[str, Any]"`

This breaks any code using `|` for type unions with these types (`DictRow | tuple`, for example), which worked in 3.1 but in 3.2 raises a `TypeError: unsupported operand type(s) for |: 'str' and 'type'`.

**Comment by dvarrazzo** [comment]
Thank you for your report.

Which Python version are you using?

**Comment by adebrecht661** [comment]
This is on Python 3.12.4.

**Comment by adebrecht661** [comment]
Looking at the linked PR and the commit history, that seems like a reasonable solution.

**Comment by dvarrazzo** [comment]
@adebrecht661 as a workaround in order to get unblocked before we make a new release, is the breakage solved if you define your typealias as string as well?

```python
MyType: TypeAlias = "DictRow | tuple"
```

**Comment by adebrecht661** [comment]
We've pinned to < 3.2 for now, but I expect that would also work.
