### ISSUE TITLE
psycopg >3.1.19 — connection failed, "could not generate nonce": M1 Mac

### ISSUE THREAD

**Issue by l00sed** [psycopg/psycopg#863]
Hi, I'm experiencing an issue where the latest version of psycopg (3.2.1) is unable to run Django migrations because of a failed connection. Postgres is running in a separate Docker container. The error I see when running `./manage.py migrate`:

`django.db.utils.OperationalError: connection failed: connection to server at "<pg_docker_container_ip>", port <port_number> failed: could not generate nonce`

Unfortunately, the traceback messages were not useful to me in diagnosing the problem:
```
  File ".../site-packages/django/db/backends/base/base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
  File ".../site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File ".../site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File ".../site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/django/db/backends/postgresql/base.py", line 277, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/psycopg/connection.py", line 119, in connect
    raise last_ex.with_traceback(None)
django.db.utils.OperationalError: connection failed: connection to server at "<pg_container_ip>", port <pg_container_port> failed: could not generate nonce
```
I did find the "could not generate nonce" string in a grep that returned the compiled `psycopg-binary`. So the error is definitely getting thrown from psycopg.  Would this have something to do with the Django SECRET_KEY? Is that how the nonce is generated?

Thanks for your help.

Mac M1
psycopg>3.1.19
django==5.0.6
python==3.12.4

**Comment by dvarrazzo** [comment]
The error seems to come from the libpq:

https://github.com/postgres/postgres/blob/2329cad1b93f268c0ec6848732c6db43eb46156c/src/interfaces/libpq/fe-auth-scram.c#L358-L362

I don't know exactly what is the difference in the libpq and openssl bundled between 3.1.19 and 3.1.20, because on macOS we bundle the libraries coming from the system at build time.

I don't think it is related to the django secret key, no.

As a workaround, it looks by the location of the error that you can disable SCRAM authentication to work around the error.

**Comment by l00sed** [comment]
Interesting... thanks for those added insights. I'll take a look at SCRAM and see what that's about. If it's doing favors for security, then it might be something we don't want to disable. I'll give it a shot and report back next week.

**Comment by dvarrazzo** [comment]
You may need to update your local libraries to get the right support for scram. Also notice that we don't support binary packages on macOS < 14 since 3.1.20, see 858. This could, or couldn't be related to your issue.

**Comment by l00sed** [comment]
MacOS 14.5 here, but psycopg is actually run on Alpine v3.20

**Comment by l00sed** [comment]
I'm building the Postgres 16 image on Alpine 3.20.
I tried manually `apk add libpq` before pip installing `psycopg[binary]`.
I was able to get the application running by overriding `/var/lib/postgresql/data/pg_hba.conf` with:
```
host    all             all             all                     trust
```
Obviously not acceptable for production, but at least it's clear that this is related to the MD5/SCRAM algorithm.
I still haven't found a solution.

**Comment by l00sed** [comment]
I looked back over the `psycopg` documentation and realized I hadn't loaded `libpq` at all as a dependency. However, adding it (with `apk add libpq`) did not resolve the issue. There is no `libpq5` for Alpine Linux, but there is a `libpq` and `libpq-dev`. I was finally able to get something working with the following packages:
```
apk add libpq postgresql-dev
```
However, the nonce issue remained for `psycopg[binary]`. Switching to `psycopg[c]==3.2.1` works with these dependencies, though. No message or error generating nonce.

We'll use the C implementation for now, but perhaps this information can help your team.

**Comment by l00sed** [comment]
The pure Python implementation also works with the same two dependencies on Alpine. It's only the `[binary]` implementation that seems to fail with the nonce issue. Perhaps I still don't understand when it's appropriate to use one or the other and I never should have been using the binary version.

**Comment by dvarrazzo** [comment]
> But now I'm realizing that may be less relevant.. because psycopg is actually run containerized (Alpine Linux) on the Mac

You should probably fix the ticket title then.

On alpine we use system libraries for openssl and we build the libpq from scratch. This is done by the `tools/build/build_libpq.sh` script.

`git log -p 3.1.19..3.1.20 --  tools/build/build_libpq.sh` shows the changes in the way the libpq is built between these two versions. Main changes are:

- OpenSSL bumped from 1.1.1 to 3.3.1 on the systems where we build the OpenSSL, but I think we use a pakcaged version on alpine
- Ssmething changed so we need to add the openssl-dev package
- We made this change in the way we look for libraries when we build libpq

```diff
     ./configure --prefix=${LIBPQ_BUILD_PREFIX} --sysconfdir=/etc/postgresql-common \
         --without-readline --without-icu \
         --with-gssapi --with-openssl --with-pam --with-ldap \
-        CPPFLAGS=-I${LIBPQ_BUILD_PREFIX}/include/ LDFLAGS=-L${LIBPQ_BUILD_PREFIX}/lib
+        CPPFLAGS=-I${LIBPQ_BUILD_PREFIX}/include/ \
+        LDFLAGS="-L${LIBPQ_BUILD_PREFIX}/lib -L${LIBPQ_BUILD_PREFIX}/lib64"
     make -C src/interfaces/libpq
     make -C src/bin/pg_config
     make -C src/include
```

So, I propose this action plan:

- remove the libpq from your docker, and remove `psycopg-binary` package, make sure that `import psycopg` fails.
- Run this script to build the libpq. You can set
  - `export LIBPQ_VERSION=16.3`
  - `export OPENSSL_VERSION=3.3.1`
- run `pip install ./psycopg_c` to build psycopg-c from source
- check if scram fails: if it does we have a repro
- can you kick the script until it builds a working libpq? If so a MR is welcome.

**Comment by l00sed** [comment]
So `pip install ./psycopg_c` will call the script (tools/build/build_libpq.sh) to build `libpq`? But this only builds `libpq` if it can't be found installed under system packages?

I don't understand how to test if postgres-c gets the nonce issue. Will I need to likewise `pip install ./psycopg` in order to test (`import psycopg`)?

The `pip install ./psycopg_c` and `pip install ./psycopg` command work with `apk add postgresql-dev` (this installs `libpq` and `libpq-dev` as dependencies— among others).

If I understand you correctly, I'll remove `postgresql-dev` and try re-running the `pip install` commands.

**Comment by l00sed** [comment]
If I run `pip install ./psycopg_c` without `apk add postgresql-dev`, I get:
```
No such file or directory: 'pg_config'
```
I see this SO answer that says `postgresql-dev` supplies the `pg_config` command on Alpine. So this would also automatically install `libpq` and `libpq-dev`.

**Comment by dvarrazzo** [comment]
> So pip install ./psycopg_c will call the script (tools/build/build_libpq.sh) to build libpq?

No, it will not.

But this only builds libpq if it can't be found installed under system packages?

`build_libpq.sh` is used in the preparation of the `binary` package. Building the binary consist pretty much in building a libpq with the desired characteristics and then build the c module (with some renaming in the way (performed by `copy_to_binary.py`).

So, it seems to me that the libpq you get from your system (the one you use with `binary` or with `c`) doesn't have the problem. Therefore my request was to build the libpq and then build the c package to obtain something similar to the shipped binary package, and see if it works.

The build libpq script also build the `pg_config` program that you reported missing if you don't install `postgresql-dev`.

Looking back at the history, we only started to build the libpq because the one shipped was too old (3593297f5222e5457d9e256a75efc5c85a58adad). We might review this choice if now the package provided is adequate, but considering that libpq 17 will provide several features I'm not sure it will be possible.

**Comment by l00sed** [comment]
Ok, thanks very much for laying that out for me. I'm beginning better understand how it works. For the time being, the available Alpine libpq (and pg_config supplied by postgresql-dev) works as expected— though, I see you're correct about it being an older version.

I will see if I can pinpoint the issue with the psycopg-generated libpq if I have time. I think there must be an issue building it on Alpine; although, perhaps it's unique to my setup.

**Comment by l00sed** [comment]
I ran the `./build_libpq.sh` script and first ran into an issue with the missing `bison` package. I did `apk add bison` (actually I added it in the `apk add` statement in the `build_libpq` script). It looks like everything is building successfully after that. However, `make -C src/bin/pg_config install` doesn't seem actually install `pg_config` into the PATH?

I'm able to `pip install ./psycopg`. If I try to `pip install ./psycopg_c` I get:
```
Processing ./psycopg_c
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-cvp4t0bt/psycopg_c.egg-info
      writing /tmp/pip-modern-metadata-cvp4t0bt/psycopg_c.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-cvp4t0bt/psycopg_c.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-modern-metadata-cvp4t0bt/psycopg_c.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-cvp4t0bt/psycopg_c.egg-info/SOURCES.txt'
      couldn't run 'pg_config' --includedir: [Errno 20] Not a directory: 'pg_config'
      error: [Errno 20] Not a directory: 'pg_config'
      [end of output]
```

After `./build_libpq.sh` finishes, `which pg_config` does not return a result. This makes me think there's an issue with the `make install`... I do see `/tmp/libpq.build/` with `bin/pg_config`.

One thing that I ran into—
I was intermittently receiving an issue with the `curl` request to postgres. I was getting this [SSL error](https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno) and fixed it by doing `apk add git && git init && git config --global http.postBuffer 524288000`. Seems like a timeout related to the size of the PG tar?

After getting that working, I am now stuck on pip installing `pip install ./psycopg_c`. If I run a python shell and try to `import psycopg`, I receive:
```
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
```

I'm not sure why libpq isn't being recognized after the `make -C install` step? Is there another step missing?

**Comment by dvarrazzo** [comment]
> However, make -C src/bin/pg_config install doesn't seem actually install pg_config into the PATH?

Probably it's installed in `LIBPQ_BUILD_PREFIX`, which might default to `/tmp/libpq.build`. The `lib`, `lib64`, `bin` directories are taken from there, so `$PATH`, `$LD_LIBRARY_PATH` must keep them into account.

> I was intermittently receiving an issue with the curl request to postgres. I was getting this [SSL error](https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno) and fixed it by doing apk add git && git init && git config --global http.postBuffer 524288000. Seems like a timeout related to the size of the PG tar?

You mean from `https://github.com/postgres/postgres/archive/${postgres_tag}.tar.gz`? Strange. I thought in the past to get timeouts when trying to download the archive from the postgresql.org mirror. I don't remember seeing this failing in CI recently.

> After getting that working, I am now stuck on pip installing pip install ./psycopg_c. If I run a python shell and try to import psycopg, I receive:

I find strange that, if `pip install ./psycopg_c` succeeds, then importing it fails. Maybe you can throw a `-v` at that command to see if there are more details? But I would expect it to fail clearly. Maybe you have pip and python from two different installations?

> I'm not sure why libpq isn't being recognized after the make -C install step? Is there another step missing?

I think you are just missing to set a few env vars:

https://github.com/psycopg/psycopg/blob/be4f63915188888d3748fee63c46cbc0e838acff/.github/workflows/packages-bin.yml#L71-L72

the second of which is the one I'm the least convinced about, because it's one of the entries that changed in the version that you report not working (it was changed in badc0b85da6cdae723699ca7f429b8dda85ad9b8).
