### ISSUE TITLE
Mypy checks failing for setting row_factory on cursor version 3.2.1

### ISSUE THREAD

**Issue by gpiks** [psycopg/psycopg#864]
I recently started running into a mypy error with version 3.2.1 setting row_factory

Per the docs: https://www.psycopg.org/psycopg3/docs/advanced/rows.html#row-factories

I should be able to set row_factory on the cursor directly like so:
```python
from psycopg.rows import dict_row
import psycopg

conn_info = psycopg.conninfo.make_conninfo(
    user="user",
    password="password",
    host="host",
    port=123,
    dbname="db",
)


conn = psycopg.connect(conn_info)
with conn.cursor() as cur:
    cur.row_factory = dict_row
```

However, when running mypy on this I receive an error:
```
script.py:15: error: Incompatible types in assignment (expression has type "Callable[[BaseCursor[Any, Any]], RowMaker[dict[str, Any]]]", variable has type "RowFactory[tuple[Any, ...]]")  [assignment]
script.py:15: note: "RowFactory[tuple[Any, ...]].__call__" has type "Callable[[Cursor[Any]], RowMaker[tuple[Any, ...]]]"
```

Would you be able to investigate why this is failing?

**Comment by dvarrazzo** [comment]
I confirm the same error, but it doesn't seem a change appearing in 3.2.1. I see the same error in 3.1.19 at least. In which version you didn't have the error?

Using this `test.py`:

```python
import psycopg
from psycopg.rows import dict_row

conn = psycopg.connect("")
with conn.cursor() as cur:
    reveal_type(cur.row_factory)
    reveal_type(dict_row)
    cur.row_factory = dict_row
    print(cur.execute("select 1 as foo, 2 as bar").fetchone())
```

Note that the cursor works well and the output is the one expected. It's just mypy to complain.

```
$ mypy test.py 
test.py:6: note: Revealed type is "psycopg.rows.RowFactory[builtins.tuple[Any, ...]]"
test.py:7: note: Revealed type is "def (cursor: psycopg.cursor.BaseCursor[Any, Any]) -> psycopg.rows.RowMaker[builtins.dict[builtins.str, Any]]"
test.py:8: error: Incompatible types in assignment (expression has type "Callable[[BaseCursor[Any, Any]], RowMaker[dict[str, Any]]]", variable has type "RowFactory[tuple[Any, ...]]")  [assignment]
test.py:8: note: "RowFactory[tuple[Any, ...]].__call__" has type "Callable[[Cursor[Any]], RowMaker[tuple[Any, ...]]]"
```

Whereas defining `with conn.cursor(row_factory=dict_row) as cur:` causes no mypy error and the output is:

```
test.py:6: note: Revealed type is "psycopg.rows.RowFactory[builtins.dict[builtins.str, Any]]"
test.py:7: note: Revealed type is "def (cursor: psycopg.cursor.BaseCursor[Any, Any]) -> psycopg.rows.RowMaker[builtins.dict[builtins.str, Any]]"
```

The problem, I think, is that if your `cur` variable is a `Cursor[TupleRow]`. By setting `cur.row_factory` you are making it become a `Cursor[DictRow]` and mypy is unhappy about that. 

A proof is the following test script. By lying to Mypy and annotating `dcur.row_factory` as `DictRow`, it will support the `dict_row` assignment. 

```python
import psycopg
from psycopg.rows import dict_row
from typing import cast

```python
conn = psycopg.connect("")
with conn.cursor() as cur:
    dcur = cast(psycopg.Cursor[psycopg.rows.DictRow], cur)
    dcur.row_factory = dict_row
    print(cur.execute("select 1 as foo, 2 as bar").fetchone())
```

This, to me, proves that the problem is with mypy unable to recognize `cur` changing type.

As far as I can see, psycopg works well, but the typing system annotations don't allow to transform a `Cursor[TupleRow]` into a `Cursor[DictRow]` using an assignment. I think that, if you want to make the type system happy and consistent with the runtime system you should use `Cursor(row_factory=dict_row)` in the constructor, so that the type of `cur` is set ok from the beginning.
