### ISSUE TITLE
row_factory is not accepting class_row on psycopg 3.2 and pyright 1.1.365+

### ISSUE THREAD

**Issue by Holi0317** [psycopg/psycopg#865]
```py
import psycopg
from psycopg.rows import RowFactory, class_row
from pydantic import BaseModel


class Person(BaseModel):
    name: str


conn = psycopg.connect("")

# Asking pyright to infer the signature will fail
with conn.cursor(row_factory=class_row(Person)) as cur:
    pass

# Explicit type hinting works
factory: RowFactory[Person] = class_row(Person)
with conn.cursor(row_factory=factory) as cur:
    pass
```

Error message from pyright is:

```
/Volumes/Projects/psycorow/main.py
  /Volumes/Projects/psycorow/main.py:12:40 - error: Argument of type "type[Person]" cannot be assigned to parameter "cls" of type "type[T@class_row]" in function "class_row"
    "type[Person]" is incompatible with "type[tuple[Any, ...]]"
    Type "type[Person]" is incompatible with type "type[tuple[Any, ...]]" (reportArgumentType)
1 error, 0 warnings, 0 informations 
```

This only shows up in pyright since [1.1.365](https://github.com/microsoft/pyright/releases/tag/1.1.365) and psycopg 3.2. 3.1 and mypy are not affected.

| Psycopg version | Typechecker | Result |
| -- | -- | -- |
| 3.1.20 | mypy | Success |
| 3.2.1 | mypy | Success |
| 3.1.20 | pyright 1.1.364 | Success |
| 3.2.1 | pyright 1.1.364 | Success |
| 3.1.20 | pyright 1.1.365, 1.1.370 | Success |
| 3.2.1 | pyright 1.1.365, 1.1.370 | Failing |

**Comment by dvarrazzo** [comment]
We don't support pyright and, in my opinion we are doing the right thing. Therefore I believe you should open a ticket to pyright.

If they can suggest us to do something different, and what they suggest is compatible with mypy, we are happy to address the problem.

**Comment by dvarrazzo** [comment]
One piece of info that might be useful, if someone wants to investigate in the pyright behaviour: I think that the only relevant difference between 3.1 and 3.2 in the rows module comes from 323be52689ec4180e75c4dd0dd5fe7b1734e2387 and is the addition of a default to the `Row` typedef:

https://github.com/psycopg/psycopg/blob/be4f63915188888d3748fee63c46cbc0e838acff/psycopg/psycopg/rows.py#L35

**Comment by mittomen** [comment]
Hi, I was looking at the module above and when I changed the definition to
`Row = TypeVar("Row", covariant=True, default=TupleRow)`, 
where the default type is assigned without the quotes, `pyright` became suddenly happy and it seemingly did not affect `mypy` (at least on my codebase).
I'm not an expert, so I'm just hoping, this is actually useful info, but :man_shrugging:

**Comment by dvarrazzo** [comment]
In most context related to types, types can be expressed both as objects and as string representing objects. This is important especially when creating mutually referring objects. With postponed annotations, types can be expressed no problem as types in annotations, but in context different than an annotation, like in this case, the postponement must be explicit.

So I think this can be reported as an error to pyright.
