### ISSUE TITLE
Build fails with strict-aliasing violations

### ISSUE THREAD

**Issue by eli-schwartz** [psycopg/psycopg#867]
I tried to build with the following *FLAGS to optimize the build: `-flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing`

The -Werror=* flags are important to detect cases where the compiler can try to optimize based on assuming UB cannot happen, and miscompile code that has UB in it. strict-aliasing issues are always bad but LTO can make them even worse.

I got this error:
```
2024-07-15 03:37:17,743 root INFO x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wformat -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=incompatible-pointer-types -DNDEBUG -fPIC -I/usr/include/postgresql-16 -I/usr/include/python3.12 -c psycopg_c/_psycopg.c -o /var/tmp/portage/dev-python/psycopg-3.1.19/work/psycopg-3.1.19-python3_12/build/temp.linux-x86_64-cpython-312/psycopg_c/_psycopg.o
psycopg_c/_psycopg.c: In function ‘__pyx_f_9psycopg_c_8_psycopg__array_load_binary’:
psycopg_c/_psycopg.c:34509:16: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
34509 | __pyx_v_dimptr = (__pyx_v_buf + (3 * (sizeof(uint32_t))));
      |                ^
In file included from /usr/include/sys/types.h:176,
                 from /usr/include/stdlib.h:514,
                 from /usr/include/python3.12/Python.h:23,
                 from psycopg_c/_psycopg.c:42:
psycopg_c/_psycopg.c: In function ‘__pyx_f_9psycopg_c_8_psycopg_20IntervalBinaryLoader_cload’:
psycopg_c/_psycopg.c:49642:52: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
49642 | __pyx_v_val = be64toh((((uint64_t *)__pyx_v_bedata)[0]));
      |                                                    ^
psycopg_c/_psycopg.c: In function ‘__pyx_f_9psycopg_c_8_psycopg_17FloatBinaryDumper_cdump’:
psycopg_c/_psycopg.c:56365:52: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
56365 | __pyx_v_beval = htobe64((((uint64_t *)(&__pyx_v_d))[0]));
      |                                                    ^
psycopg_c/_psycopg.c: In function ‘__pyx_f_9psycopg_c_8_psycopg_18Float4BinaryDumper_cdump’:
psycopg_c/_psycopg.c:56557:52: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
56557 | __pyx_v_beval = htobe32((((uint32_t *)(&__pyx_v_f))[0]));
      |                                                    ^
psycopg_c/_psycopg.c: In function ‘__pyx_f_9psycopg_c_8_psycopg_19NumericBinaryLoader_cload’:
psycopg_c/_psycopg.c:57961:20: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
57961 |   __pyx_v_digitptr = (__pyx_v_data + (sizeof(__pyx_v_behead)));
      |                    ^
```

Reported downstream at https://bugs.gentoo.org/935401
Full build log: [build.log](https://github.com/user-attachments/files/16231403/build.log)

**Comment by eli-schwartz** [comment]
Looking at the generated cython file, e.g. line 49642 points to https://github.com/psycopg/psycopg/blob/be4f63915188888d3748fee63c46cbc0e838acff/psycopg_c/psycopg_c/types/datetime.pyx#L976

There are prior comments about handling the aliasing rules :) at e.g. https://github.com/psycopg/psycopg/blob/be4f63915188888d3748fee63c46cbc0e838acff/psycopg_c/psycopg_c/types/numeric.pyx#L393-L395

**Comment by dvarrazzo** [comment]
Hello,

I thought I had fixed all the undefined behaviours in the context of #734. There is also a CI job to check for regressions:

https://github.com/psycopg/psycopg/blob/be4f63915188888d3748fee63c46cbc0e838acff/.github/workflows/tests.yml#L126-L131

I understand that the right fix for the problem you report:

https://github.com/psycopg/psycopg/blob/be4f63915188888d3748fee63c46cbc0e838acff/psycopg_c/psycopg_c/types/datetime.pyx#L973-L978

is to either define:

     cdef int64_t bedata[2]

and extract days and months from the two halves of the second 64 bits item, or to do it with two memcpy's.

However I am curious about why our test didn't find the issue: maybe your definition is stricter. Could you please propose a change to the CI job that would highlight the issue you found?

Thank you very much!

**Comment by dvarrazzo** [comment]
I assume this would be a solution for the issue (still untested):

```diff
diff --git a/psycopg_c/psycopg_c/types/datetime.pyx b/psycopg_c/psycopg_c/types/datetime.pyx
index 2e1f1eee..44b227ed 100644
--- a/psycopg_c/psycopg_c/types/datetime.pyx
+++ b/psycopg_c/psycopg_c/types/datetime.pyx
@@ -971,11 +971,11 @@ cdef class IntervalBinaryLoader(CLoader):
     format = PQ_BINARY
 
     cdef object cload(self, const char *data, size_t length):
-        cdef int32_t bedata[4]
+        cdef int64_t bedata[2]
         memcpy(&bedata, data, sizeof(bedata))
-        cdef int64_t val = endian.be64toh((<uint64_t *>bedata)[0])
-        cdef int32_t days = endian.be32toh(bedata[2])
-        cdef int32_t months = endian.be32toh(bedata[3])
+        cdef int64_t val = endian.be64toh(bedata[0])
+        cdef int32_t days = endian.be32toh((<uint32_t *>bedata)[2])
+        cdef int32_t months = endian.be32toh((<uint32_t *>bedata)[3])
 
         cdef int years
         with cython.cdivision(True):
```

however seeing the CI first failing and then fixed would reassure me.

**Comment by eli-schwartz** [comment]
Thanks for the fix! And yeah, runtime sanitizer checks are good but only tell you if on this particular run you hit an issue, whereas the -Werror tells you when the analyzer detects you violated the rule.

They can both catch (somewhat overlapping, somewhat different) issues.

**Comment by dvarrazzo** [comment]
This is what randomized tests are for :slightly_smiling_face: 

Anyway I have added the warnings you proposed in this ticket to our test suite, thank you very much!
