### ISSUE TITLE
test failure with assert "mypy: "types/__init__.py" shadows library module "types""

### ISSUE THREAD

**Issue by RoyZhang2022** [psycopg/psycopg#869]
Today I run the pytest with newest code on linux with Postgres docker image. I saw the following errors. Is it caused by the `tests\types` conflicts with library module "types"?

```
_______________________________________________________________________________________ test_version ________________________________________________________________________________________

mypy = <tests.fix_mypy.mypy.<locals>.MypyRunner object at 0x7f3c3271c3b0>

    def test_version(mypy):
        cp = mypy.run_on_source(
            """\
    from psycopg_pool import __version__
    assert __version__
    """
        )
>       assert not cp.stdout
E       assert not b'mypy: "types/__init__.py" shadows library module "types"\nnote: A user-defined top-level module with name "types" is not supported\n'
E        +  where b'mypy: "types/__init__.py" shadows library module "types"\nnote: A user-defined top-level module with name "types" is not supported\n' = CompletedProcess(args=['mypy', '--strict', '--show-error-codes', '--no-color-output', '--no-error-summary', '--config-...init__.py" shadows library module "types"\nnote: A user-defined top-level module with name "types" is not supported\n').stdout

pool/test_module.py:8: AssertionError
```

**Comment by RoyZhang2022** [comment]
I found I could make it work by rename `tests\types` to `tests\test_types`

**Comment by dvarrazzo** [comment]
But:

- CI runs the tests every day and [they passed ok](https://github.com/psycopg/psycopg/actions/runs/9952135333) with [the latest version of the packages](https://github.com/psycopg/psycopg/actions/runs/9952135333/job/27492911320#step:14:122).
- `types` is not a top-level package, `tests` is: [it has an `__init__.py` file](https://github.com/psycopg/psycopg/tree/master/tests).
- `psycopg` has also [a sub-package called `types` too](https://github.com/psycopg/psycopg/tree/master/psycopg/psycopg) which doesn't seem to bother your mypy.

So, I think you have something broken in your environment. Maybe you have `tests` in your `PYTHONPATH`?

If you share more details about how you run your tests maybe we can see what's wrong, but there is nothing wrong in this codebase: we don't have a top-level module called `types`.
