### ISSUE TITLE
SQL query doesn't work

### ISSUE THREAD

**Issue by pythonaddict** [psycopg/psycopg#871]
Does anyone have any idea why it doesn't work?

```
import psycopg


DATABASE_NAME = "mydb"

SCHEMA_NAME = "myschema"

DBLOGIN = "mysuperuser"

PASSWD = "mypass"

db = psycopg.Connection.connect(f"host=localhost port=5432 dbname={DATABASE_NAME} user={DBLOGIN} password={PASSWD}")

thecursor = db.cursor()

 

schema_create_sql = "CREATE SCHEMA IF NOT EXISTS %s"

thecursor.execute(schema_create_sql, [SCHEMA_NAME])

db.commit()
```

It gives the following error:

psycopg.errors.SyntaxError: syntax error at or near "$1"

LINE 1: CREATE SCHEMA IF NOT EXISTS $1

**Comment by dvarrazzo** [comment]
Yes, it's documented [here](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#server-side-binding). You can't bind the schema name on the server, you can only bind query values.

You must compose the query on the server using `psycopg.sql` objects. Something like:

```python
cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(SCHEMA_NAME)))
```

**Comment by pythonaddict** [comment]
Thanks. You should add this detail to this page too:

https://www.psycopg.org/psycopg3/docs/basic/params.html

**Comment by dvarrazzo** [comment]
> Thanks. You should add this detail to this page too:
> 
> https://www.psycopg.org/psycopg3/docs/basic/params.html

You might read it at:

> Only query values should be bound via this method: it shouldn’t be used to merge table or field names to the query. If you need to generate SQL queries dynamically (for instance choosing a table name at runtime) you can use the functionalities provided in the [psycopg.sql](https://www.psycopg.org/psycopg3/docs/api/sql.html#module-psycopg.sql) module:
