### ISSUE TITLE
Failing to update `notifies` while changing from 3.1 to 3.2

### ISSUE THREAD

**Issue by Blackeagle52** [psycopg/psycopg#873]
Hi Daniele,

This issue gonna have some examples, so I want to preface with an excuse for the length of this issue.

Currently I'm using psycopg3.1 within a Django app stack, and I fail to update to version 3.2. My app (quite generally described) has services notifying of tasks in a channel, and another service listening to those channels. But I've reduced my problem to a generic psycopg3.2 only example.

First I want to show you how the app currently uses LISTEN/NOTIFY (with version 3.1)

```python
    def listen(self):
        connection.ensure_connection()
        real_con = connection.connection
        real_con.autocommit = True
        with connection.cursor() as cursor:
            for name in self.tasks:
                cursor.execute(sql.SQL("LISTEN {};").format(sql.Identifier(name)))
        return real_con

    def poller(self):
        real_con = self.listen()
        while True:
            if select.select([real_con], [], [], self.timeout) == ([], [], []):
                logger.debug("Polling timeout, time to check for periodics to execute")
                yield None
            else:
                for notify in real_con.notifies():
                    logger.debug(
                        "Got NOTIFY: %s, %s, %s", notify.pid, notify.channel, notify.payload
                    )
                    yield notify.channel
```

Depending the yield-value of the poller certain CRUD stuff happened in a transaction. Having read #760, it appears it is bad practice to use the connection while the generator is being consumed, and a lock has been introduced while the `notifies` generator runs. 

This lead to a rewrite of the above code, but my attempts have been failures. My current solution does not receive all notifies. To reduce the problem I've created a small setup to reproduce the problem. I have the following two files, `main.py` and `notifier.py`. 
First step is to start `main.py` to activate the listeners. Then run the notifier a few times. 
After the files are the logs the files print, and the `postgres -E` log.

I hope the problem is properly described, and you can help me find out what's going wrong. As proper examples how to use `notifies` are hard to find. 

Thanks in advance,
Peter

 

`main.py`
```python
import datetime
import time

import psycopg
from psycopg import sql

channels = ['channel_1', 'channel_2']


def log(msg):
    print(datetime.datetime.utcnow().isoformat(), msg)


def __listen(connection):
    with connection.cursor() as cursor:
        for channel in channels:
            log(f"Listen on channel {channel}")
            cursor.execute(sql.SQL("LISTEN {};").format(sql.Identifier(channel)))


def __poller(connection, timeout):
    while True:
        n = None
        for notify in conn.notifies(timeout=timeout):
            n = notify
            break
        yield n


def run(connection):
    __listen(connection)
    for notify in __poller(connection, timeout=30):
        if notify:
            log(f"Got NOTIFY: {notify.channel}, {notify.payload}")
            time.sleep(3)  # Sleep acts like a big transaction happening
            with connection.cursor() as cursor:
                cursor.execute("SELECT 1;")
        else:
            # do something else, like check if a periodic cleanup needs to happen
            log("Hit timeout")


if __name__ == '__main__':
    with psycopg.connect("dbname=pg-test", autocommit=True) as conn:
        run(conn)
```

`notifier.py`
```python
import random

import psycopg
from psycopg import sql

from main import channels, log


if __name__ == '__main__':
    channel = random.choice(channels)
    payload = str(random.randint(1000, 9999))
    with psycopg.connect("dbname=pg-test") as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                sql.SQL("NOTIFY {}, {};").format(
                    sql.Identifier(channel), sql.Literal(payload)
                )
            )
            log(f"NOTIFIED {channel} with payload {payload}")
```

```text
(pg3.2) % python main.py
2024-07-18T21:29:55.873977 Listen on channel channel_1
2024-07-18T21:29:55.874291 Listen on channel channel_2
2024-07-18T21:29:59.743426 Got NOTIFY: channel_1, 8766
2024-07-18T21:30:08.094671 Got NOTIFY: channel_1, 8206
2024-07-18T21:30:41.101718 Hit timeout
```
```text
(pg3.2) % python notifier.py
2024-07-18T21:29:59.742958 NOTIFIED channel_1 with payload 8766
(pg3.2) % python notifier.py
2024-07-18T21:30:00.784755 NOTIFIED channel_1 with payload 1527
(pg3.2) % python notifier.py
2024-07-18T21:30:08.094288 NOTIFIED channel_1 with payload 8206
```
```text
2024-07-18 23:29:55.874 CEST [86130] LOG:  statement: LISTEN "channel_1";
2024-07-18 23:29:55.874 CEST [86130] LOG:  statement: LISTEN "channel_2";
2024-07-18 23:29:59.742 CEST [86137] LOG:  statement: BEGIN
2024-07-18 23:29:59.742 CEST [86137] LOG:  statement: NOTIFY "channel_1", '8766';
2024-07-18 23:29:59.743 CEST [86137] LOG:  statement: COMMIT
2024-07-18 23:30:00.784 CEST [86141] LOG:  statement: BEGIN
2024-07-18 23:30:00.784 CEST [86141] LOG:  statement: NOTIFY "channel_1", '1527';
2024-07-18 23:30:00.784 CEST [86141] LOG:  statement: COMMIT
2024-07-18 23:30:02.749 CEST [86130] LOG:  statement: SELECT 1;
2024-07-18 23:30:08.094 CEST [86148] LOG:  statement: BEGIN
2024-07-18 23:30:08.094 CEST [86148] LOG:  statement: NOTIFY "channel_1", '8206';
2024-07-18 23:30:08.094 CEST [86148] LOG:  statement: COMMIT
```

**Comment by dvarrazzo** [comment]
Hello Peter,

what happens here is that the select you are executing after the sleep is consuming the notifications and, when you run `__poller`, they have already been consumed.

We can show it with this change, which adds a notify handler so we can get everything:

```diff
@@ -27,14 +27,23 @@
         yield n
 
 
+def notify_handler(n):
+    log(f"got notify: {n}")
+
+
 def run(connection):
     __listen(connection)
+    connection.add_notify_handler(notify_handler)
     for notify in __poller(connection, timeout=30):
         if notify:
             log(f"Got NOTIFY: {notify.channel}, {notify.payload}")
+            log("sleeping")
             time.sleep(3)  # Sleep acts like a big transaction happening
+            log("slept")
             with connection.cursor() as cursor:
+                log("executing")
                 cursor.execute("SELECT 1;")
+                log("executed")
         else:
             # do something else, like check if a periodic cleanup needs to happen
             log("Hit timeout")
```

Running your examples:
```
$ python notifier.py 
2024-07-19T12:35:01.550922 NOTIFIED channel_2 with payload 8767
$ python notifier.py 
2024-07-19T12:35:02.410086 NOTIFIED channel_1 with payload 1995
$ python notifier.py 
2024-07-19T12:35:03.280360 NOTIFIED channel_1 with payload 6486
```

```
$ python main.py 
2024-07-19T12:34:59.961665 Listen on channel channel_1
2024-07-19T12:34:59.961875 Listen on channel channel_2
2024-07-19T12:35:01.551222 Got NOTIFY: channel_2, 8767
2024-07-19T12:35:01.551243 sleeping
2024-07-19T12:35:04.554439 slept
2024-07-19T12:35:04.554639 executing
2024-07-19T12:35:04.555858 got notify: Notify(channel='channel_1', payload='1995', pid=97516)
2024-07-19T12:35:04.555989 got notify: Notify(channel='channel_1', payload='6486', pid=97573)
2024-07-19T12:35:04.556187 executed
2024-07-19T12:35:34.556258 Hit timeout
```

As you can see running the example yourself, the notifications received during the query running are handled at the end of the query (they reach the client together with the query result). So I see two things you might do:

- if you don't care about the timing of the notification, you can register a handler and handle the notifications both in the poller and anywhere else they happen (you might for instance put them in a queue both in the handler and in the poller and then consume them uniformly).
- if you care about the timing of the notifications, you should use a dedicated connection to receive them.

Closing the ticket because the behaviour is the one expected.

**Comment by dvarrazzo** [comment]
> Although you say it's expected behaviour, I expected conn.notifies to be the only thing to consume the Notify's, especially if there is no handler added to the connection. The docs say: If you are reserving a connection only to receive notifications, the simplest way is to consume the [Connection.notifies](https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection.notifies) generator. Maybe the wording in the docs is not strong enough? Maybe it should advice against using the generator if you want to do database operations based upon the notify.

If you have a proposal for a better wording for the docs I'm happy to accept it.

About the behaviour: you seem to expect the generator will also receive notifications sent _before_ it started. It doesn't work this way; if we wanted so, the connection would need a buffer where to accumulate notifications and then send them out as soon as the generator starts - but they will be handled by the client at the wrong time.

The design is to start listening when the generator starts, and, because of the problems that arise if someone tries to use the same connection to run queries at the same time, we added the lock in 3.2.

> To me working with a Django stack, option 1 is hard to setup

I'd also ask you what happens if you deploy your django app in more than one instance? Is it ok that you will receive a notification for each deployment?

Personally, when I write web apis that may receive async notifications I use an external process with the only role of listening from the database and forwarding the notification somewhere: sometime it was in rabbitmq, lately I wrote a service that, according to the channel of the notification would craft an http request so to send a callback to the api.

> Which makes me think of something like the lines below

I don't know what this code is for: it runs 10 queries/sec, so it keeps a connection busy and active. In what this is better than using the notifies generator?

**Comment by Blackeagle52** [comment]
>The design is to start listening when the generator starts, and, because of the problems that arise if someone tries to use the same connection to run queries at the same time, we added the lock in 3.2.

Thanks for the explanation, and I understand the reason. It's quite possible we have missed some notifications in the past, but fallbacks we had resolved those without us knowing.

>I'd also ask you what happens if you deploy your django app in more than one instance? Is it ok that you will receive a notification for each deployment?

The application I'm working on is single instance, so this hasn't been a problem. It is something I should store somewhere in the back of my mind, for when I would work with multiple instances.

>Personally, when I write web apis that may receive async notifications I use an external process with the only role of listening from the database and forwarding the notification somewhere: sometime it was in rabbitmq, lately I wrote a service that, according to the channel of the notification would craft an http request so to send a callback to the api.

Yeah, my application is similar. It receives data through an API, stores it, and notifies. Next to it runs a service which listens, and aggregates the data.

>I don't know what this code is for: it runs 10 queries/sec, so it keeps a connection busy and active. In what this is better than using the notifies generator?

Yeah, my suggested solution was probably some weekend brainrot speaking. I'll add a queue, which gets filled by the handler and generator, and process it. There are already fallbacks for when queue isn't empty when the service restarts.

>If you have a proposal for a better wording for the docs I'm happy to accept it.

I'll think about it. As I get a better understandig I see why it's hard to keep it concise (and simple).
