### ISSUE TITLE
Typing of overridden row factory on pool is not identified by mypy on connection

### ISSUE THREAD

**Issue by mittomen** [psycopg/psycopg#876]
I was overriding the default raw_factory to `dict_row`via kwargs on connection pool, but mypy still believes the row factory is the global default `TupleRow`.
```python
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool


conn_pool = ConnectionPool(kwargs={"host": "pg", "row_factory": dict_row})
with conn_pool.connection() as conn:
    with conn.cursor() as cur:
        cur.execute("SELECT 'Alice' AS name")
        assert (p4 := cur.fetchone())
        print(p4["name"])  # mypy complaining, it believes the row_factory is TupleRow, maybe because it is the default type
```
the error log is:
```
p.py:11: error: No overload variant of "__getitem__" of "tuple" matches argument type "str"  [call-overload]
p.py:11: note: Possible overload variants:
p.py:11: note:     def __getitem__(self, SupportsIndex, /) -> Any
p.py:11: note:     def __getitem__(self, slice, /) -> tuple[Any, ...]

```
The row_factory is working as expected, so the returned result is a dict.

Installed pips:
```
psycopg               3.2.1
psycopg-binary        3.2.1
psycopg-pool          3.2.2
```

**Comment by dvarrazzo** [comment]
Hello,

yes, with the pool and with generic connections the typing system needs a bit of help. This is described [here](https://www.psycopg.org/psycopg3/docs/advanced/typing.html#generic-pool-types). You can pass a `connection_class` consistent with the `row_factory` to tell mypy what the pool will return.

The following should work:

```python
conn_pool = ConnectionPool(
    kwargs={"host": "pg", "row_factory": dict_row},
    connection_class=Connection[DictRow],
)
```

I know it's redundant but at the moment we haven't been able to do better than this.

**Comment by mittomen** [comment]
Hi, thank you for your great feedback, it looks like I missed that detail from the documentation.
