### ISSUE TITLE
Window: Please use a compatible event loop, for instance by setting 'asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())'

### ISSUE THREAD

**Issue by sreenivasulureddysura** [psycopg/psycopg#882]
Trying to use the async mode it's failing: [doc](https://www.psycopg.org/psycopg3/docs/advanced/async.html#async-with)

```
    import asyncio
    import platform

    print(platform.system())
    if platform.system() == "Windows":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

DATABASE_URL=f"postgresql+psycopg_async://test123:123@postgres:5432/{test}"

```
Error:

`(psycopg.InterfaceError) Psycopg cannot use the 'ProactorEventLoop' to run in async mode. Please use a compatible event loop, for instance by setting 'asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())'`

![image](https://github.com/user-attachments/assets/38cca1cc-4712-47c6-a14e-622d36c7519f)

**Comment by sreenivasulureddysura** [comment]
@dvarrazzo I'm not doing anything it's corner case it's not deducted in the test suite. Please reverify it.

**Comment by dvarrazzo** [comment]
Tests pass.

https://github.com/psycopg/psycopg/blob/2028e19e67a4875448ba25ae5a4e962c0e41b93f/tests/conftest.py#L77-L80
