### ISSUE TITLE
Provide Python 3.13 wheels

### ISSUE THREAD

**Issue by edgarrmondragon** [psycopg/psycopg#889]
Python 3.13 RC1 was released recently[^1]:

<blockquote>

We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc1 will work with future versions of Python 3.13. As always, report any issues to [the Python bug tracker ](https://github.com/python/cpython/issues).

</blockquote>

It'd  be really nice to have wheels to start testing applications that use pyscopg-binary before the eventual final release.

Thanks!

PS: This request is only for GIL-enabled 3.13 wheels and not free-threaded ones[^2], which will certainly involve a higher level of effort.

[^1]: https://discuss.python.org/t/python-3-13-0-release-candidate-1-released/59703
[^2]: https://docs.python.org/3.13/whatsnew/3.13.html#free-threaded-cpython

**Comment by dvarrazzo** [comment]
Can you provide a MR for the CI to set up the 3.13 build?

**Comment by edgarrmondragon** [comment]
> Can you provide a MR for the CI to set up the 3.13 build?

Done! https://github.com/psycopg/psycopg/pull/890

**Comment by dvarrazzo** [comment]
Packages for Python 3.13 released!

**Comment by jpmckinney** [comment]
> This request is only for GIL-enabled 3.13 wheels and not free-threaded ones[2](https://github.com/psycopg/psycopg/issues/889#user-content-fn-2-b6cb1e3156f6b413a01fc1b2333242ab), which will certainly involve a higher level of effort.

Is there a tracking issue for free-threaded, or is it already supported? (Same question for psycopg2)
