### ISSUE TITLE
New binaries are not compatible with older MacOS

### ISSUE THREAD

**Issue by madhavajay** [psycopg/psycopg#900]
The latest versions are not installable on older MacOS versions.
Cibuildwheel should support building a single binary wheel that supports multiple versions of MacOS.

<img width="664" alt="Screenshot 2024-08-28 at 7 45 48 pm" src="https://github.com/user-attachments/assets/3d4469ed-a89f-4f08-9f2f-e5300fd5acb8">
<img width="770" alt="Screenshot 2024-08-28 at 7 45 38 pm" src="https://github.com/user-attachments/assets/336231fe-1839-4f60-ad14-2abaeef80f45">

**Comment by dvarrazzo** [comment]
We only build psycopg on publicly available runners and no entity that I know of offers macos 10/11 runners anymore. The software on the runner determines the oldest supported platform, cibuildwheel cannot do more.
