### ISSUE TITLE
Handling psycopg.errors.FeatureNotSupported "cannot set transaction read-write mode during recovery" when DB failover puts the connection into recovery

### ISSUE THREAD

**Issue by MRigal** [psycopg/psycopg#904]
Hi!

Testing on a stack: SqlAlchemy -> Psycopg3.2 -> PgBouncer -> Postgres 14

Writing this issue here as I am expecting that Psycopg should give the possibilities to check/handle it. It probably would deserve a test on SqlAlchemy as well as an adaptation of their connection invalidation, once known how to detect it.

I use the pooling mechanim from SqlAlchemy and I use the psycopg enums to check for transaction status and so on when picking a connection from the pool.

However I recently had the case (occured the first and only time after switching from psycopg2 to psycopg3) where there was a DB failover and I was always getting a connection that psycopg reported as of good status, but then, when running the first query on such a connection, I get a "FeatureNotSupported, cannot set transaction read-write mode during recovery".
This exception unfortunately, inherits from NotSupportedError and thus is considered in the `e._NO_TRACEBACK` Exception which causes the traceback to be deleted.

The only thing I note on the trace is that the Cursor is in status "Closed", but this may be enough as it is a "new" connection on the sqlalchemy (although on old one on PgBouncer side).

I would actually expect pgBouncer to invalidate/close such connections on failures, but somehow it is not the case and that error kept happening until I restarted the containers.

Ideally I would like to know a way to fake/mock such a failure, how to detect it so that we can include this failure in the [sqlalchemy method](https://github.com/sqlalchemy/sqlalchemy/blob/2363b2f37cab51313d5eb86fd8bf7beffd34e17e/lib/sqlalchemy/engine/base.py#L2236) that invalidates connection.

Here the traceback for info:
```
  File "dataworker/tracking.py", line 201, in _sync
    connection.execute(update_statement)
  File "sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)File "dataworker/tracking.py", line 283, in run
    self.tracker_manager.process_log(log)
  File "dataworker/tracking.py", line 264, in process_log
    tracker.add_log(record)
  File "dataworker/tracking.py", line 211, in add_log
    self._sync()
  File "dataworker/database.py", line 333, in wrapped
    result = func(*args, **kwargs)
  File "dataworker/database.py", line 400, in wrapped
    result = func(*args, **kwargs)
  File "dataworker/tracking.py", line 201, in _sync
    connection.execute(update_statement)
  File "sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
  ```

**Comment by MRigal** [comment]
Hi @dvarrazzo !

Thanks a lot for your detailed feedback! I will still ask the sqlalchemy team what they think about it. I wanted to have your opinion too, as it is something that has changed between psycopg2 and psycopg(3), possibly due to the fact to use server-side cursor. With psycopg2, with similar failovers and recovery mode, either sqlalchemy or pgbouncer considered the connection as invalid/closed and I would not had to handle the case in the code...

I have one more question if you don't mind. The snippet you gave allows to raise on the current connection, but the next execute will go through straight.
What would really help me to ensure not landing in a "get a connection to a DB node in recovery mode that is read-only" loop, would be to raise that on every subsequent request. I was hoping to be able to use `pg_is_in_recovery`, but I couldn't do so. If you have any other suggestion in that area, it would be highly appreciated.

If I get a proper test and error handling to run on that, I would also gladly share it, as I could not find much on the subject on the web.

**Comment by dvarrazzo** [comment]
> Thanks a lot for your detailed feedback! I will still ask the sqlalchemy team what they think about it. I wanted to have your opinion too, as it is something that has changed between psycopg2 and psycopg(3) ...

Sure, do hear from them then. If they have special-cased this exception in the past it makes sense for it to be consistent.

> I have one more question if you don't mind. The snippet you gave allows to raise on the current connection, but the next execute will go through straight.

Of course: mine was just a building block to provide you with a way to simulate that failure, which might have a specific meaning (that your application, and some middleware, might use to enact some specific recovery procedure), but, from the PoV of the protocol, and the level at which psycopg operates, is not different from other exceptions raised by the server.

You might try creating a connection subclass and add it a `_test_in_recovery` flag attribute on it for instance, so that it would always execute a query raising the error we discussed instead of the query passed by the user when the flag is set, and your program will not recover until it has created a new connection.

**Comment by MRigal** [comment]
Thanks! Sounds good indeed!
