### ISSUE TITLE
sql.Operator for string composition with dynamic operators

### ISSUE THREAD

**Issue by hartelt** [psycopg/psycopg#905]
I have a project, in which I would allow a frontend to provide customizable filters `field` of format `(name, operator, value)`. 
From the `field` tuples, I generate extensions to the `where` clause like 
`" and {} {} %s".format(sql.Identifier(field.name), field.operator)`
(the `field.value` being used later in `cursor.execute(query, where.values)`.

The sql statement can be nicely built using psycopg string composition. E.g. I am using `sql.Identifier` to make the dynamic `field` value save against sql injection. 

But I am missing a `sql.Operator` to make the dynamic *operator* also save.
That would look like:
`" and {} {} %s".format(sql.Identifier(field.name), sql.Operator(field.operator))`

 Is there a reason why it does not exists? Or could this be added to psycopg?

**Comment by dvarrazzo** [comment]
You can use `sql.SQL()` to compose identifiers dynamically, which would result in the operator inserted unchanged in the query.

There is no reason to add a wrapper specifically for operators: there isn't a transformation to make an operator safe to be inserted as a literal in a query, unlike with identifiers (which need to be wrapped in double quotes if they contain anything more than lowercase letter or collide with a reserved word) or string literals (which need to be wrapped in single quote).

`"and {} {} %s".format(sql.Identifier(field.name), sql.SQL(field.operator))` does what you need. Of course you are responsible of what goes in `field.operator`. You might want to subclass `sql.SQL` and add a check on the constructor that the argument respect [the operator rules](https://www.postgresql.org/docs/16/sql-createoperator.html).

Should it be part of psycopg? Not sure. Identifiers and Literals are wrappers to certain libpq functionalities and are more common occurrences for normal usage. Operators are much more of a niche functionality and are probably less portable across different versions and vendors of compatible databases. Furthermore such wrapper would not add a functionality, such as converting a high-level object to SQL syntax, but it would just throw an exception if an user-provided literal doesn't respect a rule found in the documentation.

If you are only looking for a mechanism to pass an operator to the query, `sql.SQL` is just what you need. If you are considering to add a validation check to psycopg, I'm not sure 100% about it, but we can explore the possibility.

**Comment by hartelt** [comment]
Thanks for the quick and helpful answer! I will just use 'sql.SQL' then, some validation against a list of valid operators I will do outside of psycopg. _Closed._
