### ISSUE TITLE
Functioning SQL Query produces empty result with psycopg

### ISSUE THREAD

**Issue by vkuehn** [psycopg/psycopg#907]
Tried a select star from table and it worked even with psycopg but not for all tables as I find out now.
If I copy the query to a dbadmin tool like DBeaver all queries work.

not sure how to show a reproduceable problem.

Is there a debugging method for such odd problems ?

**Comment by dvarrazzo** [comment]
Not a bug. Please ask for help in a mailing list and with more reproducible example.
