### ISSUE TITLE
DuplicatePreparedStatement

### ISSUE THREAD

**Issue by sonfire186** [psycopg/psycopg#911]
python 3.11.4
psycopg 3.2.2

I'm using "multiprocessing" and getting the error:
`(psycopg.errors.DuplicatePreparedStatement) prepared statement "_pg3_0" already exists`

How can I fix it or how can I get more information about the error?

**Comment by dvarrazzo** [comment]
Connections are not meant to be shared about processes.

**Comment by sonfire186** [comment]
Why, then, is there no such problem in psycopg2?
@dvarrazzo

**Comment by dvarrazzo** [comment]
Because psycopg2 doesn't use prepared statements. If you want [you can disable them on psycopg 3 too](https://www.psycopg.org/psycopg3/docs/advanced/prepare.html).

Neither psycopg2 nor 3 connections can be shared across different process. Whatever you have works out of some miracle: the socket [gets shared across processes](https://www.postgresql.org/docs/current/libpq-connect.html), each one thinking to have its exclusive usage, carefully protecting from concurrent access, and totally unaware that something else is doing the same.

**Comment by sonfire186** [comment]
@dvarrazzo 
```
from sqlalchemy import create_engine
from sqlalchemy.sql import text

engine_db = create_engine(
    f'postgresql+psycopg://****'
)
....
with engine_db.connect() as connection:
   sql = text('SELECT public.f_update_usage_statistics(:uuid, :status)')

   connection.execute(sql, {'uuid': uuid, 'status': status}, prepare=True)
   connection.commit()
```

Error `TypeError: Connection.execute() got an unexpected keyword argument 'prepare'`  
Following the documentation I get an error. What's the problem?

**Comment by droganov** [comment]
@dvarrazzo 
`(psycopg.errors.DuplicatePreparedStatement) prepared statement "_pg3_0" already exists`

occurs also when using `AsyncConnectionPool` with Supabase in transaction mode (port 6543)

switching to session mode fixed it

**Comment by hcjmartin-work** [comment]
> [@dvarrazzo](https://github.com/dvarrazzo) `(psycopg.errors.DuplicatePreparedStatement) prepared statement "_pg3_0" already exists`
> 
> occurs also when using `AsyncConnectionPool` with Supabase in transaction mode (port 6543)
> 
> switching to session mode fixed it

Thanks @droganov. Documentation [here](https://supabase.com/docs/guides/database/connecting-to-postgres#supavisor-session-mode) for those using Supabase.

**Comment by nmaswood** [comment]
@droganov Do you recommend setting to the connection pool to transaction mode for AsyncConnecctionPool regardless of provider?

I am using cloud sql via gcp no pgbouncer and getting this error all the time

**Comment by dvarrazzo** [comment]
@nmaswood I am sorry but this is a bug tracker, not a free consultancy service.

If you have problems with a commercial database provider I invite you to get in touch privately to arrange a professional consultancy.

**Comment by nmaswood** [comment]
Ah sorry I didnt mean to get off topic @dvarrazzo.

Maybe a better question is what is the recommend way to disable prepared statements all together?

Is the only option to pass `(prepare=False)` on the `execute` method? I am having an issue with prepared statements I don't entirely understand and would prefer to opt out at the connnection pool layer if the API permits it.

Thanks 🙏🏼

**Comment by dvarrazzo** [comment]
The documentation page about [prepare threshold](https://www.psycopg.org/psycopg3/docs/advanced/prepare.html#prepared-statements) explains how to disable prepared threshold per-connection.

You can use `prepare_threshold` in the `kwargs` parameter of the [pool constructor](https://www.psycopg.org/psycopg3/docs/api/pool.html#psycopg_pool.ConnectionPool) to disable prepared threshold for every connection.

**Comment by nmaswood** [comment]
Thank you!
