### ISSUE TITLE
Documentation is misleading because libpq is not current on Windows

### ISSUE THREAD

**Issue by allaboutmikey** [psycopg/psycopg#912]
The [documentation](https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection.connect) for the connection class has a link to the postgresql docs for [Connection Strings](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING). 
Great, except that the link is to the current version of the postgresql docs (reasonable), but on Windows, the libpq linked to the current psycopg (3.2.2 at the time of writing) is *not* the current postgresql version (16 at time of writing, the version reported by psycopg is 14).

On Windows:
```
pip install psycopg[binary]
Successfully installed psycopg-binary-3.2.2

python
>>> import psycopg
>>> psycopg.version.__version__
'3.2.2'
>>> psycopg.pq.__impl__
'binary'
>>> psycopg.pq.version()
140012
```
On Linux:
```
pip install psycopg[binary]
Successfully installed psycopg-binary-3.2.2

python
import psycopg
>>> psycopg.version.__version__
'3.2.2'
>>> psycopg.pq.__impl__
'binary'
>>> psycopg.pq.version()
160003
```
This was a cause of much confusion for me when I tried to use a connection string that included `require_auth gss`, which crashed with an execption `psycopg.ProgrammingError: invalid connection option "require_auth"`. 
This connection option is only supported as of v16. (Older versions require `gssencmode require` for similar functionality).

Maybe the documentation should link to specific versions of the postgresql docs? (This is difficult with different versions of libpq linked to different platforms' binaries though).

I cannot find any documentation for how to update the libpq in the binary version. 
I tried to use the pure python and c wrappers, but on Windows, I cannot get them to load the system liqpq.dll at all. It keeps complaining that some dependency cannot be found (even though all are in the same folder as libpq.dll and psql works). This is not really a psycopg problem I think, but maybe a peculiarity of libpq.dll or its packaging that ctypes isn't handling?

Are there plans to update the libpq.dll version for the Windows binary? Alternatively, does anyone know how to get the local or pure python versions to work on Windows?

**Comment by dvarrazzo** [comment]
I can confirm that, at the moment, on github runners there is the libpq at least 14 installed (allowing to use the pipeline mode). Tomorrow, we don't know. Windows is not a predictable environment to work with. By the comment found in the test workflow file (see permalink ahead), in the past we had some exploration of the system and we found a bunch of undocumented libpq versions lying around. The best we could do was to fix the path to make sure to have a known one. Looking at [the Windows runner's specs](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#postgresql), there is only Postgres 14.

I am sure that, in the past, I have faffed with chocolatey to upgrade the libpq but without much luck.

I tried to run a quick test and I can't even run `ls` on windows. This command [failed](https://github.com/psycopg/psycopg/actions/runs/10974335185/job/30472745511#step:6:41).

https://github.com/psycopg/psycopg/blob/83ea6a8785e713d184c98f93a0d0ae9ec81a7928/.github/workflows/tests.yml#L317-L323

You gotta love a system where changing `PATH` makes something work but `ls` in that path fails. Except that, I don't love such system, therefore, for the moment, I'll stop here.

There is some possibility that, given enough work, it would be possible to use choco to upgrade the libpq on the builder. However, this is not a work I am available to do for free. If you have plans to sponsor the work please let me know. Alternatively, if you are able to run choco on the runner, install a more up to date libpq, package it in the binary image, your MR would be welcome and we would package the new libpq in the next release. There are other alternatives (compile the libpq on our own, install the libpq from an asset of ours), none of which I wish to attempt on my free time.

As far as I know, if a dll is in the `PATH`, it should be loaded by ctypes. Next best bet is to put it in the same directory of `python.exe`.

**Comment by dvarrazzo** [comment]
Also, I digressed... documentation.

No, I don't wish to make any guarantee about the libpq packaged with the binary package; packaging is done on a best-effort basis and changes in time. This was already explained in the [binary package documentation](https://www.psycopg.org/psycopg3/docs/basic/install.html#binary-installation) but I have expanded better on it, including links to find your version.

![image](https://github.com/user-attachments/assets/dbd9e933-3237-4ddb-8837-75d31447e439)

**Comment by allaboutmikey** [comment]
On 2024-09-22 04:09, Daniele Varrazzo wrote:

> I can confirm that, at the moment, on github runners there is the libpq 
> at least 14 installed (allowing to use the pipeline mode). Tomorrow, we 
> don't know. Windows is not a predictable environment to work with. By 
> the comment found in the test workflow file (see permalink ahead), in 
> the past we had some exploration of the system and we found a bunch of 
> undocumented libpq versions lying around. The best we could do was to 
> fix the path to make sure to have a known one. Looking at the Windows 
> runner's specs [1], there is only Postgres 14.
> 
> I am sure that, in the past, I have faffed with chocolatey to upgrade 
> the libpq but without much luck.
> 
> I tried to run a quick test and I can't even run ls on windows. This 
> command failed [2].
> 
> https://github.com/psycopg/psycopg/blob/83ea6a8785e713d184c98f93a0d0ae9ec81a7928/.github/workflows/tests.yml#L317-L323
> 
> You gotta love a system where changing PATH makes something work but ls 
> in that path fails. Except that, I don't love such system, therefore, 
> for the moment, I'll stop here.
> 
> There is some possibility that, given enough work, it would be possible 
> to use choco to upgrade the libpq on the builder. However, this is not 
> a work I am available to do for free. If you have plans to sponsor the 
> work please let me know. Alternatively, if you are able to run choco on 
> the runner, install a more up to date libpq, package it in the binary 
> image, your MR would be welcome and we would package the new libpq in 
> the next release. There are other alternatives (compile the libpq on 
> our own, install the libpq from an asset of ours), none of which I wish 
> to attempt on my free time.
> 
> As far as I know, if a dll is in the PATH, it should be loaded by 
> ctypes. Next best bet is to put it in the same directory of python.exe.
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>

That clears things up, thanks.

I don't know enough about CI runners to help or even comment here. I 
agree that Windows is a mess.

I'll just have to figure out why my local install is not loading the 
libpq.dll. The docs did say that local was the preferred production 
install.

-- 

Michael Bryce
All About Computers
E: ***@***.*** | M: 0407 473 193

The fine print. Does anybody really read this stuff? Anyway, if you are 
planning to do anything with the contents of this email that would upset 
either your mother or mine: don't! Also, if I sent this to you and it 
seems like that was by mistake, I would appreciate you letting me know. 
It's just good manners. Have a lovely day!

Links:
------
[1] 
https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#postgresql
[2] 
https://github.com/psycopg/psycopg/actions/runs/10974335185/job/30472745511#step:6:41
[3] 
https://github.com/psycopg/psycopg/issues/912#issuecomment-2365273717
[4]

**Comment by dvarrazzo** [comment]
HI @allaboutmikey,

> I'll just have to figure out why my local install is not loading the libpq.dll. The docs did say that local was the preferred production install.

I'm giving a stab at trying to package a newer libpq in Windows binaries, see #916.

Working on it, my friend @kemosh and I found what I think the same problem of yours about using the pure Python version (ctypes.utils being able to find the dll but importing failed).

If you would like to give this changeset a go it would be welcome. Thank you!
