### ISSUE TITLE
class_row and NULL values

### ISSUE THREAD

**Issue by girzel** [psycopg/psycopg#913]
I was recently a bit surprised to find that, with `row_factory=class_row(MyDataclassClass)`, a null result comes out not as a Python `None`, but as an instance of `MyDataclassClass` with all attributes set to `None`.

This caught me off guard, and required changing some down-stream checks. I guess by analogy to PostgreSQL's own `json_build_object` and friends, I would have expected a plain `None`. A `dict_row` row factory, too, returns a `None` instead of an empty dict.

I suppose changing this behavior at this point might be off the table, but if so please consider this a documentation change request! It would be easy to add a note to the `class_row` documentation.

Thanks!

**Comment by dvarrazzo** [comment]
Can you provide a repro? For me it works fine:

```python
from dataclasses import dataclass
import psycopg
from psycopg.rows import class_row

@dataclass
    class MyDataClass:
        anint: int
        astring: str

conn = psycopg.Connection.connect(autocommit=True)
cur = conn.cursor(row_factory=class_row(MyDataClass))

cur.execute("select 10 as anint, 'hi' as astring").fetchone()
MyDataClass(anint=10, astring='hi')

cur.execute("select 10 as anint, 'hi' as astring where false").fetchone()
None

cur.execute("select null").fetchone()
...
TypeError: MyDataClass.__init__() got an unexpected keyword argument '?column?'
```

This is the behaviour I expect. How do you get a null result becoming a None?

**Comment by girzel** [comment]
Bah, I should have used a simpler repro. This seems to arise from PostgreSQL behavior, nothing to do with psycopg at all.

I have a SQL function defined that looks up data using one table's PK, and returns that data as a PG custom type. That PG type matches the Python dataclass I'm using in the `class_row`. For some reason -- either the fact that I'm using a function, or the fact that it's defined as `RETURNS my_custom_type` -- if I look up a non-existent PK, I get back a row of NULLs, rather than just an overall NULL. The actual query looks like:

```sql
SELECT col1, col2, col3 from get_data(%s)
```
And in psql that returns
```
 col1 | col2 | col3
------+------+-----
      |      |           
```
not
```
 col1 | col2 | col3
------+------+-----
```
Maybe an argument for using a view instead of a function.

Anyway, sorry for the noise! Thanks for the quick response, and for the great package.

**Comment by dvarrazzo** [comment]
I thought so. As you can understand well yourself, a record full of NULLs is perfectly legit for Python and distinct from a null, so I believe we ware dong the right thing here.
