### ISSUE TITLE
Increase in query latency post upgrading to psycopg3 in gevent environment.

### ISSUE THREAD

**Issue by ns-rparshi** [psycopg/psycopg#919]
As prepared statements are not supported in psycopg2, recently i have upgraded from psycopg2 to psycopg3 & prepare statements are working as expected. 

But however we have started observing **all** the DB calls which are made from **celery + gevent ** environment query timing have significantly increased. The same query which used to take <5ms in psycopg2 is now taking more than 500ms in psycopg3 from gevent. But if the same query executed with psycopg3 outside gevent environment it is taking  <5 ms. So, only when it is run from gevent environment it is taking more time.

More info on the environment.
- Monkey patching is used with monkey.patch_all().
- Singleton DB connection is used.

Python version: Python 3.8.10
OS: ubuntu docker image

Libraries:
```
celery = "5.2.7"
gevent = "23.9.1"
psycopg = "3.2.1"
```

From psycopg3 [documentation ](https://www.psycopg.org/psycopg3/docs/advanced/async.html#gevent-support)it supports gevent. So, could you please share what is causing the increase in query timings from gevent environment & how to prevent it. Thank you in advance.

**Comment by dvarrazzo** [comment]
I can look into it only if you put together a script to reproduce the problem.

**Comment by ns-rparshi** [comment]
Thank you for the quick response. Currently i don't have a script to reproduce this issue. I will try to reproduce this issue via a script and will share it with you in a couple of days.

**Comment by ns-rparshi** [comment]
The issue is due to differences in behavior compared to psycopg2. In psycopg3, within a Celery + Gevent environment using monkey patching and a singleton DB connection, multiple gevents attempt to use the same connection, leading to increased wait times. However, there is no difference in overall execution time. A connection pool is needed to ensure other gevents don’t have to wait for the connection to become available.

Closing this issue as psycopg3 is working as expected.
