### ISSUE TITLE
Is PostgreSQL 17 officially supported?

### ISSUE THREAD

**Issue by yanivtoledano** [psycopg/psycopg#924]
Following the release of https://github.com/psycopg/psycopg/releases/tag/3.2.3, is PostgreSQL 17 officially supported? 

If so, the website does not mention this at the moment (see below).

<img width="776" alt="Screenshot 2024-10-02 at 15 58 33" src="https://github.com/user-attachments/assets/35527751-98db-4f36-9331-4de97e939067">

**Comment by dvarrazzo** [comment]
Thank you for the heads up. Yes, PG 17 is supported. I have updated the features list with last versions of Python and Postgres.
