### ISSUE TITLE
support of COPY TO PROGRAM

### ISSUE THREAD

**Issue by SailorMax** [psycopg/psycopg#927]
```python
copy_from_query = 'COPY (SELECT fname FROM tbl_name) TO PROGRAM ''gzip -c'' (FORMAT TEXT)'
copy_to_query = 'COPY tbl_name2 (fname) FROM PROGRAM ''gunzip'' (FORMAT TEXT)'
with src_conn.cursor().copy(copy_from_query) as src_copy, dst_cursor.copy(copy_to_query) as dst_copy:
	while data := src_copy.read():
		dst_copy.write(data)
```

Expected: copy of table

Actual: psycopg.ProgrammingError: copy() should be used only with COPY ... TO STDOUT or COPY ... FROM STDIN statements, got TUPLES_OK

Libs: 'psycopg-binary==3.2.3', 'psycopg==3.2.3'

Details: I have large table with raster-field. Copy it in text format multiply it size. Binary format does not support postgis for raster fields. I trying to reduce the size of text format. But have this error.
Can you help me with this kind of error or suggest alternative way?

thank you.

**Comment by dvarrazzo** [comment]
From [documentation](https://www.postgresql.org/docs/current/sql-copy.html):

> COPY with a file name instructs the PostgreSQL server to directly read from or write to a file. The file must be accessible by the PostgreSQL user (the user ID the server runs as) and the name must be specified from the viewpoint of the server. When PROGRAM is specified, the server executes the given command and reads from the standard output of the program, or writes to the standard input of the program. The command must be specified from the viewpoint of the server, and be executable by the PostgreSQL user. When STDIN or STDOUT is specified, data is transmitted via the connection between the client and the server.

So the program must run on the server. Because the statement doesn't communicate with the server on COPY protocol, I expect you need to run that command in a simple `execute()`.
