### ISSUE TITLE
Executemany: psycopg.ProgrammingError: the query has 1 placeholders but 2 parameters were passed

### ISSUE THREAD

**Issue by mookjais** [psycopg/psycopg#943]
I've read the documentation on Executemany, but still can't figure out why I'm having this issue.

`crsr.executemany('DELETE FROM users WHERE email = %s', [['searwicker3@guardian.co.uk', 'jcorballis2@mac.com']])`

Traceback (most recent call last):
  File "c:\Users\me\site-packages\psycopg\cursor.py", line 128, in executemany
    raise ex.with_traceback(None)
psycopg.ProgrammingError: the query has 1 placeholders but 2 parameters were passed

When I only have one email in the list, this executes w/o issue, but the moment there are 2 emails in the list, I get this error.  You don't have to put a placeholder for every input (i.e. I want to delete 15 users in a list, & I need to use 15 placeholders), do you?

But even if I try to do that, this what I get..

`crsr.executemany('DELETE FROM fin.users WHERE email = (%s, %s)', [['searwicker3@guardian.co.uk', 'jcorballis2@mac.com']])`

Traceback (most recent call last):
  File "c:\Users\me\site-packages\psycopg\cursor.py", line 128, in executemany
    raise ex.with_traceback(None)
psycopg.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

**Comment by stankudrow** [comment]
What if you try operator `IN` in place of `=` ?

**Comment by mookjais** [comment]
I'll try that too

**Comment by dvarrazzo** [comment]
`executemany()` takes a sequence of sequences as argument, one per record.
In your case you want 1-item records, so you want something like:

crsr.executemany('DELETE FROM fin.users WHERE email = %s', [['
***@***.***'], ***@***.***']])

However the suggestion of using one execute (not executemany) with the
`any` operator is good too, at least for small lists (a few dozens
elements, then in my experience postgres starts behaving inefficiently, I
have no idea if that changed in more revent versions).

crsr.execute('DELETE FROM fin.users WHERE email = any(%s)', [['
***@***.***', ***@***.***']])

**Comment by mookjais** [comment]
@dvarrazzo 

> crsr.executemany('DELETE FROM fin.users WHERE email = %s', [['
> ***@***.***'], ***@***.***']])

Worked for me, thanks!
