### ISSUE TITLE
Error while importing PGVector due to psycopg library issues

### ISSUE THREAD

**Issue by arnabsinha99** [psycopg/psycopg#947]
Hi everyone,

I am getting an error while running the below line (part of my .py file) on a virtual environment created through **Conda** on my **Windows 11** machine. **Python version is 3.12.4**

` from langchain_postgres import PGVector`

The error is as below:

```
Traceback (most recent call last):
  File "C:\Users\Admin\OneDrive\Documents\GitHub\UWin-gine\uwingine\llm\generate_llm_embedding.py", line 6, in <module>
    from langchain_postgres import PGVector
  File "C:\Users\Admin\anaconda3\Lib\site-packages\langchain_postgres\__init__.py", line 3, in <module>
    from langchain_postgres.chat_message_histories import PostgresChatMessageHistory
  File "C:\Users\Admin\anaconda3\Lib\site-packages\langchain_postgres\chat_message_histories.py", line 13, in <module>
    import psycopg
  File "C:\Users\Admin\anaconda3\Lib\site-packages\psycopg\__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\psycopg\pq\__init__.py", line 117, in <module>
    import_from_libpq()
  File "C:\Users\Admin\anaconda3\Lib\site-packages\psycopg\pq\__init__.py", line 109, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'NoneType'
```

The problem is that my .py file is working on the base environment but failing on the venv that I created. I am running the below list of requirements and then executing the .py file. Please help me out and let me know any extra information that I can provide to resolve this issue.

Requirements:

```
faiss-cpu
groq
langchain-groq
PyPDF2
langchain_google_genai
langchain
langchain_community
python-dotenv
pypdf
langchain-huggingface
langchain_experimental
langgraph
psycopg[binary,pool]
tiktoken
langchain-postgres
```

@dvarrazzo Tagging you since I saw a couple tickets where you were involved in similar issues. Thanks for your time in advance!

**Comment by dvarrazzo** [comment]
As far as I can see, even if you have `binary` in your dependencies, the package wasn't installed. Please try to `pip install psycopg[binary]`.

Apart from telling that, we don't support conda. If you have problems with it please refer to their support.
