### ISSUE TITLE
Python 3.13.0 significant performance regression (Linux)

### ISSUE THREAD

**Issue by ration** [psycopg/psycopg#954]
Exactly the same symptoms, as  #930, but on Linux. 

```python
#!/usr/bin/env python

from psycopg_pool import ConnectionPool


postgres_pool = ConnectionPool("host=localhost dbname=postgres user=postgres password=postgres")
conn = postgres_pool.getconn()
conn.autocommit = False
conn.execute(query="ALTER ROLE postgres WITH LOGIN")
conn.commit()
```
Produces

couldn't stop thread 'pool-1-worker-0' within 5.0 seconds
couldn't stop thread 'pool-1-worker-1' within 5.0 seconds
couldn't stop thread 'pool-1-worker-2' within 5.0 seconds
couldn't stop thread 'pool-1-scheduler' within 5.0 seconds

On more complex projects it might halt althogether.

Minimal project https://github.com/ration/psycopg_test

Linux (kernel 6.11)
Postgresql 15.6

**Comment by ration** [comment]
Thanks, my example was just a convoluted example that something has changed. But indeed using it as you suggested *does* work (my own example without the context):

```python
#!/usr/bin/env python

from psycopg_pool import ConnectionPool


postgres_pool = ConnectionPool("host=localhost dbname=postgres user=postgres password=postgres")
postgres_pool.wait()
conn = postgres_pool.getconn()
conn.autocommit = False
conn.execute(query="ALTER ROLE postgres WITH LOGIN")
conn.commit()
postgres_pool.putconn(conn)
postgres_pool.close()
```
without closing explicitly the pool it now waits, which it did not before.

**Comment by dvarrazzo** [comment]
You don't specify your python version. My wild guess is that you use 3.13, and that in 3.13 something changed so threads at interpreter shutdown don't behave as before.

Using resource properly, psycopg seems to work as expected. Therefore this can be closed here.

**Comment by ration** [comment]
You don't have to guess, the version is in the topic. But thanks anyway.

**Comment by dvarrazzo** [comment]
> You don't have to guess, the version is in the topic.

Ah you are right, apologies. It seems a Python 3.13 behaviour change.

**Comment by ration** [comment]
While I can fix my own stuff, I suspect this will cause issues on the field as applications might hang on exit without the explicit close. Assuming the manual context handling is popular..

**Comment by dvarrazzo** [comment]
This is not a performance regression, it's just the interpreter shutdown to be slowed down. I changed the title of the ticket accordingly.

**Comment by ration** [comment]
Yes this will definitely help me at least if/when I run across this again :+1:

**Comment by yrashk** [comment]
I am catching this same issue on Python 3.13, and I am using context manager for getting my connections. Closing the pool doesn't seem to help either.

**Comment by yrashk** [comment]
I was able (so far) to circumvent this by doing something like this:

```python
import atexit

@atexit.register
def close_psycopg_pools():
    import gc
    import psycopg_pool
    [obj.close() for obj in gc.get_objects() if isinstance(obj, psycopg_pool.ConnectionPool)]
```
