### ISSUE TITLE
psycopg[binary] install fails on Python 3.12.7 due to typing-extensions constraint

### ISSUE THREAD

**Issue by paulschreiber** [psycopg/psycopg#956]
## Description
When my `base.in` file contains `psycopg[binary]`, the installation fails with this error;
```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=4.6 from https://files.pythonhosted.org/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl (from psycopg==3.2.3->-r requirements.txt (line 373))
```

pip compile command (this succeeds)
```
CUSTOM_COMPILE_COMMAND="make lock" pip-compile --upgrade --generate-hashes --strip-extras --resolver=backtracking --output-file requirements.txt requirements/base.in
```

install command (this fails)
```
pip install -r requirements.txt
```

Sample run log: https://github.com/techmatters/soil-id-algorithm/actions/runs/11900934871/job/33162870992

## Regression
• fails on macOS 15.1
• fails on Ubuntu 24.04.
• installing `psycopg` (from source) works as expected.
• Using Python 3.12.7 in all cases.

**Comment by dvarrazzo** [comment]
Either you are doing something wrong with your package manager, or your package manager is designed badly.

psycopg is a library and the best practice with the libraries is to pin at most the lower bound of dependencies.
