### ISSUE TITLE
Syntax error when using dump script with CSV insertions.

### ISSUE THREAD

**Issue by jenstroeger** [psycopg/psycopg#958]
I created a dump of my db using
```
pg_dump --host localhost --port 5432 --user postgres my_db > pgdump.sql 
```
which contains the following constructs to repopulate tables:
```sql
--
-- Data for Name: some_table; Type: TABLE DATA; Schema: some_schema; Owner: postgres
--

COPY some_schema.some_table (id, created_at, updated_at, memo, reference, disputed, ...) FROM stdin;
\.
```
and I get the following error:
```
Traceback (most recent call last):
  File "/path/to/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/path/to/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/path/to/.venv/lib/python3.10/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.SyntaxError: syntax error at or near "\"
LINE 4790: \.
           ^

```
Running the script directly from `psql` works ok; pasting the script into an [Alembic](https://alembic.sqlalchemy.org/) migration and running it as 
```python
def upgrade(): 
    op.execute(sa.text(pg_dump_script)) 
```
fails with the above exception.

For now I switched to using [`--inserts`](https://www.postgresql.org/docs/current/app-pgdump.html) when creating the dump.

**Comment by dvarrazzo** [comment]
`pg_dump` dumps are not designed to be reloaded via psycopg.

**Comment by jenstroeger** [comment]
@dvarrazzo hmm, ok. 

Or did you mean that psycopg doesn’t support the dumped files completely? I would suspect that `pg_dump` is a tool independent from psycopg? (Just trying to understand the dependencies.)

**Comment by dvarrazzo** [comment]
Yes, they are two independent tools, with commonalities but they are different.

- psycopg is a library to connect PostgreSQL to a client Python program
- psql is a program to connect PostgreSQL to a client command line

so, on the client side, they talk two different languages, even if they talk to the same database (they even use the same C client library, but this is an implementation detail).

In particular, going down the technical side of the communication a little bit, for every command that the client sends to the server, the server can give a result of a certain type, and possibly the client session will move to a certain state. A result could be an error, or a success with return tuple (after a SELECT), or a return with no tuple (after an INSERT, for example). psql will decide what to do with it (if it's a result with data it will display the result for example).

One particular result type is returned after a COPY ... FROM STDIN statement, in which the server will go in COPY_IN state and will accept data in COPY format. In psql finds this state, it will start feeding the following data to the database, which is in a format accepted in COPY_IN state, until it finds the `\.` terminator, which will result in sending the server the signal that the copy data are over. This machinery is the psql behaviour, so, even if the plumbing underneath is common between psql and psycopg, it doesn't mean that psycopg behaves the same way.

So, an input file for psql is not necessarily valid for psycopg. psql behaviour is relatively simple: it will chop the statements on the `;` and will send them one by one to the server. Upon return it will display data if available, or just print the return message on success, or display the error if any, and will deal with a COPY_IN result as expected. If you just run `conn.execute(ALL_THE_STUFF)` in psycopg the behaviour will be different (all the statements will run into the same implicit transaction, and, in case of COPY, the data will not be passed correctly, as psycopg deals with COPY data in a different way).

**Comment by jenstroeger** [comment]
That’s helpful, thanks you @dvarrazzo!
