### ISSUE TITLE
cursor.statusmessage form multiquery returns first status only

### ISSUE THREAD

**Issue by doc-sheet** [psycopg/psycopg#961]
Hi.

Do I miss something or statusmessage in psycopg3 (as well as in psycopg2) returns only the first status?

```
cursor.execute("""
select 1;
select 2;
select 3;
select 4;
""")

print(cursor.statusmessage)
```

It prints just `SELECT 1`

**Comment by dvarrazzo** [comment]
In psycopg 3 if you use` nextval()` you can get the following statuses:

```python
>>> cur.execute("""
... select 1;
... show timezone;
... """)

>>> cur.statusmessage
'SELECT 1'

>>> cur.nextset()
True

>>> cur.statusmessage
'SHOW'
```

in psycopg 2 you get only the last one I think.
