### ISSUE TITLE
[question] is it possible to determine if a transaction context exited with commit or rollback?

### ISSUE THREAD

**Issue by flashdagger** [psycopg/psycopg#967]
Hello psycopg team,

I am using `transaction()` context as suggested in the documentation and need to find out if the transaction was rolled back or not, since the executed statements are not always under my control.

Is it possible to distinguish between the two transactions after context exit? In both cases the transaction state is just `terminated`:

``` python
with psycopg.connect(autocommit=True) as conn:

    cur = conn.cursor()

    with conn.transaction(force_rollback=False) as tx:
        cur.execute("SELECT;")
    # COMMIT was executed

    print(tx)
    # <dbsync.connection.Transaction (terminated) [IDLE] (...)

    with conn.transaction(force_rollback=True) as tx:
        cur.execute("SELECT;")
    # ROLLBACK was executed

    print(tx)
    # <dbsync.connection.Transaction (terminated) [IDLE] (...)

```

**Comment by dvarrazzo** [comment]
Don't use `force_rollback`, just use `conn.transaction()`. Then you can understand if there was a rollback because an exception will be thrown as well:

```python
try:
    with conn.transaction():
        ... # operations
except Exception as ex:
    ... # there was a rollback
else:
    ... # there was a commit
```

**Comment by flashdagger** [comment]
Hello @dvarrazzo,

thank you for the quick response. But what if within the transaction an exception was already caught and a rollback happened?

```python
with conn.transaction() as tx:
   a_function(conn)  # call function that can raise Rollback()
```
Does the transaction object `tx` save the rollback event, so I ca query it afterwards?

**Comment by dvarrazzo** [comment]
No, but we can consider this improvement.

**Comment by asqui** [comment]
Maybe I'm stating the obvious, but note that you can handle the "voluntary `Rollback` requested" scenario without waiting for this feature, by moving the try/catch inside the transaction and catching and re-raising the `Rollback` exception:

```python
with conn.transaction():
    try:
        a_function(conn)  # call function that can raise Rollback()
    except Rollback:
        # rollback requested
        raise
    else:
        # transaction will be committed
```

I agree that this is not as neat as just being able to query `tx` to find out the fate of the transaction.

(Moreover if you want to know if it was rolled back voluntarily by a `raise Rollback()` _or_ involuntarily by an unhandled exception, then you'd have to use both approaches together -- a try/catch inside the transaction to catch and re-raise a `Rollback` exception, _and_ a try/catch outside the transaction to catch an unhandled exception. Pretty messy, but not impossible 😄)
