### ISSUE TITLE
sqlalchemy first() loads all rows

### ISSUE THREAD

**Issue by Tommos0** [psycopg/psycopg#968]
While debugging a memory issue, we found that when using `sqlalchemy` with `psycopg`, when trying to load a single record using `first()`, it will load the whole results set into memory.
The documentation (https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.CursorResult.first) states:
> Additionally, in contrast to the behavior of the legacy ORM [Query.first()](https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html#sqlalchemy.orm.Query.first) method, no limit is applied to the SQL query which was invoked to produce this [Result](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result); for a DBAPI driver that buffers results in memory before yielding rows, all rows will be sent to the Python process and all but the first row will be discarded.

I wonder if loading a single record from a result set with multiple rows is supported by `psycopg` cursor at all? If it is, I suppose a change is required in `sqlalchemy`?

**Comment by dvarrazzo** [comment]
It is supported using [server side cursors](https://www.psycopg.org/psycopg3/docs/advanced/cursors.html#server-side-cursors). Maybe [`cursor.stream()`](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.stream) could allow less memory use, but I'm not sure.

Nothing would beat you sending a `LIMIT 1` with your query though.

Using these methods is up to SQLAlchemy, so I'm closing this ticket here.
